kolmafia/kolmafia

- .github/workflows/build.yml
- .github/workflows/test.yml
- build.gradle
- src/net/sourceforge/kolmafia/FamiliarData.java
- src/net/sourceforge/kolmafia/KoLConstants.java
- src/net/sourceforge/kolmafia/KoLmafia.java
- src/net/sourceforge/kolmafia/StaticEntity.java
- src/net/sourceforge/kolmafia/request/GenericRequest.java
- src/net/sourceforge/kolmafia/request/RelayRequest.java
- src/net/sourceforge/kolmafia/swingui/panel/VersionDataPanel.java
- src/net/sourceforge/kolmafia/textui/Parser.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/utilities/LogStream.java
- test/net/sourceforge/kolmafia/CustomScriptTest.java
- test/net/sourceforge/kolmafia/textui/ParserTest.java
> Set revision when building jar with gradle

- LICENSE.md
GitHub projects tend to have a README and LICENSE file in the root of the repository. This adds a license file: 3-clause BSD, as can be seen in each `.java` source file.
I took the license template from GitHub itself, so hopefully it will be picked up by the web interface.
Supersedes #15.
> dev: add 3-clause BSD license to repo root

- src/net/sourceforge/kolmafia/textui/Parser.java
- src/net/sourceforge/kolmafia/textui/parsetree/VariableReference.java
We never make a new VariableReference without also having access to the Variable we want it to hold.
> Language Server - Remove VariableReference(String, BasicScope)

- src/net/sourceforge/kolmafia/request/BasementRequest.java
This prevents truncating doubles to a narrower type, which could overflow and return negative values. Resolves CodeQL code analysis warning.
> Change some ints to longs in BasementRequest

- src/net/sourceforge/kolmafia/textui/command/FaxbotCommand.java
Reference: https://kolmafia.us/threads/trying-to-use-ash-to-faxbot-a-factory-overseer-fails.26271/
The bug occurs when, for example:
1. easyfax is tried first
2. easyfax offers the monster you want
3. easyfax has become trapped in a clan over rollover, so can't actually return the monster you want
The thread talks about several other options, but I think this change is still good.
> feat: try multiple faxbots if the first fails in the CLI

- src/net/sourceforge/kolmafia/combat/Macrofier.java
- src/net/sourceforge/kolmafia/session/BuffBotManager.java
- src/net/sourceforge/kolmafia/webui/DiscoCombatHelper.java
Addressed instances of Implicit narrowing conversion in compound assignment flagged by security checking.  Trivial since the issue was just a local int that should have been changed when MP, HP, etc. went to longs.  Remaining instances seem to require changing global structures or method signatures.  Keeping this small to validate that I know how to "commit changes with git".
> Security lint

- src/net/sourceforge/kolmafia/textui/Parser.java
- src/net/sourceforge/kolmafia/textui/parsetree/BasicScope.java
- src/net/sourceforge/kolmafia/textui/parsetree/BasicScript.java
- src/net/sourceforge/kolmafia/textui/parsetree/Catch.java
- src/net/sourceforge/kolmafia/textui/parsetree/Command.java
- src/net/sourceforge/kolmafia/textui/parsetree/Conditional.java
- src/net/sourceforge/kolmafia/textui/parsetree/FunctionReturn.java
- src/net/sourceforge/kolmafia/textui/parsetree/JavaForLoop.java
- src/net/sourceforge/kolmafia/textui/parsetree/Loop.java
- src/net/sourceforge/kolmafia/textui/parsetree/Operator.java
- src/net/sourceforge/kolmafia/textui/parsetree/ParseTreeNode.java
- src/net/sourceforge/kolmafia/textui/parsetree/ScriptState.java
- src/net/sourceforge/kolmafia/textui/parsetree/SortBy.java
- src/net/sourceforge/kolmafia/textui/parsetree/Switch.java
- src/net/sourceforge/kolmafia/textui/parsetree/SwitchScope.java
- src/net/sourceforge/kolmafia/textui/parsetree/Try.java
- src/net/sourceforge/kolmafia/textui/parsetree/UserDefinedFunction.java
- src/net/sourceforge/kolmafia/textui/parsetree/Value.java
Adds the Command class as an abstract subtype of ParseTreeNode.
Its existence was already assumed (shown with the presence of variable names and methods like "parseCommand", to spell it out loud), but never officially added.
This class creates a distinction between it and Symbol, and shields previous uses of "ParseTreeNode" from having a Symbol slipped in its place.
> Language Server - Command class

- build.gradle
- default.properties
- gradle.properties
- src/net/sourceforge/kolmafia/KoLConstants.java
This is a proof-of-concept, and does not actually apply any formatting
changes yet. I'd prefer to make that formatting change in a standalone
commit.
This also removes some comments in the middle of imports in
KoLConstants.java because `./gradlew spotlessCheck` was yelling at me,
because Google Java Format (gojf) doesn't like that.
To reformat the code, you'll run `./gradlew spotlessApply`.
This adds some flags so gojf continues to work for newer Java versions
(16+). But for that, requires that the Java compiler be new enough to
support exports, aka at least Java 9, which coincidentally is the
highest version supported by OpenClover.
We really should switch away from OpenClover to something like JaCoCo.
> Add spotless w/ google java style.

- .github/workflows/coverage.yml
- .github/workflows/test.yml
- build.gradle
- jenkinsfile
They have support for Java > 9...
I think I got all the references to Clover (outside of the ant build), but it's hard to be sure.
Also this may have broken the jenkinsfile, so please read this PR with extreme skepticism.
> Migrate from OpenClover to JaCoCo for coverage

- gradle/wrapper/gradle-wrapper.properties
This reverts commit c77effb1e47a8731e8029b52e84dc0a7efe71af0.
Now that we're recommending that people use Java 17, they're having
issues building with it.
We need at least Gradle 7.1.1 to build with Java 17.
> Revert "Downgrade gradle wrapper to 7.0."

- .gitattributes
Our test setup specifies that the newline separator be \n so we can
actually use golden files for testing output of scripts. This doesn't
work so well when git mangles the golden files by adding newlines to
them.
> Require all files in test/root use newlines.

- README.md
- src/net/sourceforge/kolmafia/StaticEntity.java
Sometimes we can grab the wrong MANIFEST file (i.e. from another jar) which is why some people are occasionally seeing "r0". This fixes that and also caches the manifest itself so we're not searching for it three times.
It's possible that this means we don't even really need the other caches, but leaving it like this for now.
> Better revision capture for StaticEntity

- src/licenses/kolmafia-license.txt
returned the about box from the mists of time.
If the correct answer is to remove the link for it, we coud do that, too.
> Somewhere we lost the license file and it's needed for About frame

- .github/workflows/check.yml
This also opts to use ubuntu-latest so we don't have to manually
configure it in the future.
Note that there are technically newer OSes than windows-latest and
macos-latest at this time, but I anticipate that these labels will be
automatically migrated over time (unlike a fixed label that will
require periodic maintenance).
> Run checks against latest mac/windows.

- build.gradle
- gradle.properties
The syntax to get the project property wasn't correct.
Also split into two properties and use recommended camelCase so they can be overridden with environment variables.
> Fix java source & target compatibility settings

- src/net/sourceforge/kolmafia/persistence/ScriptManager.java
If the file throws a JSONException when we try to parse it, it's most
likely not valid JSON. So, let's delete it.
Anything else that we should do here? At the very least, this should get users out of a bad state.
Maybe we should also make sure that the Content-Type isn't text/html?
We already reject file downloads that aren't 200s.
> Delete svnrepo.json if it's bad.

- src/net/sourceforge/kolmafia/webui/RelayLoader.java
This really just applies to very old Linux installations... but mafia users tend to do things like use very old Linux installations
> Warn desktops who cannot launch a browser

- build.gradle
- lib/net/java/dev/spellcast/utilities/LockableListModel.java
- src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java
- src/net/sourceforge/kolmafia/swingui/panel/AdventureSelectPanel.java
- src/net/sourceforge/kolmafia/swingui/panel/CreateItemPanel.java
- src/net/sourceforge/kolmafia/swingui/panel/CreateSpecialPanel.java
- src/net/sourceforge/kolmafia/swingui/panel/SynthesizePanel.java
- src/net/sourceforge/kolmafia/swingui/panel/UseItemDequeuePanel.java
- src/net/sourceforge/kolmafia/swingui/widget/AutoFilterComboBox.java
- src/net/sourceforge/kolmafia/swingui/widget/AutoFilterTextField.java
- src/net/sourceforge/kolmafia/swingui/widget/ShowDescriptionTable.java
- src/net/sourceforge/kolmafia/utilities/InputFieldUtilities.java
~This disables the auto-sorting tables that SwingX enables, since it's
incompatible with LockableListModel, I guess.~
~(This seems to work for me, at least with what was previously a
consistent reproducing example no longer reproduces with this change.)~
This removes the optional "force update" parameter of
LockableListModel.updateFilter, as it is error-prone and can cause listeners
to desynchronize from the actual list. This is especially evident due to
changes in SwingX 1.0 -> 1.6 implementation details.
> Upgrade swingx to 1.6.

- src/data/inebriety.txt
- src/data/modifiers.txt
- src/data/statuseffects.txt
- src/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanel.java
- test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
We apparently need to do this every time we want to access a method of
item. Worth refactoring on a later date so this is less dangerous.
This change also resolves a mismatch between the item name (1950
Vampire Vintner wine) and its presence in inebriety.txt,
modiiers.txt, and statuseffects.txt.
For reasons, we only expanded DataFileConsistencyTest to cover
inebriety.txt (since it best fit the model used by the existing check
of equipment.txt).
> Check for null in UseItemEnqueuePanel.

- .github/workflows/check.yml
No need for a separate step, the default check is set to java 11 compatibility now.
> Remove java 11 check, as that is the default now

- src/net/sourceforge/kolmafia/textui/Parser.java
- test/root/expected/test_ambiguous_literal.ash.out
- test/root/scripts/test_ambiguous_literal.ash
Have parseLiteral create his warning messages by itself, rather than making a ScriptException.
This is just a transitional state. They will eventually go back to not building the warning message by themselves. It just won't use a ScriptException.
> Language Server - parseLiteral warnings

- src/net/sourceforge/kolmafia/maximizer/Maximizer.java
the `instanceof Boost` was only done because the Iterator was a raw type.
The LockableListModel was already enforcing that the Iterator would only contain Boosts.
> maximizer raw types

- src/net/sourceforge/kolmafia/session/ConsequenceManager.java
Not part of https://github.com/kolmafia/kolmafia/pull/150 because of how it changes ConsequenceManager.skillDescs's type (even though it's only the Generic).
Said type was advertised as HashMap<String, Consequence>, but was actually HashMap<Integer, Consequence>, unnoticed because of type erasure.
> ConsequenceManager raw types

- .github/workflows/build.yml
- build.gradle
~In particular, consider it to be dirty if it's not tagged with the
corresponding revision.~ Consider a build to be dirty if it has
any changes not in origin/main. 
This should be more flexible than just checking the HEAD of
origin/main, since it'll continue to work if you build an old
revision.
~We also need to make sure that we're tagging revisions before building
jars / binaries for distribution, so they're not all marked as
"dirty".~
This PR also fixes revision detection for old builds, which previously just
used "whatever origin/main is at". Now we count the total number of
revisions, minus those that are not present upstream. (It would be nice if
grgit supported git merge-base, but this works well enough.)
> Extend what it means for a build to be "dirty".

- src/net/sourceforge/kolmafia/KoLmafiaCLI.java
- src/net/sourceforge/kolmafia/textui/command/AbstractCommand.java
- src/net/sourceforge/kolmafia/textui/command/CliRefCommand.java
- src/net/sourceforge/kolmafia/utilities/PrefixMap.java
- test/net/sourceforge/kolmafia/extensions/ClearSharedState.java
- test/net/sourceforge/kolmafia/textui/command/AbstractCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/AbstractCommandTestBase.java
- test/net/sourceforge/kolmafia/textui/command/SaberCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/SnapperCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/SpoonCommandTest.java
`AbstractCommand` had two instances of imprecise types: one in `AbstractCommand.lookup`, where `Object` was used instead of `AbstractCommand`, and one in `AbstractCommand.substringLookup`, which was a `List` that alternated `String`s and `AbstractCommand`s.
The former was generified and `AbstractCommand` used. The latter was replaced by a `Map` of `String` to `AbstractCommand`: the Map has the additional restriction that no key can appear twice, but looking at the implementation that is desired anyway (in fact, an even stricter requirement is desired: no key can strictly contain another).
Tests have been added. I renamed the existing `AbstractCommandTest` because it was used as an abstract base class for the other tests, instead of a test for the `AbstractCommand` methods.
> Refactor AbstractCommand: avoid raw types

- src/net/sourceforge/kolmafia/preferences/Preferences.java
- test/net/sourceforge/kolmafia/KoLCharacterTest.java
- test/net/sourceforge/kolmafia/extensions/ClearSharedState.java
- test/net/sourceforge/kolmafia/preferences/PreferencesTest.java
- test/net/sourceforge/kolmafia/request/AscensionHistoryRequestTest.java
- test/net/sourceforge/kolmafia/request/UseItemRequestTest.java
Lint, typos and cleanup so root\settings remains empty after tests.  Cleanup should happen automatically but tests that create multiple preferences files may have to do additional work.  A human who wants to examine a preference file after a test is probably not going to be happy.  Draft status as I ponder these things.
> Preferences

- src/net/sourceforge/kolmafia/request/RelayRequest.java
Lint saw a comparison between what was declared as two strings and suggested it be replaced by .equals
I did so but it turns out the first string can be legitimately null.  Fixed that.
> Fix hiccup

- src/data/zapgroups.txt
Wiki suggests "devil hair pasta, Hell ramen, spagecialetti" yet this is already somewhat defined. Not sure who is accurate.
This list is compiled from individual wiki pages, the zapping page on wiki still needs updating.
> Add missing zap groups

- src/net/sourceforge/kolmafia/textui/command/UseSkillCommand.java
- test/net/sourceforge/kolmafia/textui/command/UseSkillCommandTest.java
This changes the behaviour of the `skill` or `cast` command to recognise a set of well-defined shorthands and avoid asking the user for clarification. Before the powerful glove, `cast ode` was sufficient a command to get Ode to Booze. Since then, such a command would ask for more specifics as "ode" is a substring of "CHEAT CODE".
In the case of `cast ode` (and only in that case, not `cast de`, `cast od`  or indeed `cast booze` etc) this PR will now expand to `cast The Ode To Booze`. It also sets out a framework through which we could add other known shorthands in the future, as well as adding tests.
> Allow known shorthand for the skill/cast command

- test/net/sourceforge/kolmafia/textui/ParserTest.java
- test/net/sourceforge/kolmafia/textui/ScriptData.java
Arguments is no longer needed for ParserTest.data() since there is a single, consistent class for each element.
> Language Server - No longer need Stream<Arguments>

- src/net/sourceforge/kolmafia/preferences/Preferences.java
- test/net/sourceforge/kolmafia/preferences/PreferencesTest.java
Previous attempt to make security scanner happy didn't.  Try this.
New Preferences tests kept breaking old ones.  Decided to move the setup and cleanup into Before/After Each instead of All.  Seems to work much better.  Might be willing and able to deprecate ClearSharedState but for the moment just duplicated code from there instead.
> Revisit Security

- src/net/sourceforge/kolmafia/swingui/ClanManageFrame.java
- src/net/sourceforge/kolmafia/swingui/LoginFrame.java
- src/net/sourceforge/kolmafia/swingui/MallSearchFrame.java
- src/net/sourceforge/kolmafia/swingui/SendMessageFrame.java
- src/net/sourceforge/kolmafia/swingui/SkillBuffFrame.java
- src/net/sourceforge/kolmafia/swingui/panel/AdventureSelectPanel.java
- src/net/sourceforge/kolmafia/swingui/panel/ChoiceOptionsPanel.java
- src/net/sourceforge/kolmafia/swingui/panel/CustomCombatPanel.java
- src/net/sourceforge/kolmafia/swingui/panel/MoodOptionsPanel.java
- src/net/sourceforge/kolmafia/swingui/widget/AutoFilterComboBox.java
- src/net/sourceforge/kolmafia/swingui/widget/EditableAutoFilterComboBox.java
AutoFilterComboBox was split into two "modes": editable, and not.
This PR isolates the editable mode into its own class, "EditableAutoFilterComboBox", whose generic is locked as String.
This allows AutoFilterComboBox to have its own Generic.
> AutoFilterComboBox-raw-type

- src/net/sourceforge/kolmafia/session/LoginManager.java
- src/net/sourceforge/kolmafia/textui/command/SubmitSpadeDataCommand.java
If you have a lot of spading data, confirming each time is a bit annoying. This adds a command to confirm everything pre-emptively.
> cli: add ability to autoconfirm sending spading data

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
Add RuntimeLibrary commands for sending and receiving faxes. They are just wrappers around the CLI command, but are less awkward to use from ASH/JS scripts.
> feat: add fax send/receiver ash commands

- src/net/sourceforge/kolmafia/AscensionClass.java
- src/net/sourceforge/kolmafia/persistence/SkillDatabase.java
- src/net/sourceforge/kolmafia/request/AfterLifeRequest.java
- test/root/expected/test_class.ash.out
- test/root/scripts/test_class.ash
This is a partial fix for https://kolmafia.us/threads/my_class-returning-void-for-actually-ed-the-undying.26728/
It now returns:
```
> ash my_class()
Returned: Ed the Undying
primestat => Mysticality
```
This still would break compatibility for all other scripts that still refer to the path as Ed. I'm not sure how to alias it or anything otherwise.
> Updating references to Ed the Undying to fix my_class()

- src/net/sourceforge/kolmafia/textui/Parser.java
- src/net/sourceforge/kolmafia/textui/parsetree/FunctionCall.java
- src/net/sourceforge/kolmafia/textui/parsetree/FunctionInvocation.java
- test/net/sourceforge/kolmafia/textui/parsetree/FunctionInvocationTest.java
This skips over FunctionCall, because they have multiple instances of looking at another Command/Evaluable's Location, and so will need to be in the very final batch.
> Language Server - Locations - FunctionInvocation

- src/net/sourceforge/kolmafia/textui/Parser.java
- src/net/sourceforge/kolmafia/textui/parsetree/LibraryFunction.java
- src/net/sourceforge/kolmafia/textui/parsetree/VariableReference.java
- test/net/sourceforge/kolmafia/textui/parsetree/AssignmentTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/ForEachLoopTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/ForLoopTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/UserDefinedFunctionTest.java
Setting aside those that I prepared for when https://github.com/kolmafia/kolmafia/pull/224 will be merged, a large portion of what's left is composed of classes who look at other Evaluables to determine/update their Location.
Those will obviously need to all be submitted at the same time, so in order to reduce the cognitive load induced by this last patch/batch/PR, I'll do my best to work around those.
Do bear in mind that it means a few more of those "TEMPORARY" constructors, though... (they'll all be removed at the same time)
For this PR, those ignored/avoided are variable references made from expressions/function call (e.g. "foo().field"), and composite references.
> Language Server - Locations - VariableReference (...mostly)

- test/net/sourceforge/kolmafia/CustomScriptTest.java
- test/net/sourceforge/kolmafia/KoLCharacterTest.java
- test/net/sourceforge/kolmafia/extensions/ClearSharedState.java
- test/net/sourceforge/kolmafia/objectpool/ConcoctionTest.java
- test/net/sourceforge/kolmafia/preferences/PreferencesTest.java
- test/net/sourceforge/kolmafia/request/BasementRequestTest.java
- test/net/sourceforge/kolmafia/request/RequestTestBase.java
- test/net/sourceforge/kolmafia/request/ScrapheapRequestTest.java
- test/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanelTest.java
- test/net/sourceforge/kolmafia/textui/command/UseSkillCommandTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/DirectiveTest.java
As previously discussed, I have consolidated as many BeforeAll, BeforeEach, AfterEach and AfterAll activities as I could into ClearSharedState.  The remaining uses are for cases where the state must be reset between individual tests contained in the same test class.  Part of my solution was to delete the directories under test\root that are not under git control.
There us some lint cleaned up and a mistake in ConcoctionsTest that was not corrected when it was discovered.  
Everything ran locally with forkEvery at default and 1.
> ClearSharedState

- src/net/sourceforge/kolmafia/textui/Line.java
- test/net/sourceforge/kolmafia/textui/LineTest.java
Now that I'm looking into writing more tests involving locations, I realize that I forgot to make it so that the end-of-file token's position matches the actual end of the file... whups
> Language Server - End-of-file token tweak

- src/net/sourceforge/kolmafia/AdventureResult.java
- src/net/sourceforge/kolmafia/maximizer/Evaluator.java
- src/net/sourceforge/kolmafia/maximizer/MaximizerSpeculation.java
- src/net/sourceforge/kolmafia/session/RabbitHoleManager.java
- src/net/sourceforge/kolmafia/session/VolcanoMazeManager.java
- src/net/sourceforge/kolmafia/swingui/MuseumFrame.java
- src/net/sourceforge/kolmafia/textui/AshRuntime.java
For types without a generic: use covariant return types to save some type castings.
(source: http://jtechies.blogspot.com/2012/07/item-11-override-clone-judiciously.html )
For ArrayList: use the copy constructor instead of ArrayList.clone()
(source: https://stackoverflow.com/questions/3410035/how-to-make-a-copy-of-arraylist-object-which-is-type-of-list/3410133#3410133 )
For LockableListModel... ugh... just ignore the warning, I guess...
> (slightly) safe(r) cloning

- .github/workflows/build.yml
Per documentation for action-gh-release, this should automatically
generate a name and body if not present. If body is specified, then
it'll append to the specified body.
> Automatically generate release notes.

- src/net/sourceforge/kolmafia/textui/Parser.java
- test/net/sourceforge/kolmafia/textui/parsetree/ForLoopTest.java
Also does 2 small things:
1- creates "indexvar" earlier
2- only reads "upto"/"downto"/"to" in the conditional in which we see it (instead of after)
> Language Server - error locations - ForLoop

- src/net/sourceforge/kolmafia/textui/Parser.java
- test/net/sourceforge/kolmafia/textui/parsetree/IncDecTest.java
Also closes a loophole in which a FunctionCall could slip past our radar, resulting in a ClassCastException
> Language Server - error locations - IncDec

- src/net/sourceforge/kolmafia/textui/Parser.java
- test/net/sourceforge/kolmafia/textui/parsetree/AggregateLiteralTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/StringTest.java
1- also adds additional details to some of the error messages
2- also unearthed a mistake with string locations, where their location would include any whitespace immediately following them.
> Language Server - error locations - AggregateLiteral + string tweak

- src/net/sourceforge/kolmafia/textui/Parser.java
- test/net/sourceforge/kolmafia/textui/ParserTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/DirectiveTest.java
1- also removes the `targetIsRevision` boolean parameter of the `sinceException` method, as it was always true since 21.09
2- The matcher used to test invalid script's error message can now be `startsWith` rather than `containsString`
> Language Server - error locations - Directive

- src/net/sourceforge/kolmafia/textui/Line.java
- src/net/sourceforge/kolmafia/textui/Parser.java
- test/net/sourceforge/kolmafia/textui/LineTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/EscapeSequenceTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/StringTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/TemplateStringTest.java
Additionally, fixes a behavior regarding the relation between `currentIndex` and the end of file:
When moving to the next line, we would set `currentIndex` to the value of `currentLine.offset`.
However, the "end of file" line's offset is the same as the previous line.
This means that calling `getCurrentPosition()` would yield a Position that seemingly came *earlier* in the final line.
> Language Server - error locations - String

- src/net/sourceforge/kolmafia/KoLmafia.java
Apparently this changed recently and broke the CAB.
https://kolmafia.us/threads/26911
> Use new cloudfront url for KoL images.

- src/net/sourceforge/kolmafia/KoLmafia.java
Reverts kolmafia/kolmafia#303
latest reports say this breaks other things, sounds like we need to dig into this further and/or invest in a more robust solution.
> Revert "Use new cloudfront url for KoL images."

- .github/workflows/build.yml
I think this might eliminate the case where multiple releases end up
with the same summary data if they're merged in quick succession,
although it's possible the problem is deeper than that.
(I'm really not sure on this one, caveat lector.)
> Serialize build.yml executions.

- src/net/sourceforge/kolmafia/swingui/widget/RequestPane.java
"lint" showed a condition that was always false in a test.
This cleans that up a little.  It gets indices for each tag and bails if either tag is not found.  The old code would contine if the <body> tag was not present.
> Eliminate a a condition that is always true in a conditional on the presumption it is an error.

- src/net/sourceforge/kolmafia/FamiliarData.java
- src/net/sourceforge/kolmafia/KoLmafia.java
- src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
- src/net/sourceforge/kolmafia/request/CharPaneRequest.java
- src/net/sourceforge/kolmafia/request/CharSheetRequest.java
- src/net/sourceforge/kolmafia/request/DisplayCaseRequest.java
- src/net/sourceforge/kolmafia/request/RelayRequest.java
- src/net/sourceforge/kolmafia/request/TrophyRequest.java
- src/net/sourceforge/kolmafia/session/BuffBotManager.java
- src/net/sourceforge/kolmafia/session/MonsterManuelManager.java
- src/net/sourceforge/kolmafia/utilities/FileUtilities.java
- src/net/sourceforge/kolmafia/webui/BarrelDecorator.java
- src/net/sourceforge/kolmafia/webui/IslandDecorator.java
- src/net/sourceforge/kolmafia/webui/RelayAgent.java
- src/net/sourceforge/kolmafia/webui/StationaryButtonDecorator.java
KoL is currently serving a mix of cloudfront / S3 traffic, so we should be
strict about requesting from cloudfront if we originate a request, but lenient
about accepting responses that contain non-cloudfront URLs.
Further, downloadImage() was constrained such that it would look for the last
occurrence of .com, which naturally stopped matching once we moved to
cloudfront.net URLs.
Also also, there were a bunch of regexes that expected image URLs to contain
"images.kingdomofloathing.com", which was true under S3 but is no longer true
with Cloudfront. Many of these are underspecified out of laziness, but I can fix
that if needed.
> Use cloudfront for images, take two.

- src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
- src/net/sourceforge/kolmafia/webui/RelayAgent.java
DebugDatabase: a regex inadvertently introduced a new capturing group.
RelayAgent: I moved the trailing slash to the capturing group, as opposed to
having a leading slash in the rest of the pattern, so we could get away with
only exposing "PATH" constants. (Thanks Veracity for catching this)
> Fix some regressions from the cloudfront change.

- src/data/statuseffects.txt
- src/net/sourceforge/kolmafia/AdventureResult.java
- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/objectpool/SkillPool.java
- src/net/sourceforge/kolmafia/persistence/EffectDatabase.java
- src/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanel.java
- src/net/sourceforge/kolmafia/textui/parsetree/ProxyRecordValue.java
- test/net/sourceforge/kolmafia/KoLCharacterTest.java
- test/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanelTest.java
We've formerly designated effects as part of the mutex "Songs" if their skill source is a buff in the AT id range. However, `Rolando's Rondo of Resisto` is a song that doesn't meet those criteria. This PR:
- Adds `song` as an attribute in statuseffects
- Appends the musical note based on this new attribute
- Disables the "cast ode" button in the UseItemEnqueuePanel when the player has no free memory for more songs (and explains why in a tooltip)
- Tests the above
> Track AT songs explicitly, improve user experience around AT songs

- src/data/monsters.txt
This should fix the checkmanuel warning
> Add Manuel alias for Protector Spectre (Wildfire)

- src/data/statuseffects.txt
As it says in the title: now that `statuseffects` tracks what is and isn't a song, it should track that the remastered Dirge is a song.
You get it by casting Dirge of Dreadfulness with the velour vaqueros equipped.
> fix: remastered dirge counts against song limit

- src/net/sourceforge/kolmafia/AreaCombatData.java
- src/net/sourceforge/kolmafia/persistence/AdventureQueueDatabase.java
- src/net/sourceforge/kolmafia/session/EncounterManager.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/textui/command/MonsterDataCommand.java
- test/net/sourceforge/kolmafia/AreaCombatDataTest.java
This is primarily in advance of implementing Be Gregarious to our queue management. We have our queue management logic in multiple different places, so this combines them and makes it easier to support more queuey things in future.
I did this tests-first, so it shouldn't have an effect on any behaviour
> Keep appearance rate calculation DRY

- src/net/sourceforge/kolmafia/swingui/widget/RequestPane.java
The invalidation of the component is not needed, especially as it is called fairly often.
No need to unregister the component, as the component is not saved in a global object that needs to be removed later as originally thought.
> Fix html title hover not working as intended

- src/net/sourceforge/kolmafia/AscensionClass.java
- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/objectpool/Concoction.java
- src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java
- src/net/sourceforge/kolmafia/request/AscensionHistoryRequest.java
- src/net/sourceforge/kolmafia/request/CreateItemRequest.java
- src/net/sourceforge/kolmafia/request/GuildRequest.java
- src/net/sourceforge/kolmafia/request/HeyDezeRequest.java
- src/net/sourceforge/kolmafia/request/KOLHSRequest.java
- src/net/sourceforge/kolmafia/request/VolcanoIslandRequest.java
- src/net/sourceforge/kolmafia/session/ChoiceManager.java
- src/net/sourceforge/kolmafia/swingui/GearChangeFrame.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/webui/UseLinkDecorator.java
I remember seeing that having an empty "default" case was disliked, so instead, this only focuses on default cases which can immediately be inferred.
For example, if every case ends with a "return", this moves what's outside of the switch into the default case.
This cuts the "missing enum case" warnings by roughly half (~400 -> ~200)
> "enum constant needs a corresponding case label"

- src/net/sourceforge/kolmafia/swingui/SkillBuffFrame.java
Some time back, we refactored AutoFilterComboBox. In doing so, we
changed its update() method from private to protected to expose it to
a subclass. What we didn't realize was that we were subsequently
shadowing this method in SkillSelectComboBox.
Thanks Veracity for [reporting this](https://kolmafia.us/threads/26961).
> Fix text filtering in SkillBuffFrame.

- src/net/sourceforge/kolmafia/webui/CharPaneDecorator.java
This fixes a weird error on safari where the size of the different decorated elements are recalculated but not repainted
> Make sure that all of the decorations after an Effect in the charpane do not wrap

- src/net/sourceforge/kolmafia/textui/parsetree/RecordType.java
- src/net/sourceforge/kolmafia/textui/parsetree/Type.java
Minor issue with the `reference` functions @fredg1 added to Type and RecordType. Unless I'm missing something, these were broken before,.
> Cannot use `this` before it is defined (i.e. before super is called)

- test/net/sourceforge/kolmafia/extensions/ClearSharedState.java
These fields are typically set by an ApiRequest shortly after login, but we're
not actually getting the full response text.
While I'm at it, this also changes ClearSharedState to a BeforeAllCallback (so
the same initialization will also apply to the first test suite that's
executed).
> Clear state leaked by CharPaneDecoratorTest.

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/request/MallPurchaseRequest.java
Revision 20900 added a "forbiddenStores" property which is a list of stores this user will not attempt to buy from.
This change adds that property to defaults.txt (default is empty).
Also add a "autoForbidIgnoringStores" property (default true) to add any store that has you on its ignore list to that property. Simply detecting that a store is ignoring you will suppress purchasing for the rest of the session, but adding it to the forbidden list will cause it to be ignored in future sessions, as well, without having to attempt a purchase and learn - again - that you are ignored.
I suppose some stores might choose to un-ignore you eventually, but we have no way of knowing when that will happen, and until then, their presence in you mall search results will skew mall price calculations for …
> Add autoForbidIgnoringStores property

- test/net/sourceforge/kolmafia/extensions/ClearSharedStateAfter.java
- test/net/sourceforge/kolmafia/extensions/ClearSharedStateBefore.java
- test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
A test was leaking files into root\settings.  I could not find it so went for the nuclear option of cleaning out the directory after all tests.  An argument could be made that cleaning the directories before and after tests is inefficient but it provides a stronger guarantee of state.
> Clean up disk state

- src/net/sourceforge/kolmafia/request/MallPurchaseRequest.java
I notice there is a pending PR which manipulates the forbiddenStores setting. Cool!
Simplify MallPurchaseRequest.getForbiddenStores.
It now returns a mutable list.
If the forbiddenStores property is empty, return an empty list
Therefore, you can add and remove elements from the List and not worry about having an empty element present if the property has no stores in it.
> getForbiddenStores returns a mutable list with no empty elements

- src/net/sourceforge/kolmafia/session/ChoiceManager.java
This should fix timespinner considering semirare monsters and goth kid monsters (amongst others) when recording their associated state changes.
Fixes https://kolmafia.us/threads/timespinning-a-knob-goblin-embezzler-resets-the-semirare-counter.26987/
> Ignore special monsters when time-spinning

- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
The maximizer is very big and complicated, and a good target for additional tests before refactoring (or in general).
I refactored the tests a bit to prefer using names to ids; I feel it reads better.
I added tests for max and min (inside modifiers, or starting for max), stat restrictions and clownosity. The documentation says that max and min at the start of an expression should apply to the entire expression, but I tried this and I don't think it works that way for min. It looks like "min" fails the maximization if the _current_ character items / effects don't meet the minimum.
> Add some tests to the maximizer

- src/data/items.txt
- src/data/spleenhit.txt
- src/net/sourceforge/kolmafia/request/PlaceRequest.java
- test/net/sourceforge/kolmafia/DataFileTest.java
new item, new place
Also: Data File test failed because there was no "quality" listed for the spleen item.
That is allowed, as a result of KoL change:
"December 02 - Spleen items no longer show an often misleading quality rating, if they don't give adventures."
I did not remove qualities from existing spleen items, but I fixed the test to not require a quality.
> Add [experimental crimbo spleen] and Chem Lab

- src/net/sourceforge/kolmafia/session/ChoiceManager.java
Prior to #374 this always incremented by 1 because Java matchers return a String. String == string is generally false because they do not exist at the same memory location. This PR is intended to revert to the original behavior that is now expected by users and simplify logic.
> Increment gold guzzlr quests by 1 on completion

- src/net/sourceforge/kolmafia/swingui/MaximizerFrame.java
This fixes the exclusive setting of maximizer having checkboxes ticked wrongly
> Default value of a filter type is not true, but is checkbox.selected()

- src/net/sourceforge/kolmafia/swingui/widget/RequestPane.java
HTMLWriter has a default maximum line limit of 80, although I think lines with no spaces bypasses this.
What this commit does is adds a check if we're using an HTML Document, and applies a large maximum line limit.
This means lines are no longer indented.
This commit could perhaps be improved further with a proper class declaration, instead of an anonymous class.
setLineLength is a protected method you see.
Quick example of the indention follows, a straight copy/paste from the Mafia CLI display. Just a bunch of "test" with a space in between.
```
test test test test test test test test test test test test test test test     test test test test test test test test test test test test test test test     test test test test test test test test test test test test test test test     test test …
```
> Stop indents being applied to selected text

- src/net/sourceforge/kolmafia/maximizer/CheckedItem.java
This sounds like it should go into the maximizer class itself, but the maximizer class is so messy that it'd need to be rewritten just to make that viable.
This method is called several times in different locations in different orders of logic. It's just simpler and cleaner as it stands to put the check here.
> If we declare world peace, maximizer should abort

- lib/net/java/dev/spellcast/utilities/LicenseDisplay.java
- src/net/sourceforge/kolmafia/CreateFrameRunnable.java
In situations where !Desktop.isDesktopSupported(), these will throw
exceptions. That's not great, as we should degrade gracefully.
> Guard calls to Desktop.getDesktop().

- src/net/sourceforge/kolmafia/swingui/GenericFrame.java
When it restored the size of other frames outside of tabbed chat, I found it both disorientating and annoying.
It'll still remember the sizes for now however, incase we plan to change this in the future.
> Add chat frame width/height restoring

- src/net/sourceforge/kolmafia/session/EquipmentManager.java
- src/net/sourceforge/kolmafia/session/EquipmentRequirement.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Extracted `EquipmentRequirement` (the equipment requiring parsing code) from `EquipmentManager` because I wanted to re-use it in the tests to set stats appropriately.
Refactored, reordered and added a few more maximizer tests.
> Extract EquipmentRequirement, more maximizer tests

- src/data/equipment.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/Modifiers.java
Crimbo 21 items from Dec 23.
Plurals from previous Crimbo Items.
Spleen Drop modifier.
Several modifiers had added without being assigned index constants.
Subsequent modifiers simply incremented the index constants without accounting for the gap.
Obviously, those latter constants for incorrect array indices.
I added index constants for all the missing modifiers.
> New crimbo items. plurals. fixes from checkitems.

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/maximizer/Evaluator.java
- src/net/sourceforge/kolmafia/request/AdventureRequest.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Several places in the codebase checked only for The Sea and the Party Yacht instead of all underwater locations. This PR changes that, and adds a test for the Maximizer.
> When checking underwater locations, check environment instead of list

- src/net/sourceforge/kolmafia/AreaCombatData.java
Certain negative weights have special meaning (-2 == IS_BANISHED, -1
== IS_ULTRA_RARE). Users apparently rely on this.
Thanks Malibu Stacey @ kolmafia.us for [reporting this bug](https://kolmafia.us/threads/27039/).
> Propagate negative weights, unchanged.

- src/net/sourceforge/kolmafia/session/StoreManager.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
New ASH function:
int mall_price( item it, float maxAge )
This will force a mall search to update the price if the cached price is too old.
Use maxAge of 0 to always force a mall search.
> ash mall_price( $item[ milk of magnesium ] )
Searching for "milk of magnesium"...
Search complete.
Returned: 1195`
> ash mall_price( $item[ milk of magnesium ] )
Returned: 1195
> ash mall_price( $item[ milk of magnesium ], 0 )
Searching for "milk of magnesium"...
Search complete.
Returned: 1195`
> Add mall_price( item, float maxAge ) to ASH

- src/data/adventures.txt
- src/data/combats.txt
- src/data/monsters.txt
This is the December 24 adventure zone and monster.
There is also an Advent Calendar item, but I am not adding it, since it has no modifiers. Seems like an oversight.
The monster is confusing. Manuel has nothing much to say about it.
It also has multiple names and an image composed of multiple images.
This is a start, at least, and lets you automate adventures.
> add Site Alpha Primary Lab and massive goo construct

- src/data/adventures.txt
- src/data/combats.txt
- src/data/defaults.txt
- src/data/equipment.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/data/monsters.txt
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/session/ChoiceManager.java
Add tiny plastic primary lab. It has no visible Enchantments. If they fix that, we'll have to update.
Add support for Choice Adventure 1461 in the Site Alpha Primary Lab.
Note that option #5 is "Grab the Cheer Core". If I recall, you get that once - and it is your only choice.
Therefore, if you are automating and that choice comes up and that option is present, we select it, regardless of how you have the choice configured.
Note also that this choice adventure does not have a blue "Encounter" when you find it.
I bug reported it to KoL. Surely they'd prefer to have something funny, rather than nothing.
Also added two properties:
primaryLabGooIntensity (default 10)
primaryLabCheerCoreGrabbed (default false)
> Primary lab

- src/net/sourceforge/kolmafia/request/FightRequest.java
Sometimes Kolmafia might generate a combat macro which, after optimisation,
constists solely of the placeholders
#mafiaround
#mafiamp
#mafiaheader
handleMacroAction() then further optimises that kind of macro down into a bunch
of newlines, which then cause an "Invalid macro" error when sent to KoL.
With this change, we also check that the macro isn't empty *after* the pro-
cessing done by handleMacroAction(), and only send it on to KoL if it's truly
non-empty.
See also https://kolmafia.us/threads/consult-script-ccs-that-gets-optimised-out-to-nothing-leads-to-invalid-macro-abort.26620/
> Don't send empty macros to KoL

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/session/ChoiceManager.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
KoLConstant.availableCombatSkills is maintained by FightRequest; when you are in a fight, it is populated with the skills listed in the skill dropdown. This can change each round.
Added KoLCharacter.availableCombatSkill( skillId ) and KoLCharacter.availableCombatSkill( UseSkillRequest ) to check if the supplied skill is currently available.
Added ASH function: boolean combat_skill_available( skill ) to do the same thing.
Note that this is only accurate while you are in a fight; it is intended for use in consult scripts and combat filters.
Also, KoL has finally given a name to the Choice Adventure in the Site Alpha Primary Lab: Hello Knob My Old Friend
Not that this is useful, but it's nice to have the comments be correct, at least.
> add available_combat_skill ASH function.

- src/net/sourceforge/kolmafia/maximizer/Evaluator.java
- src/net/sourceforge/kolmafia/maximizer/MaximizerSpeculation.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
In particular, this affects item droppers / meat droppers / rollover
effects, but not Bs in Bees Hate You or breakables (although could
control those cases too; I figured those were generally desirable
though).
Context: https://kolmafia.us/threads/the-maximizer-ignores-tie.27073/
> Allow -tie to affect hardcoded tiebreakers.

- src/net/sourceforge/kolmafia/swingui/ChatFrame.java
If you have said something previously, pressing "Up" on your keyboard with the chat input selected, will restore what you had previously said.
However, the position of the caret remains at 0, instead of the last position as expected.
This aims to fix that, by placing the caret at the end of the text after performing the action.
> Set chat caret to last position on key up/down

- src/net/sourceforge/kolmafia/session/ChoiceManager.java
Run SpadingManager.processChoice before ChoiceManager.visitChoice() and the function returns, so choices that still need to be handled can be spaded.
@gausie this should be fine right? I'm trying to make a spading script to pull data from a multi-choice adventure where I need access to the urlString at every step.
> Process multipart choices with spade script

- src/net/sourceforge/kolmafia/KoLmafiaCLI.java
Some discussion can be found here
https://kolmafia.us/threads/four-commands-using-registersubstring.27076/
The main reason behind this change is that "registerSubstring" makes any script with "kitchen" "mirror" and "brewery" in its name impossible to run in CLI with just its name, as well as other potential shenanigans.
> Register https for visiturl command, fix three other command registrations not being explicit

- src/net/sourceforge/kolmafia/session/EncounterManager.java
right now, mafia is incorrectly decrementing the `beGregariousFightsLeft` on time-spinner, envyfish, and other definitely non-gregarious encounters. This ensures that mafia decrements the property only when the gregarity message is present.
> decrement beGregariousFightsLeft only when the gregarity text is present

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/request/FightRequest.java
In some cases, the enamoranged monster counter can be initialized, or the monster itself encountered without KoLMafia and scripts detecting it. This addition would offer more data to help automation better decide if the enamorangMonster value should be handled or ignored.
Since the monster name property and timers are unset upon encountering an enamorang monster, I left this one alone but it too could be unset if desired.
> Record the turn on which LOV Enamorang is used

- src/net/sourceforge/kolmafia/swingui/RequestSynchFrame.java
Creating the request display when headless causes an exception so there's no benefit
> Don't show RequestSynchFrame when headless

- src/net/sourceforge/kolmafia/textui/Parser.java
- test/net/sourceforge/kolmafia/textui/parsetree/AggregateLiteralTest.java
erroneous typecasting that flew below the radar for the past 6 years or so.
> fix potential ClassCastException

- src/net/sourceforge/kolmafia/textui/javascript/AshStub.java
- src/net/sourceforge/kolmafia/textui/javascript/JavascriptRuntime.java
- src/net/sourceforge/kolmafia/textui/javascript/LibraryFunctionStub.java
- src/net/sourceforge/kolmafia/textui/javascript/SafeRequire.java
- src/net/sourceforge/kolmafia/textui/javascript/UserDefinedFunctionStub.java
- test/root/expected/stdlib_prototype.js.out
- test/root/scripts/item_drops_array.js
- test/root/scripts/stdlib_prototype.js
Now you can run `.apply`, `.call` etc on js functions that are generated from ash
> Give full function prototype to all JS function stubs

- src/net/sourceforge/kolmafia/textui/AshRuntime.java
- src/net/sourceforge/kolmafia/textui/NamespaceInterpreter.java
- src/net/sourceforge/kolmafia/textui/Parser.java
- test/net/sourceforge/kolmafia/textui/ParserTest.java
The language server will run the parsing of the various scripts in separate threads.
This allows us to save resources by allowing those threads to be interrupted when we no longer need them (if, for example, a file is modified during parsing).
Is this a behaviour that needs to be tested? Not sure how I'd even test that.
> Language Server - interruptions

- src/net/sourceforge/kolmafia/request/FightRequest.java
Change Blech House progress from 10 to 11 when Fire Extinguisher zone specific skill is used.
Fixes bug:
https://kolmafia.us/threads/fire-extinguisher-effect-in-smut-orc-logging-camp-incorrect.27098/
This is my first Mafia PR - let me know if I should do anything differently! Didn't do any testing as this is a simple change. Happy to run/create a test if you all desire. Will need to be pointed in the right direction.
> fire extinguisher increments blech house progress by 11, not 10

- src/data/modifiers.txt
It's actually only Sauce Spell Damage, but this is more correct until that is supported.
> Intrinsic Spiciness is Spell Damage: [min(L,10)]

- src/net/sourceforge/kolmafia/session/CursedMagnifyingGlassManager.java
Right now, CMG tracking fails to update for particular messages, because KoL uses two periods after a space, and the wiki does not.
Now it won't fail!
> add two spaces after periods for CMG tracking

- src/net/sourceforge/kolmafia/request/FamiliarRequest.java
- src/net/sourceforge/kolmafia/request/SummoningChamberRequest.java
- src/net/sourceforge/kolmafia/session/BreakfastManager.java
- src/net/sourceforge/kolmafia/session/FamiliarManager.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/textui/command/HeistCommand.java
There are certain cases where Mafia switches to a familiar, not so that it can be used in adventuring, but so you can do something involving the familiar. In those cases, don't steal the familiar equipment (and then steal it back immediately after).
These are:
* using the Space Jellyfish in Breakfast to grab sea jelly
* using the Intergnat to summon a demon
* using the Cat Burglar to heist an item
> feat: add parameter to not steal familiar equipment

- src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
do not use/reuse static global request objects for fetching skill, outfit, and effect descriptions
We used to do that for desc_item calls, but fixed it when we had multiple threads trying to read item descriptions and they were stomping on each other.
Make the same fix for effect, skill,, and outfit descriptions.
> Make reading effect_desc, outfit_desc, and skill_desc thread safe.

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
Add a function to get the list of installed svn scripts, returning the same results as `svn list`.
```
> svn list
Ezandora-Bastille-branches-Release
Ezandora-Briefcase-branches-Release
Ezandora-Choice-Override-branches-Release
Ezandora-Far-Future-branches-Release
Ezandora-Gain-branches-Release
Loathing-Associates-Scripting-Society-combo-branches-release
Loathing-Associates-Scripting-Society-garbage-collector-branches-release
Loathing-Associates-Scripting-Society-KoL-MineVolcano-branches-master-RELEASE
therazekolmafia-canadv
zlib
> ash svn_list()
Returned: aggregate string [10]
0 => Ezandora-Bastille-branches-Release
1 => Ezandora-Briefcase-branches-Release
2 => Ezandora-Choice-Override-branches-Release
3 => Ezandora-Far-Future-branches-Release
4 => Ezandora-Gain-branches-Release
5 => …
```
> Add svn_list() ash function

- src/net/sourceforge/kolmafia/session/InventoryManager.java
Resolves https://kolmafia.us/threads/retrieve_item-appears-to-be-searching-the-mall-multiple-times-per-ingredient.27103/
Update the mall searches in InventoryManager to used the cached mall price if an exact value is desired, instead of passing in 0 as the maxAge which causes the cache to get purged. This prevents repeated unnecessary mall searches.
New output:
```
> ash retrieve_item($item[single entendre]);
Searching for "double entendre"...
Search complete.
Searching for "bottle of tequila"...
Search complete.
Searching for "bottle of anís"...
Search complete.
Searching for "single entendre"...
Search complete.
Searching for "lemon"...
Search complete.
Verifying ingredients for single entendre (1)...
Verifying ingredients for double entendre (1)...
Using cached search results for …
```
> Use getMallPrice() in InventoryManager without maxAge for exact results

- src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
Old code actually triggers for non-redirect status codes, I believe.  Am I right?
> Wrong check for redirect?

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/Modifiers.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
Make a new modifier for Sauce Spell Damage, this currently only applies to Intrinsic Spiciness.
> Add Sauce Spell Damage modifier

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/objectpool/SkillPool.java
- src/net/sourceforge/kolmafia/preferences/Preferences.java
- src/net/sourceforge/kolmafia/request/FightRequest.java
- src/net/sourceforge/kolmafia/session/ResultProcessor.java
- When you throw your cosmic bowling ball in combat, increment hiddenBowlingAlleyProgress
- When you use a bowling skill, remove it from inventory, increment _cosmicBowlingSkillsUsed, and set cosmicBowlingBallActive to true.
- When you receive a cosmic bowling ball in combat, set cosmicBowlingBallActive to false
- When you ascend, set cosmicBowlingBallActive to false
And when I inserted the case block to support the bowling skills in FightRequest.payActionCost, I noticed that the code following the case label for SkillPool.FIRE_EXTINGUISHER__ZONE_SPECIFIC ("Fire Extinguisher: Zone Specific") was a complete mess. Whoever wrote it apparently assumed that the code following the case label was an implicit block - defining local variables and omitting the break statement at the end. The result …
> track combat usage of cosmic bowling ball

- src/data/equipment.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/data/monsters.txt
Another place I noticed `lastCopyableMonster` being erroneously updated. Verified by casting Feel Nostalgic and still getting previous monsters drops even on the 3rd Snojo combat and also double checked with the print screen button to ensure it gives the failure to copy message. Log of Snojo combats casting Feel Nostalgic after a smoke monster -> [snojo_lastCopyableMonster_example.txt](https://github.com/kolmafia/kolmafia/files/7878451/snojo_lastCopyableMonster_example.txt)
Void shard is in the mall so I had mafia generate the values by searching for it then copied the entries from my session.log to the appropriate files (so formatting should be correct but if it isn't let me know).
> Snojo monsters are nocopy and add void shard

- src/net/sourceforge/kolmafia/utilities/RollingLinkedList.java
- test/net/sourceforge/kolmafia/utilities/RollingLinkedListTest.java
As implemented RollingLinkedList is potentially buggy because the implementation of addAll is provided by LinkedList.  That implementation can change the size of the list beyond the RollingLinkedList size limit.
This PR is part one of two.  The previous version of RollingLinkListTest did cover the code but was clearly driven by relearning how to write tests and by coverage reports.  It was less comprehensible in terms of RollingLinkedList functionality.
This rewrites the test in hopes of improving comprehensibility.  It includes a disabled test that fails because of addAll.
Part two will implement addAll in RollingLinkedList and enable the test.
The goal of part one is to get feedback on the test.
Part two will be along shortly.
> RollingLinkList Test

- src/net/sourceforge/kolmafia/textui/langserver/AshLanguageServer.java
- src/net/sourceforge/kolmafia/textui/langserver/StateCheckWrappers.java
- src/net/sourceforge/kolmafia/textui/langserver/textdocumentservice/AshTextDocumentService.java
- src/net/sourceforge/kolmafia/textui/langserver/workspaceservice/AshWorkspaceService.java
- test/net/sourceforge/kolmafia/textui/langserver/AshLanguageServerTest.java
- test/net/sourceforge/kolmafia/textui/langserver/StateCheckWrappersTest.java
- test/net/sourceforge/kolmafia/textui/langserver/TestLanguageClient.java
The skeleton of the Language Server, as well as StateCheckWrappers, which, like the name suggests, is a wrapper for the server, which takes care of accepting the messages in function of the server's state.
I thought making the tests for it would be simple. HAH. HAHAH. HAHAHAH. I laugh.
HAAAHAHAHA. I laugh some more.
HAAAAAAAAAAAAHHHAHAHAHA.
Kill me.
> Language Server - Outer Shell (StateCheckWrappers)

- data/SVN/svnrepo.json
What it says. zarqon has incorporated this functionality into clilinks.
> Remove Drag-n-Drop Inventories since it is obsolete

- src/net/sourceforge/kolmafia/request/FightRequest.java
Scrolling through this long function, it was always unclear whether you were writing code that is run every combat round or only in the final round because that splitting point was achieved by an early return - it was not implied to be conditional by indentation or something similar.
This should result in no difference of behaviour, but just split up a long function and make development easier (for example, my IDE tells me what the name of the function I'm currently editing is)
> Split out part of updateCombatData that only applies in a final round

- src/net/sourceforge/kolmafia/AscensionClass.java
- src/net/sourceforge/kolmafia/textui/DataTypes.java
- src/net/sourceforge/kolmafia/textui/parsetree/ProxyRecordValue.java
- src/net/sourceforge/kolmafia/textui/parsetree/Type.java
- test/root/expected/test_class.ash.out
- test/root/scripts/test_class.ash
`$class[none]` was also causing NPEs when dumped
> Fix some issues around Astral Spirit appearing in $classes

- src/net/sourceforge/kolmafia/utilities/WikiUtilities.java
- test/net/sourceforge/kolmafia/utilities/WikiUtilitiesTest.java
One bug found and fixed (zmobie).
Would it be better to put all the custom cases (e.g. ice porter) in the modifiers.txt under "Wiki Name"? I feel like it would, but that's less obvious.
> tests: more wiki utilities tests

- src/net/sourceforge/kolmafia/svn/SVNManager.java
"bogus dependency" stopped being useful when it started happening.
The other message might never be seen because SVN throws exceptions but logging something is better than silence.
> A couple of SVN messages

- src/net/sourceforge/kolmafia/textui/javascript/EnumeratedWrapperPrototype.java
We were caching EnumeratedWrapperPrototypes based on their scope and never cleaning them up, which in turn meant we held a reference to the entire scope of a defunct JS interpreter. This meant every JS script run held on to all the relevant information forever.
There is no actual reason for us to cache this information (we were never looking it up later). I think it was vestigial from earlier work on the JS interpreter. So the solution is just to remove the cache altogether.
> Close substantial memory leak in EnumeratedWrapperPrototype.

- src/data/inebriety.txt
Four data points:
Drinking 1 Doc's Special Reserve Wine...
You gain 6 Adventures
You gain 27 Beefiness
You gain 28 Magicalness
You gain 29 Smarm
You acquire an effect: Fixed Right Up (40)
You gain 1 Drunkenness
Finished drinking 1 Doc's Special Reserve Wine.
drink 1 Doc's Special Reserve Wine
You gain 6 Adventures
You gain 30 Beefiness
You gain a Muscle point!
You gain 28 Magicalness
You gain 26 Roguishness
You gain a Moxie point!
You acquire an effect: Fixed Right Up (40)
You gain 1 Drunkenness
You lose some of an effect: Ode to Booze (-1)
drink 1 Doc's Special Reserve Wine
You gain 6 Adventures
You gain 29 Beefiness
You gain 24 Wizardliness
You gain 28 Roguishness
You acquire an effect: Fixed Right Up (40)
You gain 1 Drunkenness
You lose some of an effect: Ode to Booze (-1)
drink 1 …
> consumption stats for Doc's Special Reserve Wine

- src/data/combats.txt
I'm hoping to boost the combat rate in friar zones to match a change in the game.
According to the wiki:
> On January 1, 2020, {Olive My Love To You, Oh. | I, Martin | A Secret, But Not the Secret You're Looking For} was added, the combat rate was increased from 90% to 95%, and the superlikely adventures were changed to occur 5 turns after the previous one rather than spending a flat number of turns in the zone overall (thus improving consistency).
> increasing combat rate in friar zones

- src/net/sourceforge/kolmafia/AdventureResult.java
- test/net/sourceforge/kolmafia/AdventureResultTest.java
Don't know what causes this, probably a threading issue where `KoLConstants.inventory` is changing out from under `getCount`.
> fix: rare NPE in getCount

- src/net/sourceforge/kolmafia/request/AdventureRequest.java
Handle redirect for community service tests to both council.php & ascend.php
Add logging for unhandled redirect before aborting so it's easier to fix these in the future
>  Community service choice redirects

- src/net/sourceforge/kolmafia/swingui/ItemManageFrame.java
When creating the Storage panel for the Item Manager, if you are in Ronin, set the "movers" radio button to "exactly one" rather than the default "multiple".
> In Ronin, you can only pull one of an item

- src/net/sourceforge/kolmafia/KoLmafiaCLI.java
- test/net/sourceforge/kolmafia/textui/command/HelpCommandTest.java
Currently, typing `help refresh` does not work as expected. These lines of code improperly intercept the keyword refresh and alter the inputted command in undesirable ways for all other commands as well such that any command of the form `command refresh` will attempt to run the refresh command instead.
Currently:
```
> help refresh
help cannot be refreshed.
> genie refresh
genie cannot be refreshed.
```
With this change:
```
> help refresh
refresh all | [status | effects] | [gear | equip | outfit] | inv | camp | storage | [familiar | terarrium] | stickers | quests | shop - resynchronize with KoL.
> refresh genie
genie cannot be refreshed.
> genie refresh
(no output)
```
> Remove improper handling for the refresh command

- .github/workflows/check.yml
Previously we were inadvertently hard-coding 17 as the Java
version. This was not great for maintaining Java 11 compatibility
as we purported to do.
> Actually use java version in matrix.

- src/net/sourceforge/kolmafia/AdventureResult.java
- src/net/sourceforge/kolmafia/AreaCombatData.java
- src/net/sourceforge/kolmafia/CakeArenaManager.java
- src/net/sourceforge/kolmafia/Expression.java
- src/net/sourceforge/kolmafia/FamiliarData.java
- src/net/sourceforge/kolmafia/KoLAdventure.java
- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/KoLmafia.java
- src/net/sourceforge/kolmafia/KoLmafiaASH.java
- src/net/sourceforge/kolmafia/KoLmafiaCLI.java
- src/net/sourceforge/kolmafia/KoLmafiaGUI.java
- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/MonsterData.java
- src/net/sourceforge/kolmafia/PastaThrallData.java
- src/net/sourceforge/kolmafia/RequestEditorKit.java
- src/net/sourceforge/kolmafia/RequestLogger.java
- src/net/sourceforge/kolmafia/SpecialOutfit.java
- src/net/sourceforge/kolmafia/Speculation.java
- src/net/sourceforge/kolmafia/StaticEntity.java
- src/net/sourceforge/kolmafia/VYKEACompanionData.java
- src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java
- src/net/sourceforge/kolmafia/textui/langserver/textdocumentservice/AshTextDocumentService.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/ExpressionTest.java
- test/net/sourceforge/kolmafia/FamiliarDataTest.java
- test/net/sourceforge/kolmafia/KoLCharacterTest.java
- test/net/sourceforge/kolmafia/ModifierExpressionTest.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
- test/net/sourceforge/kolmafia/request/EatItemRequestTest.java
- Add tests for Expression and ModifierExpression
- Fix some things that are broken (no one noticed that `path()` just didn't work, for example)
- Avoid string concatenation in loops in expression
- Do some simple performance improvements (like using `isBlank()` instead of comparing to a blank string)
- Remove some unnecessary iteration by using `addAll` etc
> Tests for Expression and ModifierExpression + some performance stuff

- test/internal/helpers/Cleanups.java
- test/internal/helpers/Maximizer.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerRegressionTest.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
`KoLCharacter.reset(true)` is pretty slow (in part due to `KoLCharacter.currentModifiers.resetModifiers()`, which parses the entire `modifiers.txt` file again).
For maximizer tests (the ones I work on the most), do a more targeted teardown, focusing on restoring exactly what was set up to the baseline.
Also split out the regression tests to a different file.
> tests: speed up maximizer tests

- src/net/sourceforge/kolmafia/textui/javascript/EnumeratedWrapperPrototype.java
- src/net/sourceforge/kolmafia/textui/javascript/JavascriptRuntime.java
This is in addition to global scope; will allow usage in environments where Element and Location cause conflicts with globally-defined DOM constructors.
> Expose JS enumerated types on runtime library.

- src/net/sourceforge/kolmafia/Modifiers.java
- test/net/sourceforge/kolmafia/ModifierExpressionTest.java
Fix bug where self-doubling effects were tending to infinity
> Mods doubling selves

- src/net/sourceforge/kolmafia/swingui/panel/ItemManagePanel.java
- src/net/sourceforge/kolmafia/swingui/widget/ListCellRendererFactory.java
- src/net/sourceforge/kolmafia/swingui/widget/TableCellFactory.java
- test/net/sourceforge/kolmafia/request/StorageRequestTest.java
Since the Storage pane of the Item Manager provides a button to move selected items from storage to mall, we can't simply hide items that have already been pulled today in Ronin. Instead, display the item name with a <s>strikethrough</s>.
I also provided one more test for the StorageRequest: verify that given a long list of items to pull, it puts only 11 per subinstance.
> Do not hide pulled-today items. Display them with a strike-through

- src/net/sourceforge/kolmafia/session/InventoryManager.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
This will return the price that is used when calling `acquire` or `retrieve_item` for the "cheapest" way to acquire said item.
Some things to be aware of how acquire works:
* `valueOfInventory` is taken into account for items in your inventory that determines how an item in your inventory affects the retrieve price. This is a float value that defaults to 1.8 so you may want to set this to 1.0 so it matches mall price.
* historical price is usually used (7 day max) but it will mall search on occasion if the prices are within a 2x threshold of each other to get a more exact difference.
> InventoryManager.priceToAcquire as retrieve_price

- src/net/sourceforge/kolmafia/persistence/HolidayDatabase.java
Is this a thing? Does the order here matter for some operating systems?
> Move ROLLOVER prop to before static initialization block

- src/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanel.java
Occured when doing something in the relay browser while having the consumables pop-up open, once.
"strange" because I can't see how this could happen -- the null field is non-static and populated in the constructor, and you can't only have the filter field without the rest of it... I think?
Anyway, checking for null should make it no longer happen.
```
Unexpected error, debug log printed.
class java.lang.NullPointerException: Cannot load from object array because "this.this$0.filters" is null
java.lang.NullPointerException: Cannot load from object array because "this.this$0.filters" is null
at net.sourceforge.kolmafia.swingui.panel.UseItemEnqueuePanel$ConsumableFilterField.isVisible(UseItemEnqueuePanel.java:709)
at net.java.dev.spellcast.utilities.LockableListModel.updateSingleFilter(Locka …
```
> fix: strange potential NPE

- test/internal/helpers/Maximizer.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Move the tests into nested classes for better ordering. Add tests for synergies and gelatinous noob.
Some tests are disabled. 
* At least one is definitely a Mafia bug (outfits should work in gel noob, but don't).
* one is very weird (gel noob sometimes doesn't recommend absorbing items, but I can't see why). To be more specific, it recommends absorbing a disco mask on "moxie", but not a helmet turtle on "muscle".
* the remaining one looks to also be a Mafia bug: Mafia no longer recommends Flaskfull of Hollow, even on a simple "muscle" maximization. It definitely used to, though.
> More Maximizer tests: synergies & gelatinous noob

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/persistence/ItemFinder.java
- src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java
- src/net/sourceforge/kolmafia/textui/command/StorageCommand.java
- test/net/sourceforge/kolmafia/persistence/ItemFinderTest.java
I added an extensive test suite for ItemFinder
I may add to it, once coverage runs, and I can see where it falls short.
Fixed ItemFinder issues:
- N meat -- "meat" is no longer case sensitive
- Fix NOOB skill filter
- Remove unreachable code (low level "parse one item name" code no longer worries about receiving a comma separated list of names)
- When temporarily changing a preference, put inside try/finally
- When looking for items in storage, they might be in freepulls
Fixed StorageCommand issue:
- In Hardcore, only search freepulls list
- Otherwise, search storage list - and assume ItemFinder will find it on freepulls, if necessary
> Item finder fixes

- src/net/sourceforge/kolmafia/ImageCachingEditorKit.java
- src/net/sourceforge/kolmafia/swingui/widget/RequestPane.java
I had a chat with @cdmoyer who noticed that for some reason the top 3 resource requests (by a huge margin) were to the images for hp, new age healing crystals and gold nuggets. I realised that said images show up in the GCLI when you are volcano farming with preference logging activated.
GCLI was not using the cached image renderer and I think every time it was redrawn it was pulling images from the KoL servers for all the images it was displaying. This PR should fix that.
> Use image caching in GCLI

- src/net/sourceforge/kolmafia/textui/command/AbsorbCommand.java
- src/net/sourceforge/kolmafia/textui/command/HeistCommand.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/textui/command/AbsorbCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/HeistCommandTest.java
When [farming in Gel Noob](http://forums.kingdomofloathing.com/vb/showthread.php?t=248197) you want to kick off the day by absorbing 15 of a single item. Extend the "absorb" command to allow this (most of the logic was there already).
Use the same item parsing function in `heist`, now that I know what it is.
Tested manually.
> feat: extend absorb to allow 'absorb X item'

- test/net/sourceforge/kolmafia/request/ScrapheapRequestTest.java
[Jenkins](https://ci.kolmafia.us/job/Kolmafia/) is currently failing after the banish PR. Looks like an action-at-a-distance test issue.
Use the choice manager in the currently failing test instead of just setting a property on it.
> tests: hopefully fix jenkins build

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/request/GenericRequest.java
- src/net/sourceforge/kolmafia/swingui/LoginFrame.java
Instead of being read, it was always false, so don't store it or allow it to change.
> refactor: remove unused allowSocketTimeout preference

- src/net/sourceforge/kolmafia/textui/command/RefreshStatusCommand.java
I wanted to be able to refresh only the clan stash from the CLI, this adds that functionality.
> add refresh stash command to CLI

- test/net/sourceforge/kolmafia/extensions/ClearSharedStateBefore.java
Possibly fix Jenkins. Not sure how it's getting more or less combat chance, but it must be from something leaking from Daily Deeds test, and preferences is all I can see there.
> tests: clear preferences in shared state helper

- src/data/monsters.txt
- src/net/sourceforge/kolmafia/request/FightRequest.java
... from Crowther and me.
I also made FightRequest notice and log when your locket refuses to copy a monster.
For spading.
I suppose that will be redundant, by and by, but it will let us discover new NOCOPY monsters in the session log, even if you didn't notice it as it was happening.
> mark a bunch of monsters NOCOPY based on locket data

- test/net/sourceforge/kolmafia/request/AscensionHistoryRequestTest.java
- test/net/sourceforge/kolmafia/request/MallPurchaseRequestTest.java
- test/net/sourceforge/kolmafia/request/ProcessAcquiredItemsTest.java
- test/net/sourceforge/kolmafia/request/ScrapheapRequestTest.java
- test/net/sourceforge/kolmafia/request/StorageRequestTest.java
https://kolmafia.us/threads/migration-from-http-1-1-to-http-2-0.27303/ will involve redoing some of the base class, better to have it used in fewer places.
> tests: only extend requesttestbase where used

- src/net/sourceforge/kolmafia/RequestLogger.java
- src/net/sourceforge/kolmafia/request/GenericRequest.java
- src/net/sourceforge/kolmafia/request/MallSearchRequest.java
- test/net/sourceforge/kolmafia/request/MallSearchRequestTest.java
- test/net/sourceforge/kolmafia/session/MallPriceManagerTest.java
These:
mallsearch shop #1053259
mallsearch "black & tan"
mallsearch "tea"
mallsearch tea
mallsearch tea (page 2)
mallsearch tea (page 3)
mallsearch tea (page 4)
mallsearch category food [EPIC]
mallsearch category food [awesome, EPIC]
mallsearch category food [awesome, EPIC] (page 2)
are better than:
mall.php?didadv=1&pudnuggler=&category=food&food_sortitemsby=name&booze_sortitemsby=name&othercon_sortitemsby=name&consumable_byme=0&hats_sortitemsby=name&shirts_sortitemsby=name&pants_sortitemsby=name&weapons_sortitemsby=name&weaponattribute=3&weaponhands=3&acc_sortitemsby=name&offhand_sortitemsby=name&wearable_byme=0&famequip_sortitemsby=name&nolimits=0&justitems=0&sortresultsby=price&max_price=0&x_cheapest=0&consumable_tier_1=0&consumable_tier_2=0&consumable_tier_3=0&consumable_tier_4=0&cons …
> Mall search logger

- src/net/sourceforge/kolmafia/RequestLogger.java
- test/net/sourceforge/kolmafia/request/MallSearchRequestTest.java
Should cover the last few lines from the last commit.
Also, MallSearchRequest has a variable "wasLastRequestSimple" which it sets to true for everything except raw URLs.
It uses it to decide if it needs to print a blank line before printing a raw URL. All real requests are "not simple".
Fix this for MallSearchRequest.
> Add a few more tests to improve coverage. MallSearchRequest is not 'simple'

- src/data/items.txt
- src/data/modifiers.txt
- src/data/statuseffects.txt
- src/net/sourceforge/kolmafia/request/AfterLifeRequest.java
- src/net/sourceforge/kolmafia/request/SpleenItemRequest.java
- src/net/sourceforge/kolmafia/textui/command/GooSkillsCommand.java
1) Cold Medicine Cabinet spleen items are all multi-usable
2) Therefore, when use more than one, charges multiply by count of pills used
3) Fix modifier formulae for Gravitational Compression and Hivemindedness
4) When ascend into Grey You run, you are a Grey Goo, not (Class 27)
5) Default sort order for gooskills command is now item, not id
6) Ignore case when comparing Goo Skills by name
> Fix miscellaneous small data errors

- src/net/sourceforge/kolmafia/request/GenericRequest.java
- src/net/sourceforge/kolmafia/utilities/FileUtilities.java
- test/internal/network/FakeHttpClient.java
- test/internal/network/FakeHttpResponse.java
Continuation of #639.
Some changes to test classes to try to aid in writing tests, though I've not managed to get one done yet.
Found it difficult to tell when FileUtilities was being used, but I got lowercase headers from Cloudflare when requesting images, so I think probably then.
> feat: use http client in FileUtilities

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/AscensionPath.java
- src/net/sourceforge/kolmafia/KoLAdventure.java
- src/net/sourceforge/kolmafia/persistence/AscensionSnapshot.java
- src/net/sourceforge/kolmafia/preferences/Preferences.java
- src/net/sourceforge/kolmafia/request/FightRequest.java
- src/net/sourceforge/kolmafia/session/ChoiceManager.java
- src/net/sourceforge/kolmafia/session/GreyYouManager.java
- src/net/sourceforge/kolmafia/textui/command/AbsorptionsCommand.java
- test/net/sourceforge/kolmafia/session/GreyYouManagerTest.java
Minor cleanups.
1) When in Grey You, after a fight which you win, register the monster absorption, as needed.
2) In the following cases, log a message both to gCLI and session log:
- Learned an unknown Grey You skill
- A Grey Goo "passive" skill does not have an entry in modifiers.txt 
- Found an unknown "significant" Grey Goo absorption on the charsheet
These all require a KoLmafia fix.
3) Don't need to refresh absorptions in "absorptions" command, since we read them from char sheet and update them appropriately when we absorb a monster.
4) When you try to visit a zone which is too old (per Standard restrictions), recognize that and don't count it as a visited location.
5) When free king after Grey You, you go through a choice adventure to choose a new class. Handle it in the usual way …
> register absorptions after a won fight

- src/data/familiars.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/AscensionClass.java
- src/net/sourceforge/kolmafia/AscensionPath.java
1) grey gosling hatches into a Grey Goose
2) Thwaitgold protozoa statuette. "Not yet implemented", but we know item Id and desc id
3) Correct the class and path images on the Ascension History.
This fixes the NPE when looking at your ascension history
4) Derive Arena parameters for Grey Goose
5) Derive Arena parameters for Arachnelf
(I found something useful to do in Grey You aftercore. :)
> New items, familiar. fix path images. Arena parameters

- src/net/sourceforge/kolmafia/utilities/StringUtilities.java
- test/net/sourceforge/kolmafia/utilities/StringUtilitiesTest.java
Hopefully fixes https://kolmafia.us/threads/item-manager-doesnt-work.27370/#post-167323. Last-Modified HTTP headers need to be in English.
The only non-header use of parseDate / formatDate was in `CacheCommand`. I figured it was easier to just always make it use English.
> fix: parse and store Last-Modified headers in English

- build.gradle
- test/internal/network/FakeHttpClient.java
- test/internal/network/FakeHttpClientBuilder.java
- test/net/sourceforge/kolmafia/persistence/MallPriceDatabaseTest.java
> tests: add test for mall HTTP POST

- src/net/sourceforge/kolmafia/objectpool/Concoction.java
- src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java
- src/net/sourceforge/kolmafia/swingui/ItemManageFrame.java
- src/net/sourceforge/kolmafia/swingui/panel/UseItemDequeuePanel.java
- src/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanel.java
- test/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanelTest.java
Refactor GUI panels to have a ConcoctionType enum rather than three mutually exclusive booleans
UseItemEnqueuePanel and UseItemDequeuePanel handle the list of "usables" from ConcoctionDatabase.
Each such panel can (mutually exclusively) be {food, booze, spleen, potions}.
They - and ConctionDatabase - are full of methods like this:
method(boolean food, boolean booze, boolean spleen)
FOOD = true, false, false
BOOZE = false, true, false
SPLEEN = false, false, true
POTION = false, false, false
I made an enum:
```
public static enum ConcoctionType {
FOOD,
BOOZE,
SPLEEN,
POTION;
}
```
and did a mass refactoring for all those methods to simply take one of these as an argument.
I have no idea how to write unit tests for GUI classes.
> Simplify Panels that handle ConcoctionDatabase.usables

- test/net/sourceforge/kolmafia/utilities/StringUtilitiesTest.java
Some comments I had on #616, implemented.
* replace char[] with String
* remove the explicit catch-failure on exceptions, and just let them be thrown to fail the test
* use `List.of` for expected
> tests: simplify some string utilities tests

- src/net/sourceforge/kolmafia/request/GenericRequest.java
- src/net/sourceforge/kolmafia/utilities/FileUtilities.java
Spun out of https://kolmafia.us/threads/getting-an-error-unable-to-log-in.27387/#post-167382
On earlier versions of Java 11 this isn't valid to do, and does no harm
to omit.
Remove code dealing with pics.communityofloathing.com, which no longer
resolves.
> fix: don't set the HTTP referer header

- src/net/sourceforge/kolmafia/request/GenericRequest.java
- src/net/sourceforge/kolmafia/request/RelayRequest.java
- src/net/sourceforge/kolmafia/webui/RelayAgent.java
* on a pseudo-response, the Date header had the wrong format
* on a pseudo-response, leave it up to the browser as to whether or not to close the connection
* log more information in case of IOException, to try to track down why that happens sometimes
> Further Http Headers work

- src/net/sourceforge/kolmafia/request/RelayRequest.java
HTTP/2 requests made under HttpClient may return pseudo-headers (e.g. ":status", ":version").
When proxying headers from KoL, don't include these headers.
> fix: ignore pseudo-headers

- src/net/sourceforge/kolmafia/request/GenericRequest.java
Detect, by error message, certain errors as transient and treat them as timeouts.
Related to https://kolmafia.us/threads/ioexception-goaway-received.27397/.
> feat: retry transient IOExceptions on requests

- src/net/sourceforge/kolmafia/session/ChoiceManager.java
- test/net/sourceforge/kolmafia/session/ChoiceManagerTest.java
- test/root/request/test_choice_manager_unknown_tomb_1.html
- test/root/request/test_choice_manager_unknown_tomb_2.html
- test/root/request/test_choice_manager_unknown_tomb_3.html
On the Nemesis Quest, the first task is to retrieve your Epic Weapon from the Tomb of the Unknown CLASS.
You adventure in the Unquiet Garves until you encounter the tomb.
On the door is a riddle with three (class-specific) answers.
The order of the answers (i.e. the choice option #) is shuffled every time you refresh the page.
ChoiceManager has special handling for automating this choice to choose the (currently) correct option.
This test has three saved HTML files with the correct answer in option 1, option 2, and option 3.
It verifies that we pick the correct option in each case.
> Added tests for dynamic choice options for the Unknown Tomb

- src/net/sourceforge/kolmafia/objectpool/Concoction.java
- src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java
- src/net/sourceforge/kolmafia/webui/UseLinkDecorator.java
When I was looking at how ConcoctionDatabase.usableList was implemented, I noted some unnecessarily specify datatypes.
1) Concoction.queue() took two List parameters. They were specified to be a LockableListModel and an ArrayList - only because the caller of that in ConcoctionDatabase just happened to have data of those particular types. queue() cares only that it receives a List. Change the parameter types to such.
2) ConcoctionDatabase.usableList is a LockableListModel<Concoction>.
That is fine, since a LockableListModel can be used as the model in a JList.
ConcoctionDatabase.creatableList was a SortedListModel<Concoction>
A SortedListModel is a LockableListModel that is re-sorted every time it changes.
That's expensive, but if you want your list to be sorted, OK, I guess.
It turns out …
> rationalize data types in Concoction and ConcoctionDatabase

- src/net/sourceforge/kolmafia/session/ResultProcessor.java
Mr. Cheeng's spectacles can cause Goblin Water to drop, causing the ResultProcessor to finish the Goblin King quest.  Without fixing it comepletely, I closed the hole for all other paths.
> Do not finish Q5 with Goblin Water unless in Heavy Rains

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/KoLConstants.java
- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/combat/Macrofier.java
- src/net/sourceforge/kolmafia/request/DrinkItemRequest.java
- src/net/sourceforge/kolmafia/request/EatItemRequest.java
- src/net/sourceforge/kolmafia/request/FightRequest.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/webui/StationaryButtonDecorator.java
- test/net/sourceforge/kolmafia/FamiliarDataTest.java
- test/net/sourceforge/kolmafia/session/YouRobotManagerTest.java
KoLConstants.availableCombatSkills was a LockableListModel of UseSkillRequests.
It was never used in a JList, so need not be a ListModel.
Combat skills cannot be cast using a UseSkillRequest.
Its ONLY use is to pass the list of skillIds from the fight.php skill dropdown to StationaryButtonDecorator.
KoLConstants.availableCombatSkillsMap was an IdentityMap of skillIds.
KoLConstants.availableSkillsMap was an IdentityMap of skillIds.
They could simply be sets.
KoLCharacter.hasSkill is ONLY used to look up skills in availableSkills.
KoLCharacter.availableCombatSkills is ONLY used to look up combat skills.
In both cases, UseSkillRequests were generated and passed to a method which looked up skillIds in the skill Maps.
1) KoLConstants.availableSkillsMap is now KoLConstants.availableSkillsSet …
> rationalize availableCombatSkills

- src/net/sourceforge/kolmafia/request/RelayRequest.java
From https://kolmafia.us/threads/getting-mafia-started-help-please.27407/#post-167510.
After getting past here, it hits the `System.exit` in [`KoLmafia.java`, line 286](https://github.com/kolmafia/kolmafia/blob/c1b3ad79a1b9126450162b077a2d98aa0f533f77/src/net/sourceforge/kolmafia/KoLmafia.java#L286). This means we get a message "Could not acquire file lock" right at the end, which might be helpful if it happens again in the future?
> fix: avoid NPE on start with unwritable folder

- src/net/sourceforge/kolmafia/request/RelayRequest.java
- src/net/sourceforge/kolmafia/swingui/ChatFrame.java
- src/net/sourceforge/kolmafia/swingui/menu/GlobalMenuBar.java
For links that use cached HTTP clients, there should be a tiny speed boost in that we avoid the "try HTTP/2, no it's HTTP/1.1, okay we were redirected to https, now try HTTP/2" malarkey.
For the ones that open in the browser, preferring HTTPS where stable seems good practice.
> feat: use HTTPS for hardcoded KOL links

- src/net/sourceforge/kolmafia/maximizer/MaximizerSpeculation.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerRegressionTest.java
For a long time, I've encountered a weird issue involving the buddy bjorn and the maximizer that I've had a hard time describing and duplicating. No longer!
I've also had issues when assigning a bonus value to the buddy bjorn rather than using +equip, although I had a much harder time writing a failing test for that.
> Fix maximizer behavior with force-equipping empty bjorns (and crowns)

- src/net/sourceforge/kolmafia/textui/parsetree/Try.java
- test/root/expected/test_finally_return.ash.out
- test/root/scripts/test_finally_return.ash
```
int test( int input )
{
try {
print("You gave me " + input);
} finally {
if (input == 100) {
int output = input + 1;
print("I prefer " + output);
return output;
}
}
print("Good enough!");
return input;
}
print("I received " + test(50));
print("I received " + test(100));
```
yields
```
> finally.ash
You gave me 50
Good enough!
I received 50
You gave me 100
I prefer 101
Good enough!
I received 100
```
I don't like that. Now it yields
```
> finally.ash
You gave me 50
Good enough!
I received 50
You gave me 100
I prefer 101
I received 101
```
which is what I expected, when I wrote that code.
> a finally clause is allowed to do a function return

- src/net/sourceforge/kolmafia/RequestEditorKit.java
- src/net/sourceforge/kolmafia/persistence/ScriptManager.java
- src/net/sourceforge/kolmafia/request/ChatRequest.java
- src/net/sourceforge/kolmafia/request/GenericRequest.java
- src/net/sourceforge/kolmafia/session/BuffBotManager.java
- src/net/sourceforge/kolmafia/swingui/MaximizerFrame.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/textui/command/TestCommand.java
- src/net/sourceforge/kolmafia/textui/command/WumpusCommand.java
- src/net/sourceforge/kolmafia/utilities/FileUtilities.java
- src/net/sourceforge/kolmafia/utilities/LogStream.java
- src/net/sourceforge/kolmafia/utilities/StringUtilities.java
- test/net/sourceforge/kolmafia/utilities/StringUtilitiesTest.java
Eliminate two `StringUtilities` methods that are unnecessary if charsets are used.
> refactor: use standard charsets over charset names

- src/net/sourceforge/kolmafia/AreaCombatData.java
A for loop was replaced by a stream in PR 326.
It's pretty, but it dropped a factor in the calculation.
This restores it.
> restore (accidentally deleted) factor in getAdverageML

- src/net/sourceforge/kolmafia/textui/Parser.java
Relates to https://kolmafia.us/threads/starting-mafia-with-a-script-on-the-command-line.27442/#post-167643
This should allow the error message to be printed to the screen.
> fix: avoid unexpected error in error case with no stream

- src/net/sourceforge/kolmafia/persistence/ItemFinder.java
- test/net/sourceforge/kolmafia/persistence/ItemFinderTest.java
Relates to https://kolmafia.us/threads/csend-with-commas-acts-unexpectedly-when-sending-meat.27447/
"0 meat" now parses as no meat, instead of all your meat. * continues to be all. -X continues to be all but X.
> feat: stop zero meaning all for meat

- src/net/sourceforge/kolmafia/persistence/ItemFinder.java
- src/net/sourceforge/kolmafia/textui/command/ClosetCommand.java
- test/internal/helpers/Player.java
- test/internal/listeners/FakeListener.java
- test/internal/network/FakeHttpClient.java
- test/internal/network/RequestBodyReader.java
- test/net/sourceforge/kolmafia/persistence/MallPriceDatabaseTest.java
- test/net/sourceforge/kolmafia/textui/command/ClosetCommandTest.java
There was a small problem with #699: I didn't reset the client between calls, so somehow it was winding up with different clients. Don't understand that because the builder was instantiated once in the test class (and the client against never reinstantiated), so it should have been the same client, but it wasn't.
That's fixed, enough tests have been added to cover the class (though this doesn't cover all the functionality -- e.g. passing multiple items, meat counts is not done because I haven't yet managed to get the request text, and I need that to write a meaningful test).
Small refactoring to use streams.
> tests: cover closet command, refactor

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/session/BastilleBattalionManager.java
- src/net/sourceforge/kolmafia/session/ChoiceManager.java
- test/net/sourceforge/kolmafia/session/BastilleBattalionManagerTest.java
I've been playing Bastille Battalion with two characters and have been manually recording details of battles: which round, which stance I choose, whther I ended up being offensive or defensive, castle type, and so on.
It would be nice for KoLmafia to save that data for me in a file which I can load into an ASH script to analyze.
Assuming you have set "logBastilleBattalionBattles" to true, "data/Bastille.battles.txt" will be loadable via file_to_map.
```
record battle {
int number;         // Affects strength of enemy
int [6] stats;      // MA/MD/CA/CD/PA/PD
string boosts;      // MCP
string enemy;       // {frenchcastle,masterofnone,bigcastle,berserker,shieldmaster,barracks}
string stance;      // {offensive,waiting,defensive}
boolean aggressor;  // as opposed to defender
boolean …
```
> optionally save battle details in Bastille.battles.txt

- build.gradle
This should create an install in C:\Users\ instead of C:\Program Files\.
See https://kolmafia.us/threads/exe-and-dmg-builds-dont-work-anymore.27408/#post-167736 for more context.
> Specify --win-per-user-install for exe builds.

- src/net/sourceforge/kolmafia/Modifiers.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
Relates to https://kolmafia.us/threads/irregular-combat-rate-modifiers-interact-poorly-with-the-soft-cap.27478/
Modifiers incremented capped values one at a time: for example, adding nine twice added one twice when over the soft cap (as 9 // 5 = 1). However, adding nine twice should add three total, as 18 // 5 = 3.
This changes COMBAT_RATE to store the uncapped combat rate, and `get` to return the capped one when called.
> fix: combat rate stacks in non multiples of 5

- src/net/sourceforge/kolmafia/Modifiers.java
Right now,` numericModifier("Combat Rate")` and `numericModifier("combat rate")` return different values when you're past the cap of 25, because we only are special casing the input "Combat Rate".
> make Combat Rate case insensitive

- src/net/sourceforge/kolmafia/textui/command/SkeletonCommand.java
- test/net/sourceforge/kolmafia/textui/command/SkeletonCommandTest.java
Similar to #714, this is a proof of concept for what I'd eventually like `Modifiers` to look like: only allowing enum values instead of ints or strings.
Avoid casts by moving away from `Object[][]`.
> refactor: skeleton command

- src/net/sourceforge/kolmafia/request/GenericRequest.java
Initially, I thought GOAWAY meant that the request wasn't handled at all, but someone on Discord reported accidentally hitting the Chateau twice after the HTTP2 move. While I can't be sure this is GOAWAY, it's safer to only retry if it's safe to do so.
> fix: only retry if it's safe, even on GOAWAY

- .git-blame-ignore-revs
GitHub offers [a standardized file to ignore certain revisions when running blame](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view).
Ignore the mass application of spotless.
> chore: ignore blame rev for spotless

- src/net/sourceforge/kolmafia/session/LoginManager.java
After a user logs in, show a warning if they're running a version less than 17.
This will show in the CLI and also in the adventure frame (the default main frame) until the user takes another action.
> feat: show warning after login for versions less than 17

- src/net/sourceforge/kolmafia/request/ZapRequest.java
- src/net/sourceforge/kolmafia/textui/command/ZapCommand.java
- test/internal/helpers/HttpClientWrapper.java
- test/net/sourceforge/kolmafia/textui/command/AbsorbCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/AutoSellCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/ClanStashCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/ClosetCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/RefreshStatusCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/SendMessageCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/SkeletonCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/ZapCommandTest.java
Make zap command accept counts of items, and not make requests for 0 items.
While doing this, I noticed that the zap command silently fails if the user doesn't have a wand. There's a check in `ZapRequest` that would cover this, but it isn't hit due to an earlier error case being hit. I left it as it was.
> feat: make zap command aware of counts

- src/net/sourceforge/kolmafia/listener/ItemListenerRegistry.java
- src/net/sourceforge/kolmafia/listener/ListenerRegistry.java
- src/net/sourceforge/kolmafia/listener/PreferenceListenerRegistry.java
- src/net/sourceforge/kolmafia/textui/command/ItemTraceCommand.java
- src/net/sourceforge/kolmafia/textui/command/PrefTraceCommand.java
- test/internal/helpers/Player.java
- test/internal/helpers/RequestLoggerOutput.java
- test/net/sourceforge/kolmafia/persistence/DebugDatabaseTest.java
- test/net/sourceforge/kolmafia/textui/command/AbstractCommandTestBase.java
- test/net/sourceforge/kolmafia/textui/command/ItemTraceCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/PrefTraceCommandTest.java
I changed it so you can trace any item, not just those currently in your inventory.
Item Trace had some interesting behaviour: cancelling a previous trace didn't take effect until garbage collection ran. I fixed this too.
> tests: add test for item trace

- src/net/sourceforge/kolmafia/textui/command/RecipeCommand.java
- test/net/sourceforge/kolmafia/textui/command/IngredientsCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/RecipeCommandTest.java
Consistently don't bold the colon, and add a number to the start of the list even in the "uncreatable" condition.
> Add tests for recipe command, improve consistency between `recipe` and `ingredients`

- test/net/sourceforge/kolmafia/textui/command/ItemTraceCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/PrefTraceCommandTest.java
Follow-up to #735 based on comments.
`AfterEach` instead of `BeforeEach` as we want to clear the trace from the final test.
> tests: clear traces after tests

- src/net/sourceforge/kolmafia/swingui/widget/AutoFilterTextField.java
- test/net/sourceforge/kolmafia/swingui/widget/AutoFilterTextFieldTest.java
I was trying out something with InputFieldUtilities and a bunch of strings and noticed weird behavior in AutoFilterTextField, where it was skipping over any upper case letters in the match. I'm pretty sure this was an accident back when it was written, but I admit to not knowing whether anything relies on this odd case-sensitive behavior now.
> AutoFilterTextField case sensitivity

- src/net/sourceforge/kolmafia/preferences/Preferences.java
- src/net/sourceforge/kolmafia/request/GenericRequest.java
- src/net/sourceforge/kolmafia/textui/Parser.java
- src/net/sourceforge/kolmafia/textui/command/AshMultiLineCommand.java
- src/net/sourceforge/kolmafia/textui/command/AshSingleLineCommand.java
- src/net/sourceforge/kolmafia/textui/langserver/Script.java
- src/net/sourceforge/kolmafia/utilities/FileUtilities.java
> fix: when getting bytes, always specify an encoding

- src/net/sourceforge/kolmafia/utilities/ResettingHttpClient.java
If the client isn't static, neither should the AtomicInteger be.
Received a GOAWAY just earlier.
It could be the case that this entire fix doesn't actually work. But it can easily be that the wrong client was reset.
And yes, it was on an up to date build.
I think actually testing this would mean spamming KOL ten thousand times, which for obvious reasons isn't really something I'd want to do.
> If the client isn't static, neither should the AtomicInteger be

- src/net/sourceforge/kolmafia/request/LocketRequest.java
As opposed to refreshing session, say. You still can't look at your locket, but it need not abort.
Tested by reminiscing three times and asking for another monster (generating an error) and refreshing session (not generating an error).
> only give error if trying to reminisce more then three times if yoare actually trying to fight a monster

- src/data/maximizer-help.html
- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/maximizer/Evaluator.java
- src/net/sourceforge/kolmafia/maximizer/LetterBonus.java
- test/net/sourceforge/kolmafia/maximizer/LetterBonusTest.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Various PvP minigames relate to properties of equipment like power and letters in the name. This PR starts off by adding a "letter" keyword that can count various letters in the name.
Unfortunately it doesn't work:
* it recommends all potions in inventory with the same score under circumstances I've not been able to figure out
* it doesn't recommend items not in inventory (I think it uses "modifiers" to determine the items checked, and "letter" is not)
Hopefully after I add more tests I'll be able to understand more about how Maximizer works so I can add features like this.
> Add "letter" keyword to maximizer (to prefer longer equipment names)

- src/net/sourceforge/kolmafia/request/FightRequest.java
In trying to spade the decay rate, we noticed the data didn't make any sense. It was confirmed by a dev (cannonfire40) that the base mixers operate on a completely separate roll, and should not count as a drop for the purposes of this. I have removed those familiar messages accordingly.
> remove base mixers from _roboDrops pref

- src/net/sourceforge/kolmafia/chat/ChatFormatter.java
- src/net/sourceforge/kolmafia/chat/StyledChatBuffer.java
- test/net/sourceforge/kolmafia/chat/ChatFormatterTest.java
Highlighting could be loaded multiple times, yet would not be unloaded.
This is generally a non-issue until you remove a chat highlight after reopening mafia's chat relay.
It was also possible to highlight the same string multiple times, the old string is now removed.
Previously, it was possible that highlights that are similar could be removed.
The code was confusing to read, and has been cleaned up a little.
> Chat highlighting improvements

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/request/ApiRequest.java
As Map.entry cannot have null as a parameter, an empty string is provided.
> Add preferences maydayContractOwned & cosmicBowlingBallOwned

- src/data/concoctions.txt
- test/net/sourceforge/kolmafia/objectpool/ConcoctionTest.java
In particular, fancy ingredients indicate that the concoction should
correspond to a fancy CraftingTYpe (MIX_FANCY or COOK_FANCY), and
non-fancy ingredients should correspond to a plain crafting type (MIX
or COOK).
Reported at https://kolmafia.us/threads/27566/ -- thanks TQuilla.
> Audit fancy ingredients vs concoctions.

- src/net/sourceforge/kolmafia/KoLmafia.java
- src/net/sourceforge/kolmafia/session/BastilleBattalionManager.java
A recent PR "Enabled icon images for Windows".
Unfortunately, it changed the Dock icon image on Macs from the friendly and familiar limeglass to a black & white sword and martini guy.
This PR uses the new icon only for Windows, as the other PR seems to intend.
I also fixed a comment in another file.
> keep limeglass icon if not windows. Fix a comment

- src/net/sourceforge/kolmafia/session/BastilleBattalionManager.java
- test/net/sourceforge/kolmafia/session/BastilleBattalionManagerTest.java
When you lose a battle, log cheese as 0, not previous cheese gain.
After the final battle of a game, save _bastilleLastCheese if you won.
After the final battle of a game, log total cheese gained.
Sanity check that KoL's reported amount is the same as what we accumulated in _bastilleCheese
Three "improve offense" encounters also give you cheese.
Don't make a cheese entry if you try to use the wishing well but do not have enough cheese.
> Fix various cheese bugs

- src/net/sourceforge/kolmafia/request/FightRequest.java
Usage is with a lowercase "system" as shown here: https://kol.coldfront.net/thekolwiki/index.php/Daily_dungeon_malware
> Fix Daily Malware usage not detected

- src/net/sourceforge/kolmafia/request/MallPurchaseRequest.java
- src/net/sourceforge/kolmafia/request/RaffleRequest.java
Mall Purchase using Meat from storage tells you your balance. Parse it as a long.
You can purchase raffle tickets using Meat from Storage. Allow total cost to exceed an int. Fool.
> Parse Meat as a long in mall purchase request. Allow purchasing way too many raffle tickets.

- src/data/defaults.txt
Not sure if this is "normal" or a one off tbh. 
To properly check this, would probably need to find every string matching some regex to find every preference set in the code. Then check if it exists in mafia's defaults.
> Add coat of paint to mafia defaults

- src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
For example, in ChoiceAdventures.dynamicChoiceOptions:
```
case 781:
// Earthbound and Down
result = new Option[6];
result[0] = new Option("Unlock Hidden Apartment Building");
result[1] = new Option("Get stone triangle");
result[2] = new Option("Get Blessing of Bulbazinalli");
result[5] = SKIP_ADVENTURE;
return result;
```
> You can have nulls in an array of Options

- src/data/content-types.properties
- src/net/sourceforge/kolmafia/KoLmafia.java
- test/root/expected/content-type-encoding.js.out
- test/root/scripts/content-type-encoding.js
Relates to https://kolmafia.us/threads/java-bug-on-some-versions-of-java-weird-things-happen-to-strings-with-special-characters.27531
Requires testing on non-Windows platforms.
Uses a blank content-types property file to avoid licensing problems: the [version of the file prior to the introduction of text/javascript](https://github.com/adoptium/jdk/blob/3789983e89c9de252ef546a1b98a732a7d066650/src/java.base/windows/classes/sun/net/www/content-types.properties) is distributed under GPLv2 without the classpath exception: as such, bringing it into KoLMafia would make this a derived work, and the combination would also have to be distributed under GPLv2. Using our own file (with no content) avoids this problem.
After https://github.com/mozilla/rhino/issues/1232 is fixed in some way and the fix …
> feat: blank content types to avoid a Rhino problem

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/swingui/panel/CompactSidePane.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
Per Kasekopf's report in kolmafia.us, on the Grey You path:
- your maximum HP and MP start with a particular value
- they improve by absorbing certain monsters and consumables
- they are unaffected by Muscle or Mysticality
- the only enchantments that affect them are +HP or +MP; no percentages or stats improvements
> BUFFED_HP and BUFFED_MP have a different formula in Grey You

- src/net/sourceforge/kolmafia/request/UseItemRequest.java
Do not allow 11-leaf clover use if already Lucky! If you do it in Relay Browser, do not deduct from inventory
> Using 11-leaf clover while already Lucky! is useless

- src/data/monsters.txt
- test/root/scripts/test_attack_element_proxy_fields.txt
Add a number of monster elemental attacks from wiki element pages.
Some monsters were using "E:" for the main element without a corresponding attack (e.g. Beaver). Corrected to "ED".
> feat: elemental attacks from wiki element pages

- src/net/sourceforge/kolmafia/session/InventoryManager.java
When recursively calculating priceToMake - taking into account the price to buy the ingredients - acquire was assuming that the concoction's quantityPossible was greater than 0. I.e. that you had enough "accessible" ingredients to do the creation.
Considering that we are explicitly assuming we are willing to buy ingredients, this is less than useful.
Especially since this was the place where we compared autoBuyPriceLimit against the total cost of buying all the ingredients.
Removing the quantityPossible > 0 check means we can now get this:
```
> acquire? etched hourglass
...
The average amount of meat spent on components (6,496,048) for one etched hourglass exceeds autoBuyPriceLimit (20,000)
etched hourglass: fail
```
Which is more desirable than buying more than 10,000 grains of sand and …
> When checking price to make, do not assume quantityPossible > 0

- src/net/sourceforge/kolmafia/MonsterData.java
- src/net/sourceforge/kolmafia/textui/parsetree/ProxyRecordValue.java
Monsters with poison have a poison level from 1 to 6.
The lower the level, the more severe.
The value for "no poison" is Integer.MAX_VALUE, not 0.
Added $location.poison proxy record field, which is the most virulent poison a monster in that area has.
This is the issue for the following Bug Report:
https://kolmafia.us/threads/mafia-will-not-adventure-without-acquiring-an-anti-anti-antidote.27628/
> Value for no poison is Integer.MAX_VALUE, not 0. add .poison proxy record field

- src/net/sourceforge/kolmafia/session/InventoryManager.java
As in the maximizer, in particular.
It doesn't need to be an error because almost immediately following this, the real "we coulnd't get the item" error message will be printed.
> Don't display "too expensive to create" message if simulating retrieval

- src/data/monsters.txt
- src/net/sourceforge/kolmafia/KoLmafiaCLI.java
- src/net/sourceforge/kolmafia/MonsterData.java
- src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
- src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java
- src/net/sourceforge/kolmafia/textui/command/CheckDataCommand.java
- src/net/sourceforge/kolmafia/textui/command/TestCommand.java
- src/net/sourceforge/kolmafia/utilities/WikiUtilities.java
- test/net/sourceforge/kolmafia/ModifierExpressionTest.java
- test/net/sourceforge/kolmafia/utilities/WikiUtilitiesTest.java
Make Mafia aware of the elements "shadow" and "bad spelling".
Parse wiki pages for elemental attacks, and update Mafia accordingly.
The parsing picks up "X damage", and so will pick up elemental attacks, auras, thorns etc. Not sure if this is what we want long-term but an elemental aura means you want to defend against that element, so it seems reasonable.
> feat: take elemental attacks from the wiki

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
There's a query on kolmafia.us about how the June cleaver choice adventures stop automation and there is no way to configure them. Somebody responded by instructing them to figure out which choice adventures they are, what the various options do, and then to manually set properties in the gCLI.
We considered making those configurable, but you are required to put a default into defaults.txt.
We punted on that since there is not an obvious "best default".
There are two possibilities.
Default of 4 means "skip this choice". If we choose that, you can automate right out the box without having to think about what you want. But you will miss a lot of free stats/adventures/meat/items.
Default of 0 means "show in browser". (You don't actually have to do that; you can do "choice X" in the gCLI to …
> All 9 June cleaver choices are now configurable in GUI

- src/net/sourceforge/kolmafia/request/ClanLoungeRequest.java
Use arrays of specific records instead of arrays of object arrays in ClanLoungeRequest.
Make the arrays package private -- they're not used outside ClanLoungeRequest, and there are public methods for getting the data.
Remove `speakeasyIndexToItem`: there is no item for speakeasy drinks, and this was taking the cost (an int) and casting to an AdventureResult.
> refactor: avoid Object[][] in ClanLoungeRequest

- src/net/sourceforge/kolmafia/textui/command/BarrelPrayerCommand.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/textui/command/BarrelPrayerCommandTest.java
> refactor: remove Object[][] from BarrelPrayerCommand

- build.gradle
also eliminates dependency on antlr and selects the jna version needed by current svnkit - not a later version that doesn't work with it - on my system, at least.
> upgrade svnkit from 1.10.3 to 1.10.6

- src/net/sourceforge/kolmafia/maximizer/Boost.java
- src/net/sourceforge/kolmafia/maximizer/Maximizer.java
Unbreakable umbrella was never passed into the Boost object, so code inside that class never ran.
Did this break anything? No idea. Perhaps it could have caused the umbrella to be set when it should not have been, under some circumstances?
> fix: pass unbreakable umbrella to boost constructor

- src/net/sourceforge/kolmafia/maximizer/Evaluator.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Improve maximizing exp by suggesting the umbrella when ML % offers more exp than anything else.
Might take multiple maximizations to be right because maximizer doesn't consider combinations of equipment (i.e. ML + ML%) properly. Should stabilize after you have some ML to start with though.
> fix: count ml percent when maximizing exp

- gradle.properties
Now that we're on at least 6.7.2, we should be able to remove the
`add-exports` calls.
See
https://github.com/diffplug/spotless/blob/d71bc1812f9fbcabb5cda3e82dac11d7da45e1d5/plugin-gradle/CHANGES.md#671---2022-06-10
> refactor: remove spotless workaround

- src/net/sourceforge/kolmafia/svn/SVNManager.java
- src/net/sourceforge/kolmafia/swingui/ScriptManageFrame.java
Three cases of wonky indentation (and another on another file) and one case of `Object` that can be a concrete type (presumably the relevant method came in a later version).
> chore: fix minor svn manager lints

- src/net/sourceforge/kolmafia/FamiliarData.java
- test/internal/helpers/Networking.java
- test/net/sourceforge/kolmafia/FamiliarDataTest.java
When I worked on improving the compact sidepane for Quantum Terrarium, I noticed it initially showed the incorrect base weight of the familiar. This fixed itself with the next api request.
I discovered that ApiRequest (and CharpaneRequest) were calling a FamiliarData method to check - and "fix" - if KoL's idea of modified familiar weight disagreed with KoLmafia's. It "fixed" it by changing the familiar's base weight. That is incorrect. The base weight is based on experience - and we track that and adjust as necessary.
If we don't do that, that is a KoLmafia bug.
Similarly, if KoL displays a modified weight which disagrees with our calculation, that is a KoLmafia bug.
I removed the adjustment to the base familiar weight - and, sure enough, a user noticed that we did not support Fidoxene. …
> log if KoL's modified familiar weight differs from KoLmafia's

- src/net/sourceforge/kolmafia/FamiliarData.java
- src/net/sourceforge/kolmafia/request/FightRequest.java
- test/net/sourceforge/kolmafia/request/FightRequestTest.java
2 little fixes:
1) When you log in, KoLmafia refreshes your session. The very first thing it does is to fetch api.php to see if it redirects to valhalla. If it does not so-redirect, it parses the status and learns all sorts of stuff about equipment, effects, current familiar, and so on. Note that it has not looked at your char sheet or terrarium yet. Therefore, if you have Amphibian Sympathy, we don't know it, and cannot accurately calculate the modified weight of your familiar.
Therefore, don't check modified weight if you are currently logging in. Subsequent session refreshes work fine.
2) If a familiar is wearing a Snow Suit, it has Familiar Weight +20. Every five combats (up to 75), that decrements by 1, to a minimum of Familiar Weight +5. We track that in a property, and the modifier …
> snow snow suit shrinks, recalculate adjustments

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/request/LatteRequest.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
Lord President reported that KoLmafia was not picking up familiar weight enchantment from his latte lovers member's mug in Gelatinous Noob.
Wiki says this:
- Wearing equipment provides the attack/defense power, but gives no bonuses from regular enchantments.
This includes familiar equipment, Valhalla rewards, rollover adventures.
Unique and unusual enchantments with specially coded effects will generally still work. For example, items like the KoL Con 13 snowglobe that give post-combat drops will activate. Combat skills granted by equipment also remain available, as do outfit bonuses. Choice adventure and quest interactions involving equipment remain unaltered.
Well, OK. I guess the latte lovers member's mug is special.
> latte lovers member's mug grants its enchantments in Noobcore

- .github/workflows/build.yml
- .github/workflows/check.yml
- .github/workflows/codeql-analysis.yml
- build.gradle
In recent PRs, the ubuntu version of the tests lasts over an hour, apparently without making any progress. Guesses have included "something to do with `@AfterAll`" and "something to do with circular imports". In #870, it happened without any test changes being made at all.
Update some stuff (test dependences + github workflow versions) to hopefully improve the circumstances here.
> chore: upgrade some stuff to hopefully make the tests less flakey

- .github/workflows/build.yml
- .github/workflows/check.yml
- .github/workflows/codeql-analysis.yml
Update action versions to latest.
Changes are generally that they run on node 16 instead of node 12, which merited a new major version.
> chore: update action versions

- src/net/sourceforge/kolmafia/session/BanishManager.java
- test/net/sourceforge/kolmafia/session/BanishManagerTest.java
Fixed this issue that people have been complaining about for a while. Ultimately we never want to reset a banish *per monster*, that's not how KoL works on the backend.
Added tests to cover the specific failure that I was fixing, as well as asserting some other things that we want to be true about BanishManager
> Fixing asdon banish

- lib/net/java/dev/spellcast/utilities/ChatBuffer.java
Java swingx render sometimes can't recognize the true root element, which we fetch here
https://github.com/libraryaddict/kolmafia/blob/82bc912ef32175281cec391678c5f05fe0ac9b8c/lib/net/java/dev/spellcast/utilities/ChatBuffer.java#L481
Adding debugging, it uses the "content" tag until the document is trimmed to size, then it seems to bug out and declares the <table> tag as the root.
The issue might not be fixed with this, however I can't replicate it anymore with this change with what I was previously doing to trigger the issue, namely "prefref" as tables are obvious when they break.
A better fix likely exists.
> Add the <main> tag inside <body>, help HtmlDocument recognize the root

- src/net/sourceforge/kolmafia/RequestLogger.java
- src/net/sourceforge/kolmafia/request/GenericRequest.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/RequestLoggerTest.java
I was tired of seeing `[1234] null` when I run a relativity fight from a Combat Lover's Locket fight - i.e. a fight without a location.
We have an existing infrastructure for these fights that are triggered without visiting a location. `itemMonster` might not be the best name for it really its there for handling locationless fights, so let's make sure we use it for some of the newer sources of those.
> Correctly report last location if you multifight from an itemMonster

- test/net/sourceforge/kolmafia/textui/CcsFileManagerTest.java
Follow-up to #877: add tests for CcsFileManager.
Used the existing file system, couldn't find existing file system-related tests (read / write).
Didn't move `getPath`: I prefer to have private methods below public ones, so it being where it is is about the only place it can go.
> tests: add tests for ccs file manager

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/webui/RelayLoader.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
Local Voting has Experience (familiar) and Experience (Muscle), at least, on occasion.
Since they are not variable, we can use Modifiers.parseModifiers, rather than Modifiers.evaluateModifiers.
This will look up modifiers by tag, rather than name.
Now that I think about it, why does Modifiers.evaluateModifiers not do that, too?
It splits a String into a ModifierList. The modifiers can be either names or tags.
But when we turn a ModifierList into a Modifiers object, we look up the modifier index by name.
It's easy enough to add the tag to the same nameToIndex hash table and be able to look up the index by whichever one.
I also added a catch for a bad URI string in RelayLoader. This is defensive; we supposedly always give a good input, but recent in-development code gave a bad input and an …
> use correct modifiers parsing method for voting

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/webui/TopMenuDecorator.java
I used them in the GUI and never in the browser, but apparently others have the opposite habits.
Put them back in the relay browser, if enabled.
> quick scripts in relay browser are still popular

- src/net/sourceforge/kolmafia/scripts/git/GitManager.java
- src/net/sourceforge/kolmafia/textui/DataTypes.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
Follow-up to #849.
There are various `svn_` ASH functions, of which `svn_exists_at_head` is currently know to be used. Add `git_` equivalents doing similar things.
I thought about adding a `script_` equivalent that would look over both folders, but for most of these functions you need to know the exact project name, and it's likely to be different for svn or git installations, so this wouldn't be terribly useful.
> feat: add `git_` equivalents to `svn_` ASH functions

- src/data/dailylimits.txt
- test/net/sourceforge/kolmafia/persistence/DailyLimitDatabaseTest.java
In #605, code dealing with the glove non-combat skills was added, but the skills themselves were not. Correct this.
Also fix a test class name.
> fix: add powerful glove skills to daily limits

- src/data/spleenhit.txt
Consumables tend to stay `Unspaded`. Go through the spleen items and update the ones we know about.
> feat: un-unspade some spleen items

- src/net/sourceforge/kolmafia/swingui/OptionsFrame.java
- src/net/sourceforge/kolmafia/swingui/panel/ConfigQueueingPanel.java
- src/net/sourceforge/kolmafia/swingui/widget/PreferenceButtonGroup.java
- src/net/sourceforge/kolmafia/swingui/widget/PreferenceCheckBox.java
- src/net/sourceforge/kolmafia/swingui/widget/PreferenceIntegerTextField.java
- test/net/sourceforge/kolmafia/swingui/OptionsFrameTest.java
Just as OptionsPanel is extended by various panel classes in OptionsFrame, so if ConfigQueueingPanel.
I moved the latter into its own class file in swngui/panel
PreferenceCheckBox, PreferenceIntegerTextField, and PreferenceButtonGroup are widgets that could be used in any OptionsFramePanel. I moved them into individual class files in swingui/widget
> Move ConfigQueueingPanel and Preference widgets into individual class files

- src/net/sourceforge/kolmafia/request/FightRequest.java
It was reasonable to not bother looking for additional actions if we just processed lovebugs, but the code farther down in the caller which would log it was short circuited. Fix.
> log lovebug actions again

- src/net/sourceforge/kolmafia/scripts/git/GitManager.java
- test/internal/helpers/CliCaller.java
- test/net/sourceforge/kolmafia/scripts/git/GitManagerTest.java
- test/net/sourceforge/kolmafia/textui/command/AbstractCommandTestBase.java
Certain existing scripts, such as [ChIT](https://github.com/Loathing-Associates-Scripting-Society/ChIT) install from a folder one level lower than the base directory when using SVN. It is desirable to support this from git as well, to avoid breaking existing installations.
Introduce a file `manifest.json` with a key `root_directory` to specify the directory that contains the other files Mafia is interested in: those under the permissible folders (e.g. `scripts`), and the `dependencies.txt` file.
Removed comment about not supporting local changes because local changes are supported implicitly without me having to write any code, which is nice. It seems that `git update` will handle unstaged changes -- I thought asking people to commit changes was a good halfway house, but even this isn't …
> feat: support installing git scripts from non-root folders

- test/net/sourceforge/kolmafia/scripts/git/GitManagerTest.java
Deletion of an installed git script can fail under certain circumstances. I suspect the following:
* if a script is installed and deleted fairly quickly, [deleting the items in .git/objects/pack can fail](https://stackoverflow.com/questions/19191727/pack-file-from-git-repo-cant-be-deleted-using-file-delete-method) (the solutions in the attached SO post don't work).
* GitManager catches that error and tries moving it to the temporary directory instead, which should work for most users...
* ...but can fail if the temporary directory and the current directory are on different network drives, as I suspect they are in the GitHub actions runner.
Disable the git manager test on Windows to stop it failing the builds.
> tests: disable git manager test on Windows

- src/data/monsters.txt
The tower monsters are interesting, in that they are wishable (and I think Rain Man-able) but not copyable. Apparently they get marked as nocopy after the fight starts.
> feat: mark more monsters as NOCOPY

- src/net/sourceforge/kolmafia/session/YouRobotManager.java
- test/net/sourceforge/kolmafia/request/ScrapheapRequestTest.java
- test/net/sourceforge/kolmafia/session/YouRobotManagerTest.java
Bug Report says that looking at CPU Upgrades in Reassembly Station in a You, Robot run does not learn which ones you have installed.
I could have sworn that worked for me - and I even had a working unit test that showed it.
Well, yes. If YouRobotManager.visitChoice is called with a responseText for choice 1445, it will parse the upgrades.
Unfortunately, the normal choice processing path never called visitChoice in that way for CPU upgrades. It just called postChoice1 with a URL that indicated no change was being made.
The tests for YouRobotManager all called the specific method they thought was needed - visitChoice or postChoice1.
I changed them all to call the processResponse method of the request, which does all the steps of choice processing - and that showed the error I mentioned …
> Fix You, Robot tests. Looking at CPU upgrades counts as a visit.

- src/net/sourceforge/kolmafia/session/BreakfastManager.java
Choice 1219/1 collects a sea jelly - or not, if you already have done that today.
In either case, KoL dumps you out of the choice.
whichchoice1219 defaults to 1 - and is not configurable in the GUI.
Breakfast now resets it to 1, will ye nill ye, simply not caring if ye have changed it.
Breakfast now lets ChoiceManager simply automate collecting sea jelly, rather than trying to do it manually, which simply can't work, unless you have manually changed that preference to 0 - "Show in Browser".
I am quite certain that nobody has ever done that.
> breakfast lets ChoiceManager automate sea jelly

- src/net/sourceforge/kolmafia/KoLAdventure.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/textui/command/JourneyCommand.java
- test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
Which is a bug I just noticed.
I wrote a test for it and fixed it.
Other things:
- Just as we have ASH ```can_adventure(location)```, which is validate1, now we have ASH ```prepare_for_adventure(location)``` which is validate2.
- validate2 will now build a dingy dinghy, if necessary, for Island, Pirate, and IsleWar zones
- Modernized a few more switch statements.
The following are (easy) things I am hoping to get in, but the bug is serious enough we shouldn't necessarily wait.
I can easily start yet another PR.
Throne Room:
- King not killed
- Have (and can equip) Harem Girl outfit and either effect or potion of Knob Goblin Perfume
- or have (and can equip) Guardsman outfit and birthday cake.
- (validate2 does all of that; validate1 should pre-check.)
- Tests!
PFA:
- validate2 will use …
> No NPE in can_adventure() in Standard for non-item zone

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/session/ChoiceManager.java
- test/net/sourceforge/kolmafia/session/ChoiceManagerTest.java
As suggested in https://kolmafia.us/threads/recent-problems-with-batfellow-ash.27847/#post-169118
There exist old scripts that have worked up to now and probably won't receive updates. Allow an out for users of those scripts to keep them going.
I considered whether the preference should be global or user. I figured global, as you're using this because you're using some script that needs it, and the script is shared across characters.
Abort by default, because we consider choice access when not in a choice as a bug that should be fixed.
> feat: allow setting a property to not abort on choice

- build.gradle
- test/net/sourceforge/kolmafia/FamiliarDataTest.java
- test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
- test/net/sourceforge/kolmafia/persistence/AdventureSpentDatabaseTest.java
- test/net/sourceforge/kolmafia/persistence/DailyLimitDatabaseTest.java
- test/net/sourceforge/kolmafia/persistence/ItemFinderTest.java
- test/net/sourceforge/kolmafia/persistence/MallPriceDatabaseTest.java
- test/net/sourceforge/kolmafia/request/EatItemRequestTest.java
- test/net/sourceforge/kolmafia/request/FightRequestTest.java
- test/net/sourceforge/kolmafia/request/GuildRequestTest.java
- test/net/sourceforge/kolmafia/request/QuantumTerrariumRequestTest.java
- test/net/sourceforge/kolmafia/request/RelayRequestWarningsTest.java
- test/net/sourceforge/kolmafia/request/ScrapheapRequestTest.java
- test/net/sourceforge/kolmafia/session/BanishManagerTest.java
- test/net/sourceforge/kolmafia/session/BastilleBattalionManagerTest.java
- test/net/sourceforge/kolmafia/session/ChoiceManagerTest.java
- test/net/sourceforge/kolmafia/session/EncounterManagerTest.java
- test/net/sourceforge/kolmafia/session/EquipmentManagerTest.java
- test/net/sourceforge/kolmafia/session/GreyYouManagerTest.java
- test/net/sourceforge/kolmafia/session/LocketManagerTest.java
- test/net/sourceforge/kolmafia/session/MallPriceManagerTest.java
- test/net/sourceforge/kolmafia/session/MonsterManuelManagerTest.java
- test/net/sourceforge/kolmafia/session/PriceToAcquireTest.java
- test/net/sourceforge/kolmafia/session/YouRobotManagerTest.java
- test/net/sourceforge/kolmafia/swingui/OptionsFrameTest.java
- test/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanelTest.java
- test/net/sourceforge/kolmafia/textui/langserver/AshLanguageServerTest.java
JUnit has [changed](https://junit.org/junit5/docs/5.9.0/release-notes/) behaviour to be consistent with their docs and not accept private lifecycle methods. This leads to a lot of churn.
SVNKit has some [bug fixes](https://svn.svnkit.com/repos/svnkit/trunk/CHANGES.txt) that look worth having.
> chore: update junit, svnkit

- src/net/sourceforge/kolmafia/request/QuestLogRequest.java
questL11Manor is marked as `started` once you read the MacGuffin diary; it isn't until `step1` that the cellar is open.
> Reading the macguffin diary doesn't finish the ballroom quest

- jenkinsfile
Jenkins no longer needs to run an older version of Java so we can now use the same version for both.
> Remove manual  java selection in jenkinsfile

- src/net/sourceforge/kolmafia/KoLCharacter.java
- test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
I seem to have pushed my actual support for The Skeleton Store, Madness Bakery, and The Overgrown Lot onto main, bypassing my open PR. I thought I couldn't do that any more?
In any case, this PR does this:
- simplify test set up to eliminate maps of available zones. Instead, just use static constants.
- Adds prepareForAdventure tests for the three Market Quest zones.
If already have access, no requests.
If have item that grants access, 1 request to use item
If don't have item, 3 requests to start quest with the shopkeeper
> Add tests for three market quest zones

- src/data/modifiers.txt
- src/data/statuseffects.txt
Avoid the "unrecognised effect" text, but don't try to parse the effect or anything.
> chore: add buzzed on distillate effect to data

- src/data/consequences.txt
- src/data/defaults.txt
- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/AscensionPath.java
- Nuclear autumn can be tracked like any other path, rather than just looking at the item
- 2CRS is worth tracking because you get that number of extra enchants on your ring
- Some path images were just wrong... including wosp!
> Fix up some missing path points trackers and incorrect path images

- src/net/sourceforge/kolmafia/KoLCharacter.java
There are bug reports that something maximizer-related has started breaking on https://github.com/kolmafia/kolmafia/commit/f9a268c62529d240a27c701cd3f27740adc5506f, so I took a closer look.
All I could find that appeared to have changed is folder-related: this method checked the currently equipped item instead of the passed-in item, and ValhallaManager checks all folders instead of the first 3 (though the latter two should be null, so it should wash out).
> fix: mistranslated method in r26667

- src/net/sourceforge/kolmafia/request/EquipmentRequest.java
The trigger seems to be having an accessory in acc1 and an empty slot
in some higher value, then donning an outfit that fills that empty
slot.
Note: not ready for commit as-is, as I haven't written any tests
yet. I've only confirmed that the fix works :)
> Fix outfit swapping with empty accessory slots.

- src/net/sourceforge/kolmafia/persistence/NPCStoreDatabase.java
On my IOTM-less testing alt, autoscend was attempting to drink and eat items from the Crimbo '21 shop and failing. No longer attempts to shop there after this change.
> Crimbo 21 no longer accessible

- src/net/sourceforge/kolmafia/persistence/HolidayDatabase.java
- src/net/sourceforge/kolmafia/textui/command/ShowDataCommand.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/textui/command/ShowDataCommandTest.java
No test for the mini-moon because it looks like it's wrong. Looks like an off-by-one error was introduced in the refactor: it tells you the position the mini-moon was in yesterday.
> fix: avoid debug log on moons command

- src/data/consequences.txt
- src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java
1) In monsters.txt, bas Ed the Undying is monsterId = 473, but Ed the Undying (1) - Ed the Undying (7) all have monsterId = 0. This is because we can't have a map keyed by monsterId with 8 different key = 473.
However, when processing a fight, when we look at MONSTERID of 473, but we've disambiguated the monster by image to one of the (1) - (7) versions with monsterId = 0, that doesn't mtch, so we look up the monster by ID using the aforementioned map.
When creating the MonsterData associated with the (1) - (7) names, we now set the id to 473. FIghtRequest is happy.
2) I noticed that consequences.txt tried to figure out the Ultrarare pooltergeist by image, rather than use monsterId = -94. Since we know the actual monsterId  - 425 - no need to do that any more.
> Give Ed stages the same monsterId when creating a MonsterData

- src/net/sourceforge/kolmafia/swingui/OptionsFrame.java
... as well as on Creation panels.
This bit me again. It wasn't showing that I could make unstable fulminate - although I KNEW I had the ingredients.
I finally figured out that was a Fancy concoction - so I headed to Preferences to check
> Put fancy concoction preferences on Preferences panel

- src/net/sourceforge/kolmafia/swingui/widget/RequestPane.java
- test/net/sourceforge/kolmafia/textui/RequestPaneTest.java
When a string such as
```
<table border="2" cols="4">
<tr>
<td>
<p>
roninStoragePulls
</p>
</td>
</tr>
</table>
```
has the html removed, you're left with a bunch of spaces surrounding the string itself.
You will get this, note the spaces around the string.
```
copyAsHTML                            
```
This could also be seen as another problem where the html shouldn't be formatted, but that's outside the scope of this small change.
> Strings with html removed, should be trimmed

- src/net/sourceforge/kolmafia/maximizer/Maximizer.java
- src/net/sourceforge/kolmafia/request/StandardRequest.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
actual reality goggles and fifteen minutes of flame were listed, despite the comment that they weren't.
Mocking `isAllowedInStandard` makes that test take 11 seconds, which is not good. Might refactor the class to make it more easily configurable for tests.
It looks like `ClearSharedStateBefore` runs before all nested classes, which breaks setting properties. Will look into fixing outside this PR.
> fix: don't suggest horsery if not allowed in standard

- src/net/sourceforge/kolmafia/KoLmafia.java
- src/net/sourceforge/kolmafia/session/VolcanoMazeManager.java
`VolcanoMazeManager` downloads the volcano maze images in a static initializer. This runs when running tests, and means that 15 files are "downloaded" at the start of every test. This makes debugging network requests more annoying.
These files need to be downloaded once, ever, so run this on program start -- we don't need to worry about login / logout needing to run it again.
> refactor: download volcano maze images on program startup

- src/net/sourceforge/kolmafia/textui/command/JurassicParkaCommand.java
Correct spelling, fix ordering for two dinos.
Add more aliases: e.g., "parka spikes" is easier to type than "parka kachungasaur".
Aliases were not added for "sleaze" (damage or res?) and "nc" (pterodactyl base enchant or spikolodon combat skill?)
> feat: dino parka

- test/net/sourceforge/kolmafia/textui/parsetree/ValueTest.java
Follow-up to #1037.
Use `hasSign` everywhere: couple of places were missed.
Use the reason field to describe what the test is trying to show, in pseudocode (kind of like ASH).
Add contentStrings to the buffers equal to the value of the buffers, because I don't think it's possible for it to be blank for a real buffer.
Add a element - string comparison, because by the looks of it it's case-sensitive, so any element always appears before any location (as all locations start with a capital or number).
> tests: have reasons describe tests, use hasSign everywhere

- src/net/sourceforge/kolmafia/request/BarrelShrineRequest.java
- src/net/sourceforge/kolmafia/textui/command/RefreshStatusCommand.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerCreatableTest.java
Still not sure why all these maximizer issues have come in recently.
Additionally add a "refresh concoctions" command for forcibly refreshing concoctions (i.e. fixing Mafia state), in case the session breaks in that way for some reason. Bit different to the other "refresh" commands because this deals with Mafia's internal stuff instead of interacting with KoL, but I think it's linked (as what can be created depends on KoL state).
> fix: can't create barrel lid in standard

- src/net/sourceforge/kolmafia/objectpool/Concoction.java
- src/net/sourceforge/kolmafia/request/BarrelShrineRequest.java
- test/internal/helpers/Maximizer.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerCreatableTest.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
- test/net/sourceforge/kolmafia/swingui/widget/ListCellRendererFactoryTest.java
Revert some of #1064.
This issue was introduced in 228c600a384f99c60028ce38f413e91969fe7108, where the `ConcoctionDatabase.isPermittedMethod` check was moved out of the middle of the function, and so wasn't checked for a variety of createables. This meant that things like the barrel shrine, floundry etc. were considered to be available in standard when they aren't.
Add tests for these things.
> fix: check permitted concoctions in standard

- src/net/sourceforge/kolmafia/textui/Parser.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/ReservedWordTest.java
Follow-up to #1032.
By https://kolmafia.us/threads/witchess-puzzle-solver.19964/page-3#post-169591, ASH scripts that used "path" as an array variable broke anyway.
Reserve all the unreserved types to give a better error message.
> feat: reserve extra types

- src/data/items.txt
- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/KoLAdventure.java
- src/net/sourceforge/kolmafia/Modifiers.java
Attacks Can't Miss negates 'you can't hit anything here' warning.
How would one test the new clause in the conditional in the middle of KoLAdventure.run()?
I did test the extra pattern for parsing Attacks Can't Miss using my (heavily used today) June Cleaver:
```
> test newitem 330396747
Unknown item found: June cleaver (10920, 330396747)
--------------------
10920 June cleaver 330396747 junecleaver.gif weapon 0
June cleaver 100 Mus: 0 1-handed cleaver
Item June cleaver Muscle Percent: +10, Mysticality Percent: +10, Moxie Percent: +10, HP Regen Min: 6, HP Regen Max: 8, MP Regen Min: 6, MP Regen Max: 8, Adventures: +5, Hot Damage: +48, Cold Damage: +47, Sleaze Damage: +47, Stench Damage: +47, Spooky Damage: +47, Attacks Can't Miss
--------------------
```
> June cleaver cannot miss.

- src/net/sourceforge/kolmafia/session/LoginManager.java
Remove warning message for running with Java < 17. This was added in #734 before Java 17 became mandatory in #727, so there's no point keeping it around.
> feat: remove warning message for Java < 17

- src/net/sourceforge/kolmafia/textui/parsetree/Value.java
- test/net/sourceforge/kolmafia/textui/parsetree/ValueTest.java
MonsterDatabase has special handling for Ed's forms such that they all have the same nonzero id. This has two consequences in the current implementation:
1. Ed's forms are all == to each other. This has unexpected results when inserting multiple forms into the same map.
2. Attempting to write any of Ed's forms via map_to_file will look up the Monster with id=473, namely $monster[Ed the Undying].
This commit addresses both of those cases.
> Fix serialization of Ed the Undying's forms.

- test/net/sourceforge/kolmafia/request/GenericRequestTest.java
Occasionally we (I) push code that was not intended and this is to ensure that never gets missed and accidentally merged.
> Add coverage for GenericRequest protections

- src/net/sourceforge/kolmafia/request/RelayRequest.java
- test/net/sourceforge/kolmafia/request/RelayRequestWarningsTest.java
I was irked when I got a warning that suggested I spend my DInodollars, clicked the icon to say I was fine with not doing this, and was immediately given the same warning.
The "hand" icon add a confirmation field to the URL.
The warning failed to check the confirmation.
This same issue was present in Kingdom of Explothing and Robocore.
1) I fixed all three paths.
2) I split the Robocore test into multiple single tests
I put them into a Nested test class
I made them use Cleanups
3) I added a test for Robocore
4) I added a test for Dinocore
> Break Prism Warnings should return false if previously confirmed

- CONTRIBUTING.md
Sometimes people want to just know the process without reading through dozens of pages of github documentation.
> Add quickstart to CONTRIBUTING.md.

- test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
Using the bone with a price tag on it opens The Skeleton Store but does not start the Meatsmith quest.
Talking to the Meatsmith opens the Skeleton Store and starts the quest.
Same for The Overgrown Lot and Doc Galaktik and map to a hidden booze cache.
Same for Madness Bakery and the Armorer and hypnotic breakcrumbs.
This was already the case, but I augmented my prepareForAdventure tests for those areas to verify it.
Which is to say, this PR is nothing but test changes.
> Open market area with items does not start quest, talking to vendor, does

- src/net/sourceforge/kolmafia/swingui/menu/ScriptMenu.java
The "Refresh menu" menu item under scripts doesn't do anything anymore.  It only refreshes the backing list, not the actual UI.  This change makes it refresh the UI as well.
> Fixing "Refresh menu" menu item.

- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/request/RelayRequest.java
- src/net/sourceforge/kolmafia/webui/UseLinkDecorator.java
1) 'cause regular bosses are replaced with special monsters.
2) Add "turn in" link in relay browser to turn in dinosaur droppings to Dino World owner
> No Relay Boss Warnings in Dinocore

- src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java
ConcoctionDatabase.refreshConcoctions is a relatively expensive operation.
We've made an effort to eliminate unnecessary calls. Used to be, we'd call it for each item that came into inventory after a fight. Now we defer refreshing until we've processed all the items.
I recently noticed that it now takes many seconds (well, 5 or 10) after clicking on the Item Manager icon before the frame appears. This is new. I decided to see if this was the issue. So I added a simple metric - "_concoctionDatabaseRefreshes" - to get a feel for it.
Turns out, no.
We refresh concoctions 12 times while logging in.
Building the Item Manager Frame? 0 times.
I should learn how to profile to find out what the real slowdown is. ListCellRenderers? Who knows? Need data!
In any case, this metric is still …
> count ConcoctionDatabase refreshes

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/request/FightRequest.java
- test/internal/matchers/Preference.java
- test/net/sourceforge/kolmafia/request/FightRequestTest.java
As requested in https://kolmafia.us/threads/track-combat-loss-when-adventuring.28096/, with a small change: the preference is `_lastCombatWon`, a boolean.
This counts fights won (i.e. we saw WINWINWIN) instead of lost because that's the thing we determine. This counts fights where we successfully ran away as not won.
> feat: track whether last fight was won

- src/net/sourceforge/kolmafia/scripts/git/GitManager.java
- src/net/sourceforge/kolmafia/utilities/FileUtilities.java
- test/net/sourceforge/kolmafia/scripts/git/GitManagerTest.java
- test/net/sourceforge/kolmafia/utilities/FileUtilitiesTest.java
Probably the issue on https://github.com/Loathing-Associates-Scripting-Society/ChIT/issues/24.
Suppose we have two scripts, both of which store something in the folder `images/relayimages`. Then deleting one script would fail, because the folder will fail to be deleted (as it's non-empty).
Check for a non-empty folder, and don't delete the folder in that case.
> fix: don't error on deleting shared folder for scripts

- src/net/sourceforge/kolmafia/scripts/ScriptManager.java
Google Code was shuttered in 2016. If any scripts were there, they'll no longer be accessible.
> feat: remove google code code

- src/net/sourceforge/kolmafia/request/RelayRequest.java
1. Pass through KoL's Cache-Control and Pragma headers instead of dropping them and adding our own. It looks like KoL does as desired nowadays.
2. If we receive a Content-Type from a proxied page, use that instead of our own guess. Add the UTF-8 charset if it's not already there -- I'm not certain this is right, but this is what we did before, and looking at the code in `RelayAgent` it seems reasonable.
> feat: pass through KoL's cache control headers + content-type

- .github/workflows/npm.yml
#1148 failed after the merge. Try to fix.
Move the setting up of npm before the first npm command (apparently unnecessary). Go to the right directory before running `npm install`.
> chore: run npm install from .github/npm

- src/net/sourceforge/kolmafia/textui/TypescriptDefinition.java
- src/net/sourceforge/kolmafia/textui/command/JsRefCommand.java
- src/net/sourceforge/kolmafia/textui/javascript/ProxyRecordMethodWrapper.java
- src/net/sourceforge/kolmafia/textui/javascript/ValueConverter.java
- src/net/sourceforge/kolmafia/textui/parsetree/AggregateType.java
- src/net/sourceforge/kolmafia/textui/parsetree/PluralValue.java
- src/net/sourceforge/kolmafia/textui/parsetree/PluralValueType.java
- src/net/sourceforge/kolmafia/textui/parsetree/ProxyRecordValue.java
- test/root/expected/plural_values_are_returned_as_arrays.js.out
- test/root/scripts/plural_values_are_returned_as_arrays.js
The Effect.all value cannot be accessed in Javascript because it is a PluralValue, and that is not suppored by the ValueConverter:
```
> js Effect.get("Mallowed Out").all
Script    exception: ASH function returned native Java object.
```
Here is my try to map PluralValues to arrays in Javascript. It works as expected, however the Typescript definitions are now wrong. Since PluralValues use an AggregateType to specify their content, there is no good way to distinguish them from maps on a type level. 
Some advise here would be much appreciated.
I've started a discussion about this in summer: https://kolmafia.us/threads/pluralvalues-in-javascript-and-should-effect-all-be-one.27510/
@gausie seemed to support the idea of using Arrays in Javascript. I'm happy to try any other data model, if …
> Convert PluralValues to arrays in Javascript

- src/net/sourceforge/kolmafia/textui/javascript/JavascriptRuntime.java
- src/net/sourceforge/kolmafia/textui/javascript/LibraryFunctionStub.java
- src/net/sourceforge/kolmafia/textui/javascript/UserDefinedFunctionStub.java
- test/net/sourceforge/kolmafia/CustomScriptTest.java
- test/root/expected/exception_ash_library_exception_caught.js.out
- test/root/expected/exception_ash_library_exception_uncaught.js.out
- test/root/expected/exception_ash_userfunction_exception_caught.js.out
- test/root/expected/exception_ash_userfunction_exception_uncaught.js.out
- test/root/expected/exception_javascript_syntax_caught.js.out
- test/root/expected/exception_javascript_syntax_uncaught.js.out
- test/root/expected/exception_proxy_expression_exception_caught.js.out
- test/root/expected/exception_proxy_expression_exception_uncaught.js.out
- test/root/scripts/exception_ash_library_exception_caught.js
- test/root/scripts/exception_ash_library_exception_uncaught.js
- test/root/scripts/exception_ash_userfunction_exception_caught.js
- test/root/scripts/exception_ash_userfunction_exception_uncaught.js
- test/root/scripts/exception_ash_userfunction_helper.ash
- test/root/scripts/exception_javascript_syntax_caught.js
- test/root/scripts/exception_javascript_syntax_uncaught.js
- test/root/scripts/exception_proxy_expression_exception_caught.js
- test/root/scripts/exception_proxy_expression_exception_uncaught.js
Exceptions thrown by a ASH library function cannot  be caught in Javascript. 
This PR changes the two function stubs to wrap any exception in Rhino's WrappedException (there is a helper function for that, `Context.throwAsScriptRuntimeEx(e)`).
The code that already catches the WrappedException is modified to also look at the unwrapped exception and handle ScriptExceptions the usual way.
I've added a Test as first commit before the change, to showcase the old behaviour, and make the change documented in code.
> Allow Javascript to catch exceptions from ASH functions

- src/net/sourceforge/kolmafia/request/AdventureRequest.java
- src/net/sourceforge/kolmafia/request/GenericRequest.java
- src/net/sourceforge/kolmafia/session/ChoiceManager.java
- src/net/sourceforge/kolmafia/webui/RelayAgent.java
- test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
- test/net/sourceforge/kolmafia/session/ChoiceManagerTest.java
- test/net/sourceforge/kolmafia/session/ElVibratoManagerTest.java
- test/net/sourceforge/kolmafia/session/OceanManagerTest.java
- test/net/sourceforge/kolmafia/session/QuestManagerTest.java
This came about because I had a lot of trouble with my Chess Puzzle automation test:
When I submitted a RelayRequest to use a reflection of a map via inv_use.php, it redirects to choice.php.
When I coded my test to handle that, for some reason, the list of requests did not include the initial inv_use.php. The first was choice.php. Very strange, since debug logging showed it WAS submitted. So I coded my test to ignore that and it worked perfectly every time on my Mac.
But when I pushed it github, the test failed on Ubuntu, which DID have inv_use first.
I worked around it for now by not starting with the map, but with choice.php, in my other PR.
I want to fix that, so I opened this PR to try and debug the situation.
To my surprise, in my three test cases, I got inv_use.php as the first …
> Use requested request method for redirected requests

- src/net/sourceforge/kolmafia/request/RelayRequest.java
I could add a suite of tests in RelayRequestWarningTest for this, but I tested this one-line change in the Relay Browser and won't have time for development for the next two weeks.
> Drunkula wineglass on familiar negates need for overdrunk warning

- test/net/sourceforge/kolmafia/textui/command/FoldItemCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/SaberCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/SpoonCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/UseSkillCommandTest.java
Make them use newer patterns so they're easier to copy from.
Stop testing sign in the spoon test: it doesn't change it, so there's no point.
> tests: use cleanups in early command tests

- src/data/adventures.txt
Realised while doing the checks that if something doesn't have a snarfblat, it doesn't have a difflevel, so should probably be "none". Not making that change in this PR, though.
> feat: spade some diff levels

- src/net/sourceforge/kolmafia/session/AutumnatonManager.java
- test/net/sourceforge/kolmafia/session/AutumnatonManagerTest.java
Autumnaton was consistently off by 11 just before the first longer quest.
I think it was missing the extra 11 at the start. This makes the numbers align with what I see.
> fix: autumnaton quest turn start with two 11s

- src/net/sourceforge/kolmafia/request/GenericRequest.java
From https://kolmafia.us/threads/replace-pwd-hashes-in-debug-log-with-generic-string.28127/ the session id is a dangerous item to share in DEBUG logs, and removing it is easy enough.
> feat: hide PHPSESSID from cookie in debug logs

- src/net/sourceforge/kolmafia/request/AdventureRequest.java
The autumn-aton choice adventure has an option that redirects you to your inventory. You can walk away from the choice, so you don't have to take it, but avoid crashing if you do.
Mafia prints "Unhandled redirect to inventory.php" which I think is fine.
> fix: allow autumnaton redirect to inventory

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/persistence/MallPriceDatabase.java
- src/net/sourceforge/kolmafia/session/LoginManager.java
Inspired by https://kolmafia.us/threads/autoscend-ash-demands-ancient-magi-wipes-cant-find-file-divides-by-zero.28158
I think this is a potential problem caused by #687, which removed the bundled mallprices.txt file: if the user is not sharing mall prices, then they won't get any price data, which can cause scripts to crash.
One other option would be to download the file if it doesn't exist (but not keep it up to date), which would ensure the user always has some price data.
> feat: default sharePriceData to true

- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/persistence/AdventureDatabase.java
- src/net/sourceforge/kolmafia/textui/parsetree/ProxyRecordValue.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
I mixed up `name` and `name()`, and assumed coverage meant something was tested instead of just that we had some test that ran that bit of code.
> fix: lowercase for environment + difficulty level on proxy record

- src/net/sourceforge/kolmafia/persistence/AdventureDatabase.java
- src/net/sourceforge/kolmafia/session/AutumnatonManager.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/textui/command/AutumnatonCommand.java
- src/net/sourceforge/kolmafia/textui/command/HeistCommand.java
- test/net/sourceforge/kolmafia/session/AutumnatonManagerTest.java
- test/net/sourceforge/kolmafia/textui/command/AutumnatonCommandTest.java
Add location list to autumnaton command. Also add ASH command for getting locations.
This is a useful increment, but there's more I want to do here:
* display upgrades, and what they do, if you don't have them
* cache the locations like `LocketManager` does
To update the cache, I need to know exactly what causes the location to appear (is a turn necessary, or is a combat enough?) and also where this should go in the codebase (somewhere in AdventureRequest?).
Checked "visited": initial copperhead NC is enough, as is free lianas. Didn't try canceling the copperhead NC. Next run.
> feat: autumnaton locations

- src/net/sourceforge/kolmafia/chat/ChatPoller.java
- src/net/sourceforge/kolmafia/request/ChatRequest.java
- test/net/sourceforge/kolmafia/request/ChatRequestTest.java
This PR consists of two parts:
1. Both KoL mchat and lchat have switched to 3000/10000ms somewhen in the last 8 years. Adjust our values to do the same.
lchat:
mchat (away time comes from server, not from source code):
2. KoL mchat is adding a random aa=%RANDOMNUMBER% parameter to each newchatmessages.php request. Probably some kind of cache buster? I've added this to ChatRequest for the mchat relay requests.
> Update chat to match KoL behaviour

- src/net/sourceforge/kolmafia/session/ClanManager.java
Currently there's no way to see when someone switches clans in the session log, this aims to correct that.
A potential extra feature could be detecting when you are booted from a clan, or leave the clan. But that's hardly a concern.
> In session log, note what clan we're switching to/are in

- src/data/adventures.txt
The PirateRealm Island shows up in KoL as "PirateRealm Island" but in Mafia as "The Temple" -- presumably it reads the last name.
> feat: more difflevels

- src/net/sourceforge/kolmafia/swingui/menu/ScriptMRUList.java
- src/net/sourceforge/kolmafia/textui/command/CallScriptCommand.java
Add items to the MRU List in parallel to avoid a pause before updating the GCLI after calling a script.
The `synchronized` keywords in this file can cause delays elsewhere, but this seemed the most obvious.
> fix: no visible delay in call script

- src/data/fullness.txt
After consulting years of my logs, I believe that the adventure range is wrong - I have seen examples of both 29 and 30 adventures in my logs, after accounting for consumption modifiers. Note that 29-34 is also the listed range for pickle juice, which I believe is correct.
> Extra-greasy sliders give 29-34 adventures.

- src/data/adventures.txt
This was tricky. The Rift is only open for levels 4 and 5, and you have to have completed the first part of the Wizard of Ego quest to even get it. I timed my first two Autumn-aton tasks to pick up the two upgrades that grant an additional 11-turn mission, so that when I eventually did open the rift, I could get two 11-turn and one 22-turn mission while the Rift was still open.
I did the "No Uniform" zone first and got an Autumn Debris Shield - the mid-outdoor reward.
The Cloaca Uniform mission yielded an autumn leaf - the low-outdoor reward.
The Dyspepsi Uniform missionn gave a autumn years wisdom - the high-underground reward.
I believe both of those had to also be mid-outdoor zones, but since the equipment had already been granted, it was replaced with a consumable item.
> DiffLevels for Cola Wars zones

- src/net/sourceforge/kolmafia/textui/command/AutumnatonCommand.java
- test/net/sourceforge/kolmafia/textui/command/AutumnatonCommandTest.java
- test/root/request/test_choice_autumnaton_old_locations.html
As discussed in #1216.
To ensure the test continues testing the right thing (invalid locations don't break the command), I've added "Gausie's Grotto" to the test list as number 13.
> fix: NPE on invalid locations

- src/net/sourceforge/kolmafia/textui/TypescriptDefinition.java
This lets the compiler know that the input array is not modified by the function. This is helpful when you have a const array of item names that you want to lookup:
```ts
const GIFT_PACKAGES = [
'plain brown wrapper',
'less-than-three-shaped box',
'exactly-three-shaped box',
'chocolate box',
'miniature coffin',
'solid asbestos box',
'solid linoleum box',
'solid chrome box',
'cryptic puzzle box',
'refrigerated biohazard container',
'magnetic field',
'black velvet box'
] as const;
const items = Item.get(GIFT_PACKAGES); // does not work without this change
```
> Mark RecordType.get(names) param as readonly

- src/net/sourceforge/kolmafia/RequestLogger.java
RequestLogger.registerRequest checks for quite a number of well-known requests, and marks them as wasLastRequestSimple.
This is also done for requests that are considered "external", i.e. basically every relay request and visit_url call, if I'm not mistaken.
For such requests, we can skip all the instanceof checks (which are surely measurable in that quantity), by flipping the OR conditions. Due to the lazy-evaluation of the Java logical OR, the right hand side is only evaluated if required.
I'm aware that this is probably premature optimization, especially since the single registerRequest calls will take much more time in comparison (this occurred to me during writing this description, so I'm posting it anyway), so please feel free to disregard this PR if you feel it unnecessary.
> perf: improve RequestLogger for "external" requests

- src/net/sourceforge/kolmafia/persistence/ConsumablesDatabase.java
- src/net/sourceforge/kolmafia/utilities/CaseInsensitiveHashMap.java
- test/net/sourceforge/kolmafia/utilities/CaseInsensitiveHashMapTest.java
This commit adds a CaseInsensitiveHashMap class and test, and then uses them to replace the TreeMaps in ConsumablesDatabase. These are performance-critical maps as they are read from a few thousand times during every concoction database refresh. They are modified rarely and don't grow in size essentially ever.
In the following speed test, this change caused a roughly 40% decrease in execution time for `getAdventureRange`, a function which takes up high single digits of execution time in my profiling tests.
```java
for (int i = 0; i < 500; i++) {
for (var entry : ItemDatabase.entrySet()) {
ConsumablesDatabase.getAdventureRange(entry.getValue());
}
}
```
> Use HashMap over TreeMap in ConsumablesDatabase.

- src/net/sourceforge/kolmafia/AreaCombatData.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/persistence/QuestDatabase.java
- src/net/sourceforge/kolmafia/session/ChoiceControl.java
- test/net/sourceforge/kolmafia/AreaCombatDataTest.java
I don't have the page html to write tests for the quest progress but I wrote tests for the encounter rates.
> Fix appearance_rates for jungles of ancient loathing & seaside megapolis

- src/net/sourceforge/kolmafia/persistence/ScriptManager.java
- src/net/sourceforge/kolmafia/swingui/ScriptManageFrame.java
A GUI element can have ScriptManager.getRepoScripts() or ScriptManager.getInstalledScripts() as its model.
As it turns out, the only frame that has such elements is ScriptManageFrame.
GUI tables have column headings and the names depend on the data type in the table.
If your table wraps one of the above models, TableCellFactory gets the column names from ScriptManager.
However, other GUI elements - in particular CreateSpecialPanel in the Inventory Manager - have a "not yet implemented" model, so TableCellFactory runs through all the globally known models before figuring that out.
The issue is that the above named Script models are initialized just fine via new LockableListModel<Script>(), but ScriptManager wants to load them up as part of class initialization.
Literally the only Frame …
> update repo and installed scripts from ScriptManageFrame, not ScriptManager

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/webui/RelayServer.java
Allow to specify a specific relay port for a user.
I want my characters to always be reachable under the same port, regardless of which order I start them in. Also for this reason, when a relayPort is explicitly specified in preferences, there will be no checking for other free ports, only the one will be tried.
> feat(relay): allow to specify the relay port

- src/net/sourceforge/kolmafia/persistence/ConsumablesDatabase.java
- test/net/sourceforge/kolmafia/persistence/ConsumablesDatabaseTest.java
An attempt at solving the drunki-bear problem, introduced in #1235.
> fix: some things are both food and booze

- src/net/sourceforge/kolmafia/swingui/panel/GearChangePanel.java
This code is a bottleneck. It's possible there is a reason the current code is the way it is, but I can't see one - unless there is some object-identity issues that are being worked around. newItems is mutated in this method but then the new value is never referenced afterwards.
> Simplify new equipment list.

- src/net/sourceforge/kolmafia/Modifiers.java
`getEffectModifiers` currently starts with an effect id, which then gets turned into a lookup string, which then gets parsed back into an id in `getLookupName`. Instead we should just use the id.
> Reduce frequency of name-to-id-to-name conversions.

- src/net/sourceforge/kolmafia/swingui/panel/GearChangePanel.java
I misread the profiling results. After running mafia this morning, I noticed it seems to have made things much worse. After looking more closely, I realized I had missed impact on the AWT event queue thread.
I need to spend some more time with this code to see if there's an actually working way to improve performance. For now, I suggest reverting my change from yesterday.
This reverts commit 6e1b0cf592c3d4bf0b2c8e8bed8642618bb78ba8.
> Revert "Simplify new equipment list. (#1264)"

- src/net/sourceforge/kolmafia/persistence/AdventureQueueDatabase.java
- src/net/sourceforge/kolmafia/persistence/AdventureSpentDatabase.java
- test/net/sourceforge/kolmafia/preferences/ForbiddenStoresTest.java
- test/net/sourceforge/kolmafia/preferences/PreferencesTest.java
- test/net/sourceforge/kolmafia/request/AdventureRequestTest.java
- test/net/sourceforge/kolmafia/request/AscensionRequestTest.java
- test/net/sourceforge/kolmafia/request/PlaceRequestTest.java
Added an option not to write the adventure queue and turns files and then disabled the write in tests that created them but were not cleaning them up.
Changed the username for several tests to make it easier to find which test was leaving files based on the username behind.
Lint and spotless.
Since the tests that got changed were not using the Cleanups framework I elected not to change them to do so.  baby steps.
> More test clean up of residue in data/

- src/data/combats.txt
While TTT was up, cannonfire40 confirmed rejection rates for 12 west main.
I suspect the same is true for the clan party house, but we can't know for sure without further dev leaks.
> feat: 12 west main rejection rates

- src/net/sourceforge/kolmafia/session/ResultProcessor.java
Currently, if you have NOT started the nemesis quest, and don't have fizzing spore pods in inventory:
```
> ash can_adventure($location[the "fun" house])
Returned: false
```
The above works as expected.
If you still have not started the nemesis quest, upon acquiring 6 fizzing spore pods:
```
Preference questG04Nemesis changed from unstarted to step14
> ash can_adventure($location[the "fun" house])
Returned: true
```
These are both incorrect. This proposed fix is to check that the quest state has progressed far enough.
Based on the comments from the GuildRequest describing the quest steps, step10 should be sufficiently far along, I think.
https://github.com/kolmafia/kolmafia/blob/4324e20a0e0f541486622c8e878196013046ba6c/src/net/sourceforge/kolmafia/request/GuildRequest.java#L380-L385
> Don't always progress the Nemesis quest after acquiring fizzing spore pods

- src/net/sourceforge/kolmafia/objectpool/Concoction.java
- src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java
- src/net/sourceforge/kolmafia/request/CreateItemRequest.java
- src/net/sourceforge/kolmafia/session/InventoryManager.java
Jewelrycrafting doesn't take turns, so remove code that checks free crafts related to it.
Cooking now has a separate source of free crafts, so add the "cookingLimit" and "turnFreeCookingLimit" concoctions. Still not really sure what this area of the code does.
> feat: remove turn-costing jewelcrafting, add turn-free cooking

- src/net/sourceforge/kolmafia/request/UseItemRequest.java
- src/net/sourceforge/kolmafia/session/LimitMode.java
- src/net/sourceforge/kolmafia/textui/command/GongCommand.java
- test/internal/extensions/ClearSharedStateBefore.java
- test/net/sourceforge/kolmafia/textui/command/GongCommandTest.java
We had this funky code in the responsetext parsing of UseItemRequest to detect that you hadn't finished you journey of reincarnation when you attempted to use a llama lama gong. If your effect had run out, it would visit the Noob Cave and accept your reward and then retry using the item.
Turns out this was to allow the "gong" command to immediately use a gong even if the user hadn't seen the Welcome Back adventure.
1) I moved the equivalent to the gong command itself: before it tries to use a gong, it sees if it needs to visit the Welcome Back NC, and if so, does it by visiting the Noob Cave.
2) I also learned that UseItemRequest now tells GenericRequest to follow redirects, which will leave it in a choice when the initial choice was so-followed; it did not automate the choice. Which is …
> The gong command finishes your journey of reincarnation

- src/net/sourceforge/kolmafia/session/BanishManager.java
- src/net/sourceforge/kolmafia/session/ChoiceControl.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/session/BanishManagerTest.java
- test/net/sourceforge/kolmafia/session/ResultProcessorTest.java
- Improve ice house support and modernise BanishManager tests
- Add some missing coverage
> Improve banish manager tests + ice house handling

- src/net/sourceforge/kolmafia/persistence/ConsumablesDatabase.java
- src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
- test/net/sourceforge/kolmafia/persistence/ConsumablesDatabaseTest.java
Attributes like SAUCY and CANNED are true in TCRS if they are true in the game in general. They're useful for diet planning so I'm pulling them through.
A few observations:
* I made a few small improvements to tests
* We should collect the actual substat awards from consumables - they don't get rerolled like potions do so it shouldn't be an effort that has to be repeated.
> Keep consumable attributes in TCRS

- src/net/sourceforge/kolmafia/preferences/Preferences.java
This was causing a bug when `saveSettingsOnSet` was off, so when a user closed mafia it was accidentally saving the old values.
> Reinitialize encoded values on reset.

- src/net/sourceforge/kolmafia/preferences/Preferences.java
This should reverse the performance penalty with tests.
> Don't cache encoded pref values during tests.

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/Modifiers.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
This doesn't need special casing - we can express the interaction between dodecapedes and amphibian sympathy in modifier expressions.
Also refactor to java streams and add comments.
> Remove special handling for dodecapede sympathy

- src/net/sourceforge/kolmafia/session/QuestManager.java
- test/net/sourceforge/kolmafia/session/QuestManagerTest.java
- test/root/request/test_speakeasy_brawl_(0).html
Unfortunately,the tooltip for the unusually quiet barroom brawl has (1) regardless of whether it currently costs a turn. It looks like they cover up the (1) in the image using a div, so we're now checking for the presence of that div.
> Check for the olivers_nocost div instead of (1)

- src/net/sourceforge/kolmafia/Modifiers.java
Switching to eager parsing of modifier strings had the unfortunate effect of making `resetModifiers` and thus `KoLCharacter.reset` much slower, causing the test suite to time out. This PR returns to lazy parsing, but this time keeping strings and modifiers in two separate maps for better typing.
> Go back to lazy parsing of modifier strings.

- .pre-commit-config.yaml
Add a config for [pre-commit](https://pre-commit.com/), which allows a user to locally opt-in to running some additional checks before committing. I've only enabled the additional check to run spotless as it completes very fast and it's something a few other devs have mentioned they forget to run before committing but would like to happen automatically.
To use pre-commit please see the [quick start instructions](https://pre-commit.com/#quick-start).
As an example if you were to try to commit a change that needs to be formatted by spotless, the first commit attempt fails because pre-commit modifies files then the second attempt succeeds:
```
> pre-commit install
pre-commit installed at .git/hooks/pre-commit
> git stage test/net/sourceforge/kolmafia/AreaCombatDataTest.java 
> git commit -m …
```
> Add [optional] pre-commit config

- src/data/fullness.txt
They've been found giving pizza lovers 21-24 adventures, which amounts to a base adventure gain of 19-22
> spading data for t4 cookbookbat foods

- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/request/UseItemRequest.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/request/UseItemRequestTest.java
As reported in https://kolmafia.us/threads/divide-by-zero-error-when-consuming-spleen-item.28353/. Fix from Veracity, tests from me.
> fix: fix maximum uses for non-ASCII named items

- src/net/sourceforge/kolmafia/utilities/PHPMTRandom.java
- src/net/sourceforge/kolmafia/utilities/PHPRandom.java
- test/net/sourceforge/kolmafia/utilities/PHPMTRandomTest.java
- test/net/sourceforge/kolmafia/utilities/PHPRandomTest.java
@phulin and I are working on reverse-engineering the code for TCRS item modification. On gausie/kolmafia we're close to correctly generating the mods (including the precise item name change) for every item in every seed. Expect a PR on that soon, negating the need for the TCRS datafiles!
But in doing so, it seemed pertinent to test my implementations of PHP's rand functions. @phulin found that PHPMTRandom didn't deal well with negative seeds (not used in any of the instances we've handled so far so we didn't notice) so I have fixed that issue too.
- Add tests for PHPRandom
- Add tests for PHPMTRandom
- Add tests for negative seeds
- Fix bugs with negative seeds in PHPMTRandom
> Tests and fixes for PHP Random functions

- src/net/sourceforge/kolmafia/request/FightRequest.java
I reported a bunch of typos to KoL.
Fortunately, we don't depend on the messages.
```
Round 1: Your toy train moves ahead to the Brawn Silo. You train picks up some fresh brawn!
Round 1: You gain 540 Strongness
Round 1: Your toy train moves ahead to the Brain Silo. You train picks up some fresh brain!
Round 1: You gain 555 Enchantedness
Round 1: Your toy train moves ahead to the Groin Silo. You train picks up some fresh groin!
Round 1: You gain 912 Chutzpah
Round 1: Your toy train moves ahead to the Viewing Platform. As your train passes the viewing platform, the crowd shouts and cheers inspiring you!
Round 1: You gain 225 Strongness
Round 1: You gain 225 Enchantedness
Round 1: You gain 288 Sarcasm
Round 1: Your toy train moves ahead to the Logging Mill. The lumber mill appears to be …
```
> Log toy train action in session log

- src/net/sourceforge/kolmafia/textui/command/RelayBrowserCommand.java
Occasionally the relay server slows to a crawl for me. Historically I've restarted Mafia. I thought it would be nice to have the option to stop the relay server (and perhaps restart it later) if that happens.
> feat: add ability to stop relay server

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
May as well go up a version.
I was waiting a while expecting a speedy 7.6.1, but it never arrived.
> chore: upgrade gradle to 7.6

- src/data/classskills.txt
- src/data/items.txt
- src/data/modifiers.txt
Yes, "Waiter" has two spaces after the colon. Maybe that'll get fixed. Probably not.
> feat: new crimbo skills

- src/net/sourceforge/kolmafia/preferences/Preferences.java
Java's `synchronizedSortedMap` needs to be synchronized any time we are iterating over it. Failure to do this seems to have been causing ConcurrentModificationExceptions in certain situations, especially when e.g. my laptop comes back from sleep that occurred during execution of a script. This was causing loss of preferences in some situations, as the re-login would reset the cached encoded prefs and then not successfully reinitialize them.
Not sure how to write a test for this.
> Prevent ConcurrentModificationException in preference update when re-logging.

- src/net/sourceforge/kolmafia/utilities/PHPRandom.java
- test/net/sourceforge/kolmafia/utilities/PHPRandomTest.java
The array_rand implementation in PHPRandom fails to short circuit after reaching the desired number of elements, which causes extra rolls to be drawn from the RNG. While the first result matches, future array_rand calls will be out of sync.
> Fix array_rand extra rolls.

- src/data/defaults.txt
- src/data/monsters.txt
- src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
From the wiki, all monsters drop a cinnamon machine oil.
Add the choice. Default to 1, because there's only one option so that's what you're likely to want to do.
> feat: more new zone crimbo stuff

- src/data/adventures.txt
- src/data/combats.txt
- src/data/concoctions.txt
- src/data/defaults.txt
- src/data/equipment.txt
- src/data/familiars.txt
- src/data/fullness.txt
- src/data/inebriety.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/data/monsters.txt
- src/data/outfits.txt
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/request/UseItemRequest.java
- src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
- src/net/sourceforge/kolmafia/session/ChoiceControl.java
More to come in other PRs, but I'd like to get this in quickly.
1) Coal-Shoveling Trainbot rare drop is the "really nice lump of goal" - a gift item which I have not seen yet
2) portable steam unit is once-per day
3) portable steam unit gives you an effect
4) If you have no crystal shards, Slagging Off offers only choice 3.
5) Maybe we'd like a way to alternate the options in Slagging Off? And automatically take choice 3 if you have no shards.
6) Arena parameters for Mini-Trainbot. That can certainly wait until we/I are done farming Crimbo stuff.
> Coal car stuff

- src/net/sourceforge/kolmafia/session/BreakfastManager.java
As described. In BreakfastManager, the forceContinue calls were causing userAborted to be ignored. Instead we should just set the continuation state to ignore errors incurred during the breakfast actions.
Not sure how a test could be written for this PR.
> Allow aborting breakfast with escape.

- src/data/dailylimits.txt
- src/data/defaults.txt
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/request/UseItemRequest.java
- src/net/sourceforge/kolmafia/swingui/OptionsFrame.java
- src/net/sourceforge/kolmafia/swingui/panel/DailyDeedsPanel.java
Refactor daily deeds and add portable steam unit.
Deliberately don't make a new version, because I want it to go next to
Legendary Beat, not at the end of the daily deeds.
> feat: add portable steam unit to daily deeds

- src/data/items.txt
- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/KoLmafiaCLI.java
- src/net/sourceforge/kolmafia/request/CurseRequest.java
- src/net/sourceforge/kolmafia/textui/command/PingPongCommand.java
- test/net/sourceforge/kolmafia/textui/command/CrimboTrainCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/PingPongCommandTest.java
1) pingpong TARGET - play a ping-pong game
2) crimbotrain TARGET - train a Crimbo skill
3) Fix grammar: "who" is a subject, "whom" is an object.
Both of those are once per day.
CurseRequest now checks for that.
4) train whistle is now implemented.
This is the last Crimbo 2022 content I am aware of that we had not previously supported.
Well, Arena parameters for the Mini-Trainbot. But that is for completeness; does anybody automate training in the Cake Arena anymore? I just use Familiar Jacks to get the familiar item - but when I derive the parameters, I get a slew of them to put into the mall.
Perhaps I should train, sooner, rather than later, while the price is hot. ;)
Comment: I would like to have a "Combat Items" section in modifiers.txt, preceding the "Everything Else" section.
It may …
> add pingpong command. soup up crimbotrain command. Add tests for both commands.

- src/net/sourceforge/kolmafia/swingui/widget/ListCellRendererFactory.java
While executing scripts, rendering the JLabels in the gear changer takes up something like 10-15% of CPU time in my profiling runs. The menus are all fully rerendered every time there's e.g. a status update that might change what equipment is equippable.
Changing from HTML to the basic JLabel methods dramatically reduces the amount of time needed to render. It goes from 10-15% of CPU time to essentially no time at all.
> Use setForeground instead of HTML for coloring equipment list.

- src/net/sourceforge/kolmafia/session/LocketManager.java
- test/net/sourceforge/kolmafia/session/LocketManagerTest.java
- test/net/sourceforge/kolmafia/textui/command/ReminisceCommandTest.java
In the current code, resetting when the day turns over doesn't reset LocketManager, meaning that you won't be able to make locket requests because the monsters fought property has been reset but the cached `foughtMonsters` variable hasn't. 
This PR makes it so `getFoughtMonsters` is no longer cached, meaning the value can't get out of sync with the pref (there is one source of truth). `getFoughtMonsters` gets called only infrequently, so this is not a performance issue. The PR also adds a test for this case and cleans up the tests a little.
> Don't cache fought monsters in Locket.

- src/net/sourceforge/kolmafia/request/RelayRequest.java
- test/net/sourceforge/kolmafia/request/RelayRequestWarningsTest.java
The non-intrinsic effect can be acquired via pocket wishes / hookah / other sources, and does not go away if entering a combat with equipped weapons / offhands.
This change makes a field and a method use package visibility, which is more restrictive than `public` -- I don't envision any use cases for this outside of testing.
> Only warn for the Kung Fu Fighting intrinsic.

- src/net/sourceforge/kolmafia/persistence/MallPriceDatabase.java
- src/net/sourceforge/kolmafia/request/MallSearchRequest.java
- src/net/sourceforge/kolmafia/session/MallPriceManager.java
- test/net/sourceforge/kolmafia/session/MallPriceManagerTest.java
This PR optimizes one of the remaining CPU bottlenecks in the code, the mall price database. Every write of the database serializes every recorded price again, which is slow—taking as much as 30% of execution CPU time while running mall-heavy segments of garbo.
Much like in Preferences, we can just cache the encoded values and only concatenate them when the database is written to disk. The PR also removes double-recording of mall prices when `mall_price` is called from the runtime library—in the current code `getMallPrice` saves the price and calls `searchMall`, which also saves the price.
MallPriceDatabase/MallPriceManager are sufficiently well-tested that I don't think any new tests are needed.
The PR increases speed of the following synthetic benchmark by a factor of roughly 2, and the …
> Optimize mall price database.

- src/net/sourceforge/kolmafia/KoLAdventure.java
Currently this seems to always be the case in the GCLI even on a new account:
```
ash can_adventure( $location[An Unusually Quiet Barroom Brawl] )
Returned: true
```
Visiting the wrong side of the tracks and toggling the `ownsSpeakeasy` property do not have any effect.
This change will make the `canAdventure` function check the `ownsSpeakeasy` for determining if you can adventure and should be consistent with other content-unlocker behavior.
> Check the ownsSpeakeasy property in canAdventure

- src/net/sourceforge/kolmafia/persistence/MallPriceDatabase.java
I meant to include this in #1382 - the price writing code should use a buffered output stream, instead of a LogStream which auto-flushes each byte array write.
This PR reduces time on the below benchmark from about 10 s to about 500 ms.
```java
@Test
void speed() {
int N = 300;
MallPriceDatabase.savePricesToFile = true;
for (var entry : ItemDatabase.entrySet()) {
MallPriceDatabase.recordPrice(entry.getKey(), entry.getKey(), true);
}
for (int i = 0; i < 2 * N / 5; i++) {
MallPriceDatabase.writePrices();
}
long start =
ManagementFactory.getThreadMXBean().getThreadCpuTime(Thread.currentThread().getId());
for (int i = 0; i < N; i++) {
MallPriceDatabase.writePrices();
}
long end = ManagementFactory.getThreadMXBean().getThreadCpuTime(Thread.currentThread().getId());
System.out.println("Elapsed: …
```
> Use non-autoflush PrintStream rather than LogStream for mall prices.

- src/net/sourceforge/kolmafia/swingui/panel/CompactSidePane.java
Much like the equipment PR, rendering HTML in the side pane is unnecessary computational effort. This PR removes HTML from the side pane rendering code in favor of native Java layout tools. It's not a huge speedup but seems to be a reduction of 1-2% of CPU time in my tests.
> Remove HTML from CompactSidePane.

- src/net/sourceforge/kolmafia/KoLmafia.java
- src/net/sourceforge/kolmafia/session/LoginManager.java
It would be good to know why we can't acquire the lock, whether it's because it's already held, or because we don't have write permissions to the directory, or something else.
> Elaborate when failing to acquire session lock.

- test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
The problem seems to have gone away, so don't time tests by default.
Leave the class in in case somebody (e.g. me) wants to time a test locally.
> chore: don't time tests any more

- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Came in on #1394. A modifier can end up with particular string entries (e.g. `Modifiers.EQUALIZE`) being null.
Not yet sure what's causing it, but the only way I can see that happening is if the Modifiers constructor is called, and not all the string fields are set (for some reason), Not sure how this could happen, can't reproduce from scratch. `getModifiersInternal` can return null under some circumstances, and in that case `set` doesn't populate anything, so /maybe/ that's happening?
> fix: modifiers NPE

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/FamiliarData.java
- src/net/sourceforge/kolmafia/objectpool/FamiliarPool.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/session/ResultProcessor.java
- src/net/sourceforge/kolmafia/webui/CharPaneDecorator.java
- test/net/sourceforge/kolmafia/session/ResultProcessorTest.java
Track drops from optimistic candle, rockin' robin, garbage fire and hobo in sheep's clothing.
Only the Sheep needs the number dropped today to calculate the number of turns until the next one, but the others are also useful for scripting.
Implementation question for consideration: existing code in the sidebar looked for "-1" as a signifier for "no limit". I used this, but before that I had `Integer.MAX_VALUE`. Is -1 reasonable?
> feat: track drops from infinite drop familiars (including sheep)

- src/data/adventures.txt
- src/data/inebriety.txt
- src/data/monsters.txt
Construct drop rates are likely to be 15% each, by wiki data and autumn-aton drops.
All hulking construct drops are conditional: first, you only get drops if it is told to "ATTACK FLOOR" or "ATTACK WALL". Floor gives the command cards, wall gives the object cards. Second, you get 2-4 drops total. Third, item drop bonuses are ignored.
By wiki, nice warm beer is beer. Probably not canned though!
On the topic of conditional drops, fix swarm of fire ants: the familiar items are all 5%, not 1%, but they're conditional so at most one can drop.
> feat: some data for El Vibrato

- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/request/CampgroundRequest.java
- test/net/sourceforge/kolmafia/request/CampgroundRequestTest.java
- test/root/request/test_campground_rock_garden_0.html
- test/root/request/test_campground_rock_garden_0_1.html
- test/root/request/test_campground_rock_garden_5.html
Detect rock garden levels. 
Picking is slightly unusual, haven't yet decided what the best design would be. Might want to interpret this as three "garden"s as they're all individually pickable: `campground.php?action=rgarden1`, `rgarden2`, `rgarden3`. No idea how to configure this in the harvest preference. Don't really know how the garden command should work either; maybe it should take a number or otherwise do all? I think it's most likely folk will either harvest anything or all on day 7, though.
> feat: detect rock garden levels

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
I got annoyed with the standard scripting path of calling `cliExecute("ccs xxx")` that prints an extra line of "CCS set to xxx" every adventure, so this function doesn't print anything and just returns true on success. I'll note in the docs on the wiki that script authors have to know that `battleAction` needs to be set as well or it won't work. This goes along with `read_ccs` and `write_ccs` which were recently added.
> Add set_ccs ASH function.

- src/net/sourceforge/kolmafia/KoLAdventure.java
- src/net/sourceforge/kolmafia/request/EquipmentRequest.java
- src/net/sourceforge/kolmafia/session/EquipmentManager.java
- src/net/sourceforge/kolmafia/swingui/ClanManageFrame.java
- src/net/sourceforge/kolmafia/swingui/panel/GearChangePanel.java
- src/net/sourceforge/kolmafia/textui/command/CheckDataCommand.java
- src/net/sourceforge/kolmafia/textui/command/RefreshStatusCommand.java
Accept various refactorings while we're in the file.
There are several spaces in the codebase where we use `public static final int`s where enums would be better (and prevent passing ints outside the range, or from the wrong source, to functions). This is one of them (and likely the simplest).
> refactor: move EquipmentRequestType to enum

- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/VYKEACompanionData.java
- src/net/sourceforge/kolmafia/textui/DataTypes.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/DebugModifiersTest.java
- test/root/expected/test_vykea.ash.out
- test/root/scripts/test_vykea.ash
There are several spaces in the codebase where we use `public static final int`s where enums would be better (and prevent passing ints outside the range, or from the wrong source, to functions). This is one of them.
This one uses the ordinal, both in the exposed ASH type and the image. Perhaps it should be explicitly in the enum, but equally I can't see it changing. I added a test for the image, so we'll know by failing test if the ordinal of the last entry changes.
> refactor: move VykeaCompanionType to enum

- src/net/sourceforge/kolmafia/AdventureResult.java
- src/net/sourceforge/kolmafia/MonsterData.java
- src/net/sourceforge/kolmafia/textui/command/ConditionsCommand.java
There are several spaces in the codebase where we use `public static final int`s where enums would be better (and prevent passing ints outside the range, or from the wrong source, to functions). This is one of them.
This one also used the ordinal in `compareTo`. The specific numbers have been changed (most are exactly one out, except `PSEUDO_ITEM`), and don't seem to matter.
The order has been kept the same except in the case of `EFFECT` and `BOUNTY_ITEM` which had the same priority. This may have been a bug, as it seemed unintended in most cases. Sorting a list containing both effect and bounty items should now put all the effects after all the bounty items, whereas previously it would have jumbled them together. I don't think that's behaviour we want to keep.
> refactor: convert priority into enum

- src/data/fullness.txt
- src/data/inebriety.txt
- src/data/modifiers.txt
- src/data/zonelist.txt
1) The Train adventure zones are Removed
2) The EPIC foods are now decent. I removed the consumption data and set them to Unspaded
3) The Trainbot effects are untouched, but the potions give 1 turn, not 10
> Crimbo22 is over

- src/net/sourceforge/kolmafia/request/ClanLoungeRequest.java
- src/net/sourceforge/kolmafia/session/ClanManager.java
- test/net/sourceforge/kolmafia/request/ClanLoungeRequestTest.java
As reported by ... somebody.
When switching clans, speakeasy/hotdogs/floundry are rebuilt from saved clan lounge item lists.
Don't need to - can't - re-add the item to the item list.
> Fix adding speakeasy drinks using existing AdventureResults

- src/net/sourceforge/kolmafia/moods/MPRestoreItemList.java
- src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
- src/net/sourceforge/kolmafia/request/CafeRequest.java
- src/net/sourceforge/kolmafia/request/ClanStashRequest.java
- src/net/sourceforge/kolmafia/request/ClosetRequest.java
- src/net/sourceforge/kolmafia/request/SewerRequest.java
- src/net/sourceforge/kolmafia/request/StorageRequest.java
- src/net/sourceforge/kolmafia/session/BreakfastManager.java
- src/net/sourceforge/kolmafia/session/FamiliarManager.java
- src/net/sourceforge/kolmafia/session/InventoryManager.java
- src/net/sourceforge/kolmafia/session/ValhallaManager.java
- src/net/sourceforge/kolmafia/swingui/ClanManageFrame.java
- src/net/sourceforge/kolmafia/swingui/CoinmastersFrame.java
- src/net/sourceforge/kolmafia/swingui/ItemManageFrame.java
- src/net/sourceforge/kolmafia/swingui/panel/CreateItemPanel.java
- src/net/sourceforge/kolmafia/swingui/panel/CreateSpecialPanel.java
- src/net/sourceforge/kolmafia/swingui/panel/ItemManagePanel.java
- src/net/sourceforge/kolmafia/swingui/panel/MeatTransferPanel.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/textui/command/ClanStashCommand.java
- src/net/sourceforge/kolmafia/textui/command/CleanupJunkRequest.java
- src/net/sourceforge/kolmafia/textui/command/ClosetCommand.java
- src/net/sourceforge/kolmafia/textui/command/StorageCommand.java
- test/net/sourceforge/kolmafia/request/StorageRequestTest.java
There are several spaces in the codebase where we use `public static final int`s where enums would be better (and prevent passing ints outside the range, or from the wrong source, to functions). This is one of them.
Convert the simple requests (closet, storage, stash) at once. They're all very similar.
> refactor: move simple request ints to enum

- src/data/familiars.txt
- src/net/sourceforge/kolmafia/RequestEditorKit.java
- src/net/sourceforge/kolmafia/swingui/FamiliarTrainingFrame.java
1) Our Relay Browser annotation of the Evilometer thinks the boss has 25 Evil. I fixed that.
2) Teach Familiar Trainer to use astral pet sweater
3) Arena parameters for Cookbootbat
```
Results for Cookbookbat after 10 trials using 91 turns:
Cage Match      0       0       0            0              0
Scavenger Hunt  24      31      50           0              3
Obstacle Course 43      50      43           0              2
Hide and Seek   23      38      50           0              3
```
4) Arena parameters for Mini-Trainbot
```
Results for Mini-Trainbot after 10 trials using 120 turns:
Cage Match      20      29      47           0              3
Scavenger …
```
> Arena parameters for 3 new familiars

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/AreaCombatData.java
- src/net/sourceforge/kolmafia/Expression.java
- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java
- src/net/sourceforge/kolmafia/session/ChoiceControl.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
- test/net/sourceforge/kolmafia/ModifierExpressionTest.java
- test/net/sourceforge/kolmafia/session/CrystalBallManagerTest.java
- test/net/sourceforge/kolmafia/session/GrimstoneManagerTest.java
- test/net/sourceforge/kolmafia/session/JuneCleaverManagerTest.java
- test/net/sourceforge/kolmafia/session/OceanManagerTest.java
- test/net/sourceforge/kolmafia/session/QuestManagerTest.java
- test/net/sourceforge/kolmafia/session/RabbitHoleManagerTest.java
- test/net/sourceforge/kolmafia/session/ResponseTextParserTest.java
- test/net/sourceforge/kolmafia/session/RumpleManagerTest.java
- test/net/sourceforge/kolmafia/session/VolcanoMazeManagerTest.java
- test/net/sourceforge/kolmafia/textui/command/GongCommandTest.java
Also fix The Great Tit's Blessing, which only gives the Moxie bonus for females.
Another one which uses the value, but only in modifiers. I think something like 0 for males and 1 for females would have lead to clearer expressions than the [A/2+A/2*X] thing we're using now, but no real need to change it.
> refactor: convert gender to enum

- .github/workflows/check.yml
By https://github.com/mikepenz/action-junit-report/issues/23, this might allow annotations to be created from forks.
> fix: use the default token for creating annotations

- src/net/sourceforge/kolmafia/request/CampgroundRequest.java
- src/net/sourceforge/kolmafia/textui/command/GardenCommand.java
- test/net/sourceforge/kolmafia/request/CampgroundRequestTest.java
- test/net/sourceforge/kolmafia/textui/command/AsdonMartinCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/GardenCommandTest.java
- test/root/request/test_campground_no_garden.html
Support harvesting rock garden. The normal `action=garden` destroys your garden but doesn't give you anything.
Tested with an actual rock garden.
Don't support harvesting individual slots, as that would be more complex and I think most of the time you want to harvest all the slots anyway. A user can easily do this by just calling the URL.
Fix a likely bug with harvesting grass / non-grass: the comment says that anything none-grass should have 1 request, but then sets grass (or anything with count 8) to count 1.
> feat: support rock garden in garden command

- src/data/equipment.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/data/outfits.txt
From the Wiki.
I gave it Power 50 because all Standard Normal equipment has that power.
Similarly, all Standard Hardcore equipment has power 120.
> Chiffon outfit

- src/net/sourceforge/kolmafia/KoLCharacter.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Fixes the issue reported in https://kolmafia.us/threads/maximizer-is-valuing-experience-ml-as-though-it-were-muscle-experience-percent.28513/
I am kind of confused as to why this wasn't picked up by `DebugModifiersTest.listsStatExpNormal`.
> fix: apply ML bonus to stat exp, not exp pct

- src/net/sourceforge/kolmafia/modifiers/DoubleModifierCollection.java
This gets back some of the performance gains from sparse modifier collections, but not all for some reason. Might just be the increased indirection from using an enum rather than an int.
> Add sparse/dense optimization to DoubleModifierCollection.

- src/net/sourceforge/kolmafia/DebugModifiers.java
- src/net/sourceforge/kolmafia/FamiliarData.java
- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/PastaThrallData.java
- src/net/sourceforge/kolmafia/Speculation.java
- src/net/sourceforge/kolmafia/maximizer/Evaluator.java
- src/net/sourceforge/kolmafia/maximizer/Maximizer.java
- src/net/sourceforge/kolmafia/maximizer/MaximizerSpeculation.java
- src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java
- src/net/sourceforge/kolmafia/modifiers/StringModifier.java
- src/net/sourceforge/kolmafia/modifiers/StringModifierCollection.java
- src/net/sourceforge/kolmafia/persistence/ItemDatabase.java
- src/net/sourceforge/kolmafia/request/CharPaneRequest.java
- src/net/sourceforge/kolmafia/session/GreyYouManager.java
- src/net/sourceforge/kolmafia/session/LocketManager.java
- src/net/sourceforge/kolmafia/session/TowerDoorManager.java
- src/net/sourceforge/kolmafia/session/YouRobotManager.java
- src/net/sourceforge/kolmafia/swingui/panel/GearChangePanel.java
- src/net/sourceforge/kolmafia/swingui/widget/TableCellFactory.java
- src/net/sourceforge/kolmafia/textui/command/AccordionsCommand.java
- src/net/sourceforge/kolmafia/textui/command/ModRefCommand.java
- src/net/sourceforge/kolmafia/textui/command/SpeculateCommand.java
- src/net/sourceforge/kolmafia/utilities/WikiUtilities.java
- src/net/sourceforge/kolmafia/webui/UseLinkDecorator.java
- src/net/sourceforge/kolmafia/webui/ValhallaDecorator.java
- test/net/sourceforge/kolmafia/DebugModifiersTest.java
Much easier than doubles. Might try some perf improvements, now that this is detracting:
* I think we can inline every function call that only calls a different function
* We can probably avoid doing the null checks most of the time, especially for constants
* stat-modifying intrinsic effects on equipment were removed in 2012, so code dealing with that (e.g. in the maximizer) can also be removed
> refactor: convert string modifiers to enum

- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/maximizer/Evaluator.java
- src/net/sourceforge/kolmafia/modifiers/DerivedModifier.java
- src/net/sourceforge/kolmafia/request/UseSkillRequest.java
- src/net/sourceforge/kolmafia/swingui/panel/CompactSidePane.java
- src/net/sourceforge/kolmafia/textui/command/SpeculateCommand.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
Convert "derived" modifiers to enum.
I think derived modifiers are doubles which have to be computed after all the other doubles are computed. But then, prismatic damage is in a similar boat, but that's a double.
Looking at the function `Modifiers.get`, line 681, we compute all the derived modifiers, then throw most of them away and only take the one we're interested in. Ha! But then, all the buffed stats require each other if anything is equalised, and HP and MP require muscle and mysticality respectively, so perhaps most of it washes out.
`SpeculateCommand.doNumeric` is a good example of something we can update once `bitmaps` is moved to an enum: we're starting with a modifier, converting to a string, passing through to a method that doesn't know what the type of modifier is any more, …
> refactor: make derived modifiers an enum

- src/net/sourceforge/kolmafia/request/EquipmentRequest.java
Declaring an `EquipmentRequest` with an explicit slot, where the slot was crown or bjorn, would lead to no `requestType` being set, and an NPE in `run`.
The NPE was presumably introduced in #1424: before that, `requestType` was initiliased to `0`, which matched `REFRESH`, so the command just silently did the wrong thing.
> fix: avoid NPE, and error explicitly, when using equip with crown or bjorn

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/maximizer/Evaluator.java
- src/net/sourceforge/kolmafia/maximizer/Maximizer.java
- src/net/sourceforge/kolmafia/maximizer/MaximizerSpeculation.java
- src/net/sourceforge/kolmafia/modifiers/BitmapModifier.java
- src/net/sourceforge/kolmafia/modifiers/BitmapModifierCollection.java
- src/net/sourceforge/kolmafia/swingui/panel/CompactSidePane.java
- src/net/sourceforge/kolmafia/swingui/panel/GearChangePanel.java
- src/net/sourceforge/kolmafia/swingui/widget/TableCellFactory.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/textui/command/ModRefCommand.java
- src/net/sourceforge/kolmafia/textui/command/SpeculateCommand.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
Keep doing the bit operations for now. I'm still not sure what the point of them is. It seems to be treating every int as equivalent to a list of booleans, but sometimes it counts the bits. I don't know what the "mask" is for, either. Number of relevant slots? But I don't see where this is stored.
It has bitmaps and "raw" bitmaps. Bitmaps are a count of the bits. "Raw" bitmaps are using for masking?
> refactor: convert bitmap modifiers to enum

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
More learnings on modifiers:
* "uniques" only works in the maximizer -- if you maximize "surgeonosity" with 3 masks, it'll only recommend you equip one; but if you equip all three it'll still give you a score of 3 instead of 1
* `add(final Modifiers mods)` has some code dealing with watches, but it adds in the modifier anyway if it's not "adventures". However, you can't equip watches at the same time, so they don't stack even outside of adventures. The maximizer does deal with this correctly (separately).
* added some comments on what three top-level fields were. Notably, in all three cases "String" means something different.
* the class itself could (should?) be split into `ModifiersDatabase`, which like `EffectDatabase` does the parsing of the text file and serves as a store for the …
> tests: add more tests for complex modifiers / maximizer code

- src/data/adventures.txt
- src/net/sourceforge/kolmafia/KoLConstants.java
- src/net/sourceforge/kolmafia/session/ChoiceControl.java
- src/net/sourceforge/kolmafia/session/VolcanoMazeManager.java
- src/relay/volcanomaze.2.js
- test/net/sourceforge/kolmafia/session/VolcanoMazeManagerTest.java
1) DiffLevel of the Outer Compund is mid
2) You can walk away from the Treasure House choice
3) In the Volcano Maze, once we have seen all the maps and can calculate a solution (always the case, if using cached maps - the default), the hover text over the "correct" next platform (where we will go if you click the Step button) now says "Next Platform".
I considered actually changing the image to have an "X" on it or something, but I don't seem to have access to a gif editor that lets me change the pixels.
> Hover text over next platform in Volcano Maze is now 'Next Platform'

- .github/workflows/check.yml
This should allow headless ubuntu to run tests in swing components
> Run ubuntu checks through xvfb

- jenkinsfile
This makes Jenkins starts an xvfb server at the start of running tests and then stops the server when the test run completes.
> Run tests through xvfb on Jenkins

- src/net/sourceforge/kolmafia/textui/command/UnequipCommand.java
A side-effect of #1457.
Some folk have scripts that end up running code like `equip($item[none], $slot[none])`, which gets translated into `unequip none`, which observes that "none" matches the slot "none" but can't distinguish that from being unable to find a slot, and so looks for an item with name "none", finds that the crown or bjorn has nothing in it and tries to unequip that, and then errors.
Be kinder to those folk by doing nothing in that case.
> fix: don't error when unequipping nothing

- src/net/sourceforge/kolmafia/session/EquipmentManager.java
1. `equipment` is never used in a GUI so doesn't need to be Lockable.
2. `newOutfits` is a local variable passed to a function that only uses list methods, so it can be a plain list too.
Looking at `historyLists` not sure there's benefit in storing every piece of equipment we've equipped this session, but no major harm I guess.
> refactor: remove some locked lists from equipment manager

- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- test/net/sourceforge/kolmafia/textui/command/StickersCommandTest.java
I'm looking at using enums in EquipmentManager, and as part of that I'd like a few areas of the codebase to have more unit tests.
Add tests for sticker command, checking:
* StickerCommand itself
* In EquipmentRequest, equipping a sticker
> tests: add tests for sticker command

- src/net/sourceforge/kolmafia/maximizer/Evaluator.java
- src/net/sourceforge/kolmafia/maximizer/Maximizer.java
- src/net/sourceforge/kolmafia/moods/ManaBurnManager.java
- src/net/sourceforge/kolmafia/moods/MoodTrigger.java
- src/net/sourceforge/kolmafia/webui/CharPaneDecorator.java
1. Rename `checkEffectConstraints` to what it does
2. Make `checkConstraints` return an enum describing what each number means
> refactor: small readability improvements for maximizer constraints

- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- test/net/sourceforge/kolmafia/textui/command/EquipCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/UnequipCommandTest.java
Tests for unequipping and equipping things, especially folders, as this involves arithmetic with slots.
> tests: (un)equip command

- src/net/sourceforge/kolmafia/textui/DataTypes.java
Off #1510, likely cause of autoscend issues.
Can confirm the issue (an issue) is fixed by running `ash equipped_item($slot[none])` and not getting an error.
> fix: slot 'none' is number 0, not number -1

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/maximizer/Evaluator.java
- src/net/sourceforge/kolmafia/persistence/SkillDatabase.java
- src/net/sourceforge/kolmafia/request/FightRequest.java
- src/net/sourceforge/kolmafia/request/UseSkillRequest.java
Also fix logic around blessing level.
* Spirit boon gives turns only for normal blessings -- it doesn't give anything for avatars.
* Spirit Pariah prevents casting blessings, even if you have the avatar effect (or so says the wiki, I haven't been TT for a while).
> refactor: convert turtle blessing level to enum

- src/net/sourceforge/kolmafia/request/PlaceRequest.java
Link uses an underscore instead of a dash.
> Fix typo when setting shadowRiftIngress at beanstalk

- src/net/sourceforge/kolmafia/maximizer/CheckedItem.java
- src/net/sourceforge/kolmafia/maximizer/Evaluator.java
- src/net/sourceforge/kolmafia/maximizer/Maximizer.java
- src/net/sourceforge/kolmafia/maximizer/PriceLevel.java
- src/net/sourceforge/kolmafia/swingui/MaximizerFrame.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/textui/command/ModifierMaximizeCommand.java
- test/internal/helpers/Maximizer.java
Valid values were 0, 1 and 2. -1 was also a consistent value, which was treated as 0 in practice (by functions checking > 0 or <= 0).
Names were taken from the UI: "don't check", "buyable only", "all consumables".
> refactor: convert price level to enum

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/maximizer/Evaluator.java
- src/net/sourceforge/kolmafia/maximizer/Maximizer.java
- src/net/sourceforge/kolmafia/modifiers/BitmapModifier.java
- src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java
- src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java
- src/net/sourceforge/kolmafia/swingui/panel/CompactSidePane.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Bitmap modifiers are numeric, so externally everything should continue to work.
This fixes the problem where equipping duplicate surgical equipment increased the surgeonosity modifier when it shouldn't. The maximizer always correctly didn't recommend multiple items -- it was just the modifiers that displayed the incorrect value.
Planning to do the same for clownosity and remove the concept of "unique items" -- items that are unique only for one modifier.
> refactor: make surgeonosity a bitmap modifier

- src/data/adventures.txt
- src/data/combats.txt
- src/data/zonelist.txt
- src/net/sourceforge/kolmafia/objectpool/AdventurePool.java
- src/net/sourceforge/kolmafia/persistence/AdventureDatabase.java
- src/net/sourceforge/kolmafia/request/AdventureRequest.java
- src/net/sourceforge/kolmafia/request/PlaceRequest.java
- test/net/sourceforge/kolmafia/persistence/AdventureDatabaseTest.java
This attempts to make each of the 13 places you can enter a Shadow Rift a distinct adventure area.
The first time you adventure there, it goes to place.php, which redirects to adventure.php, which redirects to fight.php.
Subsequent times through the same rift, it goes straight to adventure.php which redirects to fight.php.
Automate 1 Shadow Rift (Forest Village)
Automate 1 Shadow Rift (Somewhere Over the Beanstalk)
Automate 1 Shadow Rift (Somewhere Over the Beanstalk)
Automate 2 Shadow Rift (The Castle in the Clouds in the Sky)
```
[742] Shadow Rift (Forest Village)
Encounter: shadow spider
...
[743] Shadow Rift (Somewhere Over the Beanstalk)
Encounter: shadow stalk
...
[744] Shadow Rift (Somewhere Over the Beanstalk)
Encounter: shadow orb
...
[745] Shadow Rift (The Castle in the Clouds …
```
> Each Shadow Rift ingress is an adventure area

- src/net/sourceforge/kolmafia/request/AdventureRequest.java
- test/net/sourceforge/kolmafia/persistence/AdventureDatabaseTest.java
When switching to a new Shadow Rift, must reconstruct fields in the AdventureRequest for that location.
> Must reconstruct fields when changing rift

- src/net/sourceforge/kolmafia/request/CampgroundRequest.java
- src/net/sourceforge/kolmafia/textui/command/GardenCommand.java
- test/net/sourceforge/kolmafia/textui/command/GardenCommandTest.java
If you have a Rock Garden, "garden pick" will pick all three plots.
This PR allows:
garden pick plot1
garden pick plot1 plot3
etc., if you only want to pick a subset of the plots.
CampgroundRequest registers crop->plot for Rock Garden crops only.
If another garden with multiple plots is released in the future, changes will be required, obviously, but I don't want to try to predict what they will be. :)
> Allow 'garden pick plot1' for the Rock Garden

- src/net/sourceforge/kolmafia/maximizer/Maximizer.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
My character was overdrunk when I coded this, so, although debug logging showed the right code paths being executed, I have not actually seen the end result in-game.
However, I wrote tests - and they all seem to indicate it will work, so I look forward to trying it live after rollover - using the Wine-Fortified wine I generated with Drunkula's wineglass while overdrunk. :)
I want to see the tests succeed here, so, I opened the PR.
Edit: it worked perfectly.
Maximize for init, it says to drink the wine for +80.
Maximize for other wine effects, they are not considered.
> Maximizer suggests vintner wine only if you have one with the correct effect

- src/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanel.java
It's distracting.
You can still create them - for a casual run or to be pulled - in a Create panel.
> Don't show Legendary foods in Food panel if you've already eaten one

- src/data/monsters.txt
- src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
Yendor gave us a bunch of Avatar of Shadows over Loathing monsters.
We are grateful. We took his data and integrated it.
Yendor then edited his post in-place to give us the rest.
I happened to notice it, and brought the new data in
I want confirmation that the name "Dark Noël" contains UTF-8 characters, as opposed to HTML character entities, but other than that, we're cool.
I think in addition to path monster maps, we need class monster maps.
I did that. Observations:
- The only place these are used is in ASH functions:
get_monsters(location) returns an array: index -> monster
get_location_monsters(location) returns a map: monster -> boolean
Both of these functions used to map monsters through the path map. Now they also run them through the class map.
- get_monster_mapping(string …
> update more aosol monsters

- src/net/sourceforge/kolmafia/request/ClanLogRequest.java
Tested manually using the command "clan stashlog".
> refactor: use enum for clan log entry types

- src/data/combats.txt
- src/net/sourceforge/kolmafia/AreaCombatData.java
- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/MonsterData.java
- src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java
- src/net/sourceforge/kolmafia/request/RelayRequest.java
- src/net/sourceforge/kolmafia/swingui/panel/AdventureSelectPanel.java
- src/net/sourceforge/kolmafia/textui/command/AreaSummaryCommand.java
- src/net/sourceforge/kolmafia/textui/command/MonsterDataCommand.java
1) The Naughty Sorceress' Chamber has all three forms in it.
2) The Location Details pane in the Adventure Frame now shows the actual path-specific bosses
3) You don't need a wand in Shadows over Loathing
> Show mapped monsters in Location Details

- src/net/sourceforge/kolmafia/persistence/AscensionSnapshot.java
- src/net/sourceforge/kolmafia/persistence/ProfileSnapshot.java
- src/net/sourceforge/kolmafia/request/AscensionHistoryRequest.java
- src/net/sourceforge/kolmafia/session/ClanManager.java
- src/net/sourceforge/kolmafia/swingui/ClanManageFrame.java
- src/net/sourceforge/kolmafia/webui/RelayLoader.java
Delving into fairly obscure parts of the codebase here. These classes make a snapshot (a series of web pages) and are accessed from the Clan Manager frame.
Also fix some bugs in the area. Yes, `file.toURI()` throws a RuntimeException if it fails... I don't know why.
> refactor: convert snapshot filters to enums

- src/net/sourceforge/kolmafia/objectpool/SkillPool.java
- src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java
- src/net/sourceforge/kolmafia/request/FightRequest.java
- src/net/sourceforge/kolmafia/webui/StationaryButtonDecorator.java
1) Emmental Elemental and Stilton Splatter are once per combat Cheese Wizard skills
2) Knife in the Darkness, Venomous Rift, and Drum Roll are once per combat Jazz Agent skills
3) Motif gives 25 turns of Everything Looks Blue and cannot be cast while that effect is active.
Disable the Stationary Button for that skill if so.
I wondered why Dark Noël was not showing up as a mapped monster.
Turns out, the "key" in MONSTER_DATA is CombatActionManager.encounterKey(name, false).
Which is to say, entityEncoded, not lowercased.
4) create MonsterDatabase.monsterKey(name).
Use this when putting/getting from MONSTER_DATA - including setting up path/class boss mappings.
Note that KoL may have Dark Noël with either a UTF-8 character or a character entity. For example, the angry pi&ntilde;ata, …
> More once per combat skills

- src/net/sourceforge/kolmafia/textui/command/ModRefCommand.java
- src/net/sourceforge/kolmafia/utilities/StringUtilities.java
- test/net/sourceforge/kolmafia/textui/command/ModRefCommandTest.java
- test/net/sourceforge/kolmafia/utilities/StringUtilitiesTest.java
It can be hard to remember all the types of modifier KoL offers (e.g. for a hat drop, there is item drop, gear drop and hat drop).
Add a filter for modref so you can type `modref @Drop` to get all the drop modifiers (and some other stuff where the name contains "drop", but this is good enough for me).
> feat: add filter for modref

- src/net/sourceforge/kolmafia/request/RelayRequest.java
- src/net/sourceforge/kolmafia/request/SpelunkyRequest.java
- test/net/sourceforge/kolmafia/request/RelayRequestWarningsTest.java
These are "enum-like", in that they're all alike, and the numbers don't matter, only that they're distinct.
Generate them automatically instead. Most numbers do change, but the specific values don't matter.
This should make adding new ones slightly easier (as now you don't have to care about the string value).
> refactor: convert confirms to enum

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/modifiers/BitmapModifier.java
- src/net/sourceforge/kolmafia/modifiers/BooleanModifier.java
- src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java
- src/net/sourceforge/kolmafia/modifiers/StringModifier.java
- src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java
Fix issue reported in https://kolmafia.us/threads/gelnoob-skills-are-counted-in-rollover-adventures.28682/
Fix logic to check each modifier individually instead of matching on the whole string.
Also run `checkmodifiers` and fix the reported issues.
> fix: match modifier strings exactly

- src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java
Throw exceptions instead of silently continuing if error.
> fix: break early when iterating over modifiers if matched

- src/net/sourceforge/kolmafia/moods/HPRestoreItemList.java
- src/net/sourceforge/kolmafia/moods/MPRestoreItemList.java
- src/net/sourceforge/kolmafia/request/CampAwayRequest.java
- src/net/sourceforge/kolmafia/request/PlaceRequest.java
Your Getaway Campsite is unlocked by using the IOTM.
There is no "day pass" to get access.
If we saw you use the item, we set getawayCampsiteAvailable to true
If we see it in the woods, we set getawayCampsiteAvailable to true.
If it restricted, you will not see it in the woods.
1) Do NOT set that property to false in that case; you still own the IOTM
2) Model usage of the tent for HP/MP recovery exactly on how we do it for the Chateau:
CampAwayRequest.campAwayTentAvailable is true if you have it and have access to it.
CampAwayRequest.campAwayTentRestUsable is true if "restUsingCampAwayTent" is true and it is available.
3) HPRestoreList and MPRestoreList using that latter function (a la how it uses the Chateau) rather than explicitly checking properties on its own. This means it correctly …
> Never set campawayTentAvailable to false when viewing woods

- src/net/sourceforge/kolmafia/session/InventoryManager.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
Takes a boolean parameter on whether to check all familiars (including those not currently out).
Works like `available_amount`, but just the equipped bit.
> feat: add `equipped_amount(item, boolean)`.

- src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
- src/net/sourceforge/kolmafia/persistence/ItemDatabase.java
Instead of having separate flag variables which duplicate attribute flags, just use the attributes directly.
Also crash if we encounter an unknown flag instead of ignoring that line. It represents a data problem that should be fixed.
> refactor: reuse attributes instead of separate flags 

- src/data/modifiers.txt
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Issue introduced in #1307.
The problem is that `getAllModifiers` checks `modifierStringsByName` for keys, but `overrideModifier` only modifies `modifiersByName`. So if we override a modifier that isn't in `modifiers.txt`, the maximizer won't see it.
I wrote the test in r26967 to confirm this was the issue, then fixed it.
> fix: bird of the day doesn't show up in maximizer

- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java
Follow-up to #1596.
I couldn't get the other data structure working, so I think warning + add current modifiers is the best we can do.
We shouldn't remove the modifier we overrode from strings if removing the override: strings is loaded once and never reset. Ideally we would remove it only if it wasn't present to begin with, but we have no way of knowing that.
> feat: add modifier to strings by name if key not present

- src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java
Apparently this message displays in TCRS, so add enough information to start to debug it.
> feat: include modifier in warning message

- src/net/sourceforge/kolmafia/session/ChoiceControl.java
Dropping AWOL or ASOL loses you the classes, even though you keep it after freeing King Ralph.
Support those path dropping adventures.
> feat: do post-avatar processing after dropping awol or asol

- src/data/modifiers.txt
For experience, we don't distinguish between sporadic and non-sporadic sources, we just multiply the bonus by the occurrence rate.
I assumed they were 50/50. I'm not sure whether anyone has ever checked.
> feat: include the miniature crystal ball's sporadic enchants

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
This function already exists in both js and ash; `RuntimeLibrary.getModifierType` handles thrall perfectly. This will make `ashref` and `jsref`, as well as the typescript definitions that get published alongside each mafia revision, reflect this reality.
> numeric_modifier(thrall, string) exists

- src/data/items.txt
- src/net/sourceforge/kolmafia/KoLmafiaCLI.java
- src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
- src/net/sourceforge/kolmafia/textui/command/CheckDataCommand.java
https://museum.loathers.net exposes all the plurals for public in-game items on an API request. These are obtained from the Display Case data dump, and so are accurate to the in-game values.
Add a `checkmuseumplurals` command to compare these against Mafia's.
Also update the plurals in the items data file, automatically. Names were corrected where the issue wasn't terminal spaces: "fire ant pheromones " and "St. Pete's sneaky smoothie    " have been left as they were (without the spaces).
> feat: add checkmuseumplurals command

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/AreaCombatData.java
- src/net/sourceforge/kolmafia/objectpool/SkillPool.java
- src/net/sourceforge/kolmafia/request/FightRequest.java
- src/net/sourceforge/kolmafia/session/BanishManager.java
- src/net/sourceforge/kolmafia/webui/StationaryButtonDecorator.java
Punt banishes, behaving the same as Batter Up!
Track the motif monster, but don't modify the area combat data yet as it's still unspaded what exactly it does. I think the current guess is +2 copies, adventure queue rejection still occurs.
By wiki messages, Free-For-All can be "used" with Everything Looks Red, but does nothing.
> feat: add more support for certain aosol skills

- .github/workflows/build.yml
- .github/workflows/check.yml
- .github/workflows/npm.yml
This action is failing far too often (as a false positive: failing to access some website) to be worth doing.
The aim is to avoid being vulnerable to a social engineering attack where an outsider upgrades gradle; to avoid that we can just always ensure that we only update gradle ourselves.
> feat: remove validate gradle wrapper action

- src/net/sourceforge/kolmafia/persistence/SkillDatabase.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
`StringUtilities.parseInt` never throws a `NumberFormatException`. Check numeric first and continue if not.
As a side effect, `$skill[[anythingNonNumeric]whatever]` will no longer parse to `$skill[none]`. I hope nobody was relying on this degenerate behaviour.
> fix: accept $skill[zero placeholder]

- src/data/maximizer-help.html
Follow-up to #1624.
Add the note about "passive damage" to the in-client maximizer help, too.
> feat: include underwater passive damage with `env` modifier

- src/net/sourceforge/kolmafia/session/JuneCleaverManager.java
- test/net/sourceforge/kolmafia/request/AdventureRequestTest.java
- test/net/sourceforge/kolmafia/session/JuneCleaverManagerTest.java
If you have a KoLmafia session that has encountered at least one [June Cleaver](https://kol.coldfront.net/thekolwiki/index.php/June_cleaver) noncombat, ascend, then encounter another June cleaver noncombat, the `juneCleaverQueue` preference will do something like this:
```
Preference juneCleaverQueue changed from  to 1475,1473,1470,1467,1474,1467
```
Instead of:
```
Preference juneCleaverQueue changed from  to 1467
```
Currently, the backing queue data is not emptied because the `reset` function is not hooked up.
This change will remove the static data structure, instead use a new one each time the function is called, and populate it with data from the preference if there is any.
> Don't refill the June Cleaver queue with data from previous ascension

- src/net/sourceforge/kolmafia/session/RufusManager.java
- test/net/sourceforge/kolmafia/session/RufusManagerTest.java
After studying my logs again, I conclude I had a misunderstanding.
1) Shadow boss increments turns in zone - AFTER setting last NC turn
2) Shadow lodestone does not increment turns in zone.
Accept artifact quest
11 combats in Shadow Rift
Shadow Labyrinth (get artifact)
Turn in artifact
Follow Lodestone
Accept entity quest
11 combats in Shadow RIft
Fight & defeat boss
Talk to Rufus
Follow lodestone
Accept artifact quest
10 combats in Shadow Rift
Shadow Labyrinth (get artifact)
Talk to Rufus
Follow lodestone
Accept entity quest
11 combats in Shadow Rift
Fight and lose to boss
10 combats in Shadow Rift
Fight and defeat boss
Talk to Rufus
Follow lodestone
Accept entity quest
10 combats in Shadow Rift
Fight and defeat boss
Talk to Rufus
Follow lodestone
> shadow boss counts as a turn. shadow lodestone does not

- src/data/monsters.txt
Trivial Updates:
March 14 - Bosses you fight for Rufus will no longer consume an Adventure.
> feat: post-March 14, shadow bosses are free

- src/net/sourceforge/kolmafia/utilities/ByteBufferUtilities.java
post Java 7 & 9, most of this is inbuilt. Prefer those functions.
Also stop storing byte arrays in object. I think the aim was to avoid the overhead of creating many byte arrays, but it also stops them from being garbage collected.
Keep the previous behaviour of closing the input stream after reading it. I'm not sure this is a good idea, but easier to keep the behaviour.
> refactor: prefer java library functions

- src/data/monsters.txt
Update monster drop data. Ensure all items have a number / flag after them.
It would be nice to store the details of conditional drops somewhere, but for now I'll just put them here:
* the party skelteon always drops exactly one of the booze
* the hostile intelligent alien can drop at most one of the primitive items (identified in advance by the area), and it's also thought that they're sub-1%
* the murderbot drones drop 1-2 casings, monofillaments or power cells
* the murderbot soliders drop 2-3 of the above, plus 2-3 memory chips
* alien plant pod / animal goo can't be YRed and are probably sub-1%
* dolphin "orphan" drops exactly one waterlogged item
* the other Gingerbread Reef monsters have rare drops that can't be forced
> feat: monster drop data, ensure all drops have (number)

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/KoLAdventure.java
- src/net/sourceforge/kolmafia/persistence/AdventureDatabase.java
- src/net/sourceforge/kolmafia/session/ChoiceControl.java
- test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
Right now, to check to see if we can adventure in a piraterealm location, we just naively check whether we have access to piraterealm today; this will also verify that we have unlocked the island.
Right now, this will continue to assert that you can access Red Roger's Fortress even if you've completed piraterealm. I don't see any tracking that lets us handle this the way things are currently set up
> we can only adventure in piraterealm islands that we can currently adventure in

- src/net/sourceforge/kolmafia/KoLAdventure.java
- test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
Shadow Rift locations are place.php that redirects to adventure.php?snarfblat=567 (that further redirects to fight.php or choice.php).
Drunkula's wineglass works fine there.
> Wine Glass works in Shadow Rift locations

- src/net/sourceforge/kolmafia/webui/UseItemDecorator.java
- src/net/sourceforge/kolmafia/webui/UseLinkDecorator.java
You can only replace the item in your workshed once per day.
When you do so:
```
You remove the spinning wheel from your workshed.
You acquire an item: spinning wheel
You place the model train set in your workshed.
```
1) Do not add a "use" link to the item you removed.
(Note that if you "acquire" a workshed item by purchasing it, say, we will give you a "use" link if you have not yet replaced an item in your workshed today.)
2) Add a "[Visit your workshed]" link any time you successfully "use" a workshed item.
> Improve browser links when using workshed items

- src/data/monsters.txt
Move some "no-pickpocket" to "conditional".
Spade the candy witch zone. Non-thoroughly, as the 1% drops are very annoying in a zone that has turn-taking NCs that limit how many turns I can use the PFC drops for in a day. Still, I'm fairly confident, at least for Sweet-Ade Lake. Much better than 0 at least.
Also check the tiny goth giant for another 1% drop.
> feat: drop rates, with a focus on witch zones

- src/net/sourceforge/kolmafia/KoLAdventure.java
- test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
A follow-up to #1652 to fix issue reported in https://kolmafia.us/threads/cant-adventure-in-piraterealm-island.28793
When adventuring in specifically "PirateRealm Island" or "Sailing the PirateRealm Seas", we can always adventure if we can access the zone.
> fix: always adventure in 'PirateRealm Island'

- src/net/sourceforge/kolmafia/textui/command/MonkeyPawCommand.java
- test/net/sourceforge/kolmafia/textui/command/MonkeyPawCommandTest.java
When I wrote this branch name, I thought I would be adding a lot more than this. That being said, I can now confirm that the following are "illegal" characters: `.`, `,`, `'`, `"`, `(`, `)`, `!`, `?`.
But hey, we do get dashes! (tested using sonar-in-a-biscuit)
For future reference to any spaders, it looks like what happens is kol strips all "illegal" characters from the string and then compares it to item/effect names _including_ those characters. so `Let's Go Shopping!` gets stripped down to `Lets Go Shopping`, but that isn't a proper substring of `Let's Go Shopping!`. Which is to say if you're going to test whether a character can be used here, it needs to happen in the middle of the effect/item name, not as a bookend. Because `memento moiré`, for example, gets turned into `memento …
> More monkey characters

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
Per [This report](https://kolmafia.us/threads/allow-set_location-location-none-to-set-your-location-to-none.28807/), ASH set_location(location[none]) does not set KoL's idea of the current location.
I can't think of any reason a script would depend on that behavior, so I changed it to actually do (more or less) what KoL itself will do with KoLAdventure.setNextAdventure("None") - which KoL itself calls when it determines that using an item will lead to a fight; the fight is (usually) not deemed to occur in a particular location.
> Fix set_location($location[none])

- src/data/combats.txt
Marked zones as 100% combat where the non-combats are scheduled (e.g. every X adventures) and non-combat doesn't help to get them faster.
Pretty sure Madness Bakery, Ice Hotel, VYKEA should be in this set but I can't find any proof of it.
Mostly just add data where there was no data but also change Inside the Palindome and The Black Forest.
> feat: some combat rates from wiki

- src/net/sourceforge/kolmafia/AreaCombatData.java
- test/net/sourceforge/kolmafia/AreaCombatDataTest.java
- Handle monsters that only appear after a fixed number of kills
- Handle heroes that appear in ranges, return -1 as the rate to denote that the hero is possible but otherwise doesn't affect normal encounter rates (superlikelies with a very low chance) 
- Return boss as the only encounter when battlefield is cleared
> Combat data rates for The Battlefield

- src/data/consequences.txt
- src/net/sourceforge/kolmafia/request/FightRequest.java
- test/net/sourceforge/kolmafia/request/FightRequestTest.java
- Confetti extravaganza is once per fight and so it's not an optimal candidate for consequences.txt
- Testing that cinch went from 95 to 100 wasn't reliable because it didn't account for overshooting our cinch counts
- setting `skillSuccess` to true meant we incremented cinch as part of our dailylimit handling as well as the manual preference tracking previously included; this has been rectified.
> Cincho tracking fixes

- src/net/sourceforge/kolmafia/KoLCharacter.java
- test/net/sourceforge/kolmafia/request/ChateauRequestTest.java
Despite being in modifiers.txt, artificial skylight and antler chandelier mods  were never actually applied. This fixes that
> Include chateau items in modifiers

- src/net/sourceforge/kolmafia/textui/parsetree/ProxyRecordValue.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
Currently, proxy-record-wise:
* we expose .id fields for monster, location, path, slot, thrall and servant
* .to_int() works for everything with an id except slot, but is hard to remember
Add .id fields for KoL things we know about.
Slot, thrall and servant relay our internal ids, which probably shouldn't be exposed, but too late now ;)
> feat: expose ids for kol objects through a .id field

- src/net/sourceforge/kolmafia/KoLAdventure.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
> May 14 - The shadow rifts have faded into the... darker shadows?
The Shadow Rifts are still available in ASoL, or if you have the payphone in inventory. Closet doesn't count. I presume other places also don't count.
> feat: can only access shadow rifts with payphone or ASoL path

- src/net/sourceforge/kolmafia/FamiliarData.java
- src/net/sourceforge/kolmafia/KoLCharacter.java
- test/net/sourceforge/kolmafia/FamiliarDataTest.java
Now that standard.php no longer includes familiars, we don't need to special case this.
Probably worth waiting a little to confirm standard.php is stable before merging.
> feat: undo special LoL standard familiar handling

- src/data/spleenhit.txt
This is relevant in Legacy of Loathing, where all stats are precious.
Also vibrating mushroom gives adventures.
> feat: low level spleeners give stats

- src/data/familiars.txt
- src/net/sourceforge/kolmafia/request/MummeryRequest.java
- test/net/sourceforge/kolmafia/ModifierExpressionTest.java
- test/root/expected/TestFamiliarProxy.ash.out
With the advent of the stillsuit, there are many more relevant tags than just those for the mumming trunk, and there have also been several leaks as to what the tags' ingame names are.
Standardise the mumming trunk names, and add a few additional known tags.
Remove the "slayer" tag -- Zombie Slayer now just uses "undead" to check familiars.
Add the "cantalk" attribute, which allows familiars to tell you what is in the miniature crystal ball, and also to give you myst in the stillsuit.
> feat: standardise fam tag names to those ingame

- src/net/sourceforge/kolmafia/KoLmafiaCLI.java
- src/net/sourceforge/kolmafia/textui/AshRuntime.java
- src/net/sourceforge/kolmafia/textui/command/CallScriptCommand.java
- src/net/sourceforge/kolmafia/textui/parsetree/Function.java
- test/net/sourceforge/kolmafia/textui/AshRuntimeTest.java
This script:
```
void main(string op, int... args)
{
int result = 1;
print("op = '" + op + "' args = " + count(args));
foreach i, arg in args {
switch (op) {
case "+":
result += arg;
break;
case "-":
result -= arg;
break;
case "*":
result *= arg;
break;
}
}
print("result = " + result);
}
```
Has a main function with a required "string" arg and an optional array of ints.
It yields:
```
> call vargi -
op = '-' args = 0
result = 1
> call vargi (+, 2, 4, 6)
op = '+' args = 3
result = 13
> call vargi (*, 2, 4, 6, 8, 10)
op = '*' args = 5
result = 3840
```
Note that if I omit the required "op" argument it will prompt me for a string.
It will not prompt me for the array of ints.
This script:
```
void main(string... params)
{
foreach i, param in params {
print("param = " + param);
}
}
```
has no …
> allow ASH main function to have a vararg

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
Just as we have:
string[] array = split_string(string input);
=> split input on new-lines and return array
string[] array = split_string(string input, string pattern)
=> split input on pattern and return array
Now we have:
string output = join_strings(string[] array)
=> Join strings in array with new-lines
string output = join_strings(string[] array, string joiner)
=> Join strings in array with chosen separator
> New ASH functions: join_strings() is inverse of split_string()

- src/net/sourceforge/kolmafia/request/ArcadeRequest.java
I fired off a script and left my computer for a couple of hours.
When I returned, I found the script paused because KoLmafia just had to post a dialog box informing me I'd found a defective Game Grid token, requiring an "OK" confirmation.
Years ago, that might have been exciting. Once.
Now, it is, dare I say, annoying.
> No alert when find defective token

- src/net/sourceforge/kolmafia/KoLCharacter.java
Or so I assume, it makes the numbers work better.
The numbers still don't quite work because KoL doesn't have Long Winter's Nap in the `standard.php` page, but also it doesn't work (I presume, because the food/booze/candy summoning skills says they're too old).
> fix: getaway doesn't give free rests when not in standard

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/maximizer/Maximizer.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/request/UseItemRequest.java
- src/net/sourceforge/kolmafia/request/WitchessRequest.java
- src/net/sourceforge/kolmafia/swingui/panel/DailyDeedsPanel.java
- src/net/sourceforge/kolmafia/textui/command/WitchessCommand.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
We need to add a preference for actually using the replica Witchess set, because if you have one already it shows in your campsite, but you can't use it.
Also correctly show Witchess and Source Terminal in Daily Deeds if present.
> feat: witchess set is still visible in lol even if replica unused

- src/net/sourceforge/kolmafia/KoLCharacter.java
When breaking prism on a Legacy of Loathing run, lots of stuff changes. Try to handle it.
> fix: refresh familiars / inventory on lol clear

- src/net/sourceforge/kolmafia/request/MrStore2002Request.java
How did I not notice this?
Where do we use a coinmaster's "nickname", anyway?
> Fix nickname for Mr. Store 2002 coinmaster

- src/net/sourceforge/kolmafia/request/CampgroundRequest.java
```
> /cast summon love song
```
results in:
```
skills.php?whichskill=7221&quantity=1&ajax=1&action=Skillz&ref=1&targetplayer=XXX&pwd
Redirect -> runskillz.php?whichskill=7221&pwd&quantity=1&ajax=1&targetplayer=XXX
Redirect -> campground.php?quantity=1&preaction=summonlovesongs&pwd&ajax=1
```
Because it is an ajax request, the response does not contain an image of the campground.
Because there is no "action", we assume it's just a visit and attempt to parse the (nonexistent) image.
This will fail to find your dwelling, will forget you have a garden, and will generally wreak havoc on what we think the state of your campground is.
There are nine calls to parseCampground. Only one is known to be (sometimes) called with ajax.
Rather than changing the single call that we KNOW is sometimes …
> campground.php&ajax=1 does not have map of campground

- src/net/sourceforge/kolmafia/request/MrStore2002Request.java
- src/net/sourceforge/kolmafia/request/UseItemRequest.java
- src/net/sourceforge/kolmafia/session/BreakfastManager.java
- test/net/sourceforge/kolmafia/request/MrStore2002RequestTest.java
1) If MrStoreRequest uses an over-ridden GenericRequest, it is no longer GenericRequest.class, RequestLogger does not consider it to be an externalRequest, and it logs the raw URL rather than "use XXX". Therefore, use a UseItemRequest and set it to not follow redirects.
2) Breakfast uses a UseItemRequest which does follow redirects, but since that does not parse the shop response, credits do not update. If UseItemRequest.parseConsumption notices that the request was redirected, call MrStore2002Request.parseResponse to parse the shop. Breakfast now updates available credits correctly.
3) Unfortunately, following the redirect does not log the shop.php request nicely. I made Breakfast call MrStore2002Request, not UseItemRequest, and it looks like this in the gCLI:
```
Getting 2002 Mr Store …
```
> MrStore2002Request uses UseItemRequest for better logging

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/textui/command/FoldItemCommand.java
- test/net/sourceforge/kolmafia/textui/command/FoldItemCommandTest.java
Features for the 1%.
Some [garbo](https://github.com/Loathing-Associates-Scripting-Society/garbage-collector) users with multiple stinky cheese items are reporting maximization failures where beginning with multiple stinky cheese items equipped and none in inventory leads to a failure to maximize due to Mafia not being sure which to fold.
Add a preference for this case that always folds the last one slotwise: this will make a given `maximize` command work as it also runs the commands in sequence of slots.
> feat: add preference to not error on ambiguous fold

- src/data/items.txt
Update plurals from museum (from a few days ago, before it went down).
Don't update replica plurals because they are currently the same as the non-replica plurals (i.e. they don't include "replica"), and I'm not sure what having a duplicate plural does but probably not the right thing.
> feat: non-replica plurals

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
This was causing an NPE when JS code called runTurn.
> Buffer needs a StringBuffer for content.

- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
Had the same ID as KGB so was somewhat noticeable. What more errors could be in this file?
> fix: incorrect ID for Victor's Spoils

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/textui/parsetree/ProxyRecordValue.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
Add `$location[].pledge_allegiance` modifiers value.
Outputs a string, modifier-like (but with "All Res" instead of spelled out), of the effect you would get. If there's a nicer way of doing this, let me know: I wanted to make it nice for human readers.
Targeted at people like me who use the GCLI a lot. I expect other people will use Guide or a script or whatever.
> feat: add pledge allegiance modifiers to location proxy record 

- src/net/sourceforge/kolmafia/request/UseItemRequest.java
Not sure this will fix it, but there's an issue where Mafia doesn't accept the `terminal` commands immediately after you use the replica Source terminal -- only after you view your campground.
> feat: add source terminal to campground after replica used

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/request/LoginRequest.java
- src/net/sourceforge/kolmafia/request/PingRequest.java
- src/net/sourceforge/kolmafia/session/LoginManager.java
- src/net/sourceforge/kolmafia/session/PingManager.java
- src/net/sourceforge/kolmafia/swingui/LoginFrame.java
- src/net/sourceforge/kolmafia/swingui/widget/PreferenceButtonGroup.java
- src/net/sourceforge/kolmafia/swingui/widget/PreferenceFloatTextField.java
- src/net/sourceforge/kolmafia/textui/command/PingCommand.java
- src/net/sourceforge/kolmafia/utilities/InputFieldUtilities.java
1) Four new settings:
- pingLogin - (boolean) run a ping test at login before refreshing session.
Prints result to gCLI.
- pingLoginCheck - none, goal, threshold
(Only if pingLogin is true) Require average lag to be below goal or historical minimum + threshold
- pingLoginGoal - (int) msecs
- pingLoginThreshold - (float) fractional percent above historical lowest average
2) You can configure these on the Connection tab of the LoginFrame
3) When you log in, run a ping test (if configured) - 10 requests to api.php
If you have a pingLoginCheck configured, the average is compared to your goal or threshold.
If it succeeds, session login completes
If it fails, you are told what the average lag was and what your configured maximum lag is and are asked if you are OK with that.
- Yes - login …
> Optional ping test at login

- src/data/items.txt
Drops only on Dependence Day with the Patriotic Eagle as active familiar (looks like a 5% drop from cursory spading). No idea if anything else needs added.
Cosmetic item by the looks of things (adds flags to your profile page).
> add souvenir flag

- src/net/sourceforge/kolmafia/KoLmafiaCLI.java
- src/net/sourceforge/kolmafia/swingui/LoginFrame.java
- src/net/sourceforge/kolmafia/swingui/OptionsFrame.java
- src/net/sourceforge/kolmafia/swingui/panel/PingOptionsPanel.java
- src/net/sourceforge/kolmafia/swingui/widget/PreferenceTextArea.java
- src/net/sourceforge/kolmafia/textui/command/TimeinCommand.java
It also has a little text are which lists the shortest and longest historical ping tests we've seen.
That auto-updates when the pingLongest and pingShortest properties change.
There is also a button to clear the historical ping data (which verifies that it auto-updates).
You'd use this if you are connecting to a new network or on a new computer.
I also renamed ReloginCommand to TimeinCommand, since that more precisely describes what it does: it logs you out (just like KoL silently does when it times you out) and times you back in (just as we do to recover from KoL's silent logout).
You can use "timein", "relog", or "relogin" to invoke it.
> Put PingOptionsPanel in both LoginFrame and Preferences/General

- src/net/sourceforge/kolmafia/KoLmafiaCLI.java
- src/net/sourceforge/kolmafia/request/GenericRequest.java
- src/net/sourceforge/kolmafia/request/LoginRequest.java
- src/net/sourceforge/kolmafia/request/LogoutRequest.java
- src/net/sourceforge/kolmafia/session/LoginManager.java
- src/net/sourceforge/kolmafia/textui/command/TimeoutCommand.java
1) Added a "timeout" command which simply calls logout.php, rather than doing a full logout and shutting down everything. This is the equivalent to KoL having silently logged you out when you time out your session.
2) When timing in, replace the password hash (as seen in the pwd field of the URL, rather than whatever the current password hash is) with the current password hash. This lets timing in a GET request with a a password hash (like a storage pull) work a lot better.
3) Executing a logout.php request leaves you not-logged-in.
4) relogin following a logout returns true or false, depending on whether the login succeeded.
> timein successfully after canceling ping test

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/request/LoginRequest.java
- src/net/sourceforge/kolmafia/session/LoginManager.java
- src/net/sourceforge/kolmafia/session/PingManager.java
- src/net/sourceforge/kolmafia/swingui/OptionsFrame.java
- src/net/sourceforge/kolmafia/swingui/panel/PingOptionsPanel.java
- src/net/sourceforge/kolmafia/textui/command/TimeinCommand.java
1) Count ping test attempts when you are logging it.
If you get an acceptable ping test on attempt N, only complete login/timein when you unwind back to attempt 1.
2) When timing in to try for a better connection, via timein command or equivalent, only issue logout request if you are currently logged in.
3) When you log in for the first time, if you are in stealth mode (/q), remove that for the purpose of saving actual user name and reading Preferences, as always.
If you did NOT log in with /q, add that to the name field of the LoginRequest, so that all subsequent timeins are done in stealth mode.
4) When doing a ping test at login, if it you got redirected away from api.php (afterlife.php, for example), do not compare the measured ping time with saved historical ping times, which are …
> automate login ping tests

- src/net/sourceforge/kolmafia/modifiers/BitmapModifier.java
- src/net/sourceforge/kolmafia/modifiers/BooleanModifier.java
- src/net/sourceforge/kolmafia/modifiers/DerivedModifier.java
- src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java
- src/net/sourceforge/kolmafia/modifiers/Modifier.java
- src/net/sourceforge/kolmafia/modifiers/StringModifier.java
- src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java
- src/net/sourceforge/kolmafia/textui/DataTypes.java
- src/net/sourceforge/kolmafia/textui/Parser.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/textui/parsetree/ProxyRecordValue.java
- src/net/sourceforge/kolmafia/textui/parsetree/Type.java
- src/net/sourceforge/kolmafia/textui/parsetree/Value.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
As suggested in #1797, add a `$modifier` type.
The main downside is that `modifier` is used as a variable name in a few common scripts (e.g. some of Ezandora's (Gain, Bastille, Helix Fossil), garbage-collector), and these would need adjusting.
The main upside is improved comprehensibility for modifier code.
Modifiers have a name (same as the string you would previously use), and a type, which is one of "numeric", "string" or "boolean". This tells you which of the other methods you should use to get the value (and what the value is -- float, string or boolean respectively).
Also add a function `split_modifiers` which takes a modifier string (e.g. the string from `$location[].pledge_allegiance`) and returns a map of modifier to string. This can then be parsed, using the types, to extract …
> feat: modifier type

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
Previous:
```
> ash git_info("Veracity0-spacegate")
Returned: record {string url; string branch; string commit; string last_changed_author; string last_changed_date;}
url => https://github.com/Veracity0/spacegate.git
branch => main
commit => 897cbf723cf571e9f48e1ea359b0a8cec04ea509
last_changed_author => Veracity0 83725298+Veracity0@users.noreply.github.com>
83725298+Veracity0@users.noreply.github.com>last_changed_date => Thu Mar 23 10:03:55 2023 GMT-04:00
```
Now:
```
> ash git_info("Veracity0-spacegate")
Returned: record {string url; string branch; string commit; string last_changed_author; string last_changed_date;}
url => https://github.com/Veracity0/spacegate.git
branch => main
commit => 897cbf723cf571e9f48e1ea359b0a8cec04ea509
last_changed_author => Veracity0 …
```
> When 'dump' composite result of 'ash' command, entity encode values

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/KoLmafia.java
- src/net/sourceforge/kolmafia/request/GenericRequest.java
- src/net/sourceforge/kolmafia/request/LoginRequest.java
- src/net/sourceforge/kolmafia/request/PingRequest.java
- src/net/sourceforge/kolmafia/session/PingManager.java
- src/net/sourceforge/kolmafia/swingui/OptionsFrame.java
- src/net/sourceforge/kolmafia/swingui/panel/PingOptionsPanel.java
- src/net/sourceforge/kolmafia/textui/command/PingCommand.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
1) Fixed login command to allow /q
Finds saved password for name without /q
LoginRequest obeys /q
2) Preference pingStealthyTimein (boolean) specifies whether logging in with same request (e.g. timing in) uses /q
(Stealth mode checkbox - stealthLogin - still works))
You can manipulate this property in Connection Options in either LoginFrame or Preferences/General
3) When redirect, store base URL only as page;
afterlife.php?realworld-1 -> afterlife.php
4) Changed saved ping page to be "api", "council", or "main". I.e., without the .php
I attempted backwards compatibility with historical properties which have the page listed with .php; strip it off when read property, omit it when write property.
Add (events) and (status) as available ping pages.
api.php?what=events&for=KoLmafia …
> Improve /q. Allow ping tests to (events) and (status)

- src/net/sourceforge/kolmafia/textui/Parser.java
- src/net/sourceforge/kolmafia/textui/parsetree/RecordLiteral.java
- test/net/sourceforge/kolmafia/textui/parsetree/AggregateLiteralTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/AssignmentTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/RecordLiteralTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/RecordValueTest.java
- test/root/expected/record_literals.ash.out
- test/root/scripts/record_literals.ash
(I include the following under CustomScriptTest)
This script:
```
record Point
{
int x;
int y;
};
Point printPoint(string name, Point p)
{
print(name + ": x = " + p.x + " y = " + p.y);
return p;
}
Point point1 = { x: 1, y : 2 };
Point point2 = new Point(13, 31);
Point point3 = { y: 4, x : 3 };
printPoint("point1", point1);
printPoint("point2", point2);
printPoint("point3", point3);
record PointArray
{
string name;
Point[] points;
};
PointArray printPointArray(PointArray pa)
{
print(pa.name + " has " + count(pa.points) + " points");
foreach n, p in pa.points {
string id = pa.name + "[" + n + "]";
printPoint(id, p);
}
return pa;
}
PointArray pa1 = {
name : "pa1",
points : {
{ x : 1, y : 2 },
new Point(10, 20),
{ x : 100, y : 200 }
}
};
printPointArray(pa1);
record PointMap
{
string name; …
```
> Record Literals

- src/net/sourceforge/kolmafia/request/GenericRequest.java
- test/net/sourceforge/kolmafia/request/CampgroundRequestTest.java
I noticed that when I logged in, while inspecting the Campground, I'd see a message "You gain 1000 Meat". I collected a DEBUG log and discovered that it was from my Meat Butler. I decided that it would be nice to identify that in the gCLI/session log.
Putting a check in the response text parser for campground.php was unsatisfying, since that is called after result processing, so the "You gain" message came first.
I fixed that by putting it into GenericRequest.parseResults, where various things are checked before processing the results.
I also rationalized that method a bit by useing a modern switch on the page, rather than a series of string.startsWith tests.
> Log Meat Butler collecting Meat

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/session/LoginManager.java
- src/net/sourceforge/kolmafia/swingui/panel/PingOptionsPanel.java
Now that KoL has rolled back (for now) their attempt to assign a new server to each request, login ping testing is again valuable. This PR provides (probably) the last feature it needs.
Once you have configured ping testing with either a goal or a threshold, you're probably good to go; odds are, you'll probably get a good server fairly soon. But, if you are using a mobile computer and connecting via different networks, the historical data we use to decide if you have a "good" connection may be inadequate; a slower network connection may not allow you to achieve a desire fixed "goal". If you have a "threshold" configured, you're probably still good - assuming you reset your historical data so that you can learn a new "average" ping that fits your new network.
This PR adds a new option for …
> Add 'confirm' option on a ping check failure

- src/net/sourceforge/kolmafia/session/LoginManager.java
- src/net/sourceforge/kolmafia/session/PingManager.java
- src/net/sourceforge/kolmafia/swingui/OptionsFrame.java
- src/net/sourceforge/kolmafia/swingui/panel/PingOptionsPanel.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/textui/command/PingCommand.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
1) Login ping test configuration uses pingLoginThreshold, but when calculating it, we looked up pingLoginGood. Huh?
2) "average" and "bps" are calculated by the division of two ints. Do the calculation in floating point.
3) Similarly, threshold is a double, so use double value of average, not integer.
4) When presenting average and bps to user, use Math.round, rather than Math.floor.
> pingLoginThreshold property. Calculate average pin in floating point.

- src/net/sourceforge/kolmafia/request/PingRequest.java
- src/net/sourceforge/kolmafia/session/LoginManager.java
- src/net/sourceforge/kolmafia/session/PingManager.java
1) If a ping redirects, do not follow the redirection; there is no point in repeatedly pinging choice.php, fight.php, login.php, or even afterlife.php, since we can't compare the results to any unsupported ping page.
2) If a ping fails in a ping test, log the reason - redirect or empty responseText (due to I/O error, we assume) - and abort the test. Do NOT save the (empty - or even partial) ping test in properties.
3) If ping test fails at login, give up searching for a better time. Do not log "this ping test took 0 msec". Instead, depend on the actual failure reason being logged. See 2.
> abort ping test if redirected or no responseText

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/request/FloristRequest.java
This will allow scripts like [av-snapshot](https://github.com/m-e-meyer/av-snapshot) or [greenbox](https://github.com/loathers/greenbox) to report the florist friar as owned even if florist_available() returns false, such as a post community service run where the forest is inaccessible.
Also always set it as available if you can get into the choice instead of only on selecting choice 4
> set ownsFloristFriar to true if it is owned

- src/net/sourceforge/kolmafia/request/FloristRequest.java
I caused some "You are currently in a choice." or "You are currently in a fight." spam from scripts like tourguide that call florist_available() regularly.
Also busta found an issue, we still need to hit fv_friar before doing the request or it may not succeed. I removed that thinking it was an optimization to not hit the page unnecessarily but it was necessary.
> Don't print if in a fight for florist check

- src/net/sourceforge/kolmafia/webui/TopMenuDecorator.java
- test/net/sourceforge/kolmafia/webui/TopMenuDecoratorTest.java
- test/root/request/test_compact_topmenu.html
- test/root/request/test_fancy_topmenu.html
- test/root/request/test_normal_topmenu.html
Apparently, the script dropdown disappears in the Relay Browser for some people who use the awesomemenu.
That should only happen if we don't think they have an awesomemenu.
Since the only time we detect menu type is when we refresh the session and look at the topmenu to detect moon phases, and when parsing menu bar style changes in the account options, I can't understand how we get out of sync.
1) When decorating the topmenu, detect the topmenu style from the buffer we are decorating.
This SHOULD be unnecessary, but, whatever.
2) If detect that the menu style is not what we thought it should be, log to gCLI and session log and correct the saved style.
I'm hoping that the logging will provide some inspiration about the root cause...
> When we decorate the topmenu, detect and correct menu style

- test/net/sourceforge/kolmafia/session/QuestManagerTest.java
- test/net/sourceforge/kolmafia/swingui/panel/DailyDeedsPanelTest.java
In the process of trying to sort out https://github.com/kolmafia/kolmafia/pull/1811 I ran locally with one fork for gradle.  In the past that has given a deterministic test order.  Two tests failed.  I was able to reproduce the failures with 4 forks and when I ran the tests individually  in IntelliJ.  These changes fix that.  
For the one test the test class structure appeared to prevent the beforeEach from running before the test.  That hypothesis was supported by un-initialized preference values in the test according to the debugger.
For the other test the Familiar data was just nonexistent.
This code works individually in my IDE and when running with four forks.
> Test Fixes

- src/data/classskills.txt
- src/data/coinmasters.txt
- src/data/equipment.txt
- src/data/fullness.txt
- src/data/inebriety.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/data/monsters.txt
- src/data/outfits.txt
- src/data/statuseffects.txt
- test/net/sourceforge/kolmafia/persistence/ItemFinderTest.java
For now, just dump everything.
Needs a preference for skills cast (5 + 1 for the current day), fixodent "Craft with Teeth" store (takes fixodent + loose teeth, so probably like Sliemce?)
> feat: august skeleton items etc

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/webui/TopMenuDecorator.java
- test/net/sourceforge/kolmafia/webui/TopMenuDecoratorTest.java
Captain Scotch and others noticed that their "relay scripts" dropdown occasionally disappeared from their awesomemenu.
Since we only set topmenu style in three places:
1) MoonPhaseRequest
2) Visiting Interface tab in account.php
3) Changing menu style in account.php
this was confusing.
I inserted debug code to deduce the topmenu style from the responseText every time we decorated it to add the relay scripts dropdown.
Turns out that "visiting interface tab in account.php" was broken: KoL had changed the tag on the radio button, so if you had the "fancy" style selected, we'd think it was "normal".
With that fixed - and there are now extensive tests in AccountRequestTest - everything seems to be peachy.
Doing text searches to deduce menu style every time we decorate it is (again) no longer …
> Put TopMenuStyle detection under a debug flag

- src/data/equipment.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/data/monsters.txt
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/request/ReplicaMrStoreRequest.java
Conditions on the Deep Machine monsters are that the hollow spleen items
need the corresponding filled spleen item effect.
Conditions on the NEP are that the drop rate decreases for each item you
get in a single day (individually). This isn't really a "condition" but
it's close enough.
> feat: replica august + monster drop rates

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/session/LoginManager.java
- src/net/sourceforge/kolmafia/session/PingManager.java
- src/net/sourceforge/kolmafia/swingui/OptionsFrame.java
- src/net/sourceforge/kolmafia/swingui/panel/PingOptionsPanel.java
Shiverwarp complained recently that he was getting login ping test times of 23000+ msec and it was taking seemingly forever to login. I sympathize; I usually get <30 msec and the longest I've see in a 10-ping test is a bit more than 800 - which would still be an intolerably slow connection. And to think it took 10 pings to get that "average".
I can't imagine what caused Shiverwarp's insanely bad connection, but if it took 4 minutes to run the first test and decide it is time to retry, seems to me that we could recognize way earlier - as early as the very first ping - that this connection is a no-go.
1) Comparing ping average times with goals and thresholds in floating point seems right, but displaying them as integers, calculated either by Math.round() or Math.floor(), is problematic. If …
> Abort ping test if pings are too long

- test/internal/helpers/Utilities.java
- test/net/sourceforge/kolmafia/persistence/MallPriceDatabaseTest.java
verboseDelete proved very helpful to me when checking for test leakage exposed when the number of forks gradle used was changed.  The leakage from MallPriceDatabaseTest was discovered and fixed as part of #1811 
This copies that code from the now reverted PR.  This seemed like the easiest way to preserve it and not forget it.
> Cherry Picking for test

- src/net/sourceforge/kolmafia/textui/parsetree/ProxyRecordValue.java
Hopefully cut down on the number of queries as to which preference tracks skill X by exposing it on the skill proxy object.
> feat: expose daily limit pref for skills with one

- src/data/monsters.txt
- test/net/sourceforge/kolmafia/MonsterDataTest.java
- test/net/sourceforge/kolmafia/RequestEditorKitTest.java
Items marked `c0` failed to drop with +4900%, so there's something going on there, and I doubt it'll get spaded without a large number of logs.
Other than that, drop rates for gingerbread city (minus the Vigilante, who's very hard to encounter). Pickpocket rate for Equivocator (approx, from wiki). cheerless mime executive hasn't dropped the warehouse key since that Crimbo ended.
> feat: gingerbread item drop spading

- build.gradle
- src/net/sourceforge/kolmafia/textui/Parser.java
- src/net/sourceforge/kolmafia/textui/parsetree/AggregateValue.java
- src/net/sourceforge/kolmafia/textui/parsetree/CompositeValue.java
- src/net/sourceforge/kolmafia/textui/parsetree/Operator.java
- src/net/sourceforge/kolmafia/textui/parsetree/RecordValue.java
- src/net/sourceforge/kolmafia/textui/parsetree/Value.java
- test/net/sourceforge/kolmafia/textui/parsetree/ValueTest.java
- test/root/expected/record-equality.ash.out
- test/root/scripts/record-equality.ash
Rather than ASH believing that every record value is equal to any other record value, provide "shallow" equality testing:
1) Must be the same record type
2) All non-composite fields must be identical
3) Field which are, themselves, records must have record-equality
4) Aggregate fields must have the same size.
We do not do a "deep" comparison of aggregate values.
5) If you use the "≈" operator - "approximately equals" or "case insensitive" - string field values are compared thusly.
> ASH record equality

- src/net/sourceforge/kolmafia/textui/parsetree/CompositeValue.java
- src/net/sourceforge/kolmafia/textui/parsetree/Operator.java
- src/net/sourceforge/kolmafia/textui/parsetree/Value.java
With composites, allow "==", "!=", and "≈".
Other comparisons - "<", "<=", ">", ">=" - are meaningless and generate a compile-time error.
This simplifies things a lot: CompositeType no longer needs a compareTo method.
> Of all comparison operators, composite values only allow equality operators

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/preferences/Preferences.java
- src/net/sourceforge/kolmafia/request/FightRequest.java
- test/net/sourceforge/kolmafia/AreaCombatDataTest.java
- test/net/sourceforge/kolmafia/preferences/PreferencesTest.java
- test/net/sourceforge/kolmafia/request/FightRequestTest.java
* rwbMonsterCount should begin at 2, not 3
* screechCombats is reset daily
* _shortOrderCookCharge is not reset daily
I considered renaming the preferences straight -- `screechCombats` is only used in TourGuide that I can see, but `_shortOrderCookCharge` is used more widely.
> fix: eagle preferences, daily preferences

- src/net/sourceforge/kolmafia/session/InventoryManager.java
This is a huge QoL thing for doing dev work! With a suitable buyScript in place, I can write a script to test something and just use `acquire`. Or `acquire` from the command line. I can use the maximizer!
>  On the dev server, always check the buyScript when acquiring an item. devsters can't use the mall anyway

- src/net/sourceforge/kolmafia/textui/Parser.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
- test/net/sourceforge/kolmafia/textui/parsetree/UserDefinedFunctionTest.java
- test/root/expected/to_buffer_test.ash.out
- test/root/scripts/to_buffer_test.ash
I've wanted to be able to do this for a long time:
```
buffer b = "Initial contents";
```
Now I can.
I also moved creation of the (buffer) return value of visit_url() to the top of the method, rather than duplicating the creation in two places.
> Add to_buffer(string) and use it when initializing a buffer

- src/data/adventures.txt
- src/data/modifiers.txt
- src/data/zonelist.txt
- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/request/CampgroundRequest.java
- src/net/sourceforge/kolmafia/request/CharPaneRequest.java
The way stats work in Small is that your black stats are capped at 1, but your level is uncapped.
Implement this by ignoring charsheet requests, trusting api.php for the stats, and adding a modifier that limits your stats to 1. This makes maximizer + numberology work as desired (i.e. maximizer treats percentage buffs as acting on 1, numberology gets your level correct).
Limit fullness and inebriety.
Skip parsing campground for now. I have HTMLs, I will get back to it later. Your housing never shows up -- it's just "rest in the dirt", but we could parse whether you have free rests left.
Don't count Long Winter's Nap if it's out of standard, which it is now.
> feat: improvements to running small

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/session/BeachManager.java
- test/net/sourceforge/kolmafia/session/BeachManagerTest.java
- test/root/request/test_beach_comb_whale.html
- test/root/request/test_beach_visit_whale.html
1) When you comb a tile on the beach, we supposedly change that code in _beachLayout to a 'c'.
Except, it was checking for "You acquire", but bottles and whales do not "acquire" anything.
Look instead for "You comb"
2) When we examine a beach map, the tides wash the rows at the bottom and you cannot comb them.
Property "_beachTides" now has how many such rows are unavailable. ("_beachLayout" will have rows from N+1 - 10).
> Property _beachTides is tide-washed row count

- src/data/defaults.txt
- test/net/sourceforge/kolmafia/session/BeachManagerTest.java
1) Beach tides apply to everybody. Therefore, make _beachTides a global pref, not a user pref
2) The Wiki says they can cover up to 4 rows and rise and fall 1 row per day in a 9-day cycle.
Thus: 0, 1, 2, 3, 4, 3, 2, 1, 0, ...
Which means that 1 day out of 9, row 1 will be available to comb.
Therefore, the default for _beachTides is -1, and will be set to 0-4 when we parse a beach map.
> _beachTides is global and defaults to -1

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
Fix https://kolmafia.us/threads/offhand-remarkable-is-incorrectly-applying-to-weapons-equipped-in-offhand.29172/
> fix: only remarkably double real offhands

- src/data/monsters.txt
There's a zone effect (`diminishdrops`) that reduces the rate of all items if any drop. I don't know exactly how it works, but I spaded the base rates with copies.
One of the Jungle rares was leaked at 0.1% (the Sasq™ watch); I would be very surprised if the others weren't the same.
The mercenary's Coinspiracy is 30% base, dropping by 3% each drop. The headband is 10% with a manuel-complete conditional.
Took the scientist's rates from the wiki.
> feat: sloppy seconds item rates

- src/net/sourceforge/kolmafia/request/UneffectRequest.java
Prior to this change:
```
> uneffect citizen of a zone
Citizen of a Zone is intrinsic and cannot be removed.
```
After:
```
> uneffect citizen of a zone
Citizen of a Zone has no specific item or skill for removal. Trying generics...
Using soft green whatever...
Citizen of a Zone removed.
```
> Add exception for Citizen of a Zone as removable

- src/net/sourceforge/kolmafia/KoLCharacter.java
Otherwise, you won't see circadian rhythms unless you have used be more adventurous as well.
> Check circadianAdv instead of resolutionAdv when adding circadian rhythms to rollover adventures

- src/net/sourceforge/kolmafia/request/FightRequest.java
Currently if you encounter an orb predicted monster it won't decrement the habitat fight counter. Moving the check up in the else/if chain should fix this
> Habitat fights should still decrement on orb fights

- src/net/sourceforge/kolmafia/swingui/panel/ChoiceOptionsPanel.java
shadowLabyrinthGoal defaults to "browser".
It has a variety of other settings, and if you set it to a bogus value, we print
```
Invalid setting  for shadowLabyrinthGoal.
```
to stdout.
You also get this when opening the gCLI while not logged in, since you don't have any user preferences, and an empty setting will trigger that message.
That is completely useless. Treat "" as if it were "browser" - which is the value in defaults.txt.
Voila! No more irritating message on my terminal.
> When not logged in, who cares if shadowLabyrinthGoal is unset

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/textui/javascript/ValueConverter.java
- test/net/sourceforge/kolmafia/textui/command/JavaScriptCommandTest.java
As in https://kolmafia.us/threads/debug-log-printed-with-arrays-containing-nulls-or-undefined.29236/
Avoid debug log errors. Have reasonable behaviour: print "null", have array as "any": given this not showing up before I think printing in the CLI is the only use-case.
> fix: remove some debug logs around weird javascript null -> ASH stuff

- src/net/sourceforge/kolmafia/Modifiers.java
- test/net/sourceforge/kolmafia/DebugModifiersTest.java
Found this while working on adding free rests as modifiers.
> fix: familiars should be specified by string

- src/net/sourceforge/kolmafia/request/CampgroundRequest.java
- test/net/sourceforge/kolmafia/request/CampgroundRequestTest.java
- test/root/request/test_count_successful_rests.html
- test/root/request/test_do_not_count_failed_rests.html
If you try to rest when it is pointless to do so (full HP, full MP, no Beaten Up), the game won't let you do it, and will display a message "You don't need to rest right now." instead. This does not decrement the amount of free rests you can use, and this does not subtract an Adventure if you are out of free rests. However, KoLmafia thinks that the rest did happen, and increases timesRested accordingly. This leads to the undercounting of the amount of free rests left (Mafia fixes the data if it sees that a free rest is actually available, but it thinks it is not; however, the information that there is more than one free rest would be lost). The fix is to not increment timesRested in the case of a failed rest.
> Ignore failed rests

- src/data/classskills.txt
- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/persistence/SkillDatabase.java
- test/net/sourceforge/kolmafia/textui/command/UseSkillCommandTest.java
Fix from #1968.
I'd like to refactor the types to be more like item types; I think it's gotten rather complicated. Hot fix this issue first, though.
Also going through the code: what is a "normal" skill? By the usage in runtime library, it's a skill that can't be used outside combat? Why is it named the way it is?
> fix: allow casting disco nap

- src/data/modifiers.txt
- src/data/monsters.txt
They drop rates.
Remove trainbot items; they don't drop at all any more.
> feat: dodecahedron monster drop rates

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/scripts/svn/SVNManager.java
Add opt-in settings to force svn manager to always add or overwrite files rather than requesting user confirmation.
I run mafia in in cli mode so I have no way to confirm these dialogs (which cause a headless error if in cli mode).
> Preferences to always add or overwrite svn files

- src/data/modifiers.txt
Found while doing a celebratory Jarlsberg run for Clancy.
Searched for `	[^	:]*[^:] [+-]\?[0-9]`, I don't think there are others.
> fix: some incorrectly defined stomach modifiers

- src/net/sourceforge/kolmafia/request/FightRequest.java
Should fix https://kolmafia.us/threads/missing-img-src-with-ocrs-hilarious-modifier.29263/
No test because no HTML.
> fix: don't crash on an <img> with no src attribute

- src/data/adventures.txt
- src/data/items.txt
- src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java
- src/net/sourceforge/kolmafia/session/BadMoonManager.java
As mentioned in #1982:
* don't try to read thorns / damage aura from the game, as we use a custom valuation
* rename Knob Goblin Encryption Key, as the case has changed in-game
> fix: don't try to read thorns / damage aura from in-game description

- src/data/modifiers.txt
The AoSP skill grants 10 liver, while the AWOL skill only grants 5.
Context: https://kolmafia.us/threads/awol-hard-drinker-causes-incorrect-inebriety_limit.29280/
> Fix Hard Drinker modifiers.

- src/data/familiars.txt
- src/data/items.txt
- src/data/modifiers.txt
Skeleton Dark Jill-of-All-Trades.
Haven't added the Ghuol Whelp types because I don't think we're sure it acts as a Whelp yet.
> feat: skeleton dark jill

- src/data/monsters.txt
More item drop rate spading.
The ones marked `c0` failed to drop at +4900, so they're conditional somehow, but I don't know specifics.
> feat: crimbo 2008 penguin / elf drop rates

- src/net/sourceforge/kolmafia/AreaCombatData.java
- test/net/sourceforge/kolmafia/AreaCombatDataTest.java
This was introduced by #326 several years back, as verified by building the old revision and executing the corresponding ASH function, both at that revision and the preceding one (to confirm prior behavior).
The refactor bundled all calculations that depended on the current character's state, even though combat rate modifiers should be applied uniformly. This leads to inconsistent results, as reported by lrrat (https://kolmafia.us/threads/29297/).
> Fix appearance_rates calculation regression.

- src/data/defaults.txt
- src/data/familiars.txt
- src/net/sourceforge/kolmafia/FamiliarData.java
- src/net/sourceforge/kolmafia/objectpool/FamiliarPool.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/preferences/Preferences.java
- src/net/sourceforge/kolmafia/request/UseItemRequest.java
- src/net/sourceforge/kolmafia/session/ChoiceControl.java
- src/net/sourceforge/kolmafia/session/ResultProcessor.java
Not certain that maps cap at 3 drops, but that's the highest currently reported. It might be unlimited.
Preference for LED candle setting / command / modifiers to come later.
> feat: add preferences for jill drops

- src/net/sourceforge/kolmafia/utilities/PHPMTRandom.java
- test/net/sourceforge/kolmafia/utilities/PHPMTRandomTest.java
In the current implementation, reload always twisted the same values since the new numbers are appended to state, not overwritten. This creates a generator with a period of 624 which just loops through the first 624 numbers continuously.
The fix is to take latest STATE_LENGTH values of a state into account instead of the first ones.
> PHPMTRandom fix

- src/net/sourceforge/kolmafia/session/BanishManager.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- test/net/sourceforge/kolmafia/session/BanishManagerTest.java
Two changes, both garbo-inspired (see https://github.com/loathers/garbage-collector/pull/1607 for some context).
Fix a fencepost issue with banishers. If I banish a fluffy bunny on turn 30 with Snokebomb, after I have played turn 60 it is no longer banished -- if I play another turn, I may encounter it.
Add a function for getting which banishers have currently banished a monster. You can do this yourself by parsing `banishedMonsters` and `banishedPhyla`, but the code is not very clean, and also you need to force Mafia to recalculate the preferences before you start to ensure banishes expire properly.
> feat: add banished_by function, fix fencepost issue

- src/net/sourceforge/kolmafia/KoLmafia.java
- src/net/sourceforge/kolmafia/Modifiers.java
- test/internal/helpers/Player.java
- test/internal/network/FakeHttpClient.java
- test/net/sourceforge/kolmafia/KoLmafiaTest.java
This also includes a couple more changes to make sure that we don't accidentally populate availablePassiveSkillModifiersByVariable before we have any skills ready.
This doesn't handle the scenario where the skills list changes, but it should handle the most common scenarios (login, kingLiberated come to mind).
> Call recalculateAdjustments after loading skills.

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/request/CharSheetRequest.java
- src/net/sourceforge/kolmafia/session/ResponseTextParser.java
- test/net/sourceforge/kolmafia/KoLmafiaTest.java
This change does a few things:
- Explicitly update Modifiers.availableSkillsChanged when receiving a new skill, instead of relying on the preference listener, as that may be deferred (as we've updated the KoLmafiaTest case to cover).
- Explicitly invoke recalculateAdjustments after parsing the charsheet. This addresses messages on login about detecting free rests from campground.php.
- Add some synchronization to Modifiers.java to prevent potential data races.
- Remove redundant firePreferenceListener("(skill)") from ResponseTextParser, since that's already done several lines above in the addAvailableSkill call.
Note that I explicitly did _not_ call recalculateAdjustments() inside addAvailableSkill() because that would result in quadratic time behavior whenever …
> Address passive skill cache race condition.

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/request/EquipmentRequest.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
This change ensures that the modifiers of the sleeved card is considered instead of the card sleeve itself.
I've also included a maximizer test because I initially suspected this as the source of the problem. It seemed worthwhile to keep as I could not find any other obvious tests for the card sleeve slot.
> Double mods of sleeved cards with Offhand Remarkable

- src/data/items.txt
Mark the items given in https://kolmafia.us/threads/missing-multiusable-items.29317/ as multiusable.
> feat: mark items as multiusable, thanks to adeyke

- src/data/npcstores.txt
Remove spray paint that is no longer in The General Store.
(also adds newline to end of file.)
> Remove spray paint from The General Store.

- src/data/combats.txt
Some lines in the combats.txt data files used the //-style comment - this is the only place where it is done like that. Replaced them with #-style comments.
> Fix comment style in data files

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
My intent here is to allow relay scripts to be able to detect if another script is running or if the player is running automated adventuring, so they could defer updates or prevent the user from visiting links in the browser that could get them into a bad state.
> add is_adventuring & has_queued_commands functions

- src/data/familiars.txt
- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/modifiers/BooleanModifier.java
- src/net/sourceforge/kolmafia/objectpool/FamiliarPool.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
Extract from #2027 to fix Jill.
I think we'll want to require `Volleyball:` modifiers instead of defaulting to 1 if the familiar is the right type, but that can go later. This is the only way I can see to fix e.g. God Lobster's Ring meaning the lobster is treated as a -1x Volleyball, instead of a 0x Volleyball.
> fix: jill bonuses

- src/data/dailylimits.txt
- src/data/defaults.txt
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/request/UseItemRequest.java
Extra Time (the item you acquire from using Day Shorteners, was not in the Item Pool). Added to that, and also created a preference for it similar to the class chocolates due to the decaying nature of returns when used.
> Add Preference for Extra Time

- .classpath
- .project
- src/data/monsters.txt
- src/net/sourceforge/kolmafia/AreaCombatData.java
- src/net/sourceforge/kolmafia/MonsterData.java
- src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java
- src/net/sourceforge/kolmafia/persistence/MonsterDrop.java
- src/net/sourceforge/kolmafia/request/GenericRequest.java
- test/net/sourceforge/kolmafia/MonsterDataTest.java
Some monsters drop items all in one line, with "you acquire X items" (e.g. hobo boss drops, sprinkles, the new inflammable leaves). Support this as a custom drop type.
Multidrops are conditional. They are not necessarily no-pickpocket, but we should pretend they are, because pickpocketing a multi-drop gives you exactly 1 and prevents you from obtaining any after the combat, which sucks.
Multidrops have custom behaviour, and don't necessarily interact with item drop. They interact weirdly with things like pickpocket or monster modifiers or custom combats, which explains why e.g. Jerry Bradford replacing Groar drops one dense meat stack instead of five.
Most multi-drops are triangularly distributed among the possible values. Some aren't.
For some multi-drops, we can figure out exactly how …
> feat: begin supporting multidrops

- src/data/classskills.txt
This is a combat skill with a passive effect.
In particular, this was previously correctly categorized, since Stomach Capacity was not a modifier until recently.
It probably makes sense to add a test to guard against adding a non-passive skill that has an associated modifier, although with new skills, this is less likely to be an issue (since modifier tracking simply won't work if implemented as the wrong type).
> Fix skill type for Ravenous Pounce.

- src/net/sourceforge/kolmafia/AscensionPath.java
- test/net/sourceforge/kolmafia/request/EatItemRequestTest.java
Currently mafia thinks that the fullness limit in Nuclear Autumn starts at 5.
This PR corrects that to the real size, which is 3.
I've tested this locally, let me know if this isn't actually the best way to go about fixing this though.
> Fix Nuclear Autumn stomach size

- src/net/sourceforge/kolmafia/KoLAdventure.java
- src/net/sourceforge/kolmafia/KoLCharacter.java
See https://kol.coldfront.net/thekolwiki/index.php/Kingdom_of_Exploathing/Map
It's there, always has been since the path was live.
The blame for those lines is weird for me. It says they were last touched 11 years ago which is impossible as KoE is only 4 years old.
Lines 1150-1157 in KoLAdventure.java already handle the differences between the regular Desert Beach and the KoE "Fragment" of Desert Beach from what I can see (correct me if I am wrong).
Shadow Rifts have been confirmed to exist in the Right Side of the Tracks and Mt McLargeHuge (possibly other places too) in the KoE path but don't allow you to adventure in them for reasons known only to the KoL dev team.
> desert beach is accessible in KoE, Shadow Rifts are not

- src/data/statuseffects.txt
These 3 effects are wishable. The CLI reports:
You acquire an effect: Joke-Mad (20)
Joke-Mad is wishable, but KoLmafia thought it was not
You acquire an effect: Barely Visible (20)
Barely Visible is wishable, but KoLmafia thought it was not
You acquire an effect: Very Attractive (20)
Very Attractive is wishable, but KoLmafia thought it was not
These were changed in commit 535109e1f5b1ccb16968e1e4073ff98fa9a7891d - perhaps they assumed all the cargo cultist shorts buffs were not wishable.
> Correct 3 wrong nohookah flags in statuseffects.txt

- src/data/monsters.txt
wire-crossin' elf can't be confirmed but is likely by comparison with other monsters.
Also add some missed drops (void, awol)
The condition on the void monsters is that exactly one item drops, and the shard is much less likely.
> feat: 2009 crimbo drops

- src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java
- src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
Add Elf / Pirate Warfare Effectiveness modifiers.
Will add to items / effects after #2099.
> feat: mark items that can also be used in combat

- src/data/adventures.txt
- src/data/classskills.txt
- src/data/coinmasters.txt
- src/data/combats.txt
- src/data/equipment.txt
- src/data/fullness.txt
- src/data/inebriety.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/data/monsters.txt
- src/data/npcstores.txt
- src/data/zapgroups.txt
- src/data/zonelist.txt
- test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
Jam all the monsters (non-outfit + outfit) in the zones like The Exploaded Battlefield.
Almost all drops are conditional. The non-outfit drops increase in rate with the number of adventures spent in any Crimbo zones. The outfit drops probably ignore item drop increasers, and are rare besides.
> feat: add crimbo 23 zones, monsters, etc.

- src/data/coinmasters.txt
- src/net/sourceforge/kolmafia/AdventureResult.java
- src/net/sourceforge/kolmafia/CoinmasterRegistry.java
- src/net/sourceforge/kolmafia/RequestLogger.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/request/Crimbo23ElfArmoryRequest.java
- src/net/sourceforge/kolmafia/request/Crimbo23PirateArmoryRequest.java
- src/net/sourceforge/kolmafia/request/NPCPurchaseRequest.java
- src/net/sourceforge/kolmafia/session/ResultProcessor.java
- src/net/sourceforge/kolmafia/swingui/CoinmastersFrame.java
1) All Crimbo23 coinmasters need registerRequest support
2) Elf Guard temporary (permanent) tattoo has () in its name so does not parse correctly into an AdventureResult
3) Add support for Elf and Pirate Armory coinmasters
Those last two are new, since they use the same action "buyitem" - for both buying and selling.
- I could (should) add a test, since I have saved HTML for selling to the Pirate Armory
- I could (should) move the shared code for this new thing into CoinMasterRequest
> Support for Crimbo23 Elf and Pirate Armory coinmasters

- src/net/sourceforge/kolmafia/request/FightRequest.java
This is simply an addition (along with alphabetizing) of the missing Reagnimated Gnome adventure gain strings to catch when the Gnome's ability activates. This will allow the existing built in preference and Daily Deeds panel tracking to record a more accurate value for adventures gained.
> Add missing Gnome adventure activation strings

- src/net/sourceforge/kolmafia/session/EncounterManager.java
For consistency with adventure results.
> feat: use commas in encounter listing

- src/net/sourceforge/kolmafia/request/FightRequest.java
Carnivorous potted plant kills weren't being tracked when it was held by a left-hand man.
> Fix left-hand man held carn plant free kill tracking

- src/data/classskills.txt
- src/net/sourceforge/kolmafia/KoLConstants.java
- test/net/sourceforge/kolmafia/DataFileMechanicsTest.java
This should have gone in with #2149 -- I changed the format, so I should also have bumped the version number.
> fix: bump skills version to 6

- src/net/sourceforge/kolmafia/request/FightRequest.java
Captain Scotch posted a list of activation strings he found when running Gnome during Crimbo in a bug report on the forums. His list contains this one string that I didn't ever get myself.
> Add missing gnome adv gain activation string

- src/net/sourceforge/kolmafia/textui/javascript/JavascriptRuntime.java
- test/root/expected/promise_unresolved_main.js.out
- test/root/scripts/promise_unresolved_main.js
This is a small follow-up for #2159:
So far, Promises returned from a script can only be resolved or rejected. If they are neither yet, they will never resolve, so we should throw an exception in that case instead of returning null.
Note: this might change, if KoLmafia ever gets some event loop (which arguably might not be very likely 😄)
> Throw when a Promise did not resolve or reject

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/modifiers/BooleanModifier.java
Neither stack with other equipment that offer the same modifiers: no matter how many "75% chance to resist negative statuses" you have, it's still 75%. Similarly, having both "extra pickpocket" items still only gives you one extra pickpocket.
Add the negative status resist because there are enough of them that we may as well track it. Add the pickpockets because this is absurdly good in certain fringe scenarios, and it's easier to stay aware of it if Mafia tracks it explicitly.
> feat: add boolean modifiers for extra pickpockets and negative status resists

- src/data/monsters.txt
- src/net/sourceforge/kolmafia/session/QuestManager.java
- test/net/sourceforge/kolmafia/session/QuestManagerTest.java
- test/root/request/test_visit_beach_desert_98.html
Sometimes, Mafia will put `desertExploration` to 100 while the game thinks it's still lower. I don't know what causes this.
Correct this on visit to the beach if this occurs.
> fix: reset desertExploration to sub-100 if game says so

- build.gradle
Fallout from #2178, but I think this is the right way to do it anyway.
> fix: when building jar, use runtimeClasspath

- src/data/familiars.txt
- src/data/monsters.txt
- src/net/sourceforge/kolmafia/swingui/FamiliarTrainingFrame.java
1) Rene C. Corman (Skeleton Invasion) is marked ```NOMANUEL```. It is unnecessary (and incorrect) for it to also have ```Manuel: "Rene C. Corman"```
2) Familiar training stats:
```
Results for Flaming Leafcutter Ant after 12 trials using 144 turns:
Cage Match      47      64      48           0              2
Scavenger Hunt  36      48      63           0              3
Obstacle Course 43      61      65           0              3
Hide and Seek   71      12      18           0              1
```
```
Results for Rigging Snake after 12 trials using 144 turns:
Cage Match      36      51      56           0             3
Scavenger Hunt  62      60      27           0             1
Obstacle Course 67      42       9           0 …
```
> familiar stats and monster typo

- build.gradle
At some point in my many reconfigurations of my dev environment, git updating just totally stopped working for me. It turns out that the SSH part of JGit can sometimes not be present, which results in a misleading error about timeouts. Explicitly depending on the library fixes this. I had previously kept it in my local changeset but I have now heard reports of others having this issue.
> Explicitly add jgit ssh dependency

- src/data/equipment.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/data/statuseffects.txt
Also add crunchy leaves and ultra-soft moss.
Note that the session log says this:
```
11548	crunchy brush	865877671	drybrush.gif	potion, usable	t,d	10
11547	ultra-soft ferns	979781148	softfern.gif	potion, usable	t,d	10
```
but potions are by default multiple.
In fact:
```
add to closet: 1 ultra-soft ferns
take from closet: 1 ultra-soft ferns
ultra-soft ferns is multiusable, but KoLmafia thought it was not
You acquire an item: ultra-soft ferns
```
That's a bug in DebugDatabase.
I'll investigate, but I don't think it's a blocker for this PR, although it will fix future erroneous item submissions.
Edit: I also wonder how many potions marked "usable" in items.txt are actually "multiple"?
All the more reason to put that investigation into another PR.
> Add new IOTM, unbound and bound

- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
These changes are also in https://github.com/kolmafia/kolmafia/pull/2197 but I pulled them out to isolate them and hopefully get feedback.  With two exceptions the changes were suggested by static code analysis or spotless.
One change was to explicitly set/reset the password hash in an ApiRequest.  The test itShouldMaximizeAndEquipSelectedWeapon would pass or fail depending upon the run context and the difference was the presence of the password hash in the body of the request.  Clearing the hash in the test that set it made itShouldMaximizeAndEquipSelectedWeapon work consistently.
The other change is itShouldMaximizeAndEquipSelectedWeapon.  It is supposed to be a test that mimics using the maximizer from the CLI or from a script (not the GUI).  It should demonstrate that the Maximizer …
> A Passing Test for the Maximizer

- src/data/equipment.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/data/statuseffects.txt
- src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java
WereProfessor is going to need a fair amount of work, but here's a dump of items / effects.
Intrinsics can gain additional effects with upgrades bought. I think making this work like License to Adventure would be good. Liver / Stomach upgrades would be modifiers on the class itself.
The class itself should be "Kindly Professor" according to Cannon, but this isn't live yet so the class name is blank -- let's not support it until it's live properly to simplify things.
> feat: wereprof items / effects

- src/net/sourceforge/kolmafia/AscensionClass.java
- src/net/sourceforge/kolmafia/KoLCharacter.java
- test/net/sourceforge/kolmafia/AscensionClassTest.java
When the ascension class is unknown (during first few days of a new path), my_class() returning null causes multiple scripts to fail (TourGuide and CHIT that I know of).
So, instead of setting the current class to null when it is unknown, set it to a class called unknown.
> return unknown class instead of null in my_class

- src/data/monsters.txt
- src/net/sourceforge/kolmafia/textui/command/BanishesCommand.java
- src/net/sourceforge/kolmafia/textui/command/RestoresCommand.java
- src/net/sourceforge/kolmafia/textui/command/TaleOfDreadCommand.java
Follow-up to #2194, as reported by https://kolmafia.us/threads/banishes-cli-command-shows-html-code-rather-than-table.29624/ (for Banishes + Tale of Dread).
Also of note are "monsters" and "safe" (and "council", but that one reaches into KoL so contains e.g. script tags) which have an old HTML-stripping method call which doesn't write to the log, but these methods have worked that way for a long time so I left them.
> fix: some other commands that should print HTML

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/objectpool/SkillPool.java
- src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java
- src/net/sourceforge/kolmafia/preferences/Preferences.java
- src/net/sourceforge/kolmafia/request/FightRequest.java
- src/net/sourceforge/kolmafia/webui/FightDecorator.java
- src/net/sourceforge/kolmafia/webui/StationaryButtonDecorator.java
- test/net/sourceforge/kolmafia/request/FightRequestTest.java
1) WereProfessor does not need to buy a range or cocktailcrafting kit to do basic COOK or MIX concoctions. That includes Cookbat food. You presumably still need one for advanced recipes, like unstable fulminate, but I have not checked yet.
2) wereProfessorAdvancedResearch is a (sorted by monsterId) property of comma separated monsterIds that your Mild Mannered Professor has done Advance Research on.
3) If you are a Mild-Mannered Professor equipped with an oculus, Stationary buttons now include an "advanced research" button. This will be disabled if you have already researched this monster.
4) Similarly for KoL's built-in "Advanced Research" button. Since attempting to use it will give an error message, we'll just delete it.
> WereProfessor can do COOK and MIX. Track Advance Researched monsters

- src/net/sourceforge/kolmafia/KoLmafia.java
- src/net/sourceforge/kolmafia/objectpool/Concoction.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/request/RelayRequest.java
- src/net/sourceforge/kolmafia/session/LightsOutManager.java
- test/net/sourceforge/kolmafia/request/RelayRequestWarningsTest.java
1) No Campground if WereProfessor.
You can still buy and use a Dramatic range, and it is needed to make unstable fulminate.
We can't see it in the campground, but, fortunately, the "hasRange" property exists.
2) Don't warn that you don't have unstable fulminate equipped if you don't have it or can't make it.
3) If you have it but not equipped, offer to equip it.
4) If you don't have it but can make it, offer to make it.
> No Campground in WereProfessor. Improved Fulminate warning

- src/net/sourceforge/kolmafia/request/TinkeringBenchRequest.java
- src/net/sourceforge/kolmafia/session/ChoiceControl.java
1) If you are wearing a high-tension exoskeleton and ask the Item Manager to create (and equip) a irresponsible-tension exoskeleton - and have the required 2 smashed scientific equipment - KoLmafia is happy to unequip the item and upgrade it.
The issue is that CreateItemRequest creates an outfit checkpoint around creations and it wants to re-equip the original exo- skeleton after creating it. In fact, it tries to re-make it - which fails, since it is no longer a valid creation.
Now we remove the ingredients from checkpoints - for TinkeringBenchRequest equipment - after we tinker.
2) You can only tinker as a Mild-Mannered Professor. When you transform to a Savage Beast - or vice versa - refresh concoctions so that Tinkering Bench items disappear and reappear as appropriate.
I suppose I …
> Changing form requires concoction refresh. Drop transformed outfit pieces from checkpoints.

- src/net/sourceforge/kolmafia/textui/javascript/JavascriptNumbers.java
- src/net/sourceforge/kolmafia/textui/javascript/ValueConverter.java
- test/net/sourceforge/kolmafia/textui/javascript/AshInteropTest.java
- test/root/expected/large_integers.js.out
- test/root/scripts/large_integers.js
The Rhino javascript engine passes integers larger than `Integer.MAX_VALUE` as `Double`, because they cannot be represented as `Integer`. Since we already use `long` for integer values, pass all numbers that are "safe integers" based on Javascript's Number.isSafeInteger as `long`, instead of converting them to a `float` value that cannot even correctly represent many of the larger integer values.
I added a test in a separate commit, so you can easily compare the behavior before and after the change.
Update: also, use double precision for non-integer numbers, since TYPE_FLOAT uses `double` internally anyway.
> Support large numbers from/to Javascript runtime

- src/net/sourceforge/kolmafia/textui/TypescriptDefinition.java
Currently parameters that take a variadic number of arguments are marked as regular array types, e.g. `min(arg1: number, arg2: number[])`.
That signature only lets you call as `min(1, [2, 3])`, which is incorrect and fails.
Instead, it should be marked as `min(arg1: number, ...arg2: number[])`, otherwise the method cannot be called correctly from Typescript.
(I considered introducing an inner Parameter helper class, but that makes the descriptiveParamNames and combatFilterType overrides less convenient to handle. Let me know if I should give it a go.)
> Correctly mark vararg parameters in TypescriptDefinition

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/AscensionClass.java
- src/net/sourceforge/kolmafia/preferences/Preferences.java
- src/net/sourceforge/kolmafia/request/AfterLifeRequest.java
- src/net/sourceforge/kolmafia/request/CharPaneRequest.java
- src/net/sourceforge/kolmafia/request/RelayRequest.java
- src/net/sourceforge/kolmafia/session/EquipmentManager.java
- test/net/sourceforge/kolmafia/request/CharPaneRequestTest.java
- test/net/sourceforge/kolmafia/request/RelayRequestWarningsTest.java
1) The WereProfessor is class 31.
2) A Mild-Mannered Professor has no equipment stat requirements.
3) Parse Turns until Transform from the charpane and save in "wereProfessorTransformTurns".
This will not be useful for scripting, but will suffice for a Relay Browser warning.
4) unstable fulminate warning will work if you have ingredients and dramatic range in inventory.
I've been bitten by this.
5) relay warning if potentially entering a fight as your last turn as a Mild-Mannered Professor and you have enough Research Points to learn something.
For a later PR:
Track turns until Transform without depending on charpane.
> WereProfessor tweaks

- src/net/sourceforge/kolmafia/chat/ChatManager.java
- src/net/sourceforge/kolmafia/chat/ChatMessage.java
- test/net/sourceforge/kolmafia/chat/ChatMessageTest.java
When processing an incoming message, the ChatManager checks whether the recipient equals the currently running user, and takes that as a sign to handle the message as a private message. However, the `recipient` has spaces replaced with underscores, so if the current user has spaces in their usernames, that check won't match.
There is already the same check for triggering a bell in the chat window, and it seems nicer to pull that blocks together anyway.
This PR includes another tiny fix for injecting messages into mchat (e.g. those sent from the GUI chat), which requires timestamps to be in seconds, not millis.
> Fix processing private chat messages when user has a space in their name

- src/net/sourceforge/kolmafia/request/RelayRequest.java
- test/net/sourceforge/kolmafia/request/RelayRequestWarningsTest.java
- test/root/request/test_spookyraven_suspicious_masonry.html
Rather than simply offering the chance to adventure in the Haunted Wine Cellar or Haunted Laundry Room if you have not read the mortar-dissolving recipe with Lord Spookyraven's Spectacles equipped, offer to get the recipe (which will autoread it, if autoQuest is true), equip specs, read the recipe.
It will do none of the above if you don't have the spectacles.
> Improve Relay Warning for adventuring in Spookyraven Cellar

- src/net/sourceforge/kolmafia/request/FightRequest.java
When using a shadow brick against a monster that cannot be insta-killed, it still counts against the limit.
The check needs to be added outside the "If these items succeed, then the second one won't actually do anything" block, because against such monsters, the shadow brick can indeed be dual-used (and counts twice):
With the fix, the following situations are tracked correctly:
* Dual-using against a monster that can be insta-killed (single use should work equivalently):
```
Encounter: Fallen Archfiend
...
Round 1: That Buff Guy uses the shadow brick and uses the shadow brick!
...
Round 2: That Buff Guy wins the fight!
...
Preference _shadowBricksUsed changed from 8 to 9
...
This combat did not cost a turn
```
* Dual-using against Eldritch Tentacle:
```
Round 0: That Buff Guy uses the …
```
> Improve tracking of shadow brick against unkillable monsters

- .editorconfig
This should fix issues with tools being unaware that .txt data files have tab indents.
ASH and JS scripts are inconsistent with regards to tabs / spaces. The * default could instead be *.java.
Ref #2266, #2272.
> feat: add .editorconfig to root of repo

- src/net/sourceforge/kolmafia/textui/TypescriptDefinition.java
`TypescriptDefinitionTest` seems to not be particularly fleshed out, so I'm still thinking about a testing strategy. But this essentially allows us to do use `typeof MafiaClass` as an argument in a function and have `arg.get` return the correct type without type assertions.
I'll need to consult with @gausie once he's awake both about tests and about where `Item.none` et al are defined, because I don't see 'em and I'd like to genericize that as well as something like
```typescript
get none<T extends MafiaClass>(this: { new (): T }): T;
```
EDIT: after playinga round in the typescript playground, it won't work for specifically the `none` getter, and there's also no such thing as an abstract static _or_ a generic getter. Alas!
Still, [linking a quick …
> update `MafiaClass` typedefs to use a `this` parameter

- src/net/sourceforge/kolmafia/textui/command/AprilBandCommand.java
The usage string as is makes the help print out as
`aprilbandeffect [nc|c|drop] | item [instrument] | play [instrument] - participate in the apriling band`
> Fix typo in aprilband command usage

- src/net/sourceforge/kolmafia/AreaCombatData.java
- src/net/sourceforge/kolmafia/objectpool/EffectPool.java
- test/net/sourceforge/kolmafia/AreaCombatDataTest.java
As reported in https://kolmafia.us/threads/booze-not-recognized-on-booze-ingredients.29694/.
> fix: cook / mix items are affected by food / booze drops

- src/net/sourceforge/kolmafia/objectpool/Concoction.java
- src/net/sourceforge/kolmafia/request/TinkeringBenchRequest.java
- test/net/sourceforge/kolmafia/request/TinkeringBenchRequestTest.java
You can only create each item at the Tinkering Bench once.
You can only upgrade an item if it is in inventory, not equipped.
The TinkeringBenchRequest is able to unequip an item and upgrade it.
The CreateItemPanel now correctly accounts for equipped items counting as ingredients.
You can "create and use" to unequip, upgrade, and equip improved item.
> Account for TinkeringBenchRequest ability to use equipped items

- src/data/monsterparts.txt
shadow spider confirmed to have 6+ legs
shadow spider can show a dart board with 6 legs, meaning it has at least 6 legs. it likely has 8, to confirm would need enough samples to consider the probability of the head or thorax parts appearing and calculate the number of legs that produce that probability.
> missing parts for baabaaburan, video game miniboss, shadow spider

- src/data/monsterparts.txt
has a size 6 dart board, confirming that its made up of at least 5 John Travoltas. No way to confirm the exact amount, but the drawing only includes 5.
> Travoltron confirmed to have at least 5 parts, missing pirate arms

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
Follow-up to #2285 
Induce parameter names from a) their type, b) the function body, or c) the wiki entry.
> Provide meaningful param names to runtime library functions

- src/net/sourceforge/kolmafia/textui/TypescriptDefinition.java
Alongside typescript definitions we create a header file that will be imported when someone tries to load the kolmafia typescript library outside of KoLmafia. Each function simply throws an error.
So far, a single function was exported under all function names. This prevents a feature employed by some testing libaries called automocking, where each function is automatically replaced with a mocked version, because all functions then reference the same mock. Instead, export a separate function for each library function, and use named function syntax to ensure the function objects have a name.
> Export each function separately to ease automocking

- src/net/sourceforge/kolmafia/textui/javascript/AshStub.java
- src/net/sourceforge/kolmafia/textui/javascript/ValueConverter.java
- test/net/sourceforge/kolmafia/textui/command/JavaScriptCommandTest.java
Currently, JS `undefined` is silently converted into a string representation of Rhino's Undefined instance.
This can in theory lead to wrong function invocations if the target type is a string.
Instead, return a special undefined value with a special undefined VOID type. This prints as undefined in the console, to make it transparent what is going on.
Other than that, it behaves as void. This is consistent with JS methods returning `undefined` if no value was returned, and TypeScript void methods returning `undefined`.
To prevent any confusion, forbid undefined values from being passed to Ash functions (for now).
> Represent JS undefined as void, not string

- src/net/sourceforge/kolmafia/textui/command/MayamCommand.java
- test/net/sourceforge/kolmafia/textui/command/MayamCommandTest.java
Make resonances creatable with the mayam command.
A nice addition might be adding them to concoctions so you can e.g. `create yam battery`, but this is much less complicated.
> feat: add command for mayam resonances

- src/net/sourceforge/kolmafia/KoLAdventure.java
- src/net/sourceforge/kolmafia/maximizer/CheckedItem.java
- src/net/sourceforge/kolmafia/maximizer/Maximizer.java
- src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java
- src/net/sourceforge/kolmafia/persistence/ItemDatabase.java
- src/net/sourceforge/kolmafia/session/BreakfastManager.java
- src/net/sourceforge/kolmafia/session/InventoryManager.java
- src/net/sourceforge/kolmafia/swingui/ItemManageFrame.java
- src/net/sourceforge/kolmafia/swingui/panel/ItemManagePanel.java
- src/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanel.java
- src/net/sourceforge/kolmafia/textui/command/StorageCommand.java
- test/internal/helpers/Maximizer.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
You have to look up Standard restrictions using a String.
For items, that is the item's dataName.
We have many instances of using a constant item name. That works.
However, we have a number of instances where we have an AdventureResult and use the  "name" field - which is not fine for Modeables like the backup camera, Jurassic Parka, or unbreakeable umbrella, where KoLmafia's name includes the mode, for user convenience.
ItemDatabase has an "isAllowed" method which accepts an itemId and looks up the dataName to pass to StandardRequest.
I added an "isAllowed" method which accepts an AdventureResult, extracts the itemId, and calls that method.
I changed all places which extract the name from an AdventureResult to call isAllowed to simply call the new method.
Net result:
- ItemManager no …
> Check Standard restrictions for AdventureResults by the item's dataName

- src/net/sourceforge/kolmafia/persistence/ItemDatabase.java
... which means they have no dataName and cannot be Standard restricted.
> UseItemEnqueuePanel can queue items with itemId < 0

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
It's a replacement for calling the CLI throw command that makes parameter handling more straight-forward.
> Add curse scripting command

- src/net/sourceforge/kolmafia/textui/javascript/AshStub.java
- src/net/sourceforge/kolmafia/textui/parsetree/BasicScope.java
- src/net/sourceforge/kolmafia/textui/parsetree/Function.java
- test/net/sourceforge/kolmafia/textui/parsetree/FunctionTest.java
This PR fixes one minor bug in function parameter matching (if a function gets zero arguments for a vararg parameter, it ignores all previous (un)matched parameters). See before and after tests for the change in behavior.
Additionally, it improves parameter matching by ~~a) short-circuiting some scenarios that mismatch a lot when checking multiple overloads of a given function, and b)~~ letting the function know itself whether it has variadic parameters, instead of letting the caller check both scenarios.
I'm aware that this PR mixes several topics, so let me know if you want me to split it up. As you probably know, I'm happy to do a lot of granular PRs, but these are kind of related, so having that bunch in one squashed commit makes sense.
> Improve (vararg) function matching

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/Modifiers.java
- test/net/sourceforge/kolmafia/KoLCharacterTest.java
When liberating the king or breaking ronin, previously permed skills that are too old for Standard restrictions will be available again.
I'm not actually sure off-hand whether Mafia knows a priori if those skills are permed but unusable, or if we need to fetch the charsheet first. I know there have been occasional issues with KoL not showing them in the past.
(Also, to be clear: I don't have any reason to think this is a comprehensive fix for the liver
mismatch problem, but it's definitely a deficiency that we should address.)
> Refresh modifiers when lifting Standard restrictions.

- src/data/concoctions.txt
- src/data/statuseffects.txt
- src/net/sourceforge/kolmafia/KoLConstants.java
- src/net/sourceforge/kolmafia/objectpool/Concoction.java
- src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java
- src/net/sourceforge/kolmafia/request/CreateItemRequest.java
- src/net/sourceforge/kolmafia/request/MayamRequest.java
- src/net/sourceforge/kolmafia/textui/command/MayamCommand.java
An inverse of the normal style: here a Request calls a Command, instead of a Command calling the Request.
Given the command already existed I thought this was reasonable to avoid rewriting it.
> feat: add concoctions for Mayam resonances

- src/data/concoctions.txt
Fixes the following messages that appear in the console:
```
Unknown ingredient (magical ice cube) for concoction: sweet potato o' mine
Unknown concoction: thansgiving bomb
```
> Fix typos in Mayam concoctions

- src/net/sourceforge/kolmafia/Modifiers.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
According to the wiki, these work as normal; you just can't actively use any skills unless they contain 'G' in their names.
> However, passive skills appear to function normally.
https://kol.coldfront.net/thekolwiki/index.php/G-Lover
> Stop enforcing G-Lover restrictions for passives.

- src/net/sourceforge/kolmafia/objectpool/Concoction.java
- src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
- test/net/sourceforge/kolmafia/objectpool/ConcoctionTest.java
The gCLI command checkconcoction checks the compareTo contract for concoctions.
Without this fix several comparisons fail, for example, "Failed comparing (quasi symmetry) [11107] whet stone and [8262] Mayodiol".  All of the failures involve helpers.
The test fails without the proposed fix and passes with it.  Furthermore, after the fix checkconcoction shows no failures.
This fix will change the behavior of any sorted list of concoctions that contains two or more helpers.
> Fix Concoction compareTo contract violation.

- src/data/coinmasters.txt
- src/data/defaults.txt
- src/data/equipment.txt
- src/data/familiars.txt
- src/data/fullness.txt
- src/data/inebriety.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/data/statuseffects.txt
- src/net/sourceforge/kolmafia/FamiliarData.java
- src/net/sourceforge/kolmafia/objectpool/FamiliarPool.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/session/ResultProcessor.java
Kiwi shop failed parsing, bit more work needed there.
When the mini kiwi drops eggs, you don't get a "You acquire" message at the moment, but that'll probably get fixed.
> feat: dump mini kiwi items

- src/data/content-types.properties
- src/net/sourceforge/kolmafia/KoLmafia.java
- src/net/sourceforge/kolmafia/textui/javascript/SafeRequire.java
- test/internal/extensions/ClearSharedStateAfter.java
- test/net/sourceforge/kolmafia/CustomScriptTest.java
Alternative to #784 now that https://github.com/mozilla/rhino/issues/1232 is in.
> feat: override rhino encoding provider instead of content-types.properties

- src/data/familiars.txt
```
Results for Mini Kiwi after 12 trials using 144 turns:
Cage Match      24      30      48           0              3
Scavenger Hunt  24      24      25           0              3
Obstacle Course 24      27      55           0              3
Hide and Seek   24      24      24           0              1
```
> arena stats for Mini Kiwi

- README.md
- src/net/sourceforge/kolmafia/textui/Parser.java
- src/net/sourceforge/kolmafia/textui/command/UpdateDataCommand.java
- test/net/sourceforge/kolmafia/textui/parsetree/DirectiveTest.java
Remove Jenkins mention from README.
Don't mention major releases, as we only do daily builds.
> fix: change messages referring to jenkins to not

- build.gradle
- src/net/sourceforge/kolmafia/scripts/git/GitManager.java
Checkmarx reports CVE-2023-4759, a vulnerability in jgit < 6.7, which allows overwriting any file on a case-insensitive filesystem.
Update to latest to fix this.
> feat: update jgit to 6.10 to avoid vulnerability

- src/net/sourceforge/kolmafia/scripts/git/GitManager.java
Fixes an issue with [autoscend](https://github.com/loathers/autoscend).
Currently, we're checking to see if a `dependencies.txt` relative to the root of the repo has changed, instead of relative to the manifest root. It just so happens that everything except autoscend had a build process whereby a `dependencies.txt` in the root was copied to the final folder -- but autoscend only has one in the `RELEASE` folder.
> fix: check for dependencies relative to manifest root

- test/net/sourceforge/kolmafia/textui/ChatBufferTest.java
The test creates a chat buffer.  The chat buffer has an associated log.  Before this the cleanup code could not delete root/chat because a log file was open.  This disposes of the buffer, thus closing the log file and thus allowing the file and directory to be deleted as part of global cleanup.
(A continuing product with my obsession that everything created in test/root by testing is cleaned up.  root/relay is the last hold out).
> Dispose of chat buffer after test

- test/internal/extensions/ClearSharedStateAfter.java
- test/internal/extensions/ClearSharedStateBefore.java
- test/net/sourceforge/kolmafia/request/RelayRequestTest.java
If root/relay is always deleted then only one existing test fails.
This reinitializes root/relay for the test that must have it.
This deletes root/relay at the end of all tests.
The other changes are related to suggestions from static code analysis.
> Allow root/relay to be deleted after testing

- src/data/modifiers.txt
Aside from the fact that there is no code for it in Modifiers.overrideItem, having it marked as such means the Maximizer and modtrace do not recognize it as a source of Item Drop in zone Twitch.
> time-twitching toolbelt is not 'Variable'

- src/net/sourceforge/kolmafia/session/BanishManager.java
- src/net/sourceforge/kolmafia/swingui/panel/DailyDeedsPanel.java
- src/net/sourceforge/kolmafia/textui/command/RefreshStatusCommand.java
We manage banishers in memory and persist them to a pref. Because of a listener-related close feedback loop, the moment you edit your banishedMonsters pref to fix a tracking issue, it overwrites it with a representation of the in-memory banisher state. This fixes that, and allows users to manually reload the in-memory state from that pref with `refresh banishes`.
> Allow manually fixing banishers

- .github/workflows/build.yml
Might fix the issue on https://github.com/kolmafia/kolmafia/releases/tag/r28015 / r28014, where a single commit is double-tagged and has two releases, that occurs when builds go out too quickly.
Ref https://github.com/softprops/action-gh-release/issues/392.
> fix: tag the build-triggering commit, not the latest commit

- src/net/sourceforge/kolmafia/maximizer/CheckedItem.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/session/InventoryManager.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
As reported in https://kolmafia.us/threads/in-legacy-of-loathing-hc-runs-maximiser-considers-free-pulls-that-cant-be-pulled-due-to-path-restrictions.29581/ and https://kolmafia.us/threads/maximizer-reports-retrospecs-as-free-pull-in-legacy-of-loathing-but-they-cannot-be-pulled.29393/ among others.
Not sure if the list is exactly correct as I don't think we store the original item types, but the tests cover the cases people wanted fixed.
> fix: various items are not pullable in LoL

- src/data/coinmasters.txt
- src/net/sourceforge/kolmafia/request/Crimbo17Request.java
The Cheer-O-Vend is accessible with crystalline cheer.
You can't buy warehouse keys any more.
You can buy the skillbooks only if you participated in the event and got "sufficiently far". What does this mean? It's a mystery.
> feat: cheer-o-vend is accessible with cheer

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
Should be self-explanatory. I am not sure what the difference is between CoreMatchers and Matchers in the tests is; happy to change that if necessary.
> Don't try to dereference a none location (NPE).

- src/data/defaults.txt
- src/data/questslog.txt
- src/net/sourceforge/kolmafia/persistence/QuestDatabase.java
- src/net/sourceforge/kolmafia/request/FightRequest.java
- src/net/sourceforge/kolmafia/session/ChoiceControl.java
- src/net/sourceforge/kolmafia/session/QuestManager.java
- test/net/sourceforge/kolmafia/session/ChoiceControlTest.java
The goal here is to create a Quest in the KoLmafia format for a journey through PirateRealm. Thanks to @Shiverwarp for helping me flesh out a step plan.
<details>
<summary>Step plan hidden here for brevity (click to view)</summary>
```
unstarted: We have not yet acquired our eyepatch
started: We have acquired our eyepatch, but We have not yet finished choosing all our "start pirate realm" things (ship, crew, curio)
step 1: We've chosen all our starting equipment, but have not yet chosen our first island
// Island 1
step 2: We have chosen our first island, We are in the process of sailing to the first island (sailing turns are less than our ship speed)
step 3: We have finished our sailing turns for the first island, but we have not yet seen the Land Ho NC for the first island
step 4: We …
```
> Quest.PirateRealm

- src/net/sourceforge/kolmafia/persistence/ItemFinder.java
- test/net/sourceforge/kolmafia/persistence/ItemFinderTest.java
Kramco behaves a little differently, since its container is not a superstring.
> Tweak matching rules for Kramco-type items.

- src/net/sourceforge/kolmafia/session/ChoiceControl.java
These 2 do advance the sailing turns needed to reach the next island too. Looks like the only one which doesn't is the broken ship encounter.
> Track a couple of PirateRealm Sailing Encounters

- src/data/encounters.txt
- src/net/sourceforge/kolmafia/session/EncounterManager.java
- test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
- test/net/sourceforge/kolmafia/session/EncounterManagerTest.java
#2459 had some mismatches between encounters.txt and adventures.txt, which caused error messages on opening mafia and for some encounters to fail to load.
> Fix name mismatches in encounters.txt.

- src/data/equipment.txt
- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java
Technically some of these work differently (parka only blocks in the first round, some are staggers (so can be shrugged) while some are not), but for my purposes (having autoscend not try to block the gremlins) this is good.
> feat: add 'avoid attack' modifier

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
Oops - a bug in the hash implementation meant the hash sometimes didn't change when adding or removing an item. Added a test for the behavior.
> Fix bug in fnvHash.

- src/data/defaults.txt
- src/data/equipment.txt
- src/data/familiars.txt
- src/data/monsters.txt
- src/data/statuseffects.txt
- src/data/zonelist.txt
- src/net/sourceforge/kolmafia/KoLmafiaCLI.java
- src/net/sourceforge/kolmafia/maximizer/Maximizer.java
- src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
- src/net/sourceforge/kolmafia/session/ChoiceControl.java
- src/net/sourceforge/kolmafia/textui/command/PhotoBoothCommand.java
- test/net/sourceforge/kolmafia/textui/command/PhotoBoothCommandTest.java
A casual implementation: if your clan doesn't have the relevant item unlocked, it just silently fails. I figure 99% of users will be going to BAFH which will soon have everything unlocked, so I'm not interested in implementing a more thorough solution.
> feat: photo booth command

- src/net/sourceforge/kolmafia/combat/CombatActionManager.java
- src/net/sourceforge/kolmafia/combat/Macrofier.java
- test/net/sourceforge/kolmafia/combat/CombatActionManagerTest.java
- test/net/sourceforge/kolmafia/combat/MacrofierTest.java
A pre-adventure script may want to adventure (e.g. to pick up Shadow Waters before going to a zone requiring high item drop). Under the current implementation, the pre-adventure adventure clears the filter function from the later adventure. Fix this.
> fix: allow a pre-adventure script to adventure

- CONTRIBUTING.md
We've required Java 17 for over 2 years now, and we're discussing moving to Java 21.
> Update listed java versions in CONTRIBUTING.md.

- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
As reported in https://kolmafia.us/threads/stat-experience-modifiers-written-oddly-in-certain-tracking-preferences.30003/
A potential phase 2 would involve removing "tag" as being distinct from "name", simplifying the codebase a bit. That is more complicated than this change, and I'm also not sure why they're separate in the first place.
> fix: read split modifiers by tags

- .gitattributes
This will stop counting test HTML in our language stats, as well as looking at vendored libraries for the same
> Update gitattributes to make our stats on GitHub nicer

- src/net/sourceforge/kolmafia/preferences/Preferences.java
- test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
- test/net/sourceforge/kolmafia/preferences/PreferencesTest.java
The `lastNoncombatXXX` preferences should reset on ascension, as `turns_spent` also resets to 0.
This PR makes that change, adds an `isResetOnAscension` function, and adds a consistency test to ensure the array is updated in the future.
> Reset lastNoncombatXXX on ascension.

- src/net/sourceforge/kolmafia/session/ChoiceControl.java
Should be self-explanatory. This will prevent Adjust Your Parka and Configure Your Unbreakable Umbrella from showing up in the noncombat_queue.
> You can walk away from Adjust Parka and Configure Umbrella

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/request/FightRequest.java
- test/net/sourceforge/kolmafia/request/FightRequestTest.java
Neglected this in the original PRs. Cookbookbat announces which ingredient the quest will result in, which is useful information for the user/scripts to have.
> Add CBB quest ingredient tracking.

- test/net/sourceforge/kolmafia/textui/javascript/JSONValueConverterTest.java
The test created, used, and left behind data/x.txt.  This deletes it in fairly close proximity to when and where it was created.
> Clean up root/data after test

- src/data/monsters.txt
- src/net/sourceforge/kolmafia/request/DeckOfEveryCardRequest.java
- test/net/sourceforge/kolmafia/request/DeckOfEveryCardRequestTest.java
This adds a test for DeckOfEveryCardRequest which had not had test before.  The actual tests are somewhat irrelevant because they are somewhat mechanical in nature but at least coverage is increased.
My long term goal is to use the Deck of Every Card in a test in such a way that the test will help debug the threadlock associated with #1889
While writing the tests I added a couple of helper functions to DeckOfEveryCardRequest and cleaned up some lint.
> Deck testing

- .github/workflows/check.yml
There was discussion in https://kolmafia.us/threads/support-for-java-21-new-lts.29522/#post-175419 on moving to Java 21 (and in https://kolmafia.us/threads/r28087-whats-changed-create-json-api-for-relay-scripts-by-phulin-in.29967/ on using https://github.com/simdjson/simdjson-java which requires Java 18).
This is a necessary precursor for that (unless we do a "big bang" 17 -> 21 change I'd prefer to avoid).
> feat: also test on Java 21

- src/data/modifiers.txt
The elemental damage is off, not on, when you have the effects.
> Reverse Roman Candelabra modifiers.

- src/data/adventures.txt
- src/data/combats.txt
- src/data/defaults.txt
- src/data/equipment.txt
- src/data/fullness.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/data/monsters.txt
- src/data/statuseffects.txt
- src/net/sourceforge/kolmafia/preferences/Preferences.java
Also you can reduce the combat rate to get more NCs like the Spooky
Forest.
Update items from mall, assume rares are 0.1% because it's looking that way.
> feat: crimbo zones are 100% combat with NCs every 11 adventures

- src/net/sourceforge/kolmafia/request/FightRequest.java
Didn't check #2558 thoroughly enough when it went through:
* we should log combat actions even if we're not writing results to session log
* we should log twiddles
> fix: record lastCombatActions even if not writing to session log

- src/data/concoctions.txt
- src/data/equipment.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/data/statuseffects.txt
- src/net/sourceforge/kolmafia/request/EatItemRequest.java
- src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
1) You can create a perfect Christmas scarf by using a single ragged wool yarn - which uses up 50 of them.
2) tiny plastic Jedediah and Boiling Cloud
3) Bowl of Infinite Jelly passively increases the adventure gain of one food a day and gives you 10 turns of the Jelly-Coated Insides status effect.
4) Christmas Island choice adventure option 1 is 'fight "Santa Clause"'
> More Crimbo24 tweaks

- src/data/fullness.txt
- src/data/inebriety.txt
They're at the level of the Dreadsylvania edibles, but with a vastly lower level requirement.
Decent pulls for turnbloat but unlikely to be worthwhile for most people.
> feat: stats for post-crimbo foods

- src/data/shoprows.txt
- src/net/sourceforge/kolmafia/KoLConstants.java
- src/net/sourceforge/kolmafia/persistence/CoinmastersDatabase.java
- src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java
- src/net/sourceforge/kolmafia/persistence/NPCStoreDatabase.java
- src/net/sourceforge/kolmafia/persistence/ShopRowDatabase.java
- src/net/sourceforge/kolmafia/textui/command/TestCommand.java
I want to experiment with shop.php using ShopRow Coinmasters.
I decided to validate one of my assumptions - shop rows are unique across shops.
We model such shops as coinmasters, concoctions, and npc stores.
This PR creates a ShopRowDatabase, containing ShopRowData records, stored in shoprows.txt
I generated that file by registering a ShopRowData for all ROW items seen in coinmasters.txt, npcstores.txt, and concoctions.txt.
The "test write-shoprows" commands writes out shoprows.txt containing all the scraped data.
These are the fields:
row - integer, in numeric order in the file
type - conc, coin, or npc
item - item, or CURRENCY (n), if from a Coinmaster "sell" entry, since the data files do not tell us the item
shopName - from data files, which may or may not be exactly what KoL calls it …
> shop.php ROW investigation

- src/data/shoprows.txt
- src/net/sourceforge/kolmafia/persistence/CoinmastersDatabase.java
- src/net/sourceforge/kolmafia/persistence/ShopRowDatabase.java
1) I added a "mode" for ShopRowDatabase:
- Mode.NONE - (default) Do not read or generate shoprows.txt
- Mode.BUILD - do not read shoprows.txt, but generate database from other files
- Mode.READ - read the datafile if, eventually, we need to use it internally
2) I split "coin" into "buy", "sell" (old-style coinmasters) and "row" (new-style coinmasters)
conc  = 284
npc = 337
buy = 576
sell = 17
row = 27
Total = 1241 rows
> Improve shoprow data file generation

- src/net/sourceforge/kolmafia/CoinmasterData.java
- src/net/sourceforge/kolmafia/CoinmasterRegistry.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/persistence/CoinmastersDatabase.java
- src/net/sourceforge/kolmafia/session/ResultProcessor.java
- test/net/sourceforge/kolmafia/request/CoinMasterRequestTest.java
CoinmasterRegistry will call CoinmastersDatabase to register all the currencies of each coinmaster.
ResultProcessor will fire (coinmaster) - which alerts CoinmastersFrame - whenever you gain or lose a currency.
It did that before, but currencies used to be switch labels, rather than being found via a Set lookup.
One less thing to remember to do when implementing a new Coinmaster...
> Register currencies when initialize coinmasters

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/swingui/panel/ItemManagePanel.java
- src/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanel.java
In the Usables section of the ItemManager, you can queue items to be consumed immediately or to be created.
If the former, we limit the number you can queue to the usable amount, obeying consumption limits.
If the latter, we ignore consumption limits and you can queue as many as you have ingredients for.
A new checkbox - "to consume" - controls this behavior.
A new preference - enqueueForConsumption - (default is true) is linked to the checkbox.
> Add 'to consume' checkbox to UseItemEnqueuePanel

- src/net/sourceforge/kolmafia/CoinmasterData.java
- src/net/sourceforge/kolmafia/ShopRow.java
- src/net/sourceforge/kolmafia/request/CoinMasterRequest.java
- test/net/sourceforge/kolmafia/ShopRowTest.java
- test/root/request/test_shop_september.html
1) Hermit was failing because we were not passing in a valid item id. I fixed that.
2) Supposedly Quartersmaster is failing.
I wondered if it is because it has a token, rather than an actual item as currency.
I don't have access to the island at war, at the moment, but the Sept-Ember Censer also uses a token.
I tried that out and it failed because it was passing an item ID instead of a row ID. I fixed that.
There seems to be no issue with tokens...
I think the Quartersmaster was failing for the same reason as the Hermit, but I can't test it.
3) I made ShopRow parsing detect shops that sell items for tokens, rather than items.
I have a test for that, and it can parse the Sept-Ember Censer now.
> Parse shops with tokens as currency. Fix Coinmaster bugs.

- src/net/sourceforge/kolmafia/session/ChoiceControl.java
Looks like this was introduced in #2590 and, scrolling through the PR, no other breaks were missed.
> missing `break` in numberology case of switch statement

- src/data/allshoprows.txt
- src/data/shoprows.txt
- src/net/sourceforge/kolmafia/swingui/widget/ListCellRendererFactory.java
1) CoinMasterPurchaseRequest.getCurrency(count) was correct, back when it ignored the "count" argument.
But when I changed that method to actually account for buying that many items - so that the MallSearchFrame would give pretty results - it screwed up the display in the ItemManager usable panels. Those now need to request (1).
2) And why not add the Hack Market rows to shoprows.txt and allshoprows.txt, as long as I have a trivial PR?
> Fix ItemManager display of CoinMasterPurchaseRequests

- build.gradle
- config/checkstyle/checkstyle.xml
A follow-up to #2612: ziz helpfully provided a minimal checkstyle config, so I've added a linter to the build.
Deliberate fall-throughs require a preceding comment (e.g. `// Fall through`) to not fail the build.
Checkstyle is configured to only test for exactly this problem we are having (convenient!) and can be run with `gradlew checkstyleMain`, `gradlew checkstyleLib`, and `gradlew checkstyleTest`, and will run as part of `gradlew check`.
> feat: add checkstyle to prevent uncommented switch fallthroughs

- src/data/familiars.txt
- src/data/items.txt
- src/data/modifiers.txt
- src/data/monsterparts.txt
Some of the dedigitizer items are now no-discard.
The geofencing shield is now no-discard, which means it can't be mirror copied.
> feat: more cyber items

- src/net/sourceforge/kolmafia/RequestEditorKit.java
I noticed that the Hidden Temple did not give me a "use another stone wool" before the Adventure Again link.
Yesterday, I noticed that the Haunted Ballroom did not add its usual links before the Adventure Again link.
I conjecture that this is the same issue as I saw on A-Boo Peak.
No tests, since I can't repeat those issues until I ascend, but this PR generalizes and fixes them the same way.
I made the A-Boo Peak fix use this too, and the test still passes, so...
I'll get html for the other two zones next ascension and will make tests.
> generalize finding Adventure Again link

- src/net/sourceforge/kolmafia/CoinmasterData.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo24BarRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo24CafeRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo24FactoryRequest.java
- test/net/sourceforge/kolmafia/CoinmasterDataTest.java
As discussed in a previous PR
- **Allow coinmasters to live in zones, and use zone removal for accessibility unless overwritten**
- **Use coinmaster zone to eliminate crimbo24 coinmasters**
- **Do not rely on blank string meaning null:**
> Coinmasters can live in zones, if zone is Removed coinmaster is automatically inaccessible

- src/net/sourceforge/kolmafia/request/UseSkillRequest.java
Need to test this actually works properly, but parking here.
> fix: don't allow bat wings restore to be cast with +hp back item

- src/net/sourceforge/kolmafia/CoinmasterData.java
- src/net/sourceforge/kolmafia/request/coinmaster/CRIMBCOGiftShopRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/Crimbo11Request.java
- src/net/sourceforge/kolmafia/request/coinmaster/CrimboCartelRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo14Request.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo17Request.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo20BoozeRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo20CandyRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo20FoodRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo23ElfArmoryRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo23ElfBarRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo23ElfCafeRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo23ElfFactoryRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo23PirateArmoryRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo23PirateBarRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo23PirateCafeRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/Crimbo23PirateFactoryRequest.java
- src/net/sourceforge/kolmafia/swingui/CoinmastersFrame.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/request/CoinMasterRequestTest.java
I added inZone for previous Crimbo coinmasters and (mostly) removed their "accessible" functions.
(I retained the ones for Crimbo23, since they were interesting examples - accessibility depending on which war faction controlled them)
I moved the Crimbo24 shops to the Removed section of the CoinmastersFrame.
And, guess what: we had 11 tests that assumed Crimbo23 coinmasters were accessible.
It controlled that using the accessible() function, but the zone now overrides that.
> Crimbo24 coinmasters are Removed. Use 'inZone' for older Crimbo coinmasters.

- src/net/sourceforge/kolmafia/session/ChoiceControl.java
Convert much of ChoiceControl to use the newer choice switches. Despite #2614, I think they're nicer to deal with.
I didn't convert `postChoice1` or `postChoice2` because they're more involved, or `canWalkFromChoice` because the resulting switch would have been almost the same but slightly harder to change due to the formatting involved.
The was done using either IntelliJ or regex and manual cleanups (IntelliJ ruins comments if given the option). Some other changes were necessary as the new-style switch doesn't support multiple breaks, so I switched them to `if`/`else`.
> chore: prefer newer choice switches in ChoiceControl

- .github/workflows/check.yml
While https://github.com/awalsh128/cache-apt-pkgs-action/pull/140 was causing the pipeline failures, may as well merge this.
Although the codecov bot hasn't posted -- is there something wrong or is it just that there's no Java code changes here?
> feat: update codecov to v5

- src/data/coinmasters.txt
- src/net/sourceforge/kolmafia/CoinmasterRegistry.java
- src/net/sourceforge/kolmafia/RequestLogger.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/request/NPCPurchaseRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/DedigitizerRequest.java
- src/net/sourceforge/kolmafia/swingui/CoinmastersFrame.java
I got the recipes from the Wiki and the ROWs from "/buy xxx".
The Wiki does not have the recipes for ```3d printed server room key``` or ```STATS+++ rom chip```, but I got the ROWs.
We'll need to add those two items in a followup PR.
I put the Dedigitizer in the "Aftercore" section of the CoinmastersFrame.
Perhaps it should go in the IOTM section.
Also, we'll need to fix "accessible" once we figure out how to handle the 3d printed server room key.
It's a day pass, so it will require the sort of "access granted today" code that other day passes have.
> Dedigitizer coinmaster

- build.gradle
- test/net/sourceforge/kolmafia/textui/command/JavaScriptCommandTest.java
Rhino 1.8 was released a few days ago: it has `String.matchAll` and a whole bunch of other modern JavaScript stuff: default parameters, null coalescing, findLast, most of proxy and reflect and promises, generators, symbol keys and many other things most scripters won't use.
> feat: upgrade to Rhino 1.8

- src/net/sourceforge/kolmafia/session/BanishManager.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
It's helpful to know whether a phylum is banished without parsing the preference.
> feat: add function `is_banished(phylum)`

- test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
- test/net/sourceforge/kolmafia/DataFileMechanicsTest.java
- test/net/sourceforge/kolmafia/DataFileTest.java
The typo in kgb parsing fixed in #2662 raised a question - why didn't a data file test find it?  The answer is that there is no data file test for consequences.txt but investigating that identified several data files that were candidates for the mechanics test.  This PR adds tests for them.  
A debug print identified several files that had a version number hard-coded in a test and the current version is different.  Those were fixed.  
That same debug showed that journeyman.txt, TCRS.astral_consumables.txt and TCRS.astral_pets.txt have no version in the file yet they are being read by a versioned reader in tests.  Adding a version number to the files was not investigated nor was the use of versioned readers in the application code itself.
> Add some files to DataFileMechanicsTest

- test/net/sourceforge/kolmafia/DataFileMechanicsTest.java
Missed some in https://kolmafia.us/threads/r28280-whats-changed-add-some-files-to-datafilemechanicstest-by-jaadams5-i.30211/
For reference I used gawk to calculate the number to tab delimited fields for each file in the data directory and then added or changed code based on the results.
Something with 1 or 2 fields is too simple and something with lots field counts is too complex.  Any time x or x+1 fields are allowed this test is not going to find an error where  a space instead of a tab gives x fields instead of the intended x+1.
> More files for datafile mechanics tests

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/KoLmafia.java
- src/net/sourceforge/kolmafia/session/BanishManager.java
- src/net/sourceforge/kolmafia/session/LoginManager.java
- src/net/sourceforge/kolmafia/session/TrackManager.java
- src/net/sourceforge/kolmafia/textui/command/RefreshStatusCommand.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/session/BanishManagerTest.java
- test/net/sourceforge/kolmafia/session/ResultProcessorTest.java
- test/net/sourceforge/kolmafia/session/TrackManagerTest.java
As raised in https://kolmafia.us/threads/trackedmonsters-resets-on-login.30177/, tracked / banished monsters are reset on login, probably due to reading from the internal cache before resetting the preference.
Move to a single source of truth for banished / tracked monsters / phyla (the preference).
> fix: don't cache banished / tracked monsters internally

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/request/FightRequest.java
> A new trivial update has been posted: Only the first 11 Eldritch Tentacles you fight in a day will be free fights, going forward.
Add a pref to track this.
> feat: eldritch tentacles after 11 are not free

- src/data/outfits.txt
petrified wood wizard's pouch was missing from the outfit
> Add missing outfit piece for HC 2025

- src/net/sourceforge/kolmafia/persistence/CoinmastersDatabase.java
- src/net/sourceforge/kolmafia/persistence/NPCStoreDatabase.java
- src/net/sourceforge/kolmafia/request/MallSearchRequest.java
- src/net/sourceforge/kolmafia/shop/ShopRequest.java
For example, from ```test row-duplicate-items```:
```
Degrassi Knoll Bakery and Hardware Store	ROW600	wad of dough	50 Meat
Bugbear Bakery	ROW678	wad of dough	50 Meat
Madeline's Baking Supply	ROW737	wad of dough	40 Meat
```
If you are in a Knoll sign, have the Bugbear Costume, and have met Madeline, all three shops are available.
Any of those conditions NOT true, the corresponding shop is not available.
This PR shows all available NPC purchase requests in the Mall Search frame when you search for "wad of dough".
Hmm. The previous behavior showed the last unavailable purchase request, if none were available.
Is that right? If you don't have Degrassi Knoll available, nothing you can do will open it. It seems like luck - or perhaps the order of shops in npcstores.txt - that determines what …
> If multiple (available) NPC stores sell an item, show all in Mall Search results

- src/net/sourceforge/kolmafia/persistence/CoinmastersDatabase.java
- src/net/sourceforge/kolmafia/persistence/NPCStoreDatabase.java
- src/net/sourceforge/kolmafia/request/MallSearchRequest.java
- src/net/sourceforge/kolmafia/shop/ShopRequest.java
This is a continuation of my previous PR.
NPCStoreDatabase.contains(itemId, false) and CoinmastersDatabase.contains(itemId, false) - where the false mean "don't validate" - don't actually need to look at the PurchaseRequests on their HashMultimaps. All they need to look at is if there is at least one PurchaseRequest for the itemId.
MallSearchRequest can then only ask for a list of PurchaseRequests if the appropriate database actually has any.
> simplify 'contains' method in CoinMastersDatabase and NPCStoreDatabase

- src/net/sourceforge/kolmafia/persistence/FactDatabase.java
- test/net/sourceforge/kolmafia/persistence/FactDatabaseTest.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
Now that #2707 exposes these to non-scripters, make the fact strings more self-explanatory.
This will break scripts that were relying on exact string matches, but I haven't found one that does that -- things like `numeric_fact` are more popular.
> feat: change fact strings to be more thorough

- src/net/sourceforge/kolmafia/request/RelayRequest.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/request/RelayRequestTest.java
- **Decorate /go output in chat pane (so that I can click to go again)**
- **Add test**
Allows the placename to be clicked here to repeat the action of navigation. This is really useful for me to be able to repeat an action over and over, maybe others will find it useful.
EDIT: As the tests here touch aspects of chat for the first time it inadvertently brings our coverage over 40%!
> Make place names clickable in relay browser after a /go command"

- settings.gradle
Since https://github.com/kolmafia/kolmafia/pull/2687 I have not been able to build the application without this configuration present. I found it via gradle's documentation.
https://docs.gradle.org/current/userguide/toolchains.html#sec:provisioning
> Specify toolchain manager

- src/net/sourceforge/kolmafia/AdventureResult.java
- src/net/sourceforge/kolmafia/CoinmasterData.java
- src/net/sourceforge/kolmafia/request/coinmaster/CoinMasterRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/CoinMasterShopRequest.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/TicketCounterRequest.java
- src/net/sourceforge/kolmafia/request/concoction/shop/Crimbo16Request.java
- src/net/sourceforge/kolmafia/session/ResponseTextParser.java
- src/net/sourceforge/kolmafia/shop/ShopRequest.java
- src/net/sourceforge/kolmafia/swingui/CoinmastersFrame.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/CoinmasterDataTest.java
- test/net/sourceforge/kolmafia/request/CoinMasterRequestTest.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
Using the Genetic Fiddling coinmaster (shopid=mutate), pretty much finished supprt for coinmasters that sell skills.
1) added boolean availableSkill(int skillId) to CoinmasterData. 
Assumption is only new ShopRow coinmasters will support it.
There must be a ShopRow with the result item being a skill with that skillId.
And if you already have the skill, it is no longer "available".
2) If a coinmaster has addition requirements, it can use "withAvailableSkill" to override it.
GeneticFiddlingRequst doesn't need to to that. I assume.
3) added AdventureResult skillBuyPrice(int skillId) to CoinmasterData
Assumption is that only new ShopRow coinmasters will support it.
Assumption is there is only one "cost".
This returns that cost.
4) CoinMasterRequest only calls purchasedItem for a purchase.
It …
> More support for coinmasters that sell skills

- src/data/bookoffacts.txt
- test/net/sourceforge/kolmafia/persistence/FactDatabaseTest.java
As seen in https://github.com/loathers/BOFASpading/blob/main/bofa_data.php#L3976
Reported by Veracity in https://kolmafia.us/threads/r28327-whats-changed-feat-change-fact-strings-to-be-more-thorough-by-midgleyc-in-2715-full-changelog-r28326-r28327.30284/#post-176238
> fix: change fact order for myst / moxie stats

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/FamiliarData.java
- src/net/sourceforge/kolmafia/persistence/FamiliarDatabase.java
- src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java
- test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
- test/net/sourceforge/kolmafia/FamiliarDataTest.java
Add data file consistency test to ensure all familiars have a Throne description.
Derive FamiliarData.canCarry() from data.
Differentiate between a blank modifier (unspaded) and a modifier of "none" (cannot be carried)).
> Require a Throne line in modifiers.txt for every familiar (and do some things to support that)

- src/net/sourceforge/kolmafia/CoinmasterData.java
- test/net/sourceforge/kolmafia/CoinmasterDataTest.java
getBuyPrice returns 0 for an unsold item.
itemBuyPrice returns an AdventureResult of the shop's "currency" with the buy price.
That's OK for a shop with a single currency.
Shops with multiple currencies need to override that method and return an adventure result with the correct currency.
(Mr. Store does that, for example.)
What about ShopRow shops which might have multiple currencies and also items that have multiple costs?
What IS the "buy price" for an item that costs X of item 1 and Y of item 2?
This is primarily an issue for ASH - which has no support for coinmasters like that.
That will be a design issue for the future...
For now, if a shop has neither an "item" or a "token" and does not override itemBuyPrice - which includes the Crimbo24 shops, at least - itemBuyPrice returns null …
> itemBuyPrice returns null for an unsold item

- src/net/sourceforge/kolmafia/request/RelayRequest.java
- test/net/sourceforge/kolmafia/request/RelayRequestTest.java
These APIs currently just reset the connection, which is difficult to handle from the script side. Instead, they should respond RESTfully, which means sending back a 401 Unauthorized status code.
> Command and JSON APIs should return 401 if the password hash is incorrect.

- src/net/sourceforge/kolmafia/webui/RelayAgent.java
- test/net/sourceforge/kolmafia/webui/RelayAgentTest.java
This continues my quest to have Mafia respond reasonably with RESTful API responses. RelayAgent also currently has a nasty habit of just terminating the connection if a malformed request comes in. This PR makes it return 400/401 status codes depending on the issue, and adds some basic testing to RelayAgent.
> RelayAgent should respond to malformed requests.

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/request/CharSheetRequest.java
At the moment, every time the char page request is hit for Zootomist, it gets the wrong stats and sets your character back to level 1. This uses the code from Grey You where a similar problem existed to fix the issue.
> Stop character sheet breaking Zootomist stats

- src/net/sourceforge/kolmafia/KoLAdventure.java
- src/net/sourceforge/kolmafia/KoLCharacter.java
- test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
Kingdom of Exploathing does seem to have Campground access by wiki, and I'm not sure why this wouldn't work, so I removed that part of the code.
> fix: can adventure in mushroom garden when has campground and garden

- src/data/familiars.txt
Spooky gravy fairy was listed as stench, it's actually spooky (shockingly).
> correct wrong element in Spooky Gravy Fairy tags

- src/net/sourceforge/kolmafia/request/MallPurchaseRequest.java
We log (and set ERROR state) if we can't parse the item from the table in the responseText.
This PR also does so if it cannot find the table.
Chances are, KoL might be giving us an unexpected error message, or something.
I wonder if we should be logging the whole responseText for the other instance, as well?
I think so - we found a table, but perhaps it's a different table?
And what about if we could not find the Meat cost?
Considering we found - and processed - the purchased item, that seems extremely unlikely.
(What happens on salad day? I expect we'll find out on April 1.)
> log Mall Purchase parsing error for another failure

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/request/CharSheetRequest.java
- test/internal/helpers/Player.java
- test/net/sourceforge/kolmafia/ModifierExpressionTest.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
- test/net/sourceforge/kolmafia/textui/command/AbsorbCommandTest.java
Zootomist uses grafts for levels, so easier to just always use the API.
This introduces a race on startup in Gelatinous Noob, which isn't great, but can be fixed
by refreshing the charpane as we'll definitely have the level by then.
> feat: always read level from API, don't calculate it

- src/data/classskills.txt
- src/data/consequences.txt
- src/data/defaults.txt
- src/data/statuseffects.txt
- src/net/sourceforge/kolmafia/objectpool/EffectPool.java
- src/net/sourceforge/kolmafia/session/InventoryManager.java
- src/net/sourceforge/kolmafia/session/ResultProcessor.java
Also avoid the double space in the skills by substituting the substituted familiar race. This appears in the milk skills when `/cast`ed, and probably in the others, but isn't visible without being replaced.
Add the effects to consequences and parse them when we see them.
> feat: make zootomist effect mods show up correctly

- src/net/sourceforge/kolmafia/KoLCharacter.java
- test/net/sourceforge/kolmafia/KoLCharacterTest.java
This is causing various script failures. This PR designates them as not "usable", so `have_familiar` will return false in scripts. This works like QT or G-Lover.
> Grafted familiars can't be used in Zootomist.

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/modifiers/StringModifier.java
- src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
- src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java
- src/net/sourceforge/kolmafia/textui/command/CheckDataCommand.java
At some point, `` started appearing in at least desc_familiar and desc_item. Well, I asked CDM to do it and at some point he did!
I will probably do this in multiple pull requests; this one just supports Familiars for now as there are relatively few of them.
> Begin support for tracking Last Available Date readout

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/modifiers/BooleanModifier.java
- src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
- src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java
- test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
EDIT: This now includes all items, and is somewhat rigorously tested.
I think the only thing left to go is skills.
While I was in here, the modifier tools kept annoying me about the avatar IotMs that are only free pullable / only usable in hardcore in their special paths. I decided to make boolean modifiers support evaluating conditions, which was surprisingly easy. I retroactively applied that to the Time-Twitching Toolbelt, with which we had struggled before.
> Last Available modifier for items

- src/data/coinmasters.txt
- src/data/shoprows.txt
- src/net/sourceforge/kolmafia/request/MallSearchRequest.java
1) I noticed that searching for "Easter eggnog" listed the (removed) coinmaster twice.
Ditto for Thanksgiving ration.
Needed to canonicalize  (lower case) the name when removing it from list of processed matches.
2) The "/buy" trick for discovering ROWs I cannot otherwise see worked for my character who has a detective school and already bought the gold detective badge.
```
<font color=green>Purchasing 1 bronze detective badge.</font><br>
<font color=green>Purchasing 1 silver detective badge.</font><br>
<font color=green>Purchasing 1 gold detective badge.</font><br>
```
> fix mall search for coinmaster items with capital letters

- src/data/items.txt
- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/persistence/ConsumablesDatabase.java
- src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
- src/net/sourceforge/kolmafia/persistence/ItemDatabase.java
- src/net/sourceforge/kolmafia/webui/UseLinkDecorator.java
- test/net/sourceforge/kolmafia/persistence/DebugDatabaseTest.java
Some items newly marked as "usable" require further user interaction to actually do anything. This was already the case for e.g. ancient cure-all, so I think this is fine.
Some items marked as "food helper" were actually just used automatically from being in inventory.
Some items that send you to a shop are "usable", and some are not. Fun!
> feat: update use / combat from museum

- src/net/sourceforge/kolmafia/CoinmasterData.java
- src/net/sourceforge/kolmafia/persistence/CoinmastersDatabase.java
- src/net/sourceforge/kolmafia/persistence/StandardRewardDatabase.java
- src/net/sourceforge/kolmafia/request/coinmaster/shop/ArmoryAndLeggeryRequest.java
- src/net/sourceforge/kolmafia/shop/ShopRequest.java
- src/net/sourceforge/kolmafia/textui/command/TestCommand.java
- test/net/sourceforge/kolmafia/persistence/StandardRewardDatabaseTest.java
Currently, to update standard-rewards.txt, you have to do this:
1) Add pulverized items to standard-pulverized.txt
2) Visit the Armory & Leggery and get a log with those in inventory
3)  Do "test load FILE" and "test standard-rewards"
4) Copy resulting lines into standard-rewards.txt
5) Add 12 more lines for THIS year's rewards and put them into standard-rewards.txt with UNKNOWN rows.
What with ShopRequest parsing inventory, I want to build off that and let ArmoryAndLeggeryRequest generate the lines that go into standard-pulverized and standard-rewards. New protocol:
1) Visit Armory & Leggery with new pulverized items in inventory.
(You don't have to have both HC and SC pulverized in inventory. You can do this twice, once for HC and once for SC.)
2) Copy lines into standard_pulverized.txt …
> Armory & Leggery coinmaster deduces lines to add to standard reward data files

- src/data/fullness.txt
- src/data/inebriety.txt
- src/net/sourceforge/kolmafia/persistence/ConsumablesDatabase.java
- test/net/sourceforge/kolmafia/DataFileTest.java
- **Fix capitalisation of one item**
- **Rename sushi pseudoquality to pseudoitem, include other pseudoitems**
Removing fake quality tags from items that don't actually exist, let alone have a quality. Instead we can use `pseudoitem` as a catch-all for this kind of support.
> Fix up some consumables data

- src/net/sourceforge/kolmafia/swingui/panel/ChoiceOptionsPanel.java
Used to be:
Take a Look, it's in a Book! - whichchoice=888
option 1 = Read "The Rise of the House of Spookyraven"
option 2 = Read "The Better Haunted Homes and Conservatories Cookbook"
option 3 = Read "Ancient Forbidden Unspeakable Evil, a Love Story"
option 4 = Reading is for losers. I'm outta here.
If you select "ignore this adventure" in the drop down, we did this:
```      Preferences.setString("choiceAdventure888", "4");```
Which used to be fine, except the choice adventure now has:
option 4 = Read "Ten Times Sword Canes have Changed History"
option 5 = Reading is for losers. I'm outta here.
Option 4 only shows if you have a candy cane sword cane equipped, but the "skip adventure" is always option 5, now.
> candy cane sword adds option to choice 888

- src/net/sourceforge/kolmafia/request/ClanLoungeRequest.java
- src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
- src/net/sourceforge/kolmafia/textui/command/TestCommand.java
- test/net/sourceforge/kolmafia/request/ClanLoungeRequestTest.java
- test/root/request/test_clan_cannonball.html
1) Breakfast in a clan with a swimming pool started issuing an "Unexpected choice" error message.
Turns this is due to the recent change for detecting if we are still in a choice: cannonballing into the swimming pool redirects to a choice, but we didn't used to recognize we were in a choice. Now we do, and ChoiceManager wanted to automate it - and couldn't.
Subsequent requests were in ClanLoungeSwimmingPoolRequest, which already tells ChoiceManager to not automate.
I changed ClanLoungeRequest to automatically follow the redirect - like ClanLoungeSwimmingPoolRequest - for the "cannonball into the swimming pool" request.
I did not make every request of class do that, since there are a bunch of other redirections which we want to detect.
The difference is, I think, that those others do not …
> Don't let ChoiceManager automate swimming pool

- src/net/sourceforge/kolmafia/swingui/panel/CompactSidePane.java
> fix: update sidepane level substats on ascension / prism break

- src/net/sourceforge/kolmafia/request/FightRequest.java
Parse the dartboard before parsing rest of fight.
This allows us to correctly log dart throwing as an auto attack.
> Parse dartboard before parsing rest of fight

- src/net/sourceforge/kolmafia/CoinmasterData.java
In particular, the Cheer-o-Vend 3000, even though Crimbo17 is Removed.
The "Removed" check was intended to allow coinmasters in a zone to have accessible methods and not have to edit the method, if the zone itself is Removed, but, we can't quite do that. We CAN delete the custom method, usually.
```
> inv crystalline cheer
> ash is_accessible($coinmaster[Cheer-o-Vend 3000])
Returned: false
> ash inaccessible_reason($coinmaster[Cheer-o-Vend 3000])
Returned: You need some crystalline cheer.
> pull 1 crystalline cheer
Pulling items from storage...
Requests complete.
> ash is_accessible($coinmaster[Cheer-o-Vend 3000])
Returned: true
```
> removed coinmasters can be accessible

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/Expression.java
- src/net/sourceforge/kolmafia/ModifierExpression.java
- src/net/sourceforge/kolmafia/objectpool/FamiliarPool.java
- test/net/sourceforge/kolmafia/ModifierExpressionTest.java
For example, Dataspider and Pocket Professor count for this but aren't robots in Zoot.
> fix: warbear foil hat uses a hardcoded list of robots

- src/net/sourceforge/kolmafia/request/RelayRequest.java
Reverts kolmafia/kolmafia#2840
As @Tokoeka [mentioned](https://github.com/kolmafia/kolmafia/pull/2840#issuecomment-2732037297), completing a 100% familiar run is possible in this path and the nag was useful in doing so.
As someone who doesn't do 100% familiar runs, the feature is not useful to me at all, so proposing a revert as a neutral observer :)
> Revert "no changing familiar nag in Zootomist"

- src/data/familiars.txt
- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/persistence/FamiliarDatabase.java
Heat Wave increases init, but apparently only in combat (doesn't show up on talking spade). I have bug reported and hopefully CDM will fix it to be like the Woim, which is more useful (e.g. for modern zmobies).
I have split "delevels before combat" from "delevels during combat". There should not be any user-visible changes from this yet.
> feat: add types for zoot fams, split delevel before and during combat

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java
- src/net/sourceforge/kolmafia/modifiers/MultiStringModifier.java
Lanterns add extra spell damage equal to the largest hit of a spell, in a particular element (or elements).
Add two modifiers: "Lantern" giving the number of sources, where 1 is +100% damage; and "Lantern Element", giving the element(s) of the spell (omitted if nonconstant).
Porcelain porkpie is absent due to only working on PM spells. Novelty Belt Buckle is absent as the damage comes as an extra hit, and doesn't work for the wall of bones (and matters less for other monsters as it's only 10-20%).
> feat: add modifier for 'lantern'

- src/data/familiars.txt
- src/net/sourceforge/kolmafia/persistence/FamiliarDatabase.java
- test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
As discussed a while ago. All uses I've seen strip out the pokefam attribute as it's not actually an ingame tag.
Also add the tags for special ultimates (that we know about).
> feat: move 'pokefam' to a type, not an attribute

- src/net/sourceforge/kolmafia/textui/command/PvpAttackCommand.java
eusst told me that when you make a directed PVP attack - against a specific target, not a random target - if you are in HC or Ronin, you can no longer attack for "fame". Just "flowers".
The "pvp" or "steal" commands take a mode and a stance and goes against a random target, so is unaffected.
The "attack" command takes a stance and list of direct targets and attacks for "loot" or "fame".
The latter no longer works. Change it to "flowers".
> You can no longer make a directed attack for fame in HC or Ronin

- src/net/sourceforge/kolmafia/request/GuildRequest.java
- test/net/sourceforge/kolmafia/request/GuildRequestTest.java
In the Nemesis Quest, when you defeat your Nemesis in the mountain cave (step 15 -> 16), you must check back in with the guild (step 16 -> 16.5) This should enable the assassins, but due to a KoL bug, you must visit again (step 16.5 -> 17).
When we detect that the first visit has happened (16 -> 16.5), automatically make another visit in the background (16.5 -> 17).
If you've learned to visit the guild a second time, that's superfluous, but not an issue; you'll still see the same thing you always have.
> When visit scg after cave, auto visit a second time

- src/net/sourceforge/kolmafia/swingui/SkillBuffFrame.java
Previous PR correctly deselected skill which was disabled, but also deselected skill which was not disabled after a cast.
Turns out that is a side effect of updating skill list after casting - which was new in that PR - and is unnecessary.
Remove that and only skill which is out of casts gets deselected.
> update after casting skill incorrectly unselects skill

- test/net/sourceforge/kolmafia/session/MallPriceManagerTest.java
Everything changed was flagged by IntelliJ's analysis but not everything flagged was corrected.  Not that it matters unless an error is actually logged but assertEquals wants the first parameter to be what was expected and the second to be what the test generated.
> Suppressed unchecked cast warning and cleaned up some lint

- test/net/sourceforge/kolmafia/request/DeckOfEveryCardRequestTest.java
This test was intended as a canary for preference file corruption.  This parameterizes it so that all the combinations of two related preferences are checked.  This may be a step towards tests with Swing unavailable in #1889
> Parameterized test

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/request/GuildRequest.java
- src/net/sourceforge/kolmafia/session/InventoryManager.java
- test/net/sourceforge/kolmafia/request/GuildRequestTest.java
1) Having examined over 200 session logs, in all but 7, the menacing thug appeared between 5 and 15 turns after talk a second time to the scg in the guild - accounting for adventuring when/where wanderers are not welcome. Therefore, when the quest moves to step 17, start the Nemesis Assassin counter.
2) remove a duplicated line in KoLCharacter.removeAvailableSkill
3) I noticed that upon login I was getting "KoL thinks you have free rests but KoLmafia doesn't think so.
I added a call to KoLCharacter.recalculateAdjustments when refreshing inventory.
> Start Nemesis Assassin counter at step 17 of quest

- src/data/defaults.txt
I rediscovered a script that looked for user settings and identified those that did not have a KoL default.  I discovered two that were used by KoLmafia.
It looks to me that maximizerUseScope is actually obsolete because I cannot find a place where KoLmafia actually sets it to false.
_concoctionDatabaseRefreshes is never used, only incremented, but the increment implicitly assumes that the daily reset returns it to zero.  Adding a default makes the initialization to zero more obvious.
> Added defaults

- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/modifiers/DerivedModifier.java
- src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
Follow-on to #2885.
Maximizer only accepts double / boolean modifiers. Make raw combat rate a double modifier.
> feat: allow raw combat rate to be used in the maximizer

- src/net/sourceforge/kolmafia/request/AscensionHistoryRequest.java
- test/net/sourceforge/kolmafia/request/AscensionHistoryRequestTest.java
Parsing the ascension history was checking for the path image by "image.gif", this prefixes the image with a forward slash "/image.gif" to fix updating path points for Two Crazy Random Summer specifically because "twocrazydice.gif" was being matched by the Crazy Random Summer "dice.gif"
> Fix ascension history image parsing

- src/net/sourceforge/kolmafia/request/UseSkillRequest.java
- src/net/sourceforge/kolmafia/session/BuffBotManager.java
In the future, I hope to use "forcedItem" with the items mentioned in #2881.
This refactor can go in first. It is technically an improvement to only not remove the item required for the skill we're casting, but has no impact at the moment, as no back / pants have -MP and the powerful glove has +HP, so we never remove it anyway.
> refactor: don't have loose 'avoid removal only' items

- src/net/sourceforge/kolmafia/request/WildfireCampRequest.java
Checking the `fire_level` of a zone sometimes returns 5 instead of the actual fire level, and I think it's due to `FIRE_LEVEL` being cleared and repopulated.
So don't do that.
> fix: don't blank fire levels while parsing

- src/net/sourceforge/kolmafia/request/ForeseeRequest.java
- src/net/sourceforge/kolmafia/utilities/ChoiceUtilities.java
- test/net/sourceforge/kolmafia/utilities/ChoiceUtilitiesTest.java
- **Fix peridot parsing by widening choice parsing appropriately**
- **Linting for ChoiceUtilities class**
- **Formatting**
- **Quick fix of semi-unrelated issue**
- **Support filling extra hidden fields with the extra field in choiceAdventureXXX**
Re-fixes #2904
Whielw e were able to successfully parse the options for the choice in #2905, the choice adventure validation code was not ready to deal with multiple forms that submit the same option with a different value'd hidden input. This is essentially an alternative way of producing a single option with an extra select input. Seems reasonable to support generically so we do that.
There are some forms one could imagine in future (where mutliple overloads for a single decision form have differing sets of hidden input field), but we can …
> Fix further issues supplying a "bandersnatch" value for the Peridot choice

- src/data/statuseffects.txt
- src/net/sourceforge/kolmafia/maximizer/Maximizer.java
- src/net/sourceforge/kolmafia/moods/MoodManager.java
- src/net/sourceforge/kolmafia/moods/MoodTrigger.java
- src/net/sourceforge/kolmafia/objectpool/EffectPool.java
- src/net/sourceforge/kolmafia/objectpool/ItemPool.java
- src/net/sourceforge/kolmafia/objectpool/SkillPool.java
- src/net/sourceforge/kolmafia/request/UneffectRequest.java
- src/net/sourceforge/kolmafia/request/UseSkillRequest.java
- src/net/sourceforge/kolmafia/textui/command/UseSkillCommand.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
- test/net/sourceforge/kolmafia/moods/MoodManagerTest.java
- test/net/sourceforge/kolmafia/request/UseSkillRequestTest.java
- test/net/sourceforge/kolmafia/textui/command/MoodCommandTest.java
- test/net/sourceforge/kolmafia/textui/command/UseSkillCommandTest.java
Replacement for #2881.
Update `cast` to allow `cast SKILL ^ EFFECT` so e.g. `cast Empathy ^ Empathy; cast Empathy ^ Thoughtful Empathy` will allow obtaining both empathy effects.
> feat: update `cast` for replacing / additional buff effects

- src/net/sourceforge/kolmafia/request/FightRequest.java
I noticed some CBB quests weren't being parsed e.g. Iiti Kitty has no article in KoL & thus wasn't matching the regex. Pygmy orderlies article is `some`. Cabinet of Dr. Limpieza & Bubblemint Twins article is `the`
This appears to fix it.
I don't know if this is good regex for this or not because I can't stand regex.
> Handle articles other than a or an in Cookbookbat fight text

- src/net/sourceforge/kolmafia/session/QuestManager.java
Fixes https://kolmafia.us/threads/protonic-accelerator-pack-not-recognizing-new-ghost-location-when-received-while-killing-the-previous-ghost.29285/
> messages about ghosts when busting a ghost are no longer false alarms

- src/net/sourceforge/kolmafia/persistence/AdventureDatabase.java
Ref #2935
Avoid breaking existing scripts using the old location names.
> feat: add old cola wars names as synonyms

- src/net/sourceforge/kolmafia/Modifiers.java
- src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java
- test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
Not sure if we want the &quot;, but that is how ModifierValue works internally at the moment.
> fix: allow parsing multistring modifiers with split_string

- src/net/sourceforge/kolmafia/maximizer/Evaluator.java
- test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Follow-up to #2950; my test passed for unrelated reasons (maximizer will always try to equip something unless you specify `-tie`).
> fix: make maximizing stinky cheese actually work

- src/data/combats.txt
Wiki says 80, LAR data confirms it is definitely above 50, Phill did not hit any NCs when running capped +combat (suggesting it is at least 65). Changing to 80 to coincide with the Wiki but could spade it if needed.
> Fix Sleazy Back Alley combat rate

- src/data/adventures.txt
- src/data/combats.txt
- src/data/encounters.txt
- src/net/sourceforge/kolmafia/persistence/AdventureDatabase.java
- src/net/sourceforge/kolmafia/request/PlaceRequest.java
- src/net/sourceforge/kolmafia/session/BadMoonManager.java
- src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
- src/net/sourceforge/kolmafia/session/LeprecondoManager.java
- test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
- test/net/sourceforge/kolmafia/persistence/AdventureDatabaseTest.java
- test/net/sourceforge/kolmafia/request/PlaceRequestTest.java
Knowing the base game names for locations is useful for the Cookbookbat quest and the Sot's quest.
The Wartime versions (disguised and undisguised) have the same name as the undisguised standard versions, which is unhelpful, so these are left as they are.
> fix: names for base hippy camp, frat house, video game dungeons

- src/net/sourceforge/kolmafia/request/coinmaster/HermitRequest.java
- src/net/sourceforge/kolmafia/textui/command/HermitCommand.java
- test/net/sourceforge/kolmafia/textui/command/HermitCommandTest.java
I had tried using ItemFinder.getFirstMatchingItem(), but that apparently tries to find matching items, independent of the values in the provided source list.
Note that I removed 11-leaf clover from being added to hermitItems with a count of -1 -- nothing seems to rely on this existing. However, the presence of this entry was causing cloverCount() to return -1, which was less than the 0 clovers needed.
> Perform fuzzy matching for hermit CLI command.

- src/net/sourceforge/kolmafia/session/ChoiceManager.java
https://kolmafia.us/threads/mafia-autosells-bar-skins.30629/
It seems that Mafia autosells bar skins via 'Tree's Last Stand' choice 504 in ChoiceManager.java
But bar skins are now more useful to have to create stuff like a barskin loincloth.
This change removes the auto-sell in choiceadv 504.  The user can still do this manually, by setting the choice, or with a choiceadv script.
> do not auto-sell bar skin in choiceadv 504

- src/data/monsters.txt
wire-crossin' elf is nowish not nocopy. We have asked a few times about this elf and been told by dev members this elf is copyable, but not eligible for deck. We can't wish for it like the other quest elves which makes it nowish like them.
> wire-crossin' elf is nowish not nocopy

- src/net/sourceforge/kolmafia/KoLCharacter.java
- src/net/sourceforge/kolmafia/textui/command/AbsorbCommand.java
https://kolmafia.us/threads/gelatinous-noob-modifiers.30637/
Mafia adds McHugeLarge bonuses as 'Outfit' bonuses, but they are not actually outfits in KoL because those bonuses do not apply from that equipment in GN.  This removes McHugeLarge bonuses in GN.
Also, tweak description of the CLI 'absorb' command
> no McHuge mods for Noobs

- src/data/familiars.txt
```
Results for Cooler Yeti after 12 trials using 144 turns:
Cage Match      28      41      57           0            3
Scavenger Hunt  57      45       5           0            1
Obstacle Course 60      56      15           0            1
Hide and Seek   40      55      46           0            2
```
> familiar stats for Cooler Yeti

- src/data/defaults.txt
- src/net/sourceforge/kolmafia/chat/ChatSender.java
Jimmyking asked earlier today if there was a way to shorten that command to something like "/l", but it seemed like there were only three hardcoded commands to use ("/do", "/run", and "/cli"), so I tried to make that possible for people to do without having to compile their own build.
> Allowing for arbitrarily renaming "/cli" chat command

- src/data/combats.txt
- src/data/monsters.txt
Rejection rates are easier to test now that we have the crepe paper parachute cape, e.g.
```js
js var ariz = 0; var swimming = 0; for (var i = 0; i < 1000; i++) {var page = visitUrl("inventory.php?action=parachute&pwd="); if (page.includes("swimming pool monster")) {swimming++}; if (page.includes("Arizona bark scorpion")) {ariz++}; print("ariz=" + ariz + "/" + (i+1)); print("swimming="+swimming + "/" + (i+1));};
```
gives
```
Encounter: Parachute into a Fight
ariz=493/1000
swimming=469/1000
```
and I'm happy to call that 50% each.
For items we have (from Cannonfire):
> Anyway, the sasq watch is just straight uninfluenceable 1/1000.
and reason to think that the other charter rares are similarly pure rejection chance.
Best guesses for new Twitch drops from Nasurte:
> confetti …
> feat: rejection chance for scorpion / pool, best guess for some drops

- src/data/monsters.txt
- src/net/sourceforge/kolmafia/MonsterData.java
- src/net/sourceforge/kolmafia/swingui/MonsterDescriptionFrame.java
- src/net/sourceforge/kolmafia/utilities/GraphicsUtilities.java
Looking at the HTML that KoL generates for an Axis skeleton, I saw this:
```
Axis infantry soldier
<td>
<div id='monpic'>
<div style='width: 100px; height: 100px; position: relative;'>
</div>
</div>
</td>
Axis grenadier skeleton
<td>
<div id='monpic'>
<div style='width: 100px; height: 100px; position: relative;'>
</div>
</div>
</td>
Axis artillery skeleton
<td>
<div id='monpic'>
<div style='width: 100px; height: 100px; position: relative;'>
</div>
</div>
</td>
Axis officer skeleton
<td>
<div id='monpic'>
<div style='width: 100px; height: 100px; position: relative;'>
</div>
</div>
</td>
```
they all have a spine
heads are unique.
arms are either a sword or a bomb
there are a couple of possible legs.
there are 6 images for ribs, and which are included varies per skeleton.
I encoded them in …
> Support for monster images with overlapping .png files

- src/data/familiars.txt
```
Results for Baby Skeleton after 12 trials using 144 turns:
Cage Match      60      37      11           0            1
Scavenger Hunt  52      58      57           0            2
Obstacle Course 55      46       5           0            1
Hide and Seek   27      31      57           0            3
```
> Arena stats for Baby Skeleton

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/Expression.java
- test/net/sourceforge/kolmafia/ExpressionTest.java
- test/net/sourceforge/kolmafia/ModifiersTest.java
- **Add support for advsleft modifier symbol and mods for the unironic knife**
- **Didn't end up using, but might as well keep these eq() and neq() binary fns I added to the modifier language**
> Support unironic knife modifiers

- src/data/items.txt
Trader jar isn't public, but is in the same boat as "pimonkey item", it's in Holder's DC.
> feat: trader jar, unironic knife plural

- build.gradle.kts
Just rewrite them in Kotlin.
`outputs.upToDateWhen { true }` prevented them from running, but even after that was fixed they still didn't work. In lieu of finding out why I just changed them until they did.
> chore: fix clean tasks after migration

- src/data/modifiers.txt
- src/net/sourceforge/kolmafia/objectpool/EffectPool.java
- test/net/sourceforge/kolmafia/DebugModifiersTest.java
Also fix the Mer-kin zone penalties, they are -150% not -200% by the wiki.
Don't have a default penalty, this makes it harder to compare the penalties with the wiki.
> fix: remove zone sea penalty, just have locations

- src/net/sourceforge/kolmafia/request/UseSkillRequest.java
This will drop HP / MP but means that "cast fiesta exit" will always work, which is more valuable.
For restores, keep them non casting.
> feat: if casting a non-restore, allow swapping in equipment

- src/net/sourceforge/kolmafia/KoLCharacter.java
Fixes #2965
I'm really not sure about this, but I was able to see that at various points during the session initialization the totalItems bitmap modifier here is coming through as zero. I even got this crash when I opened the McHugeLarge duffel with Offhand Remarkable active (so with no MHL items equipped). This certainly fixes the problem, but I welcome any insight into why it's happening in the first place.
> Fix offhand remarkable left ski pole TCRS division by zero

- src/net/sourceforge/kolmafia/scripts/git/GitManager.java
Progresses https://kolmafia.us/threads/something-to-automatically-prune-git-history.30897/#post-177670
That thread mentions shallowly fetching as well: I think that's the wrong move, because we *do* want to get all changes after the single commit we have.
This saves ~100MB for me locally.
> feat: shallowly clone installed git repositories

- src/data/equipment.txt
- src/data/items.txt
- src/data/monsters.txt
- src/net/sourceforge/kolmafia/session/ChoiceControl.java
- test/net/sourceforge/kolmafia/session/ChoiceControlTest.java
`_seadentWaveUsed` should be set on successful cast, after the choice adventure.
> fix: `_seadentWaveUsed` should be set on successful cast
