kolmafia/kolmafia

src/data/items.txt, src/data/modifiers.txt
=> feat: add portable Spacegate (open)

src/net/sourceforge/kolmafia/maximizer/CheckedItem.java, src/net/sourceforge/kolmafia/textui/command/FortuneCommand.java, src/net/sourceforge/kolmafia/textui/parsetree/Type.java, src/net/sourceforge/kolmafia/utilities/LockableListFactory.java
License which didn't get deleted in https://github.com/kolmafia/kolmafia/pull/21
=> license which evaded the deletion

src/net/sourceforge/kolmafia/textui/parsetree/AggregateLiteral.java, src/net/sourceforge/kolmafia/textui/parsetree/AggregateType.java, src/net/sourceforge/kolmafia/textui/parsetree/AggregateValue.java, src/net/sourceforge/kolmafia/textui/parsetree/CompositeType.java, src/net/sourceforge/kolmafia/textui/parsetree/CompositeValue.java, src/net/sourceforge/kolmafia/textui/parsetree/RecordType.java, src/net/sourceforge/kolmafia/textui/parsetree/Symbol.java, src/net/sourceforge/kolmafia/textui/parsetree/Type.java
manual reset of https://github.com/kolmafia/kolmafia/pull/11
=> Language Server - parsetree abstracts

src/net/sourceforge/kolmafia/textui/Parser.java, test/net/sourceforge/kolmafia/textui/ParserTest.java
manual reset of https://github.com/kolmafia/kolmafia/pull/10
=> Language Server - parseType records

src/net/sourceforge/kolmafia/textui/Parser.java, test/net/sourceforge/kolmafia/textui/ParserTest.java
manual reset of https://github.com/kolmafia/kolmafia/pull/9
=> Language Server - parseFunction vararg

src/net/sourceforge/kolmafia/textui/Parser.java, test/net/sourceforge/kolmafia/textui/ParserTest.java
reset of https://github.com/kolmafia/kolmafia/pull/7
=> Language Server - parseAggregateLiteral arrays

src/net/sourceforge/kolmafia/textui/Parser.java, test/net/sourceforge/kolmafia/textui/ParserTest.java
manual reset of https://github.com/kolmafia/kolmafia/pull/8
=> Language Server - parseVariable initializations

src/net/sourceforge/kolmafia/textui/AshRuntime.java, src/net/sourceforge/kolmafia/textui/Parser.java, src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, src/net/sourceforge/kolmafia/textui/parsetree/Type.java, src/net/sourceforge/kolmafia/textui/parsetree/Value.java
Convert multiple
"(Type) == (Type)"
into
"(Type).equals( (Type) )"
The resultint logic is the same, as the only Types that were doing that are primitive types, and there's only one instance of each primitive type.
=> Language Server - Type equals Type

src/net/sourceforge/kolmafia/moods/MoodManager.java, src/net/sourceforge/kolmafia/persistence/SkillDatabase.java, src/net/sourceforge/kolmafia/request/HermitRequest.java, src/net/sourceforge/kolmafia/request/UseSkillRequest.java, src/net/sourceforge/kolmafia/session/ResultProcessor.java
Address additional implicit narrowing warnings
=> Implicit Narrowing part 2

build.gradle
ANTLR 3 Runtime 3.4 -> 3.52
FlatLaf 1.5 -> 1.6
FlatlLaf IntelliJ Themes Pack 1.5 -> 1.7
Add Flatlaf SwingX 1.6
JUnit Jupiter API 5.7.1 -> 5.8.0
JUnit Platform Launcher 1.7.2 -> 1.8.0
JUnit Vintage Engine 5.7.1 -> 5.8.0
Java Native Access 5.6.0 -> 5.9.0
Java Native Access Platform 5.6.0 -> 5.9.0
jansi 2.3.2 ->2.3.4
skipped SwingX, because it is causing conflicts with LockableListModel.
working on my system, passing tests.
=> Dependency_Update

.github/workflows/check.yml
Among many other things, thiss will run spotlessCheck to make sure
that code has been properly formatted.
=> Run gradle checks for pull requests.

build.xml
Just a little note in Daily and the description to say "we're done here..."
But nobody is going to see it unless they're already on GitHub.
and feel free to wordsmith this.  It's far from perfect.
=> Deprecating ANT

.github/workflows/check.yml
I didn't use a matrix for this because I thought it was overkill.
=> Test additional java compatibility

src/net/sourceforge/kolmafia/request/BasementRequest.java
Remove cast flagged by security scanning.   Some code cleanup suggested by inspection.  spotlessApply
=> Numeric cast

CONTRIBUTING.md, build.gradle
There's a lot more room for expansion, but I think this is a good
start.
Draft can be seen [here](https://github.com/kolmafia/kolmafia/blob/c3bb2af48b86a5c92b50a1957f6688c738a1d901/CONTRIBUTING.md).
=> Add initial pass of CONTRIBUTING.md.

build.gradle
Veracity reported this breakage.
Clearly I need to expand my pre-commit hook.
=> Fix gradle jar.

build.gradle, lib/net/java/dev/spellcast/utilities/LockableListModel.java, src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java, src/net/sourceforge/kolmafia/swingui/panel/AdventureSelectPanel.java, src/net/sourceforge/kolmafia/swingui/panel/CreateItemPanel.java, src/net/sourceforge/kolmafia/swingui/panel/CreateSpecialPanel.java, src/net/sourceforge/kolmafia/swingui/panel/SynthesizePanel.java, src/net/sourceforge/kolmafia/swingui/panel/UseItemDequeuePanel.java, src/net/sourceforge/kolmafia/swingui/widget/AutoFilterComboBox.java, src/net/sourceforge/kolmafia/swingui/widget/AutoFilterTextField.java, src/net/sourceforge/kolmafia/utilities/InputFieldUtilities.java
This reverts commit 28affc903cf4c8469c09f824bbe27358adbbccd4.
This still has some rough edges wherein it can still experience desync issues, as reported by @Veracity0.
=> Revert "Upgrade swingx to 1.6.1. (#79)"

src/net/sourceforge/kolmafia/request/FightRequest.java
Add some more strings to match against the scrapbook
=> Add some more strings to match against the scrapbook

src/net/sourceforge/kolmafia/KoLmafiaCLI.java, src/net/sourceforge/kolmafia/textui/command/SaberCommand.java, test/net/sourceforge/kolmafia/textui/command/SaberCommandTest.java
Implement a CLI command for upgrading the cosplay saber. Unlike spoon, this one is easy enough to do manually, but convenient to have through Mafia anyway.
=> Add CLI command for upgrading the cosplay saber

src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt
I think this covers everything
=> Add items and effects from November 2021 IotM

src/net/sourceforge/kolmafia/utilities/FileUtilities.java, test/net/sourceforge/kolmafia/utilities/FileUtilitiesTest.java
This plus PR 160 and PR 173 should eliminate the user controlled data in file name flagged by the security scanner.
=> More security

src/net/sourceforge/kolmafia/AdventureResult.java, src/net/sourceforge/kolmafia/persistence/EffectDatabase.java, src/net/sourceforge/kolmafia/persistence/ItemDatabase.java, src/net/sourceforge/kolmafia/persistence/SkillDatabase.java, src/net/sourceforge/kolmafia/request/BatFellowRequest.java, src/net/sourceforge/kolmafia/utilities/StringUtilities.java
Removal of assignments doing nothing.
The source of the existence of these useless assignments is documented in the commits.
=> No-effect-assignments

src/net/sourceforge/kolmafia/AreaCombatData.java, src/net/sourceforge/kolmafia/maximizer/Evaluator.java, src/net/sourceforge/kolmafia/maximizer/Maximizer.java, src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java, src/net/sourceforge/kolmafia/persistence/QuestDatabase.java, src/net/sourceforge/kolmafia/request/AdventureRequest.java, src/net/sourceforge/kolmafia/request/ArcadeRequest.java, src/net/sourceforge/kolmafia/request/FamiliarRequest.java, src/net/sourceforge/kolmafia/request/FightRequest.java, src/net/sourceforge/kolmafia/request/ProfileRequest.java, src/net/sourceforge/kolmafia/request/SushiRequest.java, src/net/sourceforge/kolmafia/session/ChoiceManager.java, src/net/sourceforge/kolmafia/session/EquipmentManager.java, src/net/sourceforge/kolmafia/session/MushroomManager.java, src/net/sourceforge/kolmafia/session/PvpManager.java, src/net/sourceforge/kolmafia/session/VioletFogManager.java, src/net/sourceforge/kolmafia/svn/SVNManager.java, src/net/sourceforge/kolmafia/svn/UpdateRunnable.java, src/net/sourceforge/kolmafia/swingui/TrophyFrame.java, src/net/sourceforge/kolmafia/swingui/panel/ChoiceOptionsPanel.java, src/net/sourceforge/kolmafia/swingui/panel/DailyDeedsPanel.java, src/net/sourceforge/kolmafia/swingui/widget/InterruptableDialog.java, src/net/sourceforge/kolmafia/swingui/widget/ListCellRendererFactory.java, src/net/sourceforge/kolmafia/swingui/widget/TableCellFactory.java, src/net/sourceforge/kolmafia/textui/Parser.java, src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, src/net/sourceforge/kolmafia/textui/command/CliRefCommand.java, src/net/sourceforge/kolmafia/textui/parsetree/ForEachLoop.java, src/net/sourceforge/kolmafia/webui/BarrelDecorator.java, src/net/sourceforge/kolmafia/webui/CharPaneDecorator.java
I can't assert that I definitely got everything; VScode was *really* not cooperative with this...
=> formatting errors caused by end-of-line comments

src/net/sourceforge/kolmafia/swingui/panel/AdventureSelectPanel.java
Deals with raw types in AdventureSelectPanel.
=> AdventureSelectPanel raw types

src/net/sourceforge/kolmafia/swingui/OptionsFrame.java
Deals with the raw types in OptionsFrame.
=> OptionsFrame raw types

src/net/sourceforge/kolmafia/swingui/panel/ChoiceOptionsPanel.java
Deals with (some of) the raw types in ChoiceOptionsPanel.
=> ChoiceOptionsPanel raw types

src/net/sourceforge/kolmafia/swingui/ClanManageFrame.java, src/net/sourceforge/kolmafia/swingui/OptionsFrame.java, src/net/sourceforge/kolmafia/swingui/panel/CardLayoutSelectorPanel.java, src/net/sourceforge/kolmafia/swingui/panel/CreateSpecialPanel.java, src/net/sourceforge/kolmafia/swingui/panel/StatusEffectPanel.java, src/net/sourceforge/kolmafia/swingui/widget/ListCellRendererFactory.java, src/net/sourceforge/kolmafia/utilities/WikiUtilities.java
Raw types whose generic can be guessed from the immediate context.
=> easy raw types

src/net/sourceforge/kolmafia/swingui/panel/DailyDeedsPanel.java, src/net/sourceforge/kolmafia/swingui/widget/DisabledItemsComboBox.java
Adds a generic to DisabledItemsComboBox.
=> DisabledItemsComboBox raw types

src/net/sourceforge/kolmafia/listener/ListenerRegistry.java, src/net/sourceforge/kolmafia/swingui/panel/GenericPanel.java
=> WeakReferences raw type

src/net/sourceforge/kolmafia/textui/Line.java, src/net/sourceforge/kolmafia/textui/Parser.java, test/net/sourceforge/kolmafia/textui/LineTest.java, test/net/sourceforge/kolmafia/textui/ParserTest.java
Exposes and tests the methods that will be used to find the location of the various ParseTreeNodes.
=> Language Server - Expose Location-related methods

src/net/sourceforge/kolmafia/swingui/BuffRequestFrame.java, src/net/sourceforge/kolmafia/swingui/ChatFrame.java, src/net/sourceforge/kolmafia/swingui/ClanManageFrame.java, src/net/sourceforge/kolmafia/swingui/FamiliarTrainingFrame.java, src/net/sourceforge/kolmafia/swingui/ItemManageFrame.java, src/net/sourceforge/kolmafia/swingui/MeatManageFrame.java, src/net/sourceforge/kolmafia/swingui/OptionsFrame.java, src/net/sourceforge/kolmafia/swingui/SkillBuffFrame.java, src/net/sourceforge/kolmafia/swingui/StoreManageFrame.java, src/net/sourceforge/kolmafia/swingui/button/ThreadedButton.java, src/net/sourceforge/kolmafia/swingui/listener/ThreadedListener.java, src/net/sourceforge/kolmafia/swingui/panel/AdventureSelectPanel.java, src/net/sourceforge/kolmafia/swingui/panel/ChoiceOptionsPanel.java, src/net/sourceforge/kolmafia/swingui/panel/CustomCombatPanel.java, src/net/sourceforge/kolmafia/swingui/panel/GenericPanel.java, src/net/sourceforge/kolmafia/swingui/panel/MoodOptionsPanel.java, src/net/sourceforge/kolmafia/swingui/panel/RestoreOptionsPanel.java
This PR *ONLY* adds Generics, and *ONLY* to JComboBoxes (was hard to restrain myself from even just adding generics to other nearby types).
\<?\> for when we can't tell (it's a parameter, and we're just passing it on)
\<String\> for when it's only fed strings (most of them)
\<Object\> for when it's a mix of strings and something else (sadly...)
=> JComboBoxes' raw type

src/net/sourceforge/kolmafia/KoLmafia.java, src/net/sourceforge/kolmafia/textui/parsetree/Catch.java, test/net/sourceforge/kolmafia/extensions/ClearSharedState.java
Discussed elsewhere.  Standardized and made constant, the value that means KoLmafia.lastMessage has no message.
=> Be consistent when resetting lastMessage

src/net/sourceforge/kolmafia/preferences/Preferences.java, src/net/sourceforge/kolmafia/request/LoginRequest.java
Trying to fix security scan by running scan manually before commit
=> Fix scan take 3-1

build.gradle, src/net/sourceforge/kolmafia/textui/parsetree/Command.java, src/net/sourceforge/kolmafia/textui/parsetree/Evaluable.java, src/net/sourceforge/kolmafia/textui/parsetree/Symbol.java, test/net/sourceforge/kolmafia/textui/ParserTest.java, test/net/sourceforge/kolmafia/textui/ScriptData.java
preliminary additions to textui in order to start submitting the other patches
=> Language Server - location tests base

test/net/sourceforge/kolmafia/preferences/PreferencesTest.java
Previous code to clean up state missed this file.  Wanted to fix that before consolidating state cleanup operations.
=> State Cleanup

src/net/sourceforge/kolmafia/textui/parsetree/Value.java
I initially planned to submit all of the Values in the same PR, but I guess it's maybe better to also split those up.
So, this is the same deal as https://github.com/kolmafia/kolmafia/pull/204, with the same promise of closing the TEMPORARY ASAP.
=> Language Server - Locations - Value (preparation)

src/data/monsters.txt
=> Update bar skin drop rate.

src/net/sourceforge/kolmafia/textui/Parser.java, src/net/sourceforge/kolmafia/textui/parsetree/Conditional.java, src/net/sourceforge/kolmafia/textui/parsetree/Else.java, src/net/sourceforge/kolmafia/textui/parsetree/ElseIf.java, src/net/sourceforge/kolmafia/textui/parsetree/If.java, test/net/sourceforge/kolmafia/textui/parsetree/ConditionalTest.java
Because we refer to If for conditional chains, it is the one to have the location of the whole chain.
I'd rather prefer if we had another way to group them, because it means we can't access the location of the first If anymore...
=> Language Server - Locations - Conditional

src/net/sourceforge/kolmafia/textui/Parser.java, src/net/sourceforge/kolmafia/textui/parsetree/Value.java, test/net/sourceforge/kolmafia/textui/parsetree/StringTest.java
=> Language Server - Locations - Value - String

src/net/sourceforge/kolmafia/textui/Parser.java, src/net/sourceforge/kolmafia/textui/parsetree/RecordInitializer.java, test/net/sourceforge/kolmafia/textui/parsetree/ConditionalTest.java, test/net/sourceforge/kolmafia/textui/parsetree/JavaForLoopTest.java, test/net/sourceforge/kolmafia/textui/parsetree/RecordValueTest.java, test/net/sourceforge/kolmafia/textui/parsetree/SwitchTest.java, test/net/sourceforge/kolmafia/textui/parsetree/VariableReferenceTest.java
This is the last PR that can be isolated from what's left.
The rest will be submitted all at once.
=> Language Server - Locations - Implicit values

src/net/sourceforge/kolmafia/swingui/ClanManageFrame.java, src/net/sourceforge/kolmafia/swingui/CoinmastersFrame.java, src/net/sourceforge/kolmafia/swingui/DatabaseFrame.java, src/net/sourceforge/kolmafia/swingui/FaxRequestFrame.java, src/net/sourceforge/kolmafia/swingui/ItemManageFrame.java, src/net/sourceforge/kolmafia/swingui/MallSearchFrame.java, src/net/sourceforge/kolmafia/swingui/MaximizerFrame.java, src/net/sourceforge/kolmafia/swingui/MuseumFrame.java, src/net/sourceforge/kolmafia/swingui/SkillBuffFrame.java, src/net/sourceforge/kolmafia/swingui/StoreManageFrame.java, src/net/sourceforge/kolmafia/swingui/panel/CreateItemPanel.java, src/net/sourceforge/kolmafia/swingui/panel/CreateSpecialPanel.java, src/net/sourceforge/kolmafia/swingui/panel/InventoryPanel.java, src/net/sourceforge/kolmafia/swingui/panel/ItemListManagePanel.java, src/net/sourceforge/kolmafia/swingui/panel/ItemManagePanel.java, src/net/sourceforge/kolmafia/swingui/panel/ItemTableManagePanel.java, src/net/sourceforge/kolmafia/swingui/panel/MoodOptionsPanel.java, src/net/sourceforge/kolmafia/swingui/panel/OverlapPanel.java, src/net/sourceforge/kolmafia/swingui/panel/PulverizePanel.java, src/net/sourceforge/kolmafia/swingui/panel/RestorativeItemPanel.java, src/net/sourceforge/kolmafia/swingui/panel/ScrollableFilteredPanel.java, src/net/sourceforge/kolmafia/swingui/panel/StatusEffectPanel.java, src/net/sourceforge/kolmafia/swingui/panel/UseItemDequeuePanel.java, src/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanel.java, src/net/sourceforge/kolmafia/swingui/panel/UseItemPanel.java, src/net/sourceforge/kolmafia/swingui/widget/GenericScrollPane.java, src/net/sourceforge/kolmafia/swingui/widget/ShowDescriptionList.java
I mean... it "started" with ShowDescriptionList, but then, with how a lot of classes have parents, and childs, etc...
...TL;DR, this affects ShowDescriptionList, ItemListManagePanel, ItemManagePanel and ItemTableManagePanel.
=> ShowDescriptionList raw types

src/net/sourceforge/kolmafia/swingui/menu/BookmarkMenu.java, src/net/sourceforge/kolmafia/swingui/menu/MenuItemList.java, src/net/sourceforge/kolmafia/swingui/menu/ScriptMenu.java, src/net/sourceforge/kolmafia/swingui/menu/WindowMenu.java
Adds a generic to MenuItemList
=> MenuItemList raw types

test/net/sourceforge/kolmafia/request/RequestTestBase.java
Adds utilities to make redirections with RequestTestBase
Also makes RequestTestBase public, because request handling is most likely to be need more or less everywhere, and it shouldn't all go in the same folder...
=> RequestTestBase redirections

src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
See https://kolmafia.us/threads/well_stocked-ash-function.26815/
boolean well_stocked(item, quantity, price)
Answers the question "can I get quantity of item spending no more than price for the last item?"
I'm not convinced I am handling and checking parameters in the best way and I have done nothing about testing.
Test script requires a logged in character so....
Spotless decided it wanted to rearrange some imports or my IDE wildcarded them and spotless doesn't care either way.
=> well_stocked

src/net/sourceforge/kolmafia/moods/HPRestoreItemList.java, src/net/sourceforge/kolmafia/moods/MPRestoreItemList.java, src/net/sourceforge/kolmafia/swingui/ItemManageFrame.java, src/net/sourceforge/kolmafia/swingui/panel/ChoiceOptionsPanel.java, src/net/sourceforge/kolmafia/swingui/panel/CustomCombatPanel.java
saying that a class implements an interface when a parent already does it does nothing.
=> remove redundant superinterfaces

src/net/sourceforge/kolmafia/persistence/ConsumablesDatabase.java
I was ready for this to take time, but then I realized that it was just the equivalent of a bitmap...
=> Raw arrays - ConsumablesDatabase

src/net/sourceforge/kolmafia/swingui/BuffBotFrame.java, src/net/sourceforge/kolmafia/swingui/FaxRequestFrame.java, src/net/sourceforge/kolmafia/swingui/ItemManageFrame.java, src/net/sourceforge/kolmafia/swingui/MaximizerFrame.java, src/net/sourceforge/kolmafia/swingui/MuseumFrame.java, src/net/sourceforge/kolmafia/swingui/OptionsFrame.java, src/net/sourceforge/kolmafia/swingui/StoreManageFrame.java, src/net/sourceforge/kolmafia/swingui/panel/CustomCombatPanel.java, src/net/sourceforge/kolmafia/swingui/panel/ItemListManagePanel.java, src/net/sourceforge/kolmafia/swingui/panel/ItemManagePanel.java, src/net/sourceforge/kolmafia/swingui/panel/ItemTableManagePanel.java, src/net/sourceforge/kolmafia/swingui/panel/MoodOptionsPanel.java, src/net/sourceforge/kolmafia/swingui/panel/PulverizePanel.java, src/net/sourceforge/kolmafia/swingui/panel/ScrollableFilteredPanel.java, src/net/sourceforge/kolmafia/swingui/panel/ScrollablePanel.java, src/net/sourceforge/kolmafia/swingui/panel/StatusEffectPanel.java
passes the type of ScrollablePanel.scrollComponent as a type parameter.
=> ScrollablePanel raw types

src/net/sourceforge/kolmafia/chat/ChatManager.java
I've been thinking about https://github.com/kolmafia/kolmafia/pull/148#issuecomment-949555223 for a while, and decided to finally apply it (split between the next few PRs)
They replace arrays of classes with a type parameter with ArrayLists.
=> Raw arrays - ChatManager

src/net/sourceforge/kolmafia/textui/Parser.java, test/net/sourceforge/kolmafia/textui/ParserTest.java, test/net/sourceforge/kolmafia/textui/ScriptData.java
I hate having to do this -- that is, having to match the location part as a String, but that's how the full ScriptException is passed right now, so I guess we have to, for now...
=> Language Server - error locations preparations

src/net/sourceforge/kolmafia/textui/Parser.java, test/net/sourceforge/kolmafia/textui/parsetree/TypeDefTest.java
Also puts the addition of the new type in the only condition that doesn't throw an error, rather than outside the conditionals
=> Language Server - error locations - TypeDef

src/net/sourceforge/kolmafia/textui/Parser.java, test/net/sourceforge/kolmafia/textui/parsetree/FunctionReturnTest.java, test/net/sourceforge/kolmafia/textui/parsetree/UserDefinedFunctionTest.java
Also puts the addition of the parameters to the parameter list slightly earlier (at the very start of the only condition that doesn't throw an error)
=> Language Server - error locations - Function

src/data/classskills.txt, src/data/equipment.txt, src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/spleenhit.txt, src/data/statuseffects.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/CampgroundRequest.java, src/net/sourceforge/kolmafia/session/ChoiceManager.java
Also register the cabinet as a workshed item
=> Item support for the cold medicine cabinet

src/net/sourceforge/kolmafia/textui/Parser.java, test/net/sourceforge/kolmafia/textui/parsetree/PluralValueTest.java, test/net/sourceforge/kolmafia/textui/parsetree/TypedValueTest.java
The last one!
Additionally, no longer bother trying to find a type matching the value of the current token if the current token isn't even an identifier
=> Language Server - error locations - TypedValue

src/data/defaults.txt, src/net/sourceforge/kolmafia/swingui/widget/RequestPane.java
This seems to fix some reported user issues (`<pre>` tags not working,
font colors not respecting LAF settings), while keeping text wrapping
in the CLI.
=> Wrap InlineView instead of LabelView.

data/SVN/svnrepo.json
https://github.com/libraryaddict/KolAccountVal/
=> Add my script "AccountVal"

src/net/sourceforge/kolmafia/RequestThread.java, src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java
As far as I can see runtime changed from 2-3 hours to 5 minutes per seed
=> TCRS derive now runs in parallel

src/net/sourceforge/kolmafia/KoLmafiaCLI.java, src/net/sourceforge/kolmafia/textui/command/GuzzlrCommand.java, test/net/sourceforge/kolmafia/textui/command/GuzzlrCommandTest.java
Another CLI command that's useful to me personally. Includes a test.
=> Add CLI command for the guzzlr tablet

src/net/sourceforge/kolmafia/swingui/DatabaseFrame.java, src/net/sourceforge/kolmafia/swingui/ScriptManageFrame.java, src/net/sourceforge/kolmafia/swingui/StoreManageFrame.java, src/net/sourceforge/kolmafia/swingui/panel/ItemTableManagePanel.java, src/net/sourceforge/kolmafia/swingui/widget/ShowDescriptionTable.java
The generic still needs to be applied to its `getSelectedValues` method, but this will be done in a separate step, as it looks like the changes needed will be rather massive (lots of transitions from arrays to lists)
=> add a generic to ShowDescriptionTable

src/net/sourceforge/kolmafia/AreaCombatData.java
come on, now, let's not regress... :p
=> AreaCombatData raw types

src/net/sourceforge/kolmafia/moods/ManaBurn.java, test/net/sourceforge/kolmafia/moods/ManaBurnTest.java
=> coverage++ ManaBurn

src/net/sourceforge/kolmafia/objectpool/SkillPool.java, src/net/sourceforge/kolmafia/session/ResponseTextParser.java
Fixes https://kolmafia.us/threads/aosp-hard-drinker-10-liver-doesnt-register-when-acquired.26890/ because it was parsing the wrong Hard Drinker skill
=> Parse new skills by id instead of name where possible

src/net/sourceforge/kolmafia/webui/CharPaneDecorator.java, test/net/sourceforge/kolmafia/webui/CharPaneDecoratorTest.java, test/root/request/test_charpane_basic.html, test/root/request/test_charpane_basic_decorated_effects.html, test/root/request/test_charpane_compact.html, test/root/request/test_charpane_compact_decorated_effects.html
Previous fix put some parentheses in the wrong place. 
Now we have tests for `decorateEffects` in both basic and compact mode
=> Move incorrectly placed parens in CharPaneDecorator

src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt
First pull request, apologies if it isn't right
=> Add Crimbo 21 Items and Effects

src/data/fullness.txt, src/data/items.txt, src/data/npcstores.txt, src/net/sourceforge/kolmafia/RequestLogger.java, src/net/sourceforge/kolmafia/request/Crimbo21TreeRequest.java, src/net/sourceforge/kolmafia/request/NPCPurchaseRequest.java, src/net/sourceforge/kolmafia/session/ResponseTextParser.java
- NPC Stores
- New food item
- Decrementing items you put on the christmas tree
- Items that are in items.txt but not in npcstores.txt will still generate "learned a new npc store item" gcli output
=> More Crimbo 2021 support

test/net/sourceforge/kolmafia/AreaCombatDataTest.java
The test leaves a queue file behind.  Not any more.
=> AreaCombatDataTest cleanup

src/net/sourceforge/kolmafia/KoLConstants.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/webui/CharPaneDecorator.java
Show camel spit charge and estimated turns remaining in the charpane and compactsidepane
=> Decorate with camel spit data

src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java, src/net/sourceforge/kolmafia/request/NPCPurchaseRequest.java
Fixes a bug I introduced in https://github.com/kolmafia/kolmafia/pull/356
=> Do not output lines for coinmasters.txt when they either already exist or can't exist

src/data/defaults.txt, src/net/sourceforge/kolmafia/KoLAdventure.java, src/net/sourceforge/kolmafia/objectpool/AdventurePool.java, src/net/sourceforge/kolmafia/request/AdventureRequest.java
Also mention it in CLI failures when they show
=> Track cold resistance required by the site alpha dormitory

src/net/sourceforge/kolmafia/KoLAdventure.java
The first time you try to adventure in the Site Alpha locations, if you have insufficient cold resistance, it says:
The extreme cold makes it impossible for you to continue...
[5 Cold Resistance Required]
Once you have adventured successfully, when the required cold resistance increases, it says:
It's getting colder! Better bundle up.
[5 Cold Resistance Required]
We already had support for the latter message, but not the original message.
The request adds support for the initial message.
=> Additional cold resistance message

src/net/sourceforge/kolmafia/request/MallPurchaseRequest.java, src/net/sourceforge/kolmafia/request/MallSearchRequest.java
Irrat pointed out I wanted "\\s*,\\s*" in my regexps for parsing forbiddenStores property. Thanks.
Use the new MallPurchaseRequest.getForbiddenStores method in MallSearchRequest
=> use getForbiddenStores in MallPurchaseRequest. Fix typo

src/net/sourceforge/kolmafia/persistence/AdventureDatabase.java, src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java, src/net/sourceforge/kolmafia/session/ChoiceManager.java, src/net/sourceforge/kolmafia/swingui/panel/AddCustomDeedsPanel.java, src/net/sourceforge/kolmafia/swingui/widget/AutoFilterTextField.java
I've run through and removed some string comparisons that use == instead of String.equals
=> <string> == <string>

src/net/sourceforge/kolmafia/request/NPCPurchaseRequest.java
Fixes https://kolmafia.us/threads/nash-crosbys-still-buy-1-bottle-of-definit-row270.27000/
=> Cater for shops that have mixed currencies within the store, but only one currency per row

src/net/sourceforge/kolmafia/request/MallPurchaseRequest.java
* Slight cleanup of code
* Don't use string.valueof when its an int hashset
* Make sure it's a number before we parse the number
=> Fix up forbidden store stuff

src/data/adventures.txt, src/data/combats.txt, src/data/monsters.txt
Site Alpha Quarry contains gooified rock slabs and gives gooified mineral matter and gooified animal matter
=> Site Alpha Quarry and gooified rock slab

src/data/adventures.txt, src/data/combats.txt, src/data/inebriety.txt, src/data/items.txt, src/data/monsters.txt, src/net/sourceforge/kolmafia/request/PlaceRequest.java
Add [experimental crimbo booze]
Log visits to place.php?whichplace=northpole
(Why is the list of changed files including my Site Alpha Quarry  changes? Those were on a completely different branch and are now merged and accepted)
=> Experimental booze

src/net/sourceforge/kolmafia/request/MallPurchaseRequest.java
Seriously. A single character change.
=> add missing space to a regexp

src/data/modifiers.txt, src/data/statuseffects.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/session/ChoiceManager.java
food takes animal matter, booze takes vegetable manner, drugs take mineral matter
experimental crimbo spleen item gives Festively Experimented-Upon
=> deduct gooified matter cost when purchasing experimental items

src/data/classskills.txt, src/data/defaults.txt, src/data/equipment.txt, src/data/familiars.txt, src/data/fullness.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt, src/net/sourceforge/kolmafia/RequestEditorKit.java, src/net/sourceforge/kolmafia/request/PlaceRequest.java, src/net/sourceforge/kolmafia/session/ChoiceManager.java
Added Crimbo Toy Lab
Configured Choice Spoilers and material consumption to choice options
Added new advent calendar item
Ran "checkpowers" and fixed a bunch of accessory powers
ChoiceAdventure configuration contains a "zone", not an "adventure location" as its first argument. I fixed a bunch
=> Crimbo toy lab

src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt
Fix powers of various Crimbo 21 items.
boxed gumball machine -> meatball machine
the Crymbich Manuscript -> the Crymbich Manuscript (used)
=> Crimbo 21 items

src/data/items.txt
Item 10877. Obtained by using a cloning kit successfully.
=> Add cloned monster

src/data/dailylimits.txt, src/data/defaults.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, src/net/sourceforge/kolmafia/session/BreakfastManager.java
Meatball machine is usable once per day. Add it to breakfast.
=> feat: use meatball machine in breakfast

src/net/sourceforge/kolmafia/request/PurchaseRequest.java
Player run store
> Purchasing BACON (5 @ 100 = 500) from #3272033...
NPC store
> Purchasing chewing gum on a string (2 @ 47 = 94)...
=> On purchase, include player id, and total cost in the CLI message

src/data/dailylimits.txt, src/data/defaults.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, src/net/sourceforge/kolmafia/session/BreakfastManager.java
Refurbished air fryer is usable once per day. Add it to breakfast.
=> feat: add air fryer to breakfast

src/data/items.txt, src/data/modifiers.txt, src/data/spleenhit.txt, src/data/statuseffects.txt
You get fried air from your refurbished air fryer - which is a reusable item
=> Add fried air item and Well-Ventilated effect

src/net/sourceforge/kolmafia/request/UneffectRequest.java
In particular:
Deadly Lampblade
Rolando's Rondo of Resisto
Dirge of Dreadfulness (Remastered)
=> Some songs are not AT skills but are still shruggable

src/net/sourceforge/kolmafia/KoLmafiaASH.java, src/net/sourceforge/kolmafia/textui/AshRuntime.java, src/net/sourceforge/kolmafia/textui/NamespaceInterpreter.java, src/net/sourceforge/kolmafia/textui/Parser.java
and have the modification timestamp as a field
=> Language Server - Map<File, Parser> imports

src/data/statuseffects.txt
Not used for anything to my knowledge, was wishable.
Taken from https://kolmafia.us/threads/kol-just-broke-transcendent-olfaction.27067/.
=> feat: add new On the Trail effect.

src/data/monsters.txt
After the SR changes.
All drops are 5%.
=> feat: miniature boiler drops from monstrous boiler

src/data/defaults.txt, src/net/sourceforge/kolmafia/KoLAdventure.java, src/net/sourceforge/kolmafia/KoLmafia.java, src/net/sourceforge/kolmafia/RequestEditorKit.java, src/net/sourceforge/kolmafia/objectpool/EffectPool.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/persistence/AdventureDatabase.java, src/net/sourceforge/kolmafia/persistence/CoinmastersDatabase.java, src/net/sourceforge/kolmafia/request/GenericRequest.java, src/net/sourceforge/kolmafia/request/HermitRequest.java, src/net/sourceforge/kolmafia/request/RelayRequest.java, src/net/sourceforge/kolmafia/session/BreakfastManager.java, src/net/sourceforge/kolmafia/session/InventoryManager.java, src/net/sourceforge/kolmafia/session/ResultProcessor.java, src/net/sourceforge/kolmafia/swingui/OptionsFrame.java, src/net/sourceforge/kolmafia/swingui/menu/LootHermitMenuItem.java, src/net/sourceforge/kolmafia/textui/command/HermitCommand.java
The Hermit has 11-leaf clovers. The "hermit" command and menu item will fetch those, as will breakfast.
Do not search for disappearing clover messages. Do not worry about protecting ten-leaf clovers.
=> remove the concept of clover protection. Hermit has 11-leaf clovers

src/data/defaults.txt, src/net/sourceforge/kolmafia/KoLCharacter.java, src/net/sourceforge/kolmafia/persistence/CoinmastersDatabase.java, src/net/sourceforge/kolmafia/request/ClanLoungeRequest.java, src/net/sourceforge/kolmafia/request/EatItemRequest.java, src/net/sourceforge/kolmafia/request/GenericRequest.java, src/net/sourceforge/kolmafia/request/RelayRequest.java, src/net/sourceforge/kolmafia/session/ChoiceManager.java, src/net/sourceforge/kolmafia/session/EncounterManager.java, src/net/sourceforge/kolmafia/session/InventoryManager.java, src/net/sourceforge/kolmafia/session/ValhallaManager.java, src/net/sourceforge/kolmafia/textui/command/ShowDataCommand.java, test/root/expected/get_counter.txt.out
This removes the three properties - lastSemirareReset, semiRareCounter, semirareLocation - as well as the "Fortune Cookie" counter.
This is essentially a subset of gausie's mega-PR which deals with the Lucky! intrinsic.
=> Remove fortune cookie counters and semirare tracking

src/data/classskills.txt, src/data/equipment.txt, src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/monsters.txt, src/data/statuseffects.txt
cosmic bowling ball + new combat skills + effect
cursed magnifying glass + monsters + item drops + consumables + effects
=> New items, effects, skills, monsters for IOTM and IOTY

build.gradle
v1.7.14 released, ready to merge!
-----
I've been running RC1 since it was released without an issue. This branch is for people to try out the same if they like.
Once 1.7.14 final is released, I'll update this branch and we can merge.
Milestone for reference: https://github.com/mozilla/rhino/milestone/14
=> Rhino v1.7.14

src/data/classskills.txt, src/data/equipment.txt, src/data/modifiers.txt, src/data/outfits.txt
The loofah and flagstone items are implemented.
The combat skills granted by loofah and flagstone items are no public.
=> 2022 Standard outfits and reward-granted skills

src/data/fullness.txt, src/data/inebriety.txt
=> preliminary consumption stats for void stuff and Doc's wines

build.gradle
Should work by https://github.com/ajoberstar/grgit/issues/334.
=> build: update grgit one patch version to possibly avoid the jcenter brownout

src/net/sourceforge/kolmafia/session/HeistManager.java, src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, src/net/sourceforge/kolmafia/textui/command/HeistCommand.java, test/net/sourceforge/kolmafia/session/HeistManagerTest.java, test/net/sourceforge/kolmafia/textui/command/HeistCommandTest.java
Another follow-up to #468.
I suspect there must be a function somewhere that can correctly parse "334 scroll" and "12 Purple Beast", but I couldn't find it and wrote my own.
=> Add commands for heisting multiple items at once

data/SVN/svnrepo.json, src/net/sourceforge/kolmafia/KoLmafiaCLI.java, src/net/sourceforge/kolmafia/persistence/DebugDatabase.java, src/net/sourceforge/kolmafia/textui/command/CheckDataCommand.java, test/net/sourceforge/kolmafia/persistence/DebugDatabaseTest.java, test/net/sourceforge/kolmafia/textui/command/CheckDataCommandTest.java
Looks at the files in the local repo and flags likely duplicates when they are copied to KoLmafia's directories.
Update svnrepo.json for two scripts that have moved to GitHub.  Might require delete and reinstall for users of the SourceForge version if they want updates.
Figured out how to Mock file system access.  This works but much room for improvement.
=> checkrepo command

src/net/sourceforge/kolmafia/maximizer/Evaluator.java, src/net/sourceforge/kolmafia/maximizer/Maximizer.java, test/internal/helpers/Player.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
More maximizer tests, mostly for bees.
=> tests: add maximizer tests for bees

src/net/sourceforge/kolmafia/request/FightRequest.java
Add missing messages for scrapbook, both collecting and tracking of the banish.
=> Scrapbook text

data/SVN/svnrepo.json, src/net/sourceforge/kolmafia/persistence/ScriptManager.java
What it says.
Also, fixed a typo in the description of another script.
And moved a comment.
=> Add combo to script repository file

src/net/sourceforge/kolmafia/textui/command/ShopCommand.java, test/net/sourceforge/kolmafia/extensions/ClearSharedStateAfter.java, test/net/sourceforge/kolmafia/textui/command/ShopCommandTest.java
Test for ShopCommand
Delete a file that leaks from a currently disabled test.
I think there is an error with "reprice d20 @ 1,333 limit 1" that results in a repriced item with no limit.  I will look at that later.
=> ShopCommandTest

src/net/sourceforge/kolmafia/textui/Parser.java
=> Tidy up loop design from #429

src/data/maximizer-help.html, src/net/sourceforge/kolmafia/maximizer/Evaluator.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Further maximizer tests, add some help about previously undocumented keywords.
=> tests: add tests for plumber keywords, add help

src/net/sourceforge/kolmafia/textui/parsetree/BasicScope.java
=> BasicScope obsolete comments

src/net/sourceforge/kolmafia/utilities/WikiUtilities.java
Fixes https://kolmafia.us/threads/drippy-plum-doesnt-correctly-link-to-the-wiki.27146/
=> Handle wiki links with question marks

src/net/sourceforge/kolmafia/request/FightRequest.java
Not at start of fight
Fixes: https://kolmafia.us/threads/force-use-should-not-increment-stinky-cheese-pantsgiving-counters.27153/
=> Increment stinky cheese and pantsgiving on fight completion

src/net/sourceforge/kolmafia/textui/Parser.java
Ran the IntelliJ static analyzer in hopes that reviewing Parser in the future would be easier.  There are several things that can be removed - notably empty conditionals - but I tried to err on the side of being a work in progress.
=> "lint" removal from Parser.java

src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java, test/net/sourceforge/kolmafia/utilities/WikiUtilitiesTest.java
And lo! I found a bug and fixed it
=> Add a few tests for WikiUtilities

src/net/sourceforge/kolmafia/VYKEACompanionData.java, src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java, test/net/sourceforge/kolmafia/CustomScriptTest.java
I wrote a test for this and then fixed the failing types
=> Enumerated types shoud be case insensitive

src/net/sourceforge/kolmafia/session/ChoiceManager.java
Fake blood has changed from a semi-rare to a NC choice, so add relay hints for it.
=> feat: add relay hints for fake blood

test/net/sourceforge/kolmafia/textui/langserver/StateCheckWrappersTest.java
This should resolve the issue noted in #482 whereby the test log gets flooded with exception logs that do not indicate test failure
=> Disable logging during testing StateCheckWrappers

test/net/sourceforge/kolmafia/request/FightRequestTest.java
Annotated reasons why other tests aren't working.  Action to address would be get some HTML of the Commerce Ghost acting, but I don't have one so...
Using the debugger shows that the minimal response text does not trigger the processing that would look for Ghost action.
Also lint on the test.
=> Enabled one disabled test because it now works.

src/net/sourceforge/kolmafia/request/StorageRequest.java
Everything seems to suggest that its just my computer on which this fails? Because this function is covered by the tests. But still, I need this fix to run mafia now.
=> Fix isEmpty() not a method on StringBuilders

test/internal/helpers/Cleanups.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Make the try-with-resources approach easier to copy between tests.
Add some tests for hobo power.
=> tests: cleanup try-with-resources, add hobo power test

src/net/sourceforge/kolmafia/maximizer/CheckedItem.java, src/net/sourceforge/kolmafia/persistence/NPCStoreDatabase.java, src/net/sourceforge/kolmafia/request/NPCPurchaseRequest.java, src/net/sourceforge/kolmafia/session/ResultProcessor.java, src/net/sourceforge/kolmafia/swingui/MaximizerFrame.java, src/net/sourceforge/kolmafia/swingui/menu/PartialMRUList.java, src/net/sourceforge/kolmafia/swingui/menu/ScriptMRUList.java, test/internal/helpers/Maximizer.java, test/net/sourceforge/kolmafia/maximizer/MaximizerCreatableTest.java
Tests are in their own file because the setup is completely different for testing creatables.
Includes one disabled test to do with meat pasting. I don't see why it doesn't work, so comments appreciated. I had added it as a "basic" test for creatables, but couldn't get it to work.
=> Prevent buying two oversized sparklers in the Maximizer

src/net/sourceforge/kolmafia/persistence/MallPriceDatabase.java, src/net/sourceforge/kolmafia/textui/DataFileCache.java, src/net/sourceforge/kolmafia/textui/command/TestCommand.java
Fix potentially unclosed things reported by SpotBugs.
=> fix: ensure resources are closed

src/data/modifiers.txt, src/net/sourceforge/kolmafia/KoLmafia.java, src/net/sourceforge/kolmafia/request/CharPaneRequest.java, src/net/sourceforge/kolmafia/request/MallPurchaseRequest.java, test/net/sourceforge/kolmafia/request/MallPurchaseRequestTest.java
Both KoLmafia.makePurchase (and therefore the "buy" command) need to understand that. Otherwise, they will believe you've not succeeded in purchasing a free pull item.
Also, the industrial fire extinguisher is not a Free Pull - although the packaged (not-yet-bound) IOTM is a free pull.
=> purchasing a free pull item when you cannot interact leaves it on the freepulls list

src/net/sourceforge/kolmafia/utilities/ChoiceUtilities.java
As seen in the "choice" command.
```
> choice
choice 1: (secret choice)
  select = mid (1 options)
    472 => cavewomyn hippy
```
=> choice 'select' arguments are different in the locket

src/net/sourceforge/kolmafia/session/BanishManager.java, test/net/sourceforge/kolmafia/session/BanishManagerTest.java
I want to refactor BanishManager, so here are some tests for it to make sure nothing breaks.
=> Add full testing suite for BanishManager

src/data/monsters.txt
https://kol.coldfront.net/thekolwiki/index.php/Blind_snake
This thing.
=> feat: add blind snake

src/net/sourceforge/kolmafia/swingui/panel/DailyDeedsPanel.java, test/internal/helpers/Player.java, test/net/sourceforge/kolmafia/swingui/panel/DailyDeedsPanelTest.java
Add tests for the daily deeds panel free fight labels.
Add some more sources: lynyrds, kramco, glitch monster, piranha plant, void monsters.
Add NEP if you have access today.
=> More daily free fights

test/internal/helpers/Player.java, test/net/sourceforge/kolmafia/maximizer/MaximizerCreatableTest.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Have to refresh concoctions after the items are in inventory.
Also make some progress on the hollow issue: works if some Smithsness is already present.
=> Unignore asshat test

src/data/monsters.txt
=> feat: pig is nocopy

src/data/inebriety.txt, src/data/modifiers.txt, src/net/sourceforge/kolmafia/persistence/DebugDatabase.java, src/net/sourceforge/kolmafia/utilities/WikiUtilities.java
Simplify the wiki name lookup by using `modifiers.txt`
Share Http Clients between calls where reasonable.
Delete commented out code.
Also mark "bad rum and good cola" as giving the effect it gives, instead of the effect the description says it gives. There's a note in `items.txt` about this.
=> Wiki check improvements

src/data/monsters.txt
Information mostly from Yendor at
https://kolmafia.us/threads/feb-2022-iotm-combat-lovers-locket.27258/page-2#post-167228
=> Add NOCOPY to Manuel monsters, and a few I fought myself.

src/net/sourceforge/kolmafia/request/GenericRequest.java
Clean up the easy warnings IntelliJ warns about.
=> chore: lint generic request

src/net/sourceforge/kolmafia/maximizer/Evaluator.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
From https://kolmafia.us/threads/maximizer-doesnt-like-outfits-with-weapons.27415/, add a test featuring an outfit without a weapon, which works.
=> tests: outfit without weapon

src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/net/sourceforge/kolmafia/Modifiers.java
This adds the Mr. Store item, what it becomes, and a new "Monster Level Percent" modifier.
I will not be doing more for this for days, at best, so if anybody wants to make UmbrellaRequest and UmbrellaCommand (a la SaberRequest/Command), please do. :)
=> beginning of unbreakable umbrella support

src/data/defaults.txt, src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/net/sourceforge/kolmafia/AdventureResult.java, src/net/sourceforge/kolmafia/KoLmafia.java, src/net/sourceforge/kolmafia/KoLmafiaCLI.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/persistence/ItemDatabase.java, src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java, src/net/sourceforge/kolmafia/request/UmbrellaRequest.java, src/net/sourceforge/kolmafia/session/ChoiceManager.java, src/net/sourceforge/kolmafia/session/InventoryManager.java, src/net/sourceforge/kolmafia/session/ResponseTextParser.java, src/net/sourceforge/kolmafia/textui/command/UmbrellaCommand.java, test/net/sourceforge/kolmafia/textui/command/SaberCommandTest.java, test/net/sourceforge/kolmafia/textui/command/UmbrellaCommandTest.java
This more or less apes the Saber code beat-for-beat. I hope that, at the very least, this is of use to someone.
=> Additional Umbrella Implementation

src/net/sourceforge/kolmafia/request/TransferItemRequest.java, test/net/sourceforge/kolmafia/textui/command/ClosetCommandTest.java
Add tests. Use the fake HTTP client to detect whether a request was sent and what it was.
=> fix: don't closet zero items

src/net/sourceforge/kolmafia/request/FightRequest.java
Update the regex pattern to acknowledge only a single drone bit flying off
=> Handle singular drone message

src/net/sourceforge/kolmafia/session/BastilleBattalionManager.java, test/net/sourceforge/kolmafia/session/BastilleBattalionManagerTest.java
This explains the seeming 1 pixel discrepancy in the PA needle.
=> All murder holes provide one more PA than calculated

src/net/sourceforge/kolmafia/request/AutoSellRequest.java, src/net/sourceforge/kolmafia/request/ClosetRequest.java, src/net/sourceforge/kolmafia/request/TransferItemRequest.java, src/net/sourceforge/kolmafia/session/ResponseTextParser.java, src/net/sourceforge/kolmafia/textui/command/HeistCommand.java, test/net/sourceforge/kolmafia/textui/command/AutoSellCommandTest.java, test/net/sourceforge/kolmafia/textui/command/ClosetCommandTest.java
Many CLI commands parse an item list and need to handle the zero case specially. Here's autosell.
Follow-up to #699.
=> Don't send a request when autoselling zero items

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/BrogurtRequest.java, src/net/sourceforge/kolmafia/request/TacoDanRequest.java, test/net/sourceforge/kolmafia/CoinmasterRegistryTest.java
https://kolmafia.us/threads/mafia-tries-to-buy-brogurt-from-coinmaster-when-unable.27483/
=> add quest checks for brogurt and taco dan coinmasters

src/net/sourceforge/kolmafia/request/CampgroundRequest.java, test/net/sourceforge/kolmafia/request/CampgroundRequestTest.java, test/root/request/test_campground_medicine_cabinet_out_of_consults.html
https://kolmafia.us/threads/getworkshed-returns-none-when-out-of-cmc-consults.27226/
Right now, mafia has a little bit of trouble tracking the Cold Medicine Cabinet when you don't have an active consult available upon logging in. This (hopefully) fixes that, by allowing it to read messages when the CMC's image is not present.
I wasn't quite sure where to put this test, and it may need a test for other behavior. but it sure as heck needs this one!
=> better cold medicine cabinet tracking

test/net/sourceforge/kolmafia/request/CampgroundRequestTest.java, test/net/sourceforge/kolmafia/request/MallSearchRequestTest.java, test/net/sourceforge/kolmafia/session/EquipmentManagerTest.java
Correct tests with no package or package not corresponding to file path.
=> fix: wrong packages in tests

jenkinsfile
This will make Jenkins start building against Java 17 instead of 16.
=> Update jenkinsfile to build against Java 17

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/persistence/ItemDatabase.java
=> refactor: avoid magic numbers in ItemDatabase

src/net/sourceforge/kolmafia/request/ClanStashRequest.java, src/net/sourceforge/kolmafia/request/TransferItemRequest.java, test/internal/helpers/Player.java, test/net/sourceforge/kolmafia/textui/command/ClanStashCommandTest.java
Follow-up to https://github.com/kolmafia/kolmafia/pull/699. Don't send a clan stash request if the user sends zero items.
=> fix: don't send clan stash without items or meat

src/net/sourceforge/kolmafia/PastaThrallData.java, src/net/sourceforge/kolmafia/textui/DataTypes.java, src/net/sourceforge/kolmafia/textui/parsetree/ProxyRecordValue.java, test/root/expected/test_pasta_thralls.ash.out, test/root/scripts/test_pasta_thralls.ash
Avoid casts by using a real object.
=> refactor: don't use Object[][] in pasta thralls

src/net/sourceforge/kolmafia/request/ClanStashRequest.java, test/net/sourceforge/kolmafia/textui/command/RefreshStatusCommandTest.java
=> fix: refresh clan stash

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/FightRequest.java, test/net/sourceforge/kolmafia/request/FightRequestTest.java, test/root/request/test_fight_slay_the_dead.html
The "decrease evilness" message is in a "p" node - and subsequent familiar actions and item drops are also in the same "p" node. Therefore, unlike other Evilometer effects, we must continue processing the node.
=> Slay the Dead has peculiar HTML structure.

src/net/sourceforge/kolmafia/DebugModifiers.java, test/net/sourceforge/kolmafia/textui/command/ModiferListCommandTest.java, test/net/sourceforge/kolmafia/textui/command/ModiferTraceCommandTest.java
Two more simple command tests, lint associated file.
=> tests: add tests for modtrace / modifies

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/session/InventoryManager.java, test/net/sourceforge/kolmafia/session/PriceToAcquireTest.java
Account for the fact that ItemValue with count returns value for that  many items
=> Price to acquire fix

src/data/defaults.txt, src/net/sourceforge/kolmafia/request/FightRequest.java, src/net/sourceforge/kolmafia/swingui/OptionsFrame.java
As requested in https://kolmafia.us/threads/anyway-to-override-ultra-rare-stopping-my-script.27428/#post-167907.
Untested ;)
=> feat: allow not stopping for an UR

src/data/modifiers.txt
=> rename "Damage Resistance" for the Unbreakable Umbrella

src/net/sourceforge/kolmafia/request/GenericRequest.java, src/net/sourceforge/kolmafia/utilities/FileUtilities.java, src/net/sourceforge/kolmafia/utilities/ResettingHttpClient.java, test/internal/helpers/Player.java
https://kolmafia.us/threads/ioexception-goaway-received.27397/#post-167957
=> Before 10k server requests are sent, reset our connection.

src/net/sourceforge/kolmafia/request/GenericRequest.java, src/net/sourceforge/kolmafia/request/LocketRequest.java, src/net/sourceforge/kolmafia/session/LocketManager.java, src/net/sourceforge/kolmafia/textui/command/ReminisceCommand.java, test/net/sourceforge/kolmafia/textui/command/ReminisceCommandTest.java
LocketRequest - like GenieRequest or other requests that redirect to a fight - now automates the whole fight.
Its run() method does all the error checking that the "reminisce" command does, before actually submitting a request.
It also retrieves the locket, if necessary: you own it, but it's not equipped or in inventory.
=> Add LocketRequest.

src/net/sourceforge/kolmafia/utilities/ResettingHttpClient.java
An omission during the refactor. My bad.
=> fix: reset count after resetting client

src/net/sourceforge/kolmafia/swingui/GenericFrame.java, src/net/sourceforge/kolmafia/swingui/listener/QuickAccessListener.java, src/net/sourceforge/kolmafia/swingui/menu/BookmarkMenu.java, src/net/sourceforge/kolmafia/swingui/menu/GlobalMenuBar.java, src/net/sourceforge/kolmafia/swingui/menu/LoadScriptMenuItem.java, src/net/sourceforge/kolmafia/swingui/menu/MenuItemList.java, src/net/sourceforge/kolmafia/swingui/widget/AutoFilterTextField.java, src/net/sourceforge/kolmafia/utilities/InputFieldUtilities.java
https://kolmafia.us/threads/ctrl-k-search-pop-up.27530/
=> Add quick access dialog to avoid having to search through menus to open windows

src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
As requested in https://kolmafia.us/threads/get-display-case-contents.27547/
Returns an empty map if the character doesn't have a display case.
=> feat: implement get_display

src/net/sourceforge/kolmafia/request/MallSearchRequest.java, src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
In standard fashion, found while I was doing #760.
Worth doing while in the file, but there's a lot so I split them out.
=> chore: runtime library lints

src/data/defaults.txt, src/net/sourceforge/kolmafia/request/ApiRequest.java
@midgleyc I realized after seeing Malibu's PR that the name wasn't as good as it should've been.
=> Better mayday & cosmic ball pref names

src/data/equipment.txt
=> Fix powers for may day quest accessories

src/net/sourceforge/kolmafia/session/CrystalBallManager.java, test/net/sourceforge/kolmafia/session/CrystalBallManagerTest.java, test/root/request/test_ponder_orb_some_article.html, test/root/request/test_ponder_orb_the_gunk.html
resolves the issue brought up here:
https://kolmafia.us/threads/orb-pondering-prefix-trimming.27561/
by accounting for the "some" and "the" articles, as well as providing for support for monsters like "the gunk" whose names unfortunately begin with an article.
=> Allow orb to properly parse pondertext

src/data/defaults.txt, src/net/sourceforge/kolmafia/session/BastilleBattalionManager.java
I want to collect the results of seeking cheese in the Bastille Battalion. 12 of the contests depend on your stats (6 stats, favoring higher or lower stats). I'd like to collect the data for as many configurations as I can in order to derive the linear (we assume) constants involved.
This saves data, just as we do for Battle results, in a new file: Bastille.cheese.txt, using the same property that controls whether battle stats are saved: "logBastilleBattalionBattles". It could be a new property, but, really: why set one but not the other?
Here are the results I saved today when my multi with the IOTM ran his daily 5 free turns.
```
20220525.1764512.1.1	1	Let the cheese horse in	MD	5	true	64
20220525.1764512.1.2	2	Use the wishing well	NONE	0	false	0
20220525.1764512.1.4	4	Rob the suburb	PA …
```
=> Save Bastille cheese seeking data

src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
choiceAdventureXXX not whichchoiceXXX
=> fix property name for choice adventures

src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
Came in in the refactor. Noticed in-game, 607 is Room 237.
=> fix: wrong choice number

src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
Exposes KoLCharacter.findWand() as an ash function.
=> Expose get_zap_wand() from KoLCharacter.findWand()

src/net/sourceforge/kolmafia/textui/command/UntinkerCommand.java, test/net/sourceforge/kolmafia/textui/command/AbortCommandTest.java, test/net/sourceforge/kolmafia/textui/command/AbstractCommandTestBase.java, test/net/sourceforge/kolmafia/textui/command/UntinkerCommandTest.java
Two more command tests, one more zero item fix.
=> feat: don't send request when untinkering no items

src/data/defaults.txt, src/data/equipment.txt, src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt, src/net/sourceforge/kolmafia/KoLCharacter.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/persistence/ItemDatabase.java, src/net/sourceforge/kolmafia/session/ChoiceAdventures.java, src/net/sourceforge/kolmafia/session/ResponseTextParser.java, test/net/sourceforge/kolmafia/request/FightRequestTest.java
=> Choice spoilers for June cleaver adventures; the rest of the june cleaver items & effects; parse June Cleaver desc

src/data/modifiers.txt, src/data/statuseffects.txt
=> feat: add Teacher's Pet

src/data/monsters.txt
I ran ckb's monsters.txt through "test fix-monster-attributes" to normalize the ordering, but other than that, the credit is all his.
=> Add Group: Phys: and Elem: to monsters, courtesy of ckb

src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
Choice 1475, option 2 was described as Mysticality substats, it should be Muscle substats.
For reference:
https://kol.coldfront.net/thekolwiki/index.php/Hypnotic_Master
From session log:
```
Took choice 1475/2: Mysticality substats
choice.php?whichchoice=1475&option=2&pwd
You gain 400 Strongness```
=> June Cleaver - Choice 1475 Correction

src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
```
Encounter: Bath Time
Took choice 1473/1: Mysticality substats, gob of wet hair
choice.php?pwd&whichchoice=1473&option=1
You gain 150 Fortitude
You gain a Muscle point!
You acquire an item: gob of wet hair
```
=> Fix choice spoiler for 1473/1

src/net/sourceforge/kolmafia/AdventureResult.java, src/net/sourceforge/kolmafia/EdServantData.java, src/net/sourceforge/kolmafia/KoLAdventure.java, src/net/sourceforge/kolmafia/RequestEditorKit.java, src/net/sourceforge/kolmafia/persistence/AdventureDatabase.java, src/net/sourceforge/kolmafia/persistence/ConsumablesDatabase.java, src/net/sourceforge/kolmafia/persistence/ItemDatabase.java, src/net/sourceforge/kolmafia/request/AdventureRequest.java, src/net/sourceforge/kolmafia/textui/DataTypes.java, src/net/sourceforge/kolmafia/textui/command/EdServantCommand.java, src/net/sourceforge/kolmafia/textui/parsetree/ProxyRecordValue.java, src/net/sourceforge/kolmafia/webui/IslandDecorator.java, test/net/sourceforge/kolmafia/textui/command/EdServantCommandTest.java
Many classes in one in this PR. Can split if necessary, but I think they're all quite simple. Simple test for `EdServantCommand` to cover `EdServantData`.
=> refactor: remove Object[][]

test/net/sourceforge/kolmafia/ModifiersTest.java
Fix some tests not tagged with `@Test`.
=> tests: make hp tests run

src/data/defaults.txt, src/net/sourceforge/kolmafia/request/SuburbanDisRequest.java, src/net/sourceforge/kolmafia/session/QuestManager.java, src/net/sourceforge/kolmafia/session/ResultProcessor.java, test/internal/helpers/Player.java, test/net/sourceforge/kolmafia/session/ResultProcessorTest.java
This should be it mostly finished. Some of the tracking had issues which have been tested and fixed here. We now track when the big boss is defeated. One thing I might want to add is a command for getting effects from the altar. I might also want to support some of the altar effects a little better.
=> More Dis support and tests

src/net/sourceforge/kolmafia/swingui/widget/RequestPane.java
See https://github.com/kolmafia/kolmafia/pull/297
The licensing of a StackOverflow post from several years ago is uncertain but since StackOverflow was referenced in the commit discussion it seems appropriate to acknowledge it in the actual code itself.
=> Provide attribution inline.

src/net/sourceforge/kolmafia/FamiliarData.java, src/net/sourceforge/kolmafia/Modifiers.java, src/net/sourceforge/kolmafia/objectpool/EffectPool.java, src/net/sourceforge/kolmafia/objectpool/FamiliarPool.java, test/net/sourceforge/kolmafia/FamiliarDataTest.java, test/net/sourceforge/kolmafia/ModifiersTest.java
Hopefully fixes https://kolmafia.us/threads/26526-breaks-fidoxene-tracking.27683
This also makes me think: the two places I had to make this change are trying to achieve the same thing (I think) - should I look at combining them?
=> Actively include Fidoxene when calculating familiar weight

src/net/sourceforge/kolmafia/Modifiers.java, test/net/sourceforge/kolmafia/ModifiersTest.java
=> fix speculation of buffed HP and buffed MP in Grey You

src/net/sourceforge/kolmafia/persistence/MallPriceDatabase.java, test/net/sourceforge/kolmafia/persistence/MallPriceDatabaseTest.java
Inspired by #865.
Test added for the only complex bit of the class. One straight `close` converted to try-with-resources.
=> refactor: remove PriceArray

src/net/sourceforge/kolmafia/Modifiers.java, src/net/sourceforge/kolmafia/maximizer/Evaluator.java, src/net/sourceforge/kolmafia/persistence/EquipmentDatabase.java, src/net/sourceforge/kolmafia/session/EquipmentManager.java, src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
Inspired by #865.
One usage went to a list, the other to a map. Order never matters for any usage that I found.
=> refactor: remove SpecialOutfitArray

src/net/sourceforge/kolmafia/persistence/AdventureDatabase.java, test/net/sourceforge/kolmafia/persistence/AdventureDatabaseTest.java
Based off comments on #865.
`adventureTable` was an array of `StringArray`s (used as lists), with the implicit requirement that all the `StringArray`s had to have the same length. A list of objects is a better fit.
=> refactor: adventure table

src/net/sourceforge/kolmafia/swingui/menu/DebugLogMenuItem.java, src/net/sourceforge/kolmafia/swingui/menu/LoadScriptMenuItem.java, src/net/sourceforge/kolmafia/swingui/menu/ThreadedMenuItem.java
This is that part of PR 759 which reverted the unpopular behavior from PR 751
=> do not auto focus gCLI when execute a script from a menu

src/net/sourceforge/kolmafia/textui/parsetree/ProxyRecordValue.java
Not sure how this happened (it was probably me)
=> Location id is an int type, not boolean

src/net/sourceforge/kolmafia/swingui/menu/LoadScriptMenuItem.java, src/net/sourceforge/kolmafia/swingui/menu/ScriptMRUList.java, src/net/sourceforge/kolmafia/swingui/menu/ScriptMenu.java, src/net/sourceforge/kolmafia/textui/command/CallScriptCommand.java
1) MRU list will no longer return duplicate Files
2) MRU scripts in the Scripts menu now display the subdirectory that they are in.
=> fixes for scriptMRUList

src/data/fullness.txt, src/data/inebriety.txt
Mark some more inedibles. I was unsure about whether these should be present, but bottle of Chateau de Vinegar was, and they're edible in TCRS.
Include Dad's brandy from sapph, posted at https://kolmafia.us/threads/data-for-dads-brandy.27759/.
=> feat: some edible data

src/data/dailylimits.txt, src/net/sourceforge/kolmafia/persistence/DailyLimitDatabase.java, src/net/sourceforge/kolmafia/request/UseSkillRequest.java, test/net/sourceforge/kolmafia/persistence/DailyLimitDatabaseTest.java, test/net/sourceforge/kolmafia/request/UseSkillRequestTest.java
Some cleaning up, more test coverage, more cases handled, more edge cases handled
=> More dailylimits work

src/data/defaults.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/session/InventoryManager.java, src/net/sourceforge/kolmafia/session/MallPriceManager.java, test/internal/helpers/Player.java, test/net/sourceforge/kolmafia/session/PriceToAcquireTest.java
And I also added the suppressMallPriceCacheMessages property.
I considered calling it suppressSuperIrritatingAndAnnoyingMallPriceCacheMessages but I thought better of it.
=> priceToAcquire should account for valueOfAdventure for all adventures spent

src/data/monsters.txt
=> remove duplicate NOCOPY

src/data/defaults.txt, src/net/sourceforge/kolmafia/scripts/git/GitManager.java, src/net/sourceforge/kolmafia/swingui/OptionsFrame.java, test/net/sourceforge/kolmafia/scripts/git/GitManagerTest.java
Could be useful for debugging broken installs.
=> feat: provide preference for not installing git dependencies

src/data/defaults.txt, src/net/sourceforge/kolmafia/scripts/git/GitManager.java, src/net/sourceforge/kolmafia/swingui/OptionsFrame.java, src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
Like SVN, add an option for showing commit messages on update.
=> feat: add option for showing git commit messages

src/data/spleenhit.txt
Breathitin 10 free advs >>> 5 free advs
=> spleenhit.txt typo

src/net/sourceforge/kolmafia/swingui/widget/PreferenceCheckBox.java
This change means that you can click on the text, in addition to the checkbox itself, to change the checkbox.
=> feat: associate checkbox text to checkbox

src/data/dailylimits.txt, src/data/defaults.txt, src/net/sourceforge/kolmafia/session/BreakfastManager.java, src/net/sourceforge/kolmafia/swingui/OptionsFrame.java
Successful use untested, will check tomorrow.
=> feat: add book of every skill to optional breakfast

src/net/sourceforge/kolmafia/textui/command/DaycareCommand.java, test/net/sourceforge/kolmafia/textui/command/DaycareCommandTest.java
Looking through my scripts, I have
```
if (get_property("_daycareGymScavenges").to_int() == 0) {
visit_url("place.php?whichplace=town_wrong&action=townwrong_boxingdaycare"); run_choice(3); run_choice(2); run_choice(5); run_choice(4);
}
```
This would be nicer as part of Mafia.
=> feat: add new 'daycare scavenge free' command

src/net/sourceforge/kolmafia/objectpool/Concoction.java, src/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanel.java, test/internal/helpers/Player.java, test/net/sourceforge/kolmafia/objectpool/ConcoctionTest.java, test/net/sourceforge/kolmafia/request/StorageRequestTest.java
Sometimes sorting Concoctions compares a steel organ to another, sometimes it doesn't. Now it always does. Also cleaned up the test file a bit.
=> Attempt to permanently meet otherwise stochastic coverage changes

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/RelayRequest.java, test/net/sourceforge/kolmafia/request/RelayRequestWarningsTest.java
Not sure whether the dinodollars go away, or the shop goes away, or the shop contents don't go away, but I think warning is a good idea if that's right.
The shop is `whichshop=dino`, though.
=> feat: warn with dinodollars at Ralph

src/data/items.txt, src/data/modifiers.txt, src/data/monsters.txt, src/data/statuseffects.txt, src/net/sourceforge/kolmafia/CoinmasterRegistry.java, src/net/sourceforge/kolmafia/RequestLogger.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/DinostaurRequest.java, src/net/sourceforge/kolmafia/request/NPCPurchaseRequest.java, src/net/sourceforge/kolmafia/swingui/CoinmastersFrame.java
More dino stuff: bosses (Frat route), last item, last effect
=> feat: more dino stuff

src/net/sourceforge/kolmafia/persistence/HolidayDatabase.java, test/net/sourceforge/kolmafia/persistence/HolidayDatabaseTest.java, test/net/sourceforge/kolmafia/textui/command/ShowDataCommandTest.java
Add tests for moon positions, reading off https://noblesse-oblige.org/calendar/
=> fix: hamburglar position

src/data/items.txt, src/data/monsters.txt, src/net/sourceforge/kolmafia/request/RelayRequest.java
Source: https://kolmafia.us/threads/fall-2022-challenge-path-fall-of-the-dinosaurs.27887/page-2#post-169386
=> feat: more dino stuff from Yendor

src/data/classskills.txt, src/data/dailylimits.txt, src/data/defaults.txt, src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/net/sourceforge/kolmafia/KoLmafiaCLI.java, src/net/sourceforge/kolmafia/Modeable.java, src/net/sourceforge/kolmafia/maximizer/Maximizer.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/preferences/Preferences.java, src/net/sourceforge/kolmafia/session/ChoiceControl.java, src/net/sourceforge/kolmafia/textui/command/BackupCameraCommand.java, src/net/sourceforge/kolmafia/textui/command/JurassicParkaCommand.java, test/net/sourceforge/kolmafia/ModeableTest.java, test/net/sourceforge/kolmafia/textui/command/JurassicParkaCommandTest.java
This covers changing out modes of the parka, maximizer handling, basic tracking for the five-a-day skill.
Everything else is pending spading, we should merge this as is
=> Jurassic Parka

src/net/sourceforge/kolmafia/KoLAdventure.java, src/net/sourceforge/kolmafia/persistence/AdventureDatabase.java, src/net/sourceforge/kolmafia/request/FightRequest.java, test/net/sourceforge/kolmafia/request/FightRequestTest.java
https://kolmafia.us/threads/tracking-zone-types-for-the-cold-medicine-cabinet.27777/#post-169497
Supersedes #1042
=> Don't count non-snarfblat zones for CMC tracking

src/data/familiars.txt
antique nutcracker figure -> antique nutcracker figurine
=> Fix Antique Nutcracker hatchling typo

src/net/sourceforge/kolmafia/request/PurchaseRequest.java, test/net/sourceforge/kolmafia/session/MallPriceManagerTest.java
First commit is a failing test
=> Don't sort mall results by shop name

src/net/sourceforge/kolmafia/textui/parsetree/Operator.java, src/net/sourceforge/kolmafia/textui/parsetree/TernaryExpression.java, src/net/sourceforge/kolmafia/textui/parsetree/Type.java, src/net/sourceforge/kolmafia/textui/parsetree/Value.java, test/net/sourceforge/kolmafia/textui/parsetree/ValueTest.java
Made a small order of operations mistake in the previous refactor, this corrects the behavior to match how it worked before :)
=> Restore behaviour of Value comparison doing string-like check first not last

.github/workflows/npm.yml
- How about this?
- Oh this will fix it
=> Check out all repository when calculating revision for TS

src/net/sourceforge/kolmafia/AscensionClass.java, test/net/sourceforge/kolmafia/AscensionClassTest.java
- Add tests for AscensionClass
- Fix some errors that testing found
=> AscensionClass tests

src/data/dailylimits.txt, src/data/defaults.txt, src/net/sourceforge/kolmafia/objectpool/SkillPool.java, src/net/sourceforge/kolmafia/request/FightRequest.java, test/net/sourceforge/kolmafia/request/FightRequestTest.java, test/root/request/test_fight_smash_and_graaagh_failure.html, test/root/request/test_fight_smash_and_graaagh_success.html
Add a preference and tracking for the Zombie Slayer skill Smash & Graaagh
=> Smash and graaagh

src/data/ocean.txt, src/net/sourceforge/kolmafia/session/OceanManager.java, test/net/sourceforge/kolmafia/session/OceanManagerTest.java
As previously discussed in https://github.com/kolmafia/kolmafia/pull/1087
=> Ocean coordinates are now read from ocean.txt

src/data/monsters.txt
https://cdn.discordapp.com/attachments/473525651043909642/1022198810874757240/Screenshot_20220921-113240_Brave.jpg
Per spading, fails to drop when YRed, so it is not "just" nopp.
=> Change big red button from nopickpocket to conditional

build.gradle
Leave those tied to other deps or with breaking changes.
=> chore: update some plugins and deps

.github/npm/.gitignore, .github/workflows/npm.yml
Fix Typescript definition validation, take 2.
=> fix: move index.d.ts to right place before validating

src/net/sourceforge/kolmafia/KoLmafiaCLI.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/textui/command/AutumnatonCommand.java, test/net/sourceforge/kolmafia/session/ElVibratoManagerTest.java, test/net/sourceforge/kolmafia/session/JourneyManagerTest.java, test/net/sourceforge/kolmafia/textui/command/AutumnatonCommandTest.java, test/root/request/test_choice_autumnaton_quest_fail.html
Doesn't check for valid locations: just sends you there, then checks for an error message.
Nice improvements would be to list the possible locations (and check against them), but that might be better suited to ASH.
=> feat: autumnaton command

src/net/sourceforge/kolmafia/persistence/ConsumablesDatabase.java
Special Feast of Boris calculations ignored all consumables which were not affected by the Holiday.
=> fix consumption stats on Feast of Boris

src/net/sourceforge/kolmafia/KoLCharacter.java, src/net/sourceforge/kolmafia/scripts/git/GitManager.java, src/net/sourceforge/kolmafia/session/LoginManager.java
Also correct a small typo on Unconscious Collective standard check
=> fix: set _gitUpdated on git update, not just breakfast

src/data/fullness.txt, src/data/inebriety.txt
These are both really good -- practically EPIC level.
=> feat: autumn food stats

src/net/sourceforge/kolmafia/textui/command/AutumnatonCommand.java, src/net/sourceforge/kolmafia/webui/StationaryButtonDecorator.java, test/net/sourceforge/kolmafia/textui/command/AutumnatonCommandTest.java, test/root/request/test_choice_autumnaton_upgrade_available_many.html, test/root/request/test_choice_autumnaton_upgrade_available_one.html, test/root/request/test_choice_autumnaton_upgrade_available_two.html
Also, show the turns left after sending. While using it I always wanted to know this information.
Also fix the HTML on the CAB addition.
=> feat: show upgrades and upgrade autumnaton

src/data/monsters.txt, src/net/sourceforge/kolmafia/webui/UseLinkDecorator.java
1) Autumn-aton redirects to a choice, so use link cannot be in-line
2) Othello also drops handkerchief, dagger, and military jacket
=> use link for autumnaton not inline. more drops for Othello

src/data/adventures.txt
More difflevels.
This should finish off low indoor.
=> feat: difflevel spading

src/data/monsters.txt
Correct ghost miner drops, add drops for Twitch 8.
=> feat: item chances for backstage, some other items

src/data/adventures.txt
These were easy.
I also tried sending the autumn-aton to The Junkyard.
I got IOExceptions on the turn it returned - code 500.
I tried again in vanilla KoL. I did see it return.
Here is the bug report I submitted:
-------------
```
I sent my autumn-aton to The Junkyard (post-war).
When it came back:
Having completed its mission, your autumn-aton walks up and presents a summary of its experiences and the items it found.
You acquire an item: autumn-aton
You gain 183 Strengthliness.
You gain 183 Magicalness.
You gain 202 Roguishness.
It found no items - not even the special autumn-aton drops.
```
=> a few more DiffLevels

src/data/fullness.txt, src/data/inebriety.txt
Confirmed via devleaks. https://discord.com/channels/466605739838930955/473525651043909642/1034213026569662544
=> Correct adventure and stat values for Hodgman's blanket and mulligan stew.

src/net/sourceforge/kolmafia/maximizer/Evaluator.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
https://kolmafia.us/threads/june-cleaver-maximizer-effective-keyword.28217/
=> Make maximizer `effective` keyword ignore June Cleaver

src/data/familiars.txt, src/data/fullness.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt, src/net/sourceforge/kolmafia/persistence/FamiliarDatabase.java
Get those items started.
Also can we just sort `modifiers.txt` alphabetically? And maybe autosort it? And same for the other files? I want to just add stuff at the end and run a script or something.
=> feat: initial items for cookbookbat

src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt
Just the items / effects. Preferences / concoctions yet to come.
=> feat: more cookbookbat items

src/net/sourceforge/kolmafia/KoLCharacter.java
The lack of this check was causing a concoction database refresh on every api.php request.
=> Only change ascension class if different.

src/net/sourceforge/kolmafia/persistence/SkillDatabase.java
See discussion at this bug report.
https://kolmafia.us/threads/one-char-doesnt-run-after-upgrade-to-kolmafia-26897-m-jar.28240/
=> Work around compiler error

src/data/familiars.txt
Otherrwise, kolmafia won't let you equip it.
=> Tag the cookbookbat's equipment in familiars.txt

src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
=> fix: NPE on unknown autumnaton location (ASH)

src/net/sourceforge/kolmafia/objectpool/Concoction.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/objectpool/SkillPool.java, test/internal/helpers/Cleanups.java, test/internal/helpers/Player.java, test/net/sourceforge/kolmafia/objectpool/ConcoctionTest.java
Follow-up to #1269. Started rewriting the world, so split out.
=> tests: concoction tests

src/data/adventures.txt, src/data/combats.txt, src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt
The barroom brawl is now indoor, as expected.
The prohibition dude's rare drop is a hat.
=> feat: oliver's place fixes

src/data/inebriety.txt
=> Strawberry wine is wine ♠️

src/data/monsters.txt
These two were just updated in-game today.
=> Update traveling hobo and goblin flapper phyla to match game changes

src/data/defaults.txt, src/net/sourceforge/kolmafia/request/FightRequest.java, src/net/sourceforge/kolmafia/session/QuestManager.java, src/net/sourceforge/kolmafia/swingui/panel/DailyDeedsPanel.java, test/net/sourceforge/kolmafia/request/FightRequestTest.java, test/net/sourceforge/kolmafia/session/QuestManagerTest.java
We call it Speakeasy elsewhere
=> Rename Oliver's Place to Speakeasy

src/data/equipment.txt, src/data/modifiers.txt, src/net/sourceforge/kolmafia/CoinmasterData.java, src/net/sourceforge/kolmafia/persistence/CoinmastersDatabase.java, src/net/sourceforge/kolmafia/request/TicketCounterRequest.java, src/net/sourceforge/kolmafia/request/TrapperRequest.java, src/net/sourceforge/kolmafia/swingui/CoinmastersFrame.java, src/net/sourceforge/kolmafia/swingui/menu/LootTrapperMenuItem.java
1) "Recipe of Before Yore: baked veggie ricotta" has recipe for "baked veggie ricotta casserole"
2) CoinmasterDatabase uses LockableListFactory to create LockableListModel objects
3) stuffed dinosaur has power 10
=> Use LockableListFactory

src/net/sourceforge/kolmafia/swingui/widget/ShowDescriptionList.java, src/net/sourceforge/kolmafia/swingui/widget/ShowDescriptionTable.java
Accidentally introduced a bug with the watchable prefs feature, fixed it here.
=> Fix context menu bug

src/data/modifiers.txt, src/net/sourceforge/kolmafia/DebugModifiers.java, src/net/sourceforge/kolmafia/KoLCharacter.java, src/net/sourceforge/kolmafia/Modifiers.java, src/net/sourceforge/kolmafia/persistence/SkillDatabase.java
- Add Puck Man and Ms Puck Man to have a variable DROPS_ITEMS modifier
- Modernize some switches
I want to make a familiardrops.txt that captures this info and the Drop Familiars info in FamiliarData too, but that's for another time
=> Add missing "drops items" override for the Puck Men

src/net/sourceforge/kolmafia/textui/command/HatterCommand.java, test/net/sourceforge/kolmafia/textui/command/HatterCommandTest.java
The potion won't ever give you the effect because it is nohookah, so this command will just waste a DRINK ME
=> Not allowed to use hatter command in TCRS

src/net/sourceforge/kolmafia/MonsterData.java, test/net/sourceforge/kolmafia/MonsterDataTest.java
- More monsters that are conditionally free
- Tidy up file
- Add tests for conditional free fights
=> More fights that are only sometimes free

src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt
=> feat: advent calendar day 1

src/net/sourceforge/kolmafia/request/DrinkItemRequest.java, src/net/sourceforge/kolmafia/request/EatItemRequest.java, src/net/sourceforge/kolmafia/request/SpleenItemRequest.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, test/net/sourceforge/kolmafia/textui/command/ChewCommandTest.java, test/net/sourceforge/kolmafia/textui/command/DrinkCommandTest.java, test/net/sourceforge/kolmafia/textui/command/EatCommandTest.java
As reported in https://kolmafia.us/threads/eat-no-longer-works-in-grey-you.28358/.
=> fix: grey you consumption

src/data/items.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/CampgroundRequest.java, src/net/sourceforge/kolmafia/session/ChoiceControl.java
adds the unbound & bound IOTMs
adds to campground items and workshed items.
=> start of support for model train set

src/data/fullness.txt, src/data/inebriety.txt
I don't have instances of every value inside the range (for the stats), but I'm quite confident given the pattern I've seen.
=> feat: oliver's basic food / drink

src/data/modifiers.txt, src/data/statuseffects.txt
Various train buildings offer effects. Add them to Mafia with no other support.
=> feat: train effects data dump

src/data/adventures.txt, src/data/combats.txt, src/data/defaults.txt, src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/data/monsters.txt, src/data/statuseffects.txt, src/data/zonelist.txt, src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
We still need:
* Tracking for Elf Gratitude, but given we don't know what it does this seems fine. We should add once they add a readout for people.
* Tracking for Ping Pong skill. This can maybe be worked out backwards from meat drops in combat, but would be nice to track if they add a readout.
=> Crimbo 22 Day 1

src/data/adventures.txt, src/data/combats.txt, src/data/defaults.txt, src/data/equipment.txt, src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/monsters.txt, src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
Don't have the autoassembly yet.
=> feat: dining car stuff

src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/data/monsters.txt
=> feat: autoassembly module

src/data/familiars.txt, src/data/modifiers.txt, src/data/monsters.txt, src/data/statuseffects.txt
No descid for the really nice lump of coal yet. Expect holder should display it by tomorrow.
=> fix: coal car monster attacks, rares

src/data/adventures.txt, src/data/defaults.txt, src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/data/monsters.txt, src/net/sourceforge/kolmafia/KoLAdventure.java, src/net/sourceforge/kolmafia/objectpool/AdventurePool.java, src/net/sourceforge/kolmafia/persistence/AdventureDatabase.java, src/net/sourceforge/kolmafia/request/AdventureRequest.java, src/net/sourceforge/kolmafia/request/PlaceRequest.java, src/net/sourceforge/kolmafia/session/QuestManager.java
1) Crimbo Train (Locomotive)
2) The Superconductor is a monster.
Once defeated, superconductorDefeated is true
3) The Superconductor's CPU has modifiers affected by elfGratitude
4) two more tiny plastic advent calendar items.
=> Crimbo Train (Locomotive), The Superconductor, and CPU

src/net/sourceforge/kolmafia/textui/command/BuyCommand.java
BuyCommand calls searchMall(item), which already calls updateMallPrice deep in the MallSearchRequest code. No need to do it again.
=> Don't double-update mall price on BuyCommand.

src/net/sourceforge/kolmafia/swingui/panel/CompactSidePane.java
This preserves performance in 99% of cases and fixes the Machine Elf visual bug (along with a few others).
=> Fix bug with <br> in CompactSidePane familiar annotation.

src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt
Custom Item given to Invariel (#1043600) that was not in the database,
https://kol.coldfront.net/thekolwiki/index.php/Golden_Mr._Eh%3F
=> Added Golden Mr. Eh

src/data/items.txt, src/data/modifiers.txt
=> feat: rock garden items

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/CampgroundRequest.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, src/net/sourceforge/kolmafia/webui/ValhallaDecorator.java
Might need to refactor the campground code a bit after figuring out how this works. First garden to have multiple images.
=> feat: rock garden day 1

src/data/concoctions.txt, src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt
plus one standard reward and beer recipe
=> feat: last garden items

src/net/sourceforge/kolmafia/request/CampgroundRequest.java, test/net/sourceforge/kolmafia/request/CampgroundRequestTest.java, test/root/request/test_campground_inspect_dwelling.html
Maids haven't been outside the dwelling in a long time. The code still worked because the full response text (including the dwelling) was passed to both the dwelling and the campground methods, but it's better to not do the check where it can't succeed.
=> refactor: move maid detection to dwelling

src/net/sourceforge/kolmafia/request/CampgroundRequest.java
* apply IntelliJ suggestions
* convert to switches where "better"
* remove unused variables / functions
* clarify `String[][]`
=> refactor: various suggested fixes + refactoring

src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/data/outfits.txt
It's harder to find the standard stuff this year, as they're not in Valhalla. Could just leave this open until we get a decent number.
=> feat: two more standard items

src/net/sourceforge/kolmafia/RequestEditorKit.java, src/net/sourceforge/kolmafia/session/ChoiceAdventures.java, src/net/sourceforge/kolmafia/session/ChoiceControl.java, src/net/sourceforge/kolmafia/session/ChoiceManager.java, src/net/sourceforge/kolmafia/session/ChoiceOption.java, src/net/sourceforge/kolmafia/session/HaciendaManager.java, src/net/sourceforge/kolmafia/session/LouvreManager.java, src/net/sourceforge/kolmafia/session/MonorailManager.java, src/net/sourceforge/kolmafia/session/SafetyShelterManager.java, src/net/sourceforge/kolmafia/session/VampOutManager.java, src/net/sourceforge/kolmafia/session/VioletFogManager.java, src/net/sourceforge/kolmafia/session/WumpusManager.java, src/net/sourceforge/kolmafia/swingui/panel/ChoiceOptionsPanel.java, src/net/sourceforge/kolmafia/textui/command/TestCommand.java, src/net/sourceforge/kolmafia/utilities/ChoiceUtilities.java, test/net/sourceforge/kolmafia/session/ChoiceOptionTest.java
Per this bug report: [https://kolmafia.us/threads/vampout-is-broken-due-to-circular-dependency.28069](url)
=> Move ChoiceAdventure.Option to ChoiceOption

src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/data/outfits.txt
Full ceramic set + trainbot halloween reward
=> feat: full ceramic set

src/data/modifiers.txt, src/net/sourceforge/kolmafia/Modifiers.java, test/net/sourceforge/kolmafia/ModifiersTest.java
Whoops! CBB and Vampire Vintner have 1.5x effectiveness not 1.5x fairy weight
=> Fix CBB and Vintner misunderstanding

src/net/sourceforge/kolmafia/KoLmafiaCLI.java, src/net/sourceforge/kolmafia/textui/command/CliRefCommand.java, src/net/sourceforge/kolmafia/utilities/PrefixMap.java
=> refactor: change prefix map key type ints to enum

src/net/sourceforge/kolmafia/combat/Macrofier.java, src/net/sourceforge/kolmafia/textui/DataTypes.java, src/net/sourceforge/kolmafia/textui/Parser.java, src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, src/net/sourceforge/kolmafia/textui/javascript/ValueConverter.java, src/net/sourceforge/kolmafia/textui/parsetree/AggregateType.java, src/net/sourceforge/kolmafia/textui/parsetree/ArrayValue.java, src/net/sourceforge/kolmafia/textui/parsetree/Assignment.java, src/net/sourceforge/kolmafia/textui/parsetree/CompositeType.java, src/net/sourceforge/kolmafia/textui/parsetree/FunctionReturn.java, src/net/sourceforge/kolmafia/textui/parsetree/MapValue.java, src/net/sourceforge/kolmafia/textui/parsetree/Operation.java, src/net/sourceforge/kolmafia/textui/parsetree/Operator.java, src/net/sourceforge/kolmafia/textui/parsetree/RecordInitializer.java, src/net/sourceforge/kolmafia/textui/parsetree/RecordType.java, src/net/sourceforge/kolmafia/textui/parsetree/RecordValue.java, src/net/sourceforge/kolmafia/textui/parsetree/Type.java, src/net/sourceforge/kolmafia/textui/parsetree/TypeDef.java, src/net/sourceforge/kolmafia/textui/parsetree/Value.java, src/net/sourceforge/kolmafia/textui/parsetree/Variable.java
Also straightforward: the int values aren't used, either directly or as comparison.
=> refactor: change scripting data types to enum

src/data/adventures.txt, src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/data/outfits.txt
1) chiffon chakram. Yes, the item description says it is a "(1-handed )"
2) plural for chiffon chaps and groveling gravel
3) Outside the Club is, as expected, DiffLevel: mid
=> chiffon chakram

src/data/familiars.txt, src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt
3 adventures and some effect turns, the rock.
=> feat: advs from pixel consumables, pixel rock

src/net/sourceforge/kolmafia/DebugModifiers.java, src/net/sourceforge/kolmafia/FamiliarData.java, src/net/sourceforge/kolmafia/KoLAdventure.java, src/net/sourceforge/kolmafia/KoLCharacter.java, src/net/sourceforge/kolmafia/Modifiers.java, src/net/sourceforge/kolmafia/maximizer/Evaluator.java, src/net/sourceforge/kolmafia/maximizer/Maximizer.java, src/net/sourceforge/kolmafia/maximizer/MaximizerSpeculation.java, src/net/sourceforge/kolmafia/modifiers/BooleanModifier.java, src/net/sourceforge/kolmafia/modifiers/BooleanModifierCollection.java, src/net/sourceforge/kolmafia/modifiers/DerivedModifier.java, src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java, src/net/sourceforge/kolmafia/modifiers/StringModifier.java, src/net/sourceforge/kolmafia/request/BigBrotherRequest.java, src/net/sourceforge/kolmafia/request/MomRequest.java, src/net/sourceforge/kolmafia/request/SkateParkRequest.java, src/net/sourceforge/kolmafia/request/UseSkillRequest.java, src/net/sourceforge/kolmafia/session/EquipmentManager.java, src/net/sourceforge/kolmafia/swingui/panel/CompactSidePane.java, src/net/sourceforge/kolmafia/swingui/panel/GearChangePanel.java, src/net/sourceforge/kolmafia/swingui/panel/ItemManagePanel.java, src/net/sourceforge/kolmafia/swingui/widget/ListCellRendererFactory.java, src/net/sourceforge/kolmafia/swingui/widget/TableCellFactory.java, src/net/sourceforge/kolmafia/textui/command/ModRefCommand.java, src/net/sourceforge/kolmafia/textui/command/SpeculateCommand.java, test/net/sourceforge/kolmafia/KoLCharacterTest.java, test/net/sourceforge/kolmafia/ModifiersTest.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java, test/net/sourceforge/kolmafia/textui/command/SpeculateCommandTest.java
Added some tests for potentially dangerous areas, but I think the coverage is pretty good. It caught a couple of issues, at least!
=> refactor: convert boolean modifiers to enum

src/net/sourceforge/kolmafia/moods/MPRestoreItemList.java
Currently very abundant if you spam Arr, M80 (for various reasons).
=> Feature: Add grogpagne as new MP restorer.

src/data/defaults.txt, src/net/sourceforge/kolmafia/KoLAdventure.java, src/net/sourceforge/kolmafia/request/RelayRequest.java, src/net/sourceforge/kolmafia/session/QuestManager.java, test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java, test/net/sourceforge/kolmafia/request/RelayRequestWarningsTest.java, test/net/sourceforge/kolmafia/session/QuestManagerTest.java, test/root/request/test_open_oasis.html, test/root/request/test_visit_beach_desert_explored.html, test/root/request/test_visit_beach_desert_explored_gnasir.html, test/root/request/test_visit_beach_desert_explored_oasis_gnasir.html, test/root/request/test_visit_beach_desert_unexplored.html
Since a milestone can add desertExploration without opening the oasis, some adjustments are needed.
1) Boolean "oasisAvailable" property tracks whether The Oasis is available
2) If we see it on the desert map, true
3) If adventure in the desert and it opens up after a fight, true
4) if we have not adventured in the desert, but have used a milestone, desertExploration > 0, but oasisAvailable is false
5) canAdventure() in The Oasis depends on oasisAvailable, not desertExploration
6) unHydratedDesert Relay Warning depends on oasisAvailable, not desertExploration
=> Add oasisAvailable property

src/data/classskills.txt, src/data/equipment.txt, src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/spleenhit.txt, src/data/statuseffects.txt
Also add modifiers entry for Imported Strength.
=> feat: dump simple items from the SIT iotm

src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt
=> feat: other sit items

src/net/sourceforge/kolmafia/moods/HPRestoreItemList.java, src/net/sourceforge/kolmafia/request/ClanFortuneRequest.java, src/net/sourceforge/kolmafia/request/ClanLoungeRequest.java, src/net/sourceforge/kolmafia/request/FloundryRequest.java, src/net/sourceforge/kolmafia/session/ClanManager.java, src/net/sourceforge/kolmafia/session/ValhallaManager.java, src/net/sourceforge/kolmafia/swingui/FaxRequestFrame.java, src/net/sourceforge/kolmafia/textui/command/CrimboTreeCommand.java, src/net/sourceforge/kolmafia/textui/command/FaxCommand.java, src/net/sourceforge/kolmafia/textui/command/HotTubCommand.java, src/net/sourceforge/kolmafia/textui/command/PoolCommand.java, src/net/sourceforge/kolmafia/textui/command/ShowerCommand.java, src/net/sourceforge/kolmafia/textui/command/SwimmingPoolCommand.java, test/net/sourceforge/kolmafia/request/ClanLoungeRequestTest.java
The ones below "actions" are "options", which are meaningful ints.
=> refactor: make clan lounge requests enum

src/net/sourceforge/kolmafia/swingui/panel/CompactSidePane.java
=> fix: correct sleaze spell dmg modifier

src/net/sourceforge/kolmafia/maximizer/MaximizerSpeculation.java
I feel like the same is probably true for the tiebreaker, but there aren't enough tests for me to be really confident about that.
=> fix: no point checking outside core slots for foldables

src/net/sourceforge/kolmafia/session/EquipmentManager.java
Should fix https://kolmafia.us/threads/trying-to-equip-a-sticker-from-the-cli-fails-and-prints-an-error.28638/
=> fix: use getOrDefault on all turnsRemaining calls

src/data/classskills.txt, src/data/defaults.txt, src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt, src/net/sourceforge/kolmafia/AscensionClass.java, src/net/sourceforge/kolmafia/AscensionPath.java
Throw a bunch of data into Mafia.
=> feat: aosol skills, effects, some items

src/data/classskills.txt, src/data/monsters.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/objectpool/SkillPool.java, src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java, src/net/sourceforge/kolmafia/request/FightRequest.java, src/net/sourceforge/kolmafia/session/ChoiceControl.java, src/net/sourceforge/kolmafia/webui/UseLinkDecorator.java
Stuff I learned from day 1 as a Pig Skinner
1) You have to be a sufficient level to learn skills. Add that level to each skill in classskills
2) Fix image for goblin king's shadow, per Manuel
3) Four Pig Skinner combat skills are once per combat
4) First cut at setting up path-specific monster mapping for AoSoL.
Not adequate, since the Naughty Sorceress has different replacements per class
5) No in-line use links for skill book, since it redirects to a choice.
6) You can walk away from Get Some Training
=> skills, monsters, use links, combat spells

src/net/sourceforge/kolmafia/request/PlaceRequest.java
The IDE suggested these improvements. I elected to put them in their own PR and not with #1539
=> PlaceRequest lint

src/data/spleenhit.txt
https://kolmafia.us/threads/unable-to-chew-new-astral-energy-drink.28677/
=> Correct AED Item ID in Spleenhit.txt

src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java, src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java, test/net/sourceforge/kolmafia/persistence/TCRSDatabaseTest.java
Fixes the issue in https://kolmafia.us/threads/fail-to-login-when-in-tcrs-on-r27237.28699/
Not a proper fix, but I can't figure out why the issue occurs. I wrote a test to try to replicate it, but it doesn't replicate the issue. The test is included anyway.
Something of an emergency fix as it's preventing login. Might try for a better fix later.
=> fix: allow login in TCRS

src/data/monsters.txt
=> Add FREE attribute to some inherently free encounters

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Remove one of the error cases, add test for mutex.
=> feat: support any bitcounts for bitmaps

.github/workflows/check.yml
https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
This seems like a generally useful thing to have, although the specific context that I wanted this was to resolve #1581.
=> Allow tests to be manually triggered.

test/net/sourceforge/kolmafia/session/QuestManagerTest.java, test/root/request/test_adventure_tower_ruins_into_the_maw_of_deepness.html, test/root/request/test_adventure_tower_ruins_staring_into_nothing.html, test/root/request/test_adventure_tower_ruins_take_a_dusty_look.html, test/root/request/test_bathole_started.html, test/root/request/test_bathole_step1.html, test/root/request/test_bathole_step2.html, test/root/request/test_bathole_step3.html, test/root/request/test_bathole_step4.html, test/root/request/test_fight_bread_golem.html
Tests for the Wizard of Ego quest and the Level 4 quest QuestManager handling.
=> Bathole and Tower Ruins tests

src/data/items.txt
These were added at some point after release.
=> feat: plurals for shadow rift items

src/data/monsters.txt
all shadow bosses drop two (fixed) shadow items.
=> feat: shadow boss drops

src/data/modifiers.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Add a test for the eelskin stuff.
=> feat: include underwater passive damage too

src/data/fullness.txt, src/data/inebriety.txt
Haven't checked shadow sausage yet.
=> feat: shadow consumable advs

src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, test/root/expected/test_to_wiki_url.ash.out, test/root/scripts/test_to_wiki_url.ash
- Add tests for to_wiki_url function
- Write to_wiki_url functions
=> to_wiki_url in the RuntimeLibrary

src/data/classskills.txt, src/data/fullness.txt, src/data/inebriety.txt, src/data/spleenhit.txt
Add images to skills.
More shadow data.
=> feat: various data updates

src/net/sourceforge/kolmafia/persistence/AdventureDatabase.java, src/net/sourceforge/kolmafia/request/AdventureRequest.java, src/net/sourceforge/kolmafia/session/ChoiceManager.java, src/net/sourceforge/kolmafia/session/RufusManager.java, test/net/sourceforge/kolmafia/persistence/AdventureDatabaseTest.java, test/net/sourceforge/kolmafia/session/RufusManagerTest.java
1) If you have Shadow Affinity, you must use a different "action" to enter a Shadow Rift
2) When Calling Back Rufus, if you have completed the quest, default is to report success. If you have not completed the quest, default is to hang up rudely. (I suppose we could report failure).
The only time the default is used is when you are automating - which for this NC only comes into play in the Relay Browser: We point the arrow at the default option and if you press the "auto" button, it takes it.
3) "spectral" is GHOST, not COLD.
=> shadow rifts have free ingresses

src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
This is ready to go. Adds `eight_bit_points(location)` that returns the points you'd currently get for an 8-bit zone, including consideration of the current bonus zone.
=> 8-bit Points function for the RuntimeLibrary

src/net/sourceforge/kolmafia/scripts/git/GitManager.java
I wasn't able to test this because the scripts I tried updated fine without needing this change.
@jaadams5, you've had issues with some scripts, right? Can you post the script, the starting commit, and a change that fails, so I can test this?
=> feat: try to sync local changes when updating with git

src/data/monsters.txt
Tiki idol drops are conditional: all 100% but max 1 drop per combat.
Ice Hotel drops from wiki, spaded by PeKaJe.
Shadow bosses are NOCOPY.
=> feat: more drop rates, finish piraterealm

src/net/sourceforge/kolmafia/session/QuestManager.java, test/net/sourceforge/kolmafia/session/QuestManagerTest.java, test/root/request/test_visit_town_wrong.html
I wondered why speakeasyName was set to "Speakeasy", not "Veracity's Place".
Turns out that KoL changed the town_wrong map and the name is in its own div now.
=> Detect speakeasyName correctly given KoL change to town_wrong map

src/data/monsters.txt
Condition is that one can drop per day.
Spaded with PFC.
=> feat: bag of foreign bribes drop rate

src/data/defaults.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/MonkeyPawRequest.java, src/net/sourceforge/kolmafia/session/ChoiceControl.java, src/net/sourceforge/kolmafia/utilities/ChoiceUtilities.java, test/net/sourceforge/kolmafia/request/MonkeyPawRequestTest.java, test/root/request/test_monkey_paw_wish_0.html, test/root/request/test_monkey_paw_wish_1.html, test/root/request/test_monkey_paw_wish_2.html, test/root/request/test_monkey_paw_wish_3.html, test/root/request/test_monkey_paw_wish_4.html, test/root/request/test_monkey_paw_wish_5.html
Property _monkeyPawWishesUsed starts at 0 and goes up to 5 as you cast wishes.
=> Track cursed monkey paw wishes used

data/SVN/svnrepo.json
1) All my scripts that have repositories:
- Arrrbor Day
- BeachComber
- Garden Harvester
- Gingerbread City
- ShadowRift
- Spacegate Sounds
- VeracityMeatFarm
- VeracitySpacegate
- vcon
- vprops
2) Aventuristo's Snapshot maker
3) 8bit-relay
4) combo
All of the above have forum threads announcing github repositories accessed via git.
=> update repository registry to contain various git scripts

src/data/consequences.txt, src/data/defaults.txt, src/net/sourceforge/kolmafia/AreaCombatData.java, src/net/sourceforge/kolmafia/objectpool/SkillPool.java, src/net/sourceforge/kolmafia/preferences/Preferences.java, src/net/sourceforge/kolmafia/request/FightRequest.java, src/net/sourceforge/kolmafia/session/BanishManager.java, test/net/sourceforge/kolmafia/session/ConsequenceManagerTest.java, test/root/request/test_consequences_cursed_monkey_point.html, test/root/request/test_consequences_cursed_monkey_point_banish.html
Pointing at a monster adds 2 copies, crosses rollover.
Slapping is a banish, resets at rollover. Track both.
Reading the pointed monster from the description doesn't work perfectly because some monsters can contain dots, and we can't be sure where the sentence ends. But I think it's probably better than not doing that.
=> feat: monkey's paw banish / track

src/net/sourceforge/kolmafia/KoLAdventure.java, test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
This is mostly relevant for paths that don't follow the traditional council quests, like Community Service or Grey Goo.
=> the citadel quest grants access to the distant woods

src/data/monsters.txt
From information on the wiki, as well as my own testing via autumnaton
https://kol.coldfront.net/thekolwiki/index.php/C._H._U._M.
=> non-C.H.U.M. chum items are no-pickpocket

src/net/sourceforge/kolmafia/request/FightRequest.java, test/net/sourceforge/kolmafia/session/RufusManagerTest.java, test/root/request/test_defeat_shadow_boss.html, test/root/request/test_defeat_shadow_monster.html
Per [This report](https://kolmafia.us/threads/new-shadow-rift-ncs-buffs-and-buff-extension.28712/page-2#post-171840) from Malibu Stacey:
> ```encountersUntilSRChoice``` is being incremented at the start of combat. This means it will be off if you end combat in a manner which doesn't end combat (e.g Using the Force).
=> Count shadow rift turn at end of fight, not start

src/data/modifiers.txt, src/net/sourceforge/kolmafia/persistence/CafeDatabase.java, test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
Noticed Ancient Crimbo Lore was wrong, wondered if there were any more, wrote a test to confirm and fixed.
=> fix: check modifiers apply to valid entries

src/net/sourceforge/kolmafia/session/InventoryManager.java, src/net/sourceforge/kolmafia/session/ResultProcessor.java
If you start the session without the belt in inventory, then obtain it, you should be able to use the skills, but Mafia doesn't know you can.
=> feat: add cincho skills when obtaining cincho

data/SVN/svnrepo.json
Add some more scripts that are only installed through git.
Change some GitHub scripts which are installed through SVN to use git.
=> feat: more git scripts

data/SVN/svnrepo.json, src/data/monsters.txt
Landscaper gnome drop rates, some other drop rates from wiki.
Update CONSUME to be git installed (thanks soolar!)
=> feat: landscaper gnome drop rates

src/net/sourceforge/kolmafia/KoLCharacter.java, src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java, src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java, src/net/sourceforge/kolmafia/request/CampgroundRequest.java, src/net/sourceforge/kolmafia/request/ChateauRequest.java, test/internal/helpers/Player.java, test/net/sourceforge/kolmafia/persistence/TCRSDatabaseTest.java, test/net/sourceforge/kolmafia/request/ChateauRequestTest.java
Plus a small refactor to the latter to use a Set
=> Chateau items keep their mods in TCRS, just like Campground items

src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
As reported in https://kolmafia.us/threads/cursed-monkey-paw.28797/#post-172067
=> fix: don't abort if no monkey paw request was ever made

src/data/familiars.txt
There's a lot of tag spading going on, but for now just add the extra robots.
=> feat: sweet nutcracker and pocket professor are both robots

src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/data/monsters.txt, src/net/sourceforge/kolmafia/FamiliarData.java, src/net/sourceforge/kolmafia/Modifiers.java, src/net/sourceforge/kolmafia/MonsterData.java, src/net/sourceforge/kolmafia/RequestEditorKit.java, src/net/sourceforge/kolmafia/maximizer/Maximizer.java, src/net/sourceforge/kolmafia/objectpool/FamiliarPool.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/persistence/FamiliarDatabase.java, src/net/sourceforge/kolmafia/persistence/SkillDatabase.java, src/net/sourceforge/kolmafia/request/FightRequest.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, src/net/sourceforge/kolmafia/request/UseSkillRequest.java, src/net/sourceforge/kolmafia/session/EquipmentManager.java, src/net/sourceforge/kolmafia/swingui/panel/DailyDeedsPanel.java, src/net/sourceforge/kolmafia/textui/command/GapCommand.java
Also fix an issue where I was displaying 1.0% for 1% drops instead of 1%.
=> feat: more LoL monsters / items

src/data/coinmasters.txt, src/data/equipment.txt, src/data/items.txt, src/net/sourceforge/kolmafia/CoinmasterRegistry.java, src/net/sourceforge/kolmafia/RequestLogger.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/NPCPurchaseRequest.java, src/net/sourceforge/kolmafia/request/ReplicaMrStoreRequest.java, src/net/sourceforge/kolmafia/session/ResultProcessor.java, src/net/sourceforge/kolmafia/swingui/CoinmastersFrame.java, test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
Copied Dinostaur, as this is another store with one currency.
=> feat: add replica mr store

src/data/monsters.txt, src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java
```
> ash get_monster_mapping("Legacy of Loathing")
Returned: aggregate monster [monster]
Boss Bat => Classic Boss Bat
Knob Goblin King => Weirdly Scrawny Knob Goblin King
Bonerdagon => Orignial Bonerdagon
Protector Spectre => Protector Spectre Candidate
Dr. Awkward => Jr. Awkwarj
Lord Spookyraven => Little Lord Spookyraven
The Big Wisniewski => The Little Wisniewski
The Man => The Boy
Groar => Flock of Groars?
```
=> boss mapping for LoL

src/data/monsters.txt
Spaded furry pill and excitement pill.
Others from wiki.
=> feat: more drop rates

src/data/classskills.txt, src/data/equipment.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt
We'll know on Saturday how good Mr. Accessaturday is.
=> feat: dump for mr 2002

src/data/classskills.txt
From the skateboard and dousing accessory.
=> feat: temporary 2002 combat skills

src/net/sourceforge/kolmafia/KoLmafia.java, src/net/sourceforge/kolmafia/request/PlaceRequest.java, src/net/sourceforge/kolmafia/swingui/CalendarFrame.java
Remove comments about "visible for testing" which was a requirement elsewhere but not for KoLmafia.
=> Remove comments

src/data/coinmasters.txt, src/data/defaults.txt, src/data/items.txt, src/net/sourceforge/kolmafia/CoinmasterRegistry.java, src/net/sourceforge/kolmafia/RequestLogger.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/preferences/Preferences.java, src/net/sourceforge/kolmafia/request/MrStore2002Request.java, src/net/sourceforge/kolmafia/request/NPCPurchaseRequest.java, src/net/sourceforge/kolmafia/swingui/CoinmastersFrame.java, src/net/sourceforge/kolmafia/webui/UseLinkDecorator.java
=> Mr. Store 2002

src/data/defaults.txt, src/data/modifiers.txt, src/data/monsters.txt, src/data/statuseffects.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/MrStore2002Request.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, src/net/sourceforge/kolmafia/session/BreakfastManager.java, src/net/sourceforge/kolmafia/webui/ValhallaDecorator.java, test/net/sourceforge/kolmafia/webui/ValhallaDecoratorTest.java
Going to the store directly gets you nothing. Credits carry over between days. Visit in breakfast.
Also warn at gash if you have credits remaining.
=> feat: use the 2002 catalogue in breakfast

src/data/defaults.txt, src/net/sourceforge/kolmafia/objectpool/EffectPool.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/CampgroundRequest.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, test/net/sourceforge/kolmafia/request/CampgroundRequestTest.java, test/root/request/test_campground_tracks_black_monolith_first_use.html, test/root/request/test_campground_tracks_black_monolith_second_use.html
Track _blackMonolithUsed from campground.php?action=monolith
=> Support for giant black monolith in campground

src/data/defaults.txt, src/data/statuseffects.txt, src/net/sourceforge/kolmafia/KoLmafiaCLI.java, src/net/sourceforge/kolmafia/maximizer/Maximizer.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/session/ChoiceAdventures.java, src/net/sourceforge/kolmafia/textui/command/LoathingIdolCommand.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java, test/net/sourceforge/kolmafia/textui/command/LoathingIdolCommandTest.java
I was hoping that if you had "satisfy with coinmasters" it would say "acquire a loathing idol microphone & loathingidol WHATEVER" but it doesn't.
Still, this is good enough for me.
=> feat: add loathingidol command

src/data/coinmasters.txt, src/net/sourceforge/kolmafia/maximizer/Maximizer.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Now that I've actually got the GAP in-run, this wasn't quite right.
=> feat: allow using replica gap from maximizer

src/net/sourceforge/kolmafia/request/GenieRequest.java
This made breakfast make a pocket wish, then use the pocket wish to make 2 other pocket wishes. This isn't quite right.
=> fix: prefer replica genie bottle to pocket wish

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/textui/command/FoldItemCommand.java, test/net/sourceforge/kolmafia/textui/command/FoldItemCommandTest.java
This isn't perfect: the maximizer won't suggest folding unless you've got one of the non-replica foldables in inventory.
Still, that's pretty good.
=> feat: allow folding with the replica garbage tote

src/data/foldgroups.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/textui/command/FoldItemCommand.java, test/net/sourceforge/kolmafia/maximizer/MaximizerCreatableTest.java, test/root/expected/test_get_related_fold.ash.out
Only thought of this one after #1753 went in, but it's both simpler and allows prompting folding without a generated item.
=> feat: allow folding replica garbage tote without items

src/net/sourceforge/kolmafia/CoinmasterData.java, src/net/sourceforge/kolmafia/CoinmasterRegistry.java, src/net/sourceforge/kolmafia/request/DimemasterRequest.java, src/net/sourceforge/kolmafia/request/FunALogRequest.java, src/net/sourceforge/kolmafia/request/GameShoppeRequest.java, src/net/sourceforge/kolmafia/request/MrStore2002Request.java, src/net/sourceforge/kolmafia/request/QuartersmasterRequest.java, src/net/sourceforge/kolmafia/request/SwaggerShopRequest.java
Make `create` work with Mr. Store 2002.
Talking about different people's way of using Mafia -- this is how I normally buy items from NPC stores (when I'm not using `/buy`).
=> fix: allow 'create 3 spooky vhs'

src/data/statuseffects.txt
From excavator and Ezandora's genie script. Checked by trying pocket wishes.
Excavator has many more but I have to check them one-by-one because some of them do work, e.g. Painted-On Bikini and A Little Bit Evil.
=> feat: some more unwishable effects

src/net/sourceforge/kolmafia/session/ChoiceControl.java, src/net/sourceforge/kolmafia/session/ChoiceManager.java, test/net/sourceforge/kolmafia/request/UseItemRequestTest.java, test/root/request/test_microphone_100.html, test/root/request/test_microphone_25.html, test/root/request/test_microphone_50.html, test/root/request/test_microphone_75.html, test/root/request/test_microphone_choice.html
You can maximize to use a microphone.
The first time you select such a boost, your microphone uses a charge - is replaced by a different item - but we did not recognize that happening.
Your next attempt to use the loathingidol command fails, attempting to use the previous microphone.
=> Selecting a song on a Loathing Idol Microphone uses a charge

src/net/sourceforge/kolmafia/request/LocketRequest.java
Noticed my pre-adventure script wasn't being run before using the Combat Lovers Locket.
=> run BetweenBattleScript before locket combats

src/data/items.txt
Wow, look at all those empty ids !
=> feat: name change form item

src/net/sourceforge/kolmafia/maximizer/Maximizer.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
We will re-fold a broken champagne bottle if it has no charges left.
If we folded it already today, that will not reset charges, but we don't know whether we did that.
I clarified the code where that is done and included tests for that behavior.
=> Fold broken champagne bottle to reset charges

src/net/sourceforge/kolmafia/request/CampgroundRequest.java, test/net/sourceforge/kolmafia/request/CampgroundRequestTest.java, test/root/request/test_campground_vampyre.html
https://kolmafia.us/threads/unable-to-parse-housing-in-dark-gyffte-27426.28973/
=> Do not check dwelling if Vampyre

src/net/sourceforge/kolmafia/request/GenieRequest.java
If you've used your replica genie bottle 3 times today, subsequent uses need to use a pocket wish.
=> if depleted replica genie bottle, use pocket wishes

src/net/sourceforge/kolmafia/swingui/panel/CompactSidePane.java
This could feasibly be behind a preference, but why would you not want your favourite familiars to also appear under the category listings?
=> feat: also add favourite familiars to dropdown

src/net/sourceforge/kolmafia/webui/CharPaneDecorator.java
Fixes ***Everything Looks Red*** and colorizes the new effect ***Everything Looks Red, White And Blue***.
Before:
After:
=> Add charpane support for new effect from July 2023's IotM

src/data/classskills.txt, src/data/familiars.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt
Citizen of A Zone is going to need more work: a preference, hooking up to modifiers etc.
Also recognising it in the effects pane: it's not an intrinsic, but `Citizen of A Mob of Zeppelin Protesters (Today)`.
=> feat: patriotic eagle dump

src/net/sourceforge/kolmafia/KoLmafiaCLI.java, src/net/sourceforge/kolmafia/request/LoginRequest.java, src/net/sourceforge/kolmafia/session/PingManager.java, src/net/sourceforge/kolmafia/textui/command/PingCommand.java, src/net/sourceforge/kolmafia/textui/command/ReloginCommand.java
1) the "relog" command will log you out and time you back in, giving you a new server.
2) The "ping" command's third argument specifies verbose logging. Allow it to be "true" or "verbose"
3) Do one extra ping in a ping test before starting to count & measure.
For example,  If the ping command had to time you in, there will be login and a whole 'nother ping test included in the first ping's time.
=> relog command. 'verbose' keyword. Extra first ping.

src/net/sourceforge/kolmafia/persistence/NPCStoreDatabase.java, src/net/sourceforge/kolmafia/session/IslandManager.java
Especially in NPCStoreDatabase.canPurchase.
- alphabetized by shopId
- added comments to identify all shops with their name
- removed abridged dictionary from Barrrtelby's Barrrgain Books
- removed digital key from The Crackpot Mystic's Shed
=> Replace a few if-then-elseif chains with new-style switches

src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
This was spaded in 2020, and it's nice to have integrated.
=> feat: add ASH function for computing sausage goblin chance

src/data/statuseffects.txt, test/net/sourceforge/kolmafia/DataFileTest.java
I have five characters that equip a hookah when running their turns.
```
All Rainbow-y is good quality, but KoLmafia thought it was neutral
Aloofah is good quality, but KoLmafia thought it was neutral
Anti-Burning is good quality, but KoLmafia thought it was neutral
Anti-Creeped is good quality, but KoLmafia thought it was neutral
Anti-Freezing is good quality, but KoLmafia thought it was neutral
Anti-Goosebumped is good quality, but KoLmafia thought it was neutral
Anti-Hurt is good quality, but KoLmafia thought it was neutral
Anti-Odored is good quality, but KoLmafia thought it was neutral
Ashamed is good quality, but KoLmafia thought it was neutral
Bet Your Autumn Dollar is good quality, but KoLmafia thought it was neutral
Bulging Jaw Muscles is good quality, but KoLmafia thought it was …
```
=> more good status effects via hookah

jenkinsfile
Update Jenkins to retry on build/testing 3 times if timed out longer than 15 minutes.
=> Update Jenkins to retry on timeout

test/net/sourceforge/kolmafia/webui/TopMenuDecoratorTest.java, test/root/request/test_awesomemenu_1.html, test/root/request/test_awesomemenu_2.html
Using HTML from Captain Scotch and myself, verify that we will attempt to add script menus to the fancy style of topmenu.
=> tests for awesomemenu decoration

src/net/sourceforge/kolmafia/scripts/ScriptManager.java, src/net/sourceforge/kolmafia/scripts/git/GitManager.java, test/net/sourceforge/kolmafia/scripts/ScriptManagerTest.java, test/net/sourceforge/kolmafia/scripts/git/GitManagerTest.java
Use URL to make identifier for non-GitHub / sourceforge projects (https://kolmafia.us/threads/git-projects-outside-of-github-are-not-named-correctly.29066)
Only return folders when looking for git folders (https://kolmafia.us/threads/error-on-running-git-update-and-on-mafia-start.29067)
=> feat: minor git improvements

src/net/sourceforge/kolmafia/request/UseItemRequest.java, src/net/sourceforge/kolmafia/swingui/OptionsFrame.java
see: https://kolmafia.us/threads/r26152-basicscope-obsolete-comments-by-fredg1-in.27175/
=> Rollback of pref for suppressing messages

src/net/sourceforge/kolmafia/persistence/AdventureSpentDatabase.java, src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, test/net/sourceforge/kolmafia/persistence/AdventureSpentDatabaseTest.java
Keeping track of the turns in a separate Integer in AdventureSpentDatabase to prevent the need to reducing the Map values every time the function is called
=> my_total_turns_spent() to return the sum of all $location[] turns_spent

src/data/monsters.txt
Various PFC spading.
For the drunken rat king, I put the whiskers at 100% from Wildfire testing assuming that only 100% drops didn't burn, but quest items don't burn either, so this was just wrong. Tested again at -100% drop.
=> feat: item drops

src/net/sourceforge/kolmafia/swingui/OptionsFrame.java, src/net/sourceforge/kolmafia/swingui/panel/ConfigQueueingPanel.java, src/net/sourceforge/kolmafia/swingui/panel/PingOptionsPanel.java, src/net/sourceforge/kolmafia/swingui/widget/PreferenceCheckBox.java, src/net/sourceforge/kolmafia/swingui/widget/PreferenceFloatTextField.java, src/net/sourceforge/kolmafia/swingui/widget/PreferenceIntegerTextField.java
Primarily, moved pingStealthyTimein checkbox to a panel with TimeInButton - which is in Preferences/General/Connection Options but not in LoginFrame/Connection
=> Tweak PingOptionsPanel so that 3 triggers will fit on LoginFrame

src/data/coinmasters.txt, src/data/concoctions.txt, src/net/sourceforge/kolmafia/KoLConstants.java, src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java, src/net/sourceforge/kolmafia/request/CreateItemRequest.java, src/net/sourceforge/kolmafia/request/FixodentRequest.java
Add store for using fixodent.
Also add some refactors in ConcoctionDatabase (new switches).
Also correct some things I thought were issues in ConcoctionDatabase:
* being able to smith for free doesn't let you make awesome items for free
* add no shaker excuse if you don't have a shaker, instead of only if you do
=> feat: fixodent store

src/data/monsters.txt
Trickling these in. Also add a couple of others from the wiki.
The LOV Enforcer's condition is to kill using only regular attacks. The LOV Engineer's condition is to kill using only spells.
=> feat: item drops: gingerbread train station

src/net/sourceforge/kolmafia/objectpool/EffectPool.java, src/net/sourceforge/kolmafia/request/FightRequest.java
Make it easier to tell when a drop came from serendipity.
=> feat: log serendipity message before additional drop

src/data/adventures.txt, src/data/combats.txt, src/data/items.txt, src/data/monsters.txt, src/net/sourceforge/kolmafia/AscensionPath.java, src/net/sourceforge/kolmafia/KoLCharacter.java, src/net/sourceforge/kolmafia/session/EquipmentManager.java
Locations / monsters / path, path ignores stat requirements.
Haven't spaded all the monsters yet but did check ncle, daddy shortlegs and rutabaga bug, and they all matched 50 equipment / 30 potion so I think it's reasonably likely.
=> feat: more small stuff

src/net/sourceforge/kolmafia/textui/Parser.java
=> revert untested breaking parser change

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/webui/ValhallaDecorator.java
Currently Trip Scrip and the t2, 3 and 4 Cookbook Bat foods.
=> feat: add reminder to collect untradable pulls

src/data/monsters.txt
=> Sloppy Seconds Meat-inflating and sugar cubes are nopp

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/UseSkillRequest.java
Also fix the `AVOID_REMOVAL_ONLY` count.
=> fix: use the baywatch to reduce mp cost if available

src/data/monsters.txt
Quick data drop before I head off to France for the rest of the week.
=> feat: sparkling orb from Very Mad Scientist, sausage drops from wiki

src/net/sourceforge/kolmafia/KoLCharacter.java, test/net/sourceforge/kolmafia/ModifiersTest.java
As reported in https://kolmafia.us/threads/august-scepter.29095/#post-173259.
=> fix: umbrella bonuses are doubled by offhand remarkable

src/net/sourceforge/kolmafia/AscensionPath.java, src/net/sourceforge/kolmafia/preferences/Preferences.java
[Reset monsterHabitats prefs on ascension]
=> Habitat reset

src/net/sourceforge/kolmafia/request/FightRequest.java
=> feat: failed perpetrate casts no longer consume charges

src/data/modifiers.txt
Can't add Arachnelf. You might be able to add Pixel Rock, I don't have one.
=> feat: throne familiars since last update

src/data/classskills.txt, src/data/modifiers.txt, src/net/sourceforge/kolmafia/KoLCharacter.java, src/net/sourceforge/kolmafia/ModifierType.java, src/net/sourceforge/kolmafia/Modifiers.java, src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java, src/net/sourceforge/kolmafia/persistence/SkillDatabase.java, test/net/sourceforge/kolmafia/DebugModifiersTest.java, test/net/sourceforge/kolmafia/request/ChateauRequestTest.java
Add Noncombat / Passive category for Disco Nap.
=> feat: store free rests in modifiers

src/data/modifiers.txt
The "Insatiable Hunger" effect is listed as having +5 stomach capacity since the organ update a few days ago. There is an Insatiable Hunger that does provide +5 stomach capacity, but it is a skill.
=> Fix Insatiable Hunger

src/data/monsters.txt
I think this is all the ones that actually exist as separate monsters:
* butts are somebody else's butt with a flag
* elfbots became elfborgs
* hard mode dread bosses are the same as normal ones
* all slime tube monsters are the same as each other
* intelligent alien is not actually a monster
=> feat: fix some negative ids

src/data/defaults.txt, src/net/sourceforge/kolmafia/request/GrandpaRequest.java, src/net/sourceforge/kolmafia/session/BeachManager.java, src/net/sourceforge/kolmafia/session/ResponseTextParser.java, test/net/sourceforge/kolmafia/request/GrandpaRequestTest.java, test/net/sourceforge/kolmafia/session/BeachManagerTest.java, test/root/request/test_beach_twinkles.html, test/root/request/test_grandpa_hierfal.html
New property: "hasTwinkleVision".
1) set when you ask grandpa about hierfal
2) set if we see twinkles on a beach
=> detect TwinkleVision with grandpa and when parsing beach

src/net/sourceforge/kolmafia/chat/ChatManager.java, src/net/sourceforge/kolmafia/request/ApiRequest.java
- Refresh inventory when devsters spawn an item
- Replace some heavily nested ternaries with enchanced switch statements
=> Refresh inventory when devsters spawn items

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/webui/ValhallaDecorator.java
Fix item id for roasted vegetable of Jarlsberg.
Fix "acquire" command.
=> feat: fix some valhalla pull issues

src/net/sourceforge/kolmafia/request/CampAwayRequest.java, test/net/sourceforge/kolmafia/request/CampAwayRequestTest.java, test/root/request/test_campaway_free.html, test/root/request/test_campaway_non_free.html
Progresses one of the issues in https://kolmafia.us/threads/mafia-setting-timesrested-to-0-on-login.29268/
=> feat: detect whether we have free rests at campaway

src/data/modifiers.txt
Add those missing; add comments for those impossible to add (by wiki).
=> feat: more throne enchants

src/data/monsters.txt
The condition is that at most one costume can drop (like the scarab beatle shirts).
=> feat: halloween 2008 drop rates

src/data/consequences.txt, src/data/defaults.txt, src/data/items.txt, src/data/modifiers.txt, src/net/sourceforge/kolmafia/KoLmafiaCLI.java, src/net/sourceforge/kolmafia/preferences/Preferences.java, src/net/sourceforge/kolmafia/request/LedCandleRequest.java, src/net/sourceforge/kolmafia/session/ChoiceControl.java, src/net/sourceforge/kolmafia/textui/command/LedCandleCommand.java, src/net/sourceforge/kolmafia/textui/command/SaberCommand.java, test/internal/helpers/Networking.java, test/net/sourceforge/kolmafia/session/ConsequenceManagerTest.java, test/net/sourceforge/kolmafia/textui/command/LedCandleCommandTest.java, test/root/request/test_desc_item_led_candle_disco.html, test/root/request/test_desc_item_led_candle_reading.html, test/root/request/test_desc_item_led_candle_red_light.html, test/root/request/test_desc_item_led_candle_ultraviolet.html
Read mode from item description, or from choice result.
Add command for adjusting candle (`ledcandle`).
Add modifiers: to my understanding, fairy / lep are weight and volley / sombrero are effectiveness. Perhaps this may change.
=> feat: led candle modes

src/data/monsters.txt
=> Missed no pickpocket items last PR

src/data/outfits.txt, src/net/sourceforge/kolmafia/SpecialOutfit.java, src/net/sourceforge/kolmafia/persistence/EquipmentDatabase.java, src/net/sourceforge/kolmafia/request/CustomOutfitRequest.java, src/net/sourceforge/kolmafia/session/ChoiceAdventures.java, src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, test/net/sourceforge/kolmafia/persistence/EquipmentDatabaseTest.java
Fixes https://kolmafia.us/threads/outfit_treats-returns-empty-aggregate-for-outfits-with-multiple-treats.29327/
- Add chances for outfit treats
- Remove choice for gift shop from The Shore
- Formatting
=> Support Halloween treats that are randomly selected

src/data/monsters.txt
funky junk key conditional is that it starts at 5 and increases by 5% each time one fails to drop.
Worse Homes and Gardens conditional is like the funky junk key but it only happens after your third funky junk key.
=> feat: ellsburys claim monsters, start spacegate, other misc

src/data/classskills.txt, src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/data/monsters.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/objectpool/SkillPool.java, src/net/sourceforge/kolmafia/request/FightRequest.java, src/net/sourceforge/kolmafia/session/EquipmentManager.java
Embezzler visor drop rate.
Note McTwist gives +75% item.
Fix Jill LED candle modifiers to be on candle, not Jill.
=> feat: skeleton franken stein, misc changes

src/data/items.txt, src/data/monsters.txt, src/data/statuseffects.txt
=> feat: autumnic bomb is multi-usable, gives effect

src/data/familiars.txt, src/data/items.txt, src/data/modifiers.txt
This is all right as of now but it feels like some casing should change and some plurals are clearly wrong
=> Last leaves items

src/data/familiars.txt, src/data/items.txt, src/data/modifiers.txt
- Capitalisation changed on familiar, plurals have been added, Throne passive spaded
=> Some more leaf tweaks

src/data/monsters.txt
White Wednesday penguins / yeti, Gnollish Bodybuilder.
Mark more conditional items.
Mark some unencounterable monsters as NOCOPY.
Mark the leaves from the new monsters as 100%, but it would be nice to do the multi-drop properly (i.e. the first one drops 6-8, the second drops ~100-150)
=> feat: early monster items

test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
=> tests: skills with modifiers should be passive

src/net/sourceforge/kolmafia/KoLCharacter.java
Not tested because I'm not going into Small, but I think this should fix the issues people have been having with Drinking to Drink not applying.
=> fix: small cannot expand liver / stomach

src/data/adventures.txt, src/data/combats.txt, src/data/monsters.txt
ID badge condition is that it's a post-combat drop from the first wardrobot killed (per day? ever?).
=> feat: add TTT jet monsters

src/data/monsters.txt
Only about 500 turns each, but seems fairly likely.
=> feat: automa-core rates

src/data/monsters.txt
I tried with snokebomb, malibustacey tried with Asdon Martin
=> toxic beastie cannot be banished

src/data/modifiers.txt, src/data/statuseffects.txt
Also the booze gives an effect.
=> feat: hobeep clothing now more powerful

src/data/monsters.txt
Cannon leaked another wishable monster (in March)
=> feat: add falcoer

src/data/classskills.txt, src/data/equipment.txt, src/data/familiars.txt, src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/monsters.txt, src/data/npcstores.txt, src/data/outfits.txt, src/data/statuseffects.txt, src/net/sourceforge/kolmafia/persistence/FamiliarDatabase.java
This is almost all automated (putting the monsters in a nicely named and positioned block in monsters.txt is the only thing I did manually, as well as rearrange some of the blocks in there).
I am not 100% sure that this is all kosher so please give it a look over. If it works well, I can put the code up for others to use in future. I wrote it in TypeScript.
=> Result of a tool I made today to automatically make patches from session log readouts when new content arrives

src/net/sourceforge/kolmafia/session/LoginManager.java
Temp reset instead of #2010, left a todo to remove next month
=> reset pingDefaultTestPage if set to api.php

src/data/items.txt
Also update Asdon Martin keyfob (on ring) from podcast for G-Lover.
=> feat: update plurals from museum

src/net/sourceforge/kolmafia/AreaCombatData.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java
this was simplified by all the monsters having the same prefix (so far). gonna be gone for a bit so if there's any todos feel free to add them or i can finish it up when I'm home this evening
=> set appearance rates for crimbo23 monsters

src/net/sourceforge/kolmafia/request/MallSearchRequest.java, test/internal/helpers/Player.java, test/net/sourceforge/kolmafia/webui/MallSearchDecoratorTest.java
Highlight your own store in blue in the relay browser's mall search.
This is nice if you want to see at a glance whether you're selling something, and whether it's likely to sell / too low / whatever.
=> feat: highlight own store in relay browser

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/FightRequest.java, src/net/sourceforge/kolmafia/session/BanishManager.java
Add the crimbo banishes.
Assume they reset at rollover.
=> feat: add crimbo23 banishes

src/data/coinmasters.txt, src/data/equipment.txt, src/data/fullness.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt, src/net/sourceforge/kolmafia/CoinmasterRegistry.java, src/net/sourceforge/kolmafia/request/Crimbo23ElfFactoryRequest.java, src/net/sourceforge/kolmafia/request/NPCPurchaseRequest.java, src/net/sourceforge/kolmafia/swingui/CoinmastersFrame.java
Effects are mixed around due to use of https://github.com/kolmafia/kolmafia-ingest/. It probably won't happen again. Some comments changed accordingly.
Add coinmaster for elf factory.
`checkpowers` run and equipment updated.
=> feat: new Crimbo items

src/data/coinmasters.txt, src/data/fullness.txt, src/data/inebriety.txt
Also add Junkworks to coinmasters.txt.
=> feat: fill in consumable data where we have a reasonable guess

src/net/sourceforge/kolmafia/objectpool/EffectPool.java, src/net/sourceforge/kolmafia/request/UneffectRequest.java, src/net/sourceforge/kolmafia/webui/CharPaneDecorator.java
Do what we do for the other "Everything Looks" effects but for Green.
=> feat: everything looks green color + noremove

src/data/dailylimits.txt, src/data/defaults.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/DrinkItemRequest.java, src/net/sourceforge/kolmafia/request/EatItemRequest.java, src/net/sourceforge/kolmafia/request/SpleenItemRequest.java
Hodgman drops to come, apparently.
For daily limits, I copied fudge spork in putting them in both Eat and Use (or Drink and Use).
=> feat: most Hobopolis boss consumables are now once/day

src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/data/monsters.txt, src/data/outfits.txt, src/data/statuseffects.txt
Also add a couple more item drops (bugbears from wiki, warehouse worker from PFC)
=> feat: adobe items

src/net/sourceforge/kolmafia/DeadlockDetector.java, src/net/sourceforge/kolmafia/KoLmafia.java
Copied the deadlock detector from #1889
IMO it is worth preserving regardless of what happens with #1889.
=> Deadlock Detector

build.gradle
Fix the gradle warnings as reported in #2177.
=> fix: gradle warnings

src/data/equipment.txt, src/data/items.txt, src/data/pulverize.txt, src/data/spleenhit.txt
Also update some powers and moss floss plural.
=> feat: moss mulch

build.gradle, src/net/sourceforge/kolmafia/DeadlockDetector.java, src/net/sourceforge/kolmafia/KoLConstants.java, src/net/sourceforge/kolmafia/equipment/SlotSet.java, src/net/sourceforge/kolmafia/maximizer/Evaluator.java, src/net/sourceforge/kolmafia/persistence/ItemDatabase.java, src/net/sourceforge/kolmafia/persistence/ModifierDatabase.java, src/net/sourceforge/kolmafia/request/ClanFortuneRequest.java, src/net/sourceforge/kolmafia/request/RelayRequest.java, src/net/sourceforge/kolmafia/request/ShowClanRequest.java, src/net/sourceforge/kolmafia/session/EquipmentManager.java, src/net/sourceforge/kolmafia/session/TowerDoorManager.java, src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, src/net/sourceforge/kolmafia/textui/command/ColdMedicineCabinetCommand.java, src/net/sourceforge/kolmafia/textui/javascript/AshStub.java, src/net/sourceforge/kolmafia/utilities/ResettingHttpClient.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java, test/net/sourceforge/kolmafia/request/UseItemRequestTest.java, test/net/sourceforge/kolmafia/textui/ScriptData.java, test/net/sourceforge/kolmafia/utilities/StringUtilitiesTest.java
Not particularly keen on the blowing up of one-liners, but it is what it is.
=> feat: update plugins, run spotless

src/data/defaults.txt, src/net/sourceforge/kolmafia/objectpool/SkillPool.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, src/net/sourceforge/kolmafia/session/ResponseTextParser.java
=> feat: add skill level pref for kokomo

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/webui/UseLinkDecorator.java
... and therefore the Use Link cannot be inline.
=> Black and White Apron Meal Kit leads to a choice

src/data/fullness.txt, src/data/inebriety.txt
=> feat: post-crimbo 2023 food / drink stats

src/data/monsters.txt
Not sure about these given how factory workers / overseers came out, but it does seem like this is it.
Also when I first added these way back I put the male overseer's drops on the female. Oops.
=> feat: velvet mine drop rates

src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt
Also set the name to the mall-searchable ones, instead of the ones that appear in-game.
=> feat: crimbo 23 tiny plastic effects

src/data/defaults.txt, src/data/equipment.txt, src/data/monsters.txt, src/net/sourceforge/kolmafia/AscensionPath.java, src/net/sourceforge/kolmafia/KoLCharacter.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java, src/net/sourceforge/kolmafia/request/RelayRequest.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, src/net/sourceforge/kolmafia/session/ChoiceControl.java
Will undraft after Boss Bat / Goblin King / Man replacements are known.
=> feat: wereprof boss replacements

data/SVN/svnrepo.json
Ezandora has now updated all of her scripts to support git install, and to be preferably installed from the master branch.
Update our JSON collections of known scripts accordingly.
=> feat: update all Ezan's scripts to recommended git install

src/data/classskills.txt, src/data/concoctions.txt, src/net/sourceforge/kolmafia/KoLCharacter.java, src/net/sourceforge/kolmafia/KoLConstants.java, src/net/sourceforge/kolmafia/objectpool/EffectPool.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java, src/net/sourceforge/kolmafia/request/CreateItemRequest.java, src/net/sourceforge/kolmafia/request/FightRequest.java
1) Add Beast skills
2) Add recipes for things you can create at the Tinkering Bench.
Added a TINKER crafting method to the enum.
I have no yet made it usable by creating a Request class to implement it.
3) If you have a "focused magnetron pistol" equipped as your weapon, you can pickpocket, either as a Beast or as a Professor.
=> WereProfessor stuff

src/net/sourceforge/kolmafia/session/ChoiceControl.java
Match case of html as received (balm != Balm)
=> Update ChoiceControl.java for WereProf Liver

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/RelayRequest.java, test/net/sourceforge/kolmafia/request/RelayRequestWarningsTest.java
I wrote the code and the test at level 8 and tested it in the browser as soon as I hit level 10.
Unsurprisingly, it worked. ;)
=> Relay warning for equipping spring shoes for coffee grounds

src/net/sourceforge/kolmafia/KoLmafia.java, src/net/sourceforge/kolmafia/session/ChoiceControl.java, src/net/sourceforge/kolmafia/session/ResultProcessor.java, src/net/sourceforge/kolmafia/session/SorceressLairManager.java, src/net/sourceforge/kolmafia/swingui/panel/CompactSidePane.java, test/net/sourceforge/kolmafia/session/ChoiceControlTest.java, test/root/request/test_mild_mannered_professor_contest_booth.html, test/root/request/test_savage_beast_contest_booth.html, test/root/request/test_savage_beast_effect.html, test/root/request/test_wereprofessor_contest_booth.html
Also add a Character Listener to the Compact Side Pane, so it will refresh when this happens.
=> recalculate adjustments when switch between Savage Beast <-> Mild-Mannered Professor

data/SVN/svnrepo.json
This now deploys from a branch. I will add a script to the main branch that uninstalls itself and installs the new version, and keep that in for say 6 months.
=> Update svnrepo.json for Excavator

src/net/sourceforge/kolmafia/session/RufusManager.java, src/net/sourceforge/kolmafia/webui/StationaryButtonDecorator.java, test/net/sourceforge/kolmafia/session/RufusManagerTest.java, test/root/request/test_call_rufus_salad.html
```
"First thing. Salad a big shadow entity. Salad the place salad rifts salad to. It's a tongue. Salad. a big tongue, salad far as Salad can salad He pauses.
"I've also salad an artifact I need somebody to recover for me. A shadow bucket," salad continues.
After salad moment Salad speaks again. "I can also always salad salad of more mundane items from the rifts. Right now, 3 salad salad would be valuable."
```
Figuring out what "3 salad salad" is fails - and previously threw an NPE.
=> Rufus salad

src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt
Skeleton the items / effects.
Going to inventory.php?action=apriling allows you to:
* change intrinsic every 11 turns
* select two items, each of which has a 3/day effect
* one of which is an NC force
I'll probably create a command for picking instruments / effects if nobody else gets to it first.
So there'll be a fair amount of follow up.
=> feat: apriling band skeleton

src/net/sourceforge/kolmafia/RequestEditorKit.java, src/net/sourceforge/kolmafia/webui/StationaryButtonDecorator.java, test/net/sourceforge/kolmafia/RequestEditorKitTest.java, test/root/request/test_cyrpt_empty.html, test/root/request/test_cyrpt_four_corners.html, test/root/request/test_cyrpt_haert.html
I provided test fixtures for a Cyrpt with 4 active corners, just the Haert, and empty.
I wrote tests to verify that we decorate those cases correctly - and also that we do not decorate if there are no corners but the evilness properties are incorrect.
=> Improve Evilometer decorating

src/net/sourceforge/kolmafia/KoLmafiaCLI.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/GenericRequest.java, src/net/sourceforge/kolmafia/textui/command/AprilBandCommand.java, test/internal/helpers/Networking.java, test/net/sourceforge/kolmafia/textui/command/AprilBandCommandTest.java
Command for getting an effect or instrument, or playing an instrument.
=> feat: apriling band command

src/net/sourceforge/kolmafia/session/LoginManager.java
=> fix: remove Jan 2024 temporary fix

src/net/sourceforge/kolmafia/session/ChoiceControl.java
Ref #2091.
Took a while for someone to put the last choice on the wiki.
=> feat: set frat war start candy cane absence preferences

src/net/sourceforge/kolmafia/textui/TypescriptDefinition.java, src/net/sourceforge/kolmafia/textui/javascript/AshStub.java, test/net/sourceforge/kolmafia/textui/TypescriptDefinitionTest.java
* Merge related library function overloads into a single signature with optional parameters
* Strip trailing undefined function args
=> Mark typescript parameters as optional

src/net/sourceforge/kolmafia/persistence/HolidayDatabase.java, src/net/sourceforge/kolmafia/utilities/StringUtilities.java, test/net/sourceforge/kolmafia/persistence/HolidayDatabaseTest.java, test/net/sourceforge/kolmafia/utilities/StringUtilitiesTest.java
Since KoLmafia turns 20 this year (first commit https://github.com/kolmafia/kolmafia/commit/90cdd5f3bda502278beef2ad2b8b43d8e17efd4d) I thought it might be nice to mark that date for our users to see.
=> Celebrate KoLmafia's birthday

src/net/sourceforge/kolmafia/AscensionPath.java
As #2337 lead to discussion, add just the path in a separate PR.
=> feat: add 11 things as valid path

src/net/sourceforge/kolmafia/persistence/DebugDatabase.java
I routinely run IntelliJ's analyze on a file I am working in.  I was  working in DebugDatabase and there was so much that could be cleaned up that it obscured the code I was changing.  So there are no changes in this file other than what the tool suggested.  Most of them are the usual suspects "static final" and not using isEmpty().
=> Remove some lint found by static analysis

.classpath, build.gradle
I have been running 1.7.15 for a couple of weeks and all the big JavaScript projects work well (as do all of the small ones!)
=> Upgrade Rhino to 1.7.15

src/data/defaults.txt
Set default value for "Eye-eye-eye!", Choice adventure 1528.
=> Eye-eye-eye!

src/data/familiars.txt
so mafia knows the mini kiwi can equip the aviator goggles
=> mini kiwi fam equip

src/net/sourceforge/kolmafia/objectpool/Concoction.java, test/net/sourceforge/kolmafia/objectpool/ConcoctionTest.java
As reported in https://kolmafia.us/threads/ronin-crafting-of-mini-kiwi-intoxicating-sprits.29800/
=> fix: need kiwis to buy intoxicating spirits

src/data/modifiers.txt, src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java
Seems worth having this so I don't need to go to the wiki to look it up ;)
=> feat: add combat item damage percent as a modifier

src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java
Mayam Calendar is a free pull, and this is causing problems for people, and I think this is the fix.
=> fix: mayam calendar is not available in bad moon

src/data/equipment.txt, test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
- **Add consistency check for repeated and non-disambiguated equipment in equipment.txt**
- **Remove data inconsistency violation**
=> Catch duplicate items in equipment.txt

src/net/sourceforge/kolmafia/session/EquipmentManager.java
Is this it? Is there anything left outstanding?
=> Add conditional skills for candelabra

src/data/familiars.txt, src/data/items.txt, src/data/modifiers.txt
evolving organism needs more types but I don't know whether the HP/MP is mosquito-like or whelp-like.
=> feat: extra ooze, backfill modifiers

src/net/sourceforge/kolmafia/MonsterData.java
Otherwise users get "Unrecognized monster modifier: mimeo" warnings
=> Add new monster modifier to recognised set

src/data/equipment.txt, src/data/familiars.txt, src/data/monsters.txt
Messenger Bag RNA power.
Evolving organism is apparently whelp / potato.
Rare drops are probably 0.1% but it's hard to tell at that level. Somebody did get drops at -130%.
Provide images for all monsters: some fanmade projects are using the data directly.
=> feat: more twitch stuff

src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt
I made enough dumb comments in /dev that Jick gave me my own custom item to represent it. Sorry if it is gauche to add your own custom item, I just want to script such that I always equip it for nightcap.
=> New item (a custom one!)

src/data/equipment.txt, src/data/modifiers.txt, src/data/statuseffects.txt
Comes from using the head of emberg lettuce, then eating something. I was tempted to add "use head of emberg lettuce" as a source, but it's not quite right.
=> feat: lettuce rejoice

src/data/monsters.txt
100% with 50% rejection rate, one-time per ascension
=> feat: neptune flytrap pellet rate

src/data/coinmasters.txt, src/data/defaults.txt, src/net/sourceforge/kolmafia/CoinmasterRegistry.java, src/net/sourceforge/kolmafia/RequestLogger.java, src/net/sourceforge/kolmafia/request/NPCPurchaseRequest.java, src/net/sourceforge/kolmafia/request/SeptEmberCenserRequest.java, src/net/sourceforge/kolmafia/swingui/CoinmastersFrame.java, test/net/sourceforge/kolmafia/request/UseItemRequestTest.java
Also uncomment a passing commented out test.
=> feat: sept ember censer coinmaster

src/net/sourceforge/kolmafia/textui/TypescriptDefinition.java, src/net/sourceforge/kolmafia/textui/javascript/EnumeratedWrapperPrototype.java, src/net/sourceforge/kolmafia/textui/javascript/JavascriptRuntime.java, src/net/sourceforge/kolmafia/textui/parsetree/TypeList.java, test/root/expected/mafia_classes.js.out, test/root/scripts/mafia_classes.js
This is useful for tooling scripts like https://github.com/loathers/libram amongst others!
=> Add array of all MafiaClasses to JS stdlib

src/data/defaults.txt, src/net/sourceforge/kolmafia/request/VolcanoIslandRequest.java, test/net/sourceforge/kolmafia/request/VolcanoIslandRequestTest.java
Mostly for my own automation use, adds a preference that tracks the ten slime harvests you get in a day.
=> Adding preference to track slime vials harvested in a day

test/internal/helpers/Maximizer.java, test/internal/matchers/Maximizer.java, test/internal/matchers/Preference.java, test/internal/matchers/SignMatcher.java, test/net/sourceforge/kolmafia/maximizer/MaximizerCreatableTest.java, test/net/sourceforge/kolmafia/maximizer/MaximizerRegressionTest.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Main benefit is better messages on failure.
=> tests: use hamcrest matcher for maximizer custom assertions

test/net/sourceforge/kolmafia/request/AccountRequestTest.java, test/net/sourceforge/kolmafia/request/GrandpaRequestTest.java, test/net/sourceforge/kolmafia/session/BeachManagerTest.java, test/net/sourceforge/kolmafia/session/CryptManagerTest.java
i expect these were copy/paste mistakes
=> fix incorrect test packages

src/data/modifiers.txt, src/net/sourceforge/kolmafia/KoLAdventure.java, src/net/sourceforge/kolmafia/modifiers/BooleanModifier.java
=> Always Fumble boolean modifier

src/data/modifiers.txt
=> feat: yes, can haz is like o hai

src/data/modifiers.txt
=> Suburbs of Dis & Haiku Dungeon alter page text

src/data/monsterparts.txt
I feel like General Bruise probably has four arms but the data's from excavator.
=> feat: some boss monster parts

src/data/familiars.txt, src/net/sourceforge/kolmafia/session/TrackManager.java
Also more confident Hunt is 3/ignore queue.
=> feat: cookbookbat is undead

src/net/sourceforge/kolmafia/session/ChoiceManager.java
I started rolling this out to different invoked user scripts, but the usage type varies a bit too much to make into a single non-complicated function
=> Allow users to set custom entrypoints for choiceAdventureScripts using atsign syntax

src/data/equipment.txt, src/data/statuseffects.txt, src/net/sourceforge/kolmafia/maximizer/Maximizer.java, src/net/sourceforge/kolmafia/request/ClosetRequest.java, src/net/sourceforge/kolmafia/request/MallPurchaseRequest.java, src/net/sourceforge/kolmafia/request/TransferItemRequest.java, src/net/sourceforge/kolmafia/session/ChoiceAdventures.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Change some meat entries to longs. Untested as I don't have over 2b meat.
=> feat: bat wings airship spoilers, aprilband to maximizer

src/net/sourceforge/kolmafia/session/EquipmentManager.java, src/net/sourceforge/kolmafia/session/InventoryManager.java, src/net/sourceforge/kolmafia/session/ResultProcessor.java, test/net/sourceforge/kolmafia/request/UseSkillRequestTest.java
Necessary to make #2460 work properly.
=> feat: make bat wings rest always available

src/net/sourceforge/kolmafia/textui/javascript/JSONValueConverter.java, test/net/sourceforge/kolmafia/request/RelayRequestTest.java, test/root/request/test_relay_request_identity_with_loops_location.json
The algorithm for identifierString was incorrect for Location, Servant, and Thrall types.
=> JSON API: fix generation of identifierString and test.

src/net/sourceforge/kolmafia/KoLAdventure.java, test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java
- **Cannot adventure in Boss Bat's Lair after completing the quest**
- **Test for Boss Bat Lair access**
=> Fix canAdventure for Boss Bat Lair post quest finish

src/data/concoctions.txt, src/data/familiars.txt, src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt
- **Peace Turkey skeleton**
- **Add modifiers for Helping Fingers**
Should peace turkey be `drops,other1,hp1,mp1` or should those just be wrapped up in `variable`? Whether it does each of those things is dependent on some state (what step of the apparent cycle it is in). In any case, it will also have `block,delevel,passive` as it has those abilities all the time.
For reference:
```
```
=> Peace Turkey skeleton

src/data/modifiers.txt, src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java
Also remove hat drop / accessory drop etc. as I don't think these are
in-game.
=> feat: add remaining video... games? effects

src/net/sourceforge/kolmafia/request/FightRequest.java, test/net/sourceforge/kolmafia/request/FightRequestTest.java
Fixes a possible NPE issue with #2501, thanks @libraryaddict.
=> CBB: lastVisitedLocation can be null.

src/net/sourceforge/kolmafia/RequestThread.java
Saw someone make a joke along these lines, I think it would be fun to include
=> Some harmless fun :)

src/data/items.txt
=> Mark whalecake as no-discard

src/data/familiars.txt
These aren't complete, several familiars have tags we don't know or haven't documented. These are simply the known tags that are as of yet unupdated.
=> Update several familiar tags

src/data/fullness.txt, src/data/items.txt, src/data/modifiers.txt
On #2509, noticed that some of the other Crimbo items were also no-discard.
Also some older items have lost their autosell.
=> feat: checkitems updates

src/data/fullness.txt, src/data/inebriety.txt
=> feat: peaza / peasco sour stats

src/data/classskills.txt, src/data/equipment.txt, src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/outfits.txt, src/data/statuseffects.txt, src/data/zapgroups.txt
Some items remain (e.g. familiar hatchlings) but seems enough for a first skeleton.
=> feat: initial dec iotm dump

src/data/familiars.txt, src/data/items.txt
=> feat: takerspace items

src/data/classskills.txt, src/data/equipment.txt, src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt
Monsters / shops to come later.
=> feat: dec item dump

src/data/adventures.txt, src/data/defaults.txt, src/data/items.txt, src/data/monsterparts.txt, src/data/zonelist.txt, src/net/sourceforge/kolmafia/session/ChoiceAdventures.java
Holiday -> Crimbo24 -> Holiday Islands -> Easter Island
plurals
monster parts detected when looking at Manuel
=> crimbo24 tweaks

src/data/combats.txt, src/net/sourceforge/kolmafia/combat/CustomCombatLookup.java
1) Add St. Patrick's Day Island monsters to combats.txt
2) All CCS to match not only monster and adventure location, but adventure zone
=> Add St. Patrick's Day Island monsters to area

src/net/sourceforge/kolmafia/request/FightRequest.java
Avoiding the ones where I thought there might be a reason for it, or there was symmetry, or I thought we were better off not doing it.
Convert all the switch-cases to ones without breaks because these are prime places for people forgetting to put breaks in (there was one in Fist -> Peace Turkey).
=> chore: accept many intellij suggestions for FightRequest

src/net/sourceforge/kolmafia/request/NPCPurchaseRequest.java, src/net/sourceforge/kolmafia/request/SpinMasterLatheRequest.java
Part two of making coinmasters that can handle shop.php with multi-cost items.
1) I split parseShopInventory() out of parseShopResponse().
This means I will be able to write tests on that functionality without all the quest updating done in the latter.
2) Logging of new coinmaster rows now groups them. Thus:
```
--------------------
Crimbo24 Cafe	ROW1527	chocolate ostrich egg	Spirit of Easter (15)
Crimbo24 Cafe	ROW1528	candied beef and cabbage	Spirit of St. Patrick's Day (15)
Crimbo24 Cafe	ROW1529	candy rations	Spirit of Veteran's Day (15)
Crimbo24 Cafe	ROW1530	double-candied yams	Spirit of Thanksgiving (15)
--------------------
--------------------
Crimbo24 Bar	ROW1521	Easter grasshopper	Spirit of Easter (15)
Crimbo24 Bar	ROW1522	Irish eggnog	Spirit of St. Patrick's Day (15)
Crimbo24 Bar …
```
=> Part two of fancy shop.php Coinmasters

src/data/concoctions.txt, src/data/items.txt, src/data/modifiers.txt, src/data/monsterparts.txt, src/data/monsters.txt, src/data/spleenhit.txt
Not certain gravy skin smithing is ASMITH, but it's not SAM and you need some skill, so it probably is.
=> feat: santa claus

src/net/sourceforge/kolmafia/session/ChoiceControl.java
This will prevent it from showing up in NC queue, etc.
=> Differentiate this Egg is walkable.

src/data/classskills.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt
Candies obtained from the candy egg deviler choice adventure using:
```
js var x = visitUrl("choice.php"); xpath(x, "//option/@value").filter(x
=> x!=0).map(x => Item.get(x)).filter(x => !x.candy)
```
=> feat: standard effects, more candies

src/data/defaults.txt, src/net/sourceforge/kolmafia/objectpool/Concoction.java, src/net/sourceforge/kolmafia/objectpool/EffectPool.java, src/net/sourceforge/kolmafia/objectpool/SkillPool.java, src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java, src/net/sourceforge/kolmafia/request/CreateItemRequest.java, src/net/sourceforge/kolmafia/session/InventoryManager.java, src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
Add the functions 
* free_crafts()
* free_cooks()
* free_mixes()
* free_smiths()
exposing how many of each resource you have.
Support the three new Crimbo skills (one from this year, two from last year).
=> feat: free craft skills, expose ASH functions

src/data/items.txt, src/data/modifiers.txt, src/data/npcstores.txt, src/data/spleenhit.txt, src/data/statuseffects.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/persistence/NPCStoreDatabase.java, src/net/sourceforge/kolmafia/request/NPCPurchaseRequest.java
This includes the fix to make unknown NPC stores log items in npcstores.txt format.
=> Add Hack Market NPC store

src/data/equipment.txt, src/data/fullness.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/spleenhit.txt, src/data/statuseffects.txt
=> feat: item dump from mall

src/net/sourceforge/kolmafia/session/ChoiceControl.java
If the ingredients have changed, the items we can make have also changed.
=> fix: refresh concoctions on takerspace visit

src/net/sourceforge/kolmafia/KoLCharacter.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, src/net/sourceforge/kolmafia/session/ResultProcessor.java
It's easy to find bugs when you actually ascend ;)
=> fix: pirate dinghy unlocks island on use, not on obtain

src/data/defaults.txt, src/data/monsters.txt
Also Nas spaded the hacker drops.
=> feat: do not autoburn for crimbo +/- combat skills

src/net/sourceforge/kolmafia/textui/DataTypes.java
This will also change the behaviour of `$item[1]` to be `1` instead of `seal-clubbing club`, which I figure is fine... but I'll think more overnight.
=> feat: make $item[0] match the item called '0'

src/data/dailylimits.txt, src/data/defaults.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/objectpool/SkillPool.java, src/net/sourceforge/kolmafia/request/FightRequest.java, src/net/sourceforge/kolmafia/session/EquipmentManager.java
Shame that #2462 wasn't finished.
=> feat: add conditional combat skills since last update

src/net/sourceforge/kolmafia/RequestEditorKit.java, test/net/sourceforge/kolmafia/RequestEditorKitTest.java, test/root/request/test_place_mclargehuge_trapper_give_quest.html
Yet Another place where KoL changed a <b> tag
=> Fix New Area Unlocked links

src/data/classskills.txt, src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/data/monsters.txt, src/data/statuseffects.txt
The enemies scale at different values depending on the zone: the hackers seem to be 3, 6, 9 respectively and the viruses 1, 6, 9. The HP scaling is also off: ~30, ~90, ~200. Need more spading to figure out what's happening here.
If you can conspire to fight one outside a zone (e.g. using the parachute) it looks like Scale: 9.
=> feat: more cyberrealm items

src/net/sourceforge/kolmafia/RequestEditorKit.java, test/net/sourceforge/kolmafia/RequestEditorKitTest.java, test/root/request/test_aboo_peak_flee_the_horror.html
Yet another KoL change that broke a Relay Browser decoration.
=> Fix 'Use another A-Boo clue' decoration

src/net/sourceforge/kolmafia/request/CharPaneRequest.java
It was implemented as "ski avalanche".
=> fix: noncomforcers avalanche name

src/data/coinmasters.txt, src/data/defaults.txt, src/data/equipment.txt, src/data/items.txt, src/data/modifiers.txt, src/net/sourceforge/kolmafia/KoLAdventure.java, src/net/sourceforge/kolmafia/RequestEditorKit.java, src/net/sourceforge/kolmafia/swingui/OptionsFrame.java, test/net/sourceforge/kolmafia/RequestEditorKitTest.java, test/root/request/test_fight_cyberrealm.html, test/root/request/test_place_cyberrealm.html
1) suppressCyberRealmDarkMode will not make CyberRealm pages green on black - which my aging eyes can't read.
2) suppressCyberRealmGreenImages will not make all the images on the page green. I actually sort of like that, but, whatever.
3) add geofencing rapier and its dedigitizer schematic.
4) recognize message that a location has been hacked for the day and count that as an adventure failure.
=> Preferences to make CyberRealm easier to read

src/data/defaults.txt, src/net/sourceforge/kolmafia/KoLAdventure.java, src/net/sourceforge/kolmafia/RequestEditorKit.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/ApiRequest.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, src/net/sourceforge/kolmafia/request/coinmaster/shop/DedigitizerRequest.java, src/net/sourceforge/kolmafia/session/QuestManager.java, test/net/sourceforge/kolmafia/KoLAdventureValidationTest.java, test/net/sourceforge/kolmafia/RequestEditorKitTest.java, test/net/sourceforge/kolmafia/session/QuestManagerTest.java, test/root/request/test_adventure_hacked_cyberrealm_zone1.html, test/root/request/test_adventure_hacked_cyberrealm_zone2.html, test/root/request/test_visit_monorail.html
1) crAlways property tracks  if you have permanent access to CyberRealm
2) _crToday property tracks if you have one-day access to CyberRealm
3) Add "Back to the Network Map" link if you've hacked the system in that zone today.
=> crAlways and _crToday properties

src/data/coinmasters.txt, src/data/defaults.txt, src/net/sourceforge/kolmafia/objectpool/AdventurePool.java, src/net/sourceforge/kolmafia/preferences/Preferences.java, src/net/sourceforge/kolmafia/request/FightRequest.java, src/net/sourceforge/kolmafia/request/PlaceRequest.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, src/net/sourceforge/kolmafia/session/BreakfastManager.java, src/net/sourceforge/kolmafia/session/ChoiceControl.java, src/net/sourceforge/kolmafia/session/QuestManager.java, test/net/sourceforge/kolmafia/session/QuestManagerTest.java, test/root/request/test_place_serverroom_filedrawer.html
1) Recipe for dedigitizer schematic: 3d printed server room key
2) Visit trash1 (or trash2) in server room sets _cyberTrashCollected to true
3) Breakfast visits trash1 if you have access to CyberRealm and have not collected trash yet
4) Visit filedrawer in server room parses text and sets (for example)
```
assertThat("_cyberZone1Owner", isSetTo("Century-Price Quasi-Marketing Companies"));
assertThat("_cyberZone1Defense", isSetTo("null container"));
assertThat("_cyberZone1Hacker", isSetTo("blackhat"));
assertThat("_cyberZone2Owner", isSetTo("Taking Compu-Equipment"));
assertThat("_cyberZone2Defense", isSetTo("parental controls"));
assertThat("_cyberZone2Hacker", isSetTo("blackhat"));
assertThat("_cyberZone3Owner", isSetTo("United Kingdom Compu-Industry"));
assertThat("_cyberZone3Defense", …
```
=> Add properties for filedrawer, trash, adventuring in cyber zones

src/data/modifiers.txt, src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java, src/net/sourceforge/kolmafia/persistence/NPCStoreDatabase.java
Thought about also making `my_ram()` but it's just 3 plus however much extra you have.
=> feat: add new RAM modifier

src/data/allshoprows.txt, src/data/shoprows.txt, src/net/sourceforge/kolmafia/RequestEditorKit.java, src/net/sourceforge/kolmafia/request/AdventureRequest.java, src/net/sourceforge/kolmafia/session/QuestManager.java, test/net/sourceforge/kolmafia/request/AdventureRequestTest.java, test/net/sourceforge/kolmafia/request/FightRequestTest.java, test/net/sourceforge/kolmafia/session/ChoiceControlTest.java, test/net/sourceforge/kolmafia/session/QuestManagerTest.java, test/root/request/test_cyber_zone1_choice1.html, test/root/request/test_cyber_zone1_choice2.html, test/root/request/test_cyber_zone1_fight.html, test/root/request/test_cyber_zone2_choice1.html, test/root/request/test_cyber_zone2_choice2.html, test/root/request/test_cyber_zone2_fight.html, test/root/request/test_cyber_zone3_choice1.html, test/root/request/test_cyber_zone3_choice2.html, test/root/request/test_cyber_zone3_fight.html
1) Added row info of The Dedigitizer to shoprows.txt and allshoprows.txt
2) In CyberRealm, change Black-on-Green text in Fight Rounds, etc. to White-on-Blue, if suppressCyberRealmDarkMode
This allows round counting to work again in the Relay Browser
3) When parse filedrawer, convert "Intrusion" keyword to actual monster name
4) When parsing Encounter name, don't get confused by stray CR character within bold text
5) Tests for fights in CyberRealm incrementing appropriate Turns property
6) Tests for choice adventures (half-way and final) setting appropriate Turns property.
=> more CyberRealm improvements

src/data/monsters.txt
=> monster name typo correction to Jedediah

src/data/familiars.txt
For the record:
(The first was from a previous commit)
```
Results for Profane Parrot after 12 trials using 144 turns:
Cage Match      61      63      12           0              2
Scavenger Hunt  36      47      65           0              3
Obstacle Course 52      65      57           0              2
Hide and Seek   47      65      56           0              2
Results for Significant Bit after 12 trials using 144 turns:
Cage Match      73      42      12           0              1
Scavenger Hunt  67      66       0           0              1
Obstacle Course 60      60       6           0              1
Hide and Seek   36      49      67           0 …
```
=> Train Significant Bit and Doll Moll

src/net/sourceforge/kolmafia/session/ChoiceControl.java
Sorry for leaving this in, I added it when I was writing tests and it seems that I and all reviewers missed it.
=> Remove accidentally included test code from boxing daycare

src/data/modifiers.txt
I just bug reported (to kol) a bunch of unbjornable familiars; will add empty lines for them in about a week if they haven't been added
=> bjorn enchantments for new familiars

src/net/sourceforge/kolmafia/request/RelayRequest.java, test/net/sourceforge/kolmafia/request/RelayRequestTest.java
=> feat: make chat '/goto' links

src/net/sourceforge/kolmafia/AdventureResult.java, test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
As reported in https://kolmafia.us/threads/checking-sell_price-of-cyburger-results-in-a-npe.30320/#post-176341
=> fix: flip .equals as this.name may be null

src/data/familiars.txt
Adds tags that have been found for familiars through Z is for Zootomist spading as of 2/19/25
=> Updated tags from Zootomist

src/net/sourceforge/kolmafia/maximizer/Maximizer.java, src/net/sourceforge/kolmafia/request/concoction/MayamRequest.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
This disables not-currently-available resonances in the maximizer (by graying them out).
=> Disable unavailable resonances in the maximizer.

src/data/concoctions.txt, src/data/npcstores.txt, src/data/shoprows.txt
=> Code archaeology fills in gaps in shoprows.txt

src/net/sourceforge/kolmafia/AscensionPath.java
Bench is 1 + points and caps at 11, so points cap at 10.
=> feat: zoot point cap

src/data/statuseffects.txt, src/net/sourceforge/kolmafia/KoLmafiaCLI.java, src/net/sourceforge/kolmafia/maximizer/Maximizer.java, src/net/sourceforge/kolmafia/textui/command/CampAwayCommand.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java, test/net/sourceforge/kolmafia/textui/command/CampAwayCommandTest.java
This way we can display cloud-talk in the maximizer, which I always forget.
=> Add getaway campsite command.

src/data/classskills.txt, src/data/inebriety.txt, src/data/items.txt, src/data/modifiers.txt, src/data/statuseffects.txt
leprecondo, plus whatever else I had in my session logs
=> feat: leprecondo

src/net/sourceforge/kolmafia/preferences/Preferences.java
This is a speculative fix, but what I think may have been happening for the preference reset is during the process for a time-in login:
1. The user is timed out from being idle, laptop goes to sleep, etc.
2. An action occurs where the user is timed back in
3. Preferences.reset(null) is called, the current user's preferences are flushed to disk and the pref collections are cleared
4. Preferences.reset(user) is called, which calls loadUserPreferences()
5. Preferences.userPropertiesFile is set to the user's preference file, before it is loaded from disk, this happens while the pref collections are still empty and the preferences are set later in this function
6. Preference collections are reloaded from the user file contents
I speculate that between step 5 and 6:
1. Another thread receives a …
=> synchronize loadUserPreferences with saveToFile

src/net/sourceforge/kolmafia/request/ClanRumpusRequest.java
- **Click PvP and Adv furniture as part of rumpus room daily action**
- **Simplify some of the rest of the code**
=> Include clicking Adv and PvP rumpus furniture in breakfast task

src/net/sourceforge/kolmafia/KoLCharacter.java, src/net/sourceforge/kolmafia/ModifierType.java, test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
=> feat: remove rumpus modifiers entirely

src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
=> fix: when looking for string modifiers, check multistring too

src/data/statuseffects.txt
Turns out these are totally wishable which is funny and useful
=> Mark some effects as wishable

src/data/defaults.txt, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/persistence/ConcoctionDatabase.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, src/net/sourceforge/kolmafia/request/concoction/CreateItemRequest.java
Not certain this is how they work but I feel like it probably is.
=> feat: support crafting plans

src/data/monsterparts.txt
=> Chester and Knott Slanding use default parts, villainous henchperson was missing a foot

src/data/familiars.txt, src/data/modifiers.txt, src/net/sourceforge/kolmafia/modifiers/MultiStringModifier.java, test/net/sourceforge/kolmafia/DataFileConsistencyTest.java
=> tests: ensure all modifiers for effects have durations

src/data/items.txt
Ref: https://kolmafia.us/threads/candy-spadings.30536/
=> feat: candy spading by VinnyB

src/net/sourceforge/kolmafia/objectpool/ItemPool.java, src/net/sourceforge/kolmafia/request/UseItemRequest.java, src/net/sourceforge/kolmafia/session/ChoiceControl.java, src/net/sourceforge/kolmafia/session/QuestManager.java
Also added a one line fix for the experimental serum P-00 when handing in the Serum Sortie quest on Conspiracy Island.
=> handle almost-dead walkie-talkie same as protonic accelerator pack

src/data/defaults.txt, src/net/sourceforge/kolmafia/AscensionPath.java, test/net/sourceforge/kolmafia/request/AscensionHistoryRequestTest.java
starting [1,960 pokédollar bills](https://kol.coldfront.net/thekolwiki/index.php/1,960_pok%C3%A9dollar_bill) would be pokefamPoints * 5
=> Add pokefamPoints

src/net/sourceforge/kolmafia/utilities/ChoiceUtilities.java, test/net/sourceforge/kolmafia/utilities/ChoiceUtilitiesTest.java
- **Fix peridot parsing by widening choice parsing appropriately**
- **Linting for ChoiceUtilities class**
- **For2matting**
Fixes #2904
=> Fix peridot location choice parsing

src/net/sourceforge/kolmafia/moods/ManaBurn.java, src/net/sourceforge/kolmafia/moods/ManaBurnManager.java, test/net/sourceforge/kolmafia/moods/ManaBurnTest.java
=> fix: mana burn manager casting custom effects

src/net/sourceforge/kolmafia/request/FightRequest.java
Avoids having to enumerate the children.
=> perf: use new recommended way of selecting from children

src/data/familiars.txt
Cookbookbat was fixed 27th Feb 2025, previously had a typo on the spooky tag.
=> feat: more familiar tags

src/data/familiars.txt
Data from Rinn, Grumble Guy and Deltroy.
=> feat: more fam tags

src/data/familiars.txt
=> feat: coffee pixie / cheshire bat tags

src/data/familiars.txt
=> feat: fam tags for old iotms

src/data/modifiers.txt, src/net/sourceforge/kolmafia/maximizer/Evaluator.java, src/net/sourceforge/kolmafia/modifiers/BitmapModifier.java, src/net/sourceforge/kolmafia/persistence/TCRSDatabase.java, src/net/sourceforge/kolmafia/session/EquipmentManager.java, test/net/sourceforge/kolmafia/maximizer/MaximizerCreatableTest.java
This will let incredibly rich people manage their equipment slightly more effectively.
=> feat: make stinky cheese count a modifier

gradle/wrapper/gradle-wrapper.properties, src/data/defaults.txt, src/net/sourceforge/kolmafia/AreaCombatData.java, src/net/sourceforge/kolmafia/request/FightRequest.java, test/net/sourceforge/kolmafia/AreaCombatDataTest.java
- **Add statefulness to area combat data in SMOOCH Army HQ**
- **Formatting**
- **Upgrade gradle**
=> The SMOOCH Army HQ appearance rates are stateful

src/net/sourceforge/kolmafia/KoLCharacter.java, src/net/sourceforge/kolmafia/Modifiers.java, src/net/sourceforge/kolmafia/objectpool/ItemPool.java, test/net/sourceforge/kolmafia/maximizer/MaximizerTest.java
Maximizer still doesn't work perfectly because prismatic beret doesn't value "items that increase power" even though that's what contributes.
=> feat: prismatic beret mods

src/net/sourceforge/kolmafia/session/ChoiceControl.java
Despite looking similar, the allied radio backpack and handheld allied radio choice adventures have different IDs
=> can walk from handheld radio choice

src/data/defaults.txt, src/data/fambattle.txt, src/data/monsters.txt, src/net/sourceforge/kolmafia/request/FightRequest.java, src/net/sourceforge/kolmafia/session/ChoiceControl.java
Track:
* when we received the stock certificate (meat gained is turns spent since * 10)
* how many time cops we fought today (the first 11 are free)
* when we last received the mobius NC, and how many we've received today (I'm informed there is something kramco-like going on)
=> feat: start tracking mobius stuff

src/data/items.txt, src/data/modifiers.txt, src/net/sourceforge/kolmafia/modifiers/DoubleModifier.java
Schrodinger's Anticipation has this as a potential, so add it as a modifier.
=> feat: damage vs. mer-kin modifier

src/net/sourceforge/kolmafia/persistence/MonsterDatabase.java, src/net/sourceforge/kolmafia/session/ChoiceAdventures.java, test/net/sourceforge/kolmafia/session/ChoiceAdventuresTest.java
Remove the pronoun, disambiguate with Mafia's names where relevant.
=> feat: decorate Mimic DNA Bank

build.gradle
=> Upgrade jpackage

build.gradle.kts
=> fix: clean and prune with no folder

src/net/sourceforge/kolmafia/persistence/WardrobeOMaticDatabase.java, src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, test/internal/helpers/Player.java, test/net/sourceforge/kolmafia/persistence/WardrobeOMaticDatabaseTest.java, test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
Expose a function `futuristic_wardrobe($slot[], tier)` to return the modifiers the futuristic clothing of a particular slot would have, if you received it at a particular tier 1-5.
=> feat: wardrobe-o-matic generation

src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java, test/net/sourceforge/kolmafia/textui/RuntimeLibraryTest.java
=> fix: futuristic_wardrobe return type

src/net/sourceforge/kolmafia/KoLConstants.java, src/net/sourceforge/kolmafia/maximizer/Maximizer.java, src/net/sourceforge/kolmafia/swingui/MaximizerFrame.java
A couple of people have requested this.
=> feat: add a wish filter checkbox for maximizer

src/data/statuseffects.txt
also remove notcrs from effects marked neutral, also mark some of the new effects good
=> change good+notcrs effects to neutral+none if you can't get them from the hookah

src/data/modifiers.txt
=> fix: ink bladder does not give effect
